// ============================================================
// src/registry/lessons/pythonLessons.js
// STUB — same shape as htmlLessons.js, empty until you fill it in.
// lessonRegistry.js can safely import this right now without
// breaking anything; it'll just show 0 lessons for Python until
// you add sections here.
// ============================================================

import { STATUS } from "../../config/constants";

export const tutorialInfo = {
  id: "amazon-web-services",
  title: "AWS Tutorial",
  shortTitle: "AWS",
  category: "DevOps",
  description: "Master AWS from beginner to advanced with a comprehensive tutorial covering cloud computing fundamentals, IAM, EC2, S3, VPC, RDS, Lambda, CloudFront, Route 53, CloudWatch, containers, serverless applications, security, monitoring, deployment, scalability, and practical AWS cloud architecture.",
  icon: "amazon-web-services",
  difficulty: "Advanced", // course-level badge, separate from per-section defaults
  estimatedHours: 41,
  totalLessons: 94,
  version: "Latest Version",
  language: "English",
  path: "/amazon-web-services",
  authorId: "faiz",
  updatedAt: "2026-07-09",
  tags: ["aws", "amazon web services", "aws tutorial", "cloud computing", "cloud", "cloud development", "cloud infrastructure", "aws services", "aws console", "aws cli", "iam", "ec2", "s3", "vpc", "rds", "lambda", "cloudfront", "route 53", "cloudwatch", "aws networking", "aws security", "serverless", "aws containers", "docker on aws", "kubernetes on aws", "aws devops", "cloud deployment", "aws architecture", "aws monitoring", "aws cost optimization"],
  seo: {
    title: "AWS Tutorial - Learn Amazon Web Services from Beginner to Advanced | DevSphere",
    description: "Learn AWS from scratch with a complete Amazon Web Services tutorial covering cloud computing, IAM, EC2, S3, VPC, RDS, Lambda, CloudFront, Route 53, CloudWatch, serverless, security, deployment, scalability, and AWS architecture.",
    keywords: ["AWS Tutorial", "AWS Tutorial for Beginners", "Learn AWS", "AWS Course", "AWS for Beginners", "AWS Training", "Amazon Web Services Tutorial", "Amazon Web Services Course", "Amazon Web Services for Beginners", "AWS Basics", "AWS Fundamentals", "AWS Cloud Tutorial", "Cloud Computing", "Cloud Computing Tutorial", "Cloud Computing for Beginners", "AWS Cloud Computing", "AWS Architecture", "AWS Architecture Tutorial", "AWS Services", "AWS Management Console", "AWS CLI", "AWS Command Line Interface", "AWS Account Setup", "AWS IAM", "IAM AWS Tutorial", "AWS Identity and Access Management", "AWS Users and Groups", "AWS Roles and Policies", "AWS EC2",  "EC2 Tutorial", "Amazon EC2 Tutorial", "AWS EC2 Instance", "EC2 Instance Types", "EC2 Security Groups", "EC2 Auto Scaling", "AWS S3", "S3 Tutorial", "Amazon S3 Tutorial", "AWS S3 Bucket", "S3 Storage", "S3 Static Website Hosting", "AWS VPC", "VPC Tutorial", "Amazon VPC", "AWS Networking", "AWS Subnets", "AWS Route Tables", "AWS Internet Gateway", "AWS NAT Gateway", "AWS Security Groups", "AWS Network ACL", "AWS RDS", "RDS Tutorial", "Amazon RDS", "AWS Database", "AWS Lambda", "Lambda Tutorial", "AWS Lambda Tutorial", "Serverless AWS", "Serverless Computing", "AWS Serverless Architecture", "AWS API Gateway", "AWS CloudFront", "CloudFront Tutorial", "AWS CDN", "AWS Route 53", "Route 53 Tutorial", "AWS DNS", "AWS CloudWatch", "CloudWatch Tutorial", "AWS Monitoring",  "AWS Logging", "AWS CloudTrail", "AWS Elastic Load Balancing", "AWS Load Balancer", "AWS Auto Scaling", "AWS Elastic Beanstalk", "AWS ECS", "AWS ECR", "AWS EKS", "Docker AWS", "Kubernetes AWS", "AWS DevOps", "AWS CI/CD", "AWS CodePipeline", "AWS CodeBuild", "AWS CodeDeploy", "AWS Deployment", "AWS Cloud Deployment", "AWS Security", "AWS Security Best Practices", "AWS Encryption", "AWS Secrets Manager", "AWS KMS", "AWS Cost Optimization", "AWS Pricing", "AWS Free Tier", "AWS High Availability", "AWS Scalability", "AWS Fault Tolerance", "AWS Disaster Recovery", "AWS Infrastructure", "AWS Cloud Architecture", "AWS Projects", "AWS Real World Projects", "AWS DevOps Tutorial", "AWS Certification Preparation", "AWS Solutions Architecture", "DevSphere"]
  }
};

export const sections = [
  {
    id: "aws-fundamentals",
    title: "AWS Fundamentals",
    order: 1,
    difficulty: "Beginner",
    lessons: [
      {
        id: 1,
        order: 1,
        slug: "aws-what-is-cloud-computing",
        title: "What is Cloud Computing?",
        shortTitle: "What is Cloud Computing",
        readingTime: 9,
        tags: ["aws", "amazon web services", "cloud computing", "aws fundamentals", "cloud architecture"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get a comprehensive introduction to cloud computing and how it transforms modern IT infrastructure.",
        prerequisites: [],
        related: ["aws-what-is-aws", "aws-what-is-aws-iam"],
        recommended: ["aws-aws-cloud-computing-model", "aws-benefits-of-using-aws"]
      },
      {
        id: 2,
        order: 2,
        slug: "aws-what-is-aws",
        title: "What is AWS?",
        shortTitle: "What is AWS",
        readingTime: 10,
        tags: ["aws", "amazon web services", "cloud computing", "aws fundamentals", "cloud architecture"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand what Amazon Web Services is and why it is the leading cloud computing platform globally.",
        prerequisites: ["aws-what-is-cloud-computing", "aws-aws-cloud-computing-model"],
        related: ["aws-aws-cloud-computing-model", "aws-what-is-cloud-computing"],
        recommended: ["aws-benefits-of-using-aws", "aws-aws-global-infrastructure"]
      },
      {
        id: 3,
        order: 3,
        slug: "aws-aws-cloud-computing-model",
        title: "AWS Cloud Computing Model",
        shortTitle: "AWS Cloud Computing Model",
        readingTime: 11,
        tags: ["aws", "amazon web services", "cloud computing", "aws fundamentals", "cloud architecture"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the shared responsibility model and service models (IaaS, PaaS, SaaS) in AWS.",
        prerequisites: ["aws-what-is-aws", "aws-what-is-cloud-computing"],
        related: ["aws-benefits-of-using-aws", "aws-what-is-aws"],
        recommended: ["aws-aws-global-infrastructure", "aws-aws-regions-and-availability-zones"]
      },
      {
        id: 4,
        order: 4,
        slug: "aws-benefits-of-using-aws",
        title: "Benefits of Using AWS",
        shortTitle: "Benefits of Using AWS",
        readingTime: 12,
        tags: ["aws", "amazon web services", "cloud computing", "aws fundamentals", "cloud architecture"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover the key advantages of AWS, including scalability, reliability, and cost-effectiveness.",
        prerequisites: ["aws-aws-cloud-computing-model", "aws-what-is-aws"],
        related: ["aws-aws-global-infrastructure", "aws-aws-cloud-computing-model"],
        recommended: ["aws-aws-regions-and-availability-zones", "aws-aws-edge-locations-and-points-of-presence"]
      },
      {
        id: 5,
        order: 5,
        slug: "aws-aws-global-infrastructure",
        title: "AWS Global Infrastructure",
        shortTitle: "AWS Global Infrastructure",
        readingTime: 13,
        tags: ["aws", "amazon web services", "cloud computing", "aws fundamentals", "cloud architecture"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn about the global footprint of AWS and how it ensures high availability and low latency.",
        prerequisites: ["aws-benefits-of-using-aws", "aws-aws-cloud-computing-model"],
        related: ["aws-aws-regions-and-availability-zones", "aws-benefits-of-using-aws"],
        recommended: ["aws-aws-edge-locations-and-points-of-presence", "aws-creating-and-navigating-an-aws-account"]
      },
      {
        id: 6,
        order: 6,
        slug: "aws-aws-regions-and-availability-zones",
        title: "AWS Regions and Availability Zones",
        shortTitle: "AWS Regions and Availabilit...",
        readingTime: 14,
        tags: ["aws", "amazon web services", "cloud computing", "aws fundamentals", "cloud architecture"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the difference between AWS Regions and Availability Zones for fault-tolerant architecture.",
        prerequisites: ["aws-aws-global-infrastructure", "aws-benefits-of-using-aws"],
        related: ["aws-aws-edge-locations-and-points-of-presence", "aws-aws-global-infrastructure"],
        recommended: ["aws-creating-and-navigating-an-aws-account", "aws-what-is-aws-iam"]
      },
      {
        id: 7,
        order: 7,
        slug: "aws-aws-edge-locations-and-points-of-presence",
        title: "AWS Edge Locations and Points of Presence",
        shortTitle: "AWS Edge Locations and Point...",
        readingTime: 15,
        tags: ["aws", "amazon web services", "cloud computing", "aws fundamentals", "cloud architecture"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how AWS Edge Locations and Points of Presence power services like CloudFront and Route 53.",
        prerequisites: ["aws-aws-regions-and-availability-zones", "aws-aws-global-infrastructure"],
        related: ["aws-creating-and-navigating-an-aws-account", "aws-aws-regions-and-availability-zones"],
        recommended: ["aws-creating-and-navigating-an-aws-account", "aws-what-is-aws-iam"]
      },
      {
        id: 8,
        order: 8,
        slug: "aws-creating-and-navigating-an-aws-account",
        title: "Creating and Navigating an AWS Account",
        shortTitle: "Creating and Navigating an A...",
        readingTime: 8,
        tags: ["aws", "amazon web services", "cloud computing", "aws fundamentals", "cloud architecture"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Step-by-step guide to setting up your AWS account and navigating the AWS Management Console.",
        prerequisites: ["aws-aws-edge-locations-and-points-of-presence", "aws-aws-regions-and-availability-zones"],
        related: ["aws-what-is-aws-iam", "aws-aws-edge-locations-and-points-of-presence"],
        recommended: ["aws-what-is-aws-iam", "aws-iam-users-groups-roles-and-policies"]
      }
    ]
  },
  {
    id: "aws-identity-and-access-management",
    title: "AWS Identity and Access Management",
    order: 2,
    difficulty: "Beginner",
    lessons: [
      {
        id: 9,
        order: 1,
        slug: "aws-what-is-aws-iam",
        title: "What is AWS IAM?",
        shortTitle: "What is AWS IAM",
        readingTime: 9,
        tags: ["aws", "amazon web services", "cloud computing", "aws iam", "aws security"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to AWS Identity and Access Management (IAM) and its role in securing your AWS environment.",
        prerequisites: ["aws-creating-and-navigating-an-aws-account", "aws-aws-edge-locations-and-points-of-presence"],
        related: ["aws-iam-users-groups-roles-and-policies", "aws-creating-and-navigating-an-aws-account"],
        recommended: ["aws-iam-users-groups-roles-and-policies", "aws-iam-policies-and-permissions"]
      },
      {
        id: 10,
        order: 2,
        slug: "aws-iam-users-groups-roles-and-policies",
        title: "IAM Users, Groups, Roles, and Policies",
        shortTitle: "IAM Users, Groups, Roles, an...",
        readingTime: 10,
        tags: ["aws", "amazon web services", "cloud computing", "aws iam", "aws security"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn the core IAM entities and how they interact to grant or deny access to AWS resources.",
        prerequisites: ["aws-what-is-aws-iam", "aws-creating-and-navigating-an-aws-account"],
        related: ["aws-iam-policies-and-permissions", "aws-what-is-aws-iam"],
        recommended: ["aws-iam-policies-and-permissions", "aws-authentication-vs-authorization"]
      },
      {
        id: 11,
        order: 3,
        slug: "aws-iam-policies-and-permissions",
        title: "IAM Policies and Permissions",
        shortTitle: "IAM Policies and Permissions",
        readingTime: 11,
        tags: ["aws", "amazon web services", "cloud computing", "aws iam", "aws security"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the JSON structure of IAM policies and how to write least-privilege permissions.",
        prerequisites: ["aws-iam-users-groups-roles-and-policies", "aws-what-is-aws-iam"],
        related: ["aws-authentication-vs-authorization", "aws-iam-users-groups-roles-and-policies"],
        recommended: ["aws-authentication-vs-authorization", "aws-iam-roles-and-temporary-credentials"]
      },
      {
        id: 12,
        order: 4,
        slug: "aws-authentication-vs-authorization",
        title: "Authentication vs Authorization",
        shortTitle: "Authentication vs Authorizat...",
        readingTime: 12,
        tags: ["aws", "amazon web services", "cloud computing", "aws iam", "aws security"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the critical difference between verifying identity (authentication) and granting access (authorization).",
        prerequisites: ["aws-iam-policies-and-permissions", "aws-iam-users-groups-roles-and-policies"],
        related: ["aws-iam-roles-and-temporary-credentials", "aws-iam-policies-and-permissions"],
        recommended: ["aws-iam-roles-and-temporary-credentials", "aws-multi-factor-authentication-in-aws"]
      },
      {
        id: 13,
        order: 5,
        slug: "aws-iam-roles-and-temporary-credentials",
        title: "IAM Roles and Temporary Credentials",
        shortTitle: "IAM Roles and Temporary Cred...",
        readingTime: 13,
        tags: ["aws", "amazon web services", "cloud computing", "aws iam", "aws security"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to use IAM roles to grant temporary, secure access to AWS services and external identities.",
        prerequisites: ["aws-authentication-vs-authorization", "aws-iam-policies-and-permissions"],
        related: ["aws-multi-factor-authentication-in-aws", "aws-authentication-vs-authorization"],
        recommended: ["aws-multi-factor-authentication-in-aws", "aws-iam-best-practices"]
      },
      {
        id: 14,
        order: 6,
        slug: "aws-multi-factor-authentication-in-aws",
        title: "Multi-Factor Authentication in AWS",
        shortTitle: "Multi-Factor Authentication ...",
        readingTime: 14,
        tags: ["aws", "amazon web services", "cloud computing", "aws iam", "aws security"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how to enforce MFA to add a crucial layer of security to your AWS root and IAM users.",
        prerequisites: ["aws-iam-roles-and-temporary-credentials", "aws-authentication-vs-authorization"],
        related: ["aws-iam-best-practices", "aws-iam-roles-and-temporary-credentials"],
        recommended: ["aws-iam-best-practices", "aws-organizations-and-multi-account-strategy"]
      },
      {
        id: 15,
        order: 7,
        slug: "aws-iam-best-practices",
        title: "IAM Best Practices",
        shortTitle: "IAM Best Practices",
        readingTime: 15,
        tags: ["aws", "amazon web services", "cloud computing", "aws iam", "aws security"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Review industry-standard best practices for securing your AWS environment using IAM.",
        prerequisites: ["aws-multi-factor-authentication-in-aws", "aws-iam-roles-and-temporary-credentials"],
        related: ["aws-organizations-and-multi-account-strategy", "aws-multi-factor-authentication-in-aws"],
        recommended: ["aws-organizations-and-multi-account-strategy", "aws-what-is-amazon-ec2"]
      },
      {
        id: 16,
        order: 8,
        slug: "aws-organizations-and-multi-account-strategy",
        title: "AWS Organizations and Multi-Account Strategy",
        shortTitle: "AWS Organizations and Multi-...",
        readingTime: 8,
        tags: ["aws", "amazon web services", "cloud computing", "aws iam", "aws security"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to manage multiple AWS accounts securely and efficiently using AWS Organizations.",
        prerequisites: ["aws-iam-best-practices", "aws-multi-factor-authentication-in-aws"],
        related: ["aws-iam-best-practices", "aws-what-is-amazon-ec2"],
        recommended: ["aws-what-is-amazon-ec2", "aws-ec2-instance-types"]
      }
    ]
  },
  {
    id: "amazon-ec2-and-compute",
    title: "Amazon EC2 and Compute",
    order: 3,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 17,
        order: 1,
        slug: "aws-what-is-amazon-ec2",
        title: "What is Amazon EC2?",
        shortTitle: "What is Amazon EC2",
        readingTime: 9,
        tags: ["aws", "amazon web services", "cloud computing", "aws ec2", "aws compute"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to Amazon Elastic Compute Cloud (EC2), the foundational compute service of AWS.",
        prerequisites: ["aws-organizations-and-multi-account-strategy", "aws-iam-best-practices"],
        related: ["aws-ec2-instance-types", "aws-organizations-and-multi-account-strategy"],
        recommended: ["aws-ec2-instance-types", "aws-choosing-an-ec2-instance"]
      },
      {
        id: 18,
        order: 2,
        slug: "aws-ec2-instance-types",
        title: "EC2 Instance Types",
        shortTitle: "EC2 Instance Types",
        readingTime: 10,
        tags: ["aws", "amazon web services", "cloud computing", "aws ec2", "aws compute"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the different EC2 instance families and how to choose the right one for your workload.",
        prerequisites: ["aws-what-is-amazon-ec2", "aws-organizations-and-multi-account-strategy"],
        related: ["aws-choosing-an-ec2-instance", "aws-what-is-amazon-ec2"],
        recommended: ["aws-choosing-an-ec2-instance", "aws-amazon-machine-images-amis"]
      },
      {
        id: 19,
        order: 3,
        slug: "aws-choosing-an-ec2-instance",
        title: "Choosing an EC2 Instance",
        shortTitle: "Choosing an EC2 Instance",
        readingTime: 11,
        tags: ["aws", "amazon web services", "cloud computing", "aws ec2", "aws compute"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn the factors to consider when selecting the optimal EC2 instance type for performance and cost.",
        prerequisites: ["aws-ec2-instance-types", "aws-what-is-amazon-ec2"],
        related: ["aws-amazon-machine-images-amis", "aws-ec2-instance-types"],
        recommended: ["aws-amazon-machine-images-amis", "aws-launching-and-connecting-to-an-ec2-instance"]
      },
      {
        id: 20,
        order: 4,
        slug: "aws-amazon-machine-images-amis",
        title: "Amazon Machine Images (AMIs)",
        shortTitle: "Amazon Machine Images (AMIs)",
        readingTime: 12,
        tags: ["aws", "amazon web services", "cloud computing", "aws ec2", "aws compute"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand AMIs and how they serve as the blueprint for launching your EC2 instances.",
        prerequisites: ["aws-choosing-an-ec2-instance", "aws-ec2-instance-types"],
        related: ["aws-launching-and-connecting-to-an-ec2-instance", "aws-choosing-an-ec2-instance"],
        recommended: ["aws-launching-and-connecting-to-an-ec2-instance", "aws-security-groups-and-instance-security"]
      },
      {
        id: 21,
        order: 5,
        slug: "aws-launching-and-connecting-to-an-ec2-instance",
        title: "Launching and Connecting to an EC2 Instance",
        shortTitle: "Launching and Connecting to ...",
        readingTime: 13,
        tags: ["aws", "amazon web services", "cloud computing", "aws ec2", "aws compute"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Step-by-step guide to launching an EC2 instance and connecting to it via SSH or RDP.",
        prerequisites: ["aws-amazon-machine-images-amis", "aws-choosing-an-ec2-instance"],
        related: ["aws-security-groups-and-instance-security", "aws-amazon-machine-images-amis"],
        recommended: ["aws-security-groups-and-instance-security", "aws-ec2-storage-and-instance-lifecycle"]
      },
      {
        id: 22,
        order: 6,
        slug: "aws-security-groups-and-instance-security",
        title: "Security Groups and Instance Security",
        shortTitle: "Security Groups and Instance...",
        readingTime: 14,
        tags: ["aws", "amazon web services", "cloud computing", "aws ec2", "aws compute"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to configure Security Groups to act as virtual firewalls for your EC2 instances.",
        prerequisites: ["aws-launching-and-connecting-to-an-ec2-instance", "aws-amazon-machine-images-amis"],
        related: ["aws-ec2-storage-and-instance-lifecycle", "aws-launching-and-connecting-to-an-ec2-instance"],
        recommended: ["aws-ec2-storage-and-instance-lifecycle", "aws-elastic-ip-addresses"]
      },
      {
        id: 23,
        order: 7,
        slug: "aws-ec2-storage-and-instance-lifecycle",
        title: "EC2 Storage and Instance Lifecycle",
        shortTitle: "EC2 Storage and Instance Lif...",
        readingTime: 15,
        tags: ["aws", "amazon web services", "cloud computing", "aws ec2", "aws compute"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the different storage options for EC2 and the lifecycle states of an instance.",
        prerequisites: ["aws-security-groups-and-instance-security", "aws-launching-and-connecting-to-an-ec2-instance"],
        related: ["aws-elastic-ip-addresses", "aws-security-groups-and-instance-security"],
        recommended: ["aws-elastic-ip-addresses", "aws-ec2-auto-scaling"]
      },
      {
        id: 24,
        order: 8,
        slug: "aws-elastic-ip-addresses",
        title: "Elastic IP Addresses",
        shortTitle: "Elastic IP Addresses",
        readingTime: 8,
        tags: ["aws", "amazon web services", "cloud computing", "aws ec2", "aws compute"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to use Elastic IPs to provide static, persistent public IP addresses for your EC2 instances.",
        prerequisites: ["aws-ec2-storage-and-instance-lifecycle", "aws-security-groups-and-instance-security"],
        related: ["aws-ec2-auto-scaling", "aws-ec2-storage-and-instance-lifecycle"],
        recommended: ["aws-ec2-auto-scaling", "aws-elastic-load-balancing"]
      },
      {
        id: 25,
        order: 9,
        slug: "aws-ec2-auto-scaling",
        title: "EC2 Auto Scaling",
        shortTitle: "EC2 Auto Scaling",
        readingTime: 9,
        tags: ["aws", "amazon web services", "cloud computing", "aws ec2", "aws compute"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how to automatically adjust the number of EC2 instances to handle changes in demand.",
        prerequisites: ["aws-elastic-ip-addresses", "aws-ec2-storage-and-instance-lifecycle"],
        related: ["aws-elastic-load-balancing", "aws-elastic-ip-addresses"],
        recommended: ["aws-elastic-load-balancing", "aws-what-is-amazon-vpc"]
      },
      {
        id: 26,
        order: 10,
        slug: "aws-elastic-load-balancing",
        title: "Elastic Load Balancing",
        shortTitle: "Elastic Load Balancing",
        readingTime: 10,
        tags: ["aws", "amazon web services", "cloud computing", "aws ec2", "aws compute"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how ELB distributes incoming application traffic across multiple EC2 instances for high availability.",
        prerequisites: ["aws-ec2-auto-scaling", "aws-elastic-ip-addresses"],
        related: ["aws-ec2-auto-scaling", "aws-what-is-amazon-vpc"],
        recommended: ["aws-what-is-amazon-vpc", "aws-vpc-components-and-architecture"]
      }
    ]
  },
  {
    id: "aws-networking",
    title: "AWS Networking",
    order: 4,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 27,
        order: 1,
        slug: "aws-what-is-amazon-vpc",
        title: "What is Amazon VPC?",
        shortTitle: "What is Amazon VPC",
        readingTime: 11,
        tags: ["aws", "amazon web services", "cloud computing", "aws networking", "aws vpc"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to Amazon Virtual Private Cloud (VPC) and how it lets you provision a logically isolated network.",
        prerequisites: ["aws-elastic-load-balancing", "aws-ec2-auto-scaling"],
        related: ["aws-vpc-components-and-architecture", "aws-elastic-load-balancing"],
        recommended: ["aws-vpc-components-and-architecture", "aws-public-vs-private-subnets"]
      },
      {
        id: 28,
        order: 2,
        slug: "aws-vpc-components-and-architecture",
        title: "VPC Components and Architecture",
        shortTitle: "VPC Components and Architect...",
        readingTime: 12,
        tags: ["aws", "amazon web services", "cloud computing", "aws networking", "aws vpc"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the core building blocks of a VPC, including subnets, route tables, and gateways.",
        prerequisites: ["aws-what-is-amazon-vpc", "aws-elastic-load-balancing"],
        related: ["aws-public-vs-private-subnets", "aws-what-is-amazon-vpc"],
        recommended: ["aws-public-vs-private-subnets", "aws-route-tables-and-routing"]
      },
      {
        id: 29,
        order: 3,
        slug: "aws-public-vs-private-subnets",
        title: "Public vs Private Subnets",
        shortTitle: "Public vs Private Subnets",
        readingTime: 13,
        tags: ["aws", "amazon web services", "cloud computing", "aws networking", "aws vpc"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the difference between public and private subnets and when to use each.",
        prerequisites: ["aws-vpc-components-and-architecture", "aws-what-is-amazon-vpc"],
        related: ["aws-route-tables-and-routing", "aws-vpc-components-and-architecture"],
        recommended: ["aws-route-tables-and-routing", "aws-internet-gateways-and-nat-gateways"]
      },
      {
        id: 30,
        order: 4,
        slug: "aws-route-tables-and-routing",
        title: "Route Tables and Routing",
        shortTitle: "Route Tables and Routing",
        readingTime: 14,
        tags: ["aws", "amazon web services", "cloud computing", "aws networking", "aws vpc"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how route tables control the flow of network traffic within and outside your VPC.",
        prerequisites: ["aws-public-vs-private-subnets", "aws-vpc-components-and-architecture"],
        related: ["aws-internet-gateways-and-nat-gateways", "aws-public-vs-private-subnets"],
        recommended: ["aws-internet-gateways-and-nat-gateways", "aws-network-acls-vs-security-groups"]
      },
      {
        id: 31,
        order: 5,
        slug: "aws-internet-gateways-and-nat-gateways",
        title: "Internet Gateways and NAT Gateways",
        shortTitle: "Internet Gateways and NAT Ga...",
        readingTime: 15,
        tags: ["aws", "amazon web services", "cloud computing", "aws networking", "aws vpc"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how to enable internet connectivity for public subnets and outbound-only access for private subnets.",
        prerequisites: ["aws-route-tables-and-routing", "aws-public-vs-private-subnets"],
        related: ["aws-network-acls-vs-security-groups", "aws-route-tables-and-routing"],
        recommended: ["aws-network-acls-vs-security-groups", "aws-vpc-peering-and-private-connectivity"]
      },
      {
        id: 32,
        order: 6,
        slug: "aws-network-acls-vs-security-groups",
        title: "Network ACLs vs Security Groups",
        shortTitle: "Network ACLs vs Security Gro...",
        readingTime: 8,
        tags: ["aws", "amazon web services", "cloud computing", "aws networking", "aws vpc"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Compare stateless Network ACLs and stateful Security Groups to implement defense-in-depth.",
        prerequisites: ["aws-internet-gateways-and-nat-gateways", "aws-route-tables-and-routing"],
        related: ["aws-vpc-peering-and-private-connectivity", "aws-internet-gateways-and-nat-gateways"],
        recommended: ["aws-vpc-peering-and-private-connectivity", "aws-dns-with-amazon-route-53"]
      },
      {
        id: 33,
        order: 7,
        slug: "aws-vpc-peering-and-private-connectivity",
        title: "VPC Peering and Private Connectivity",
        shortTitle: "VPC Peering and Private Conn...",
        readingTime: 9,
        tags: ["aws", "amazon web services", "cloud computing", "aws networking", "aws vpc"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to connect two VPCs privately using VPC peering or AWS Transit Gateway.",
        prerequisites: ["aws-network-acls-vs-security-groups", "aws-internet-gateways-and-nat-gateways"],
        related: ["aws-dns-with-amazon-route-53", "aws-network-acls-vs-security-groups"],
        recommended: ["aws-dns-with-amazon-route-53", "aws-vpc-endpoints"]
      },
      {
        id: 34,
        order: 8,
        slug: "aws-dns-with-amazon-route-53",
        title: "DNS with Amazon Route 53",
        shortTitle: "DNS with Amazon Route 53",
        readingTime: 10,
        tags: ["aws", "amazon web services", "cloud computing", "aws networking", "aws vpc"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how to use Route 53 for highly available and scalable Domain Name System (DNS) web services.",
        prerequisites: ["aws-vpc-peering-and-private-connectivity", "aws-network-acls-vs-security-groups"],
        related: ["aws-vpc-endpoints", "aws-vpc-peering-and-private-connectivity"],
        recommended: ["aws-vpc-endpoints", "aws-designing-a-basic-aws-network"]
      },
      {
        id: 35,
        order: 9,
        slug: "aws-vpc-endpoints",
        title: "VPC Endpoints",
        shortTitle: "VPC Endpoints",
        readingTime: 11,
        tags: ["aws", "amazon web services", "cloud computing", "aws networking", "aws vpc"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to privately connect your VPC to supported AWS services without using the public internet.",
        prerequisites: ["aws-dns-with-amazon-route-53", "aws-vpc-peering-and-private-connectivity"],
        related: ["aws-designing-a-basic-aws-network", "aws-dns-with-amazon-route-53"],
        recommended: ["aws-designing-a-basic-aws-network", "aws-aws-storage-services-overview"]
      },
      {
        id: 36,
        order: 10,
        slug: "aws-designing-a-basic-aws-network",
        title: "Designing a Basic AWS Network",
        shortTitle: "Designing a Basic AWS Networ...",
        readingTime: 12,
        tags: ["aws", "amazon web services", "cloud computing", "aws networking", "aws vpc"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Put it all together by designing a secure, highly available, and scalable VPC architecture.",
        prerequisites: ["aws-vpc-endpoints", "aws-dns-with-amazon-route-53"],
        related: ["aws-vpc-endpoints", "aws-aws-storage-services-overview"],
        recommended: ["aws-aws-storage-services-overview", "aws-amazon-s3-fundamentals"]
      }
    ]
  },
  {
    id: "aws-storage",
    title: "AWS Storage",
    order: 5,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 37,
        order: 1,
        slug: "aws-aws-storage-services-overview",
        title: "AWS Storage Services Overview",
        shortTitle: "AWS Storage Services Overview",
        readingTime: 13,
        tags: ["aws", "amazon web services", "cloud computing", "aws storage", "amazon s3"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get a high-level overview of the diverse storage solutions available in AWS.",
        prerequisites: ["aws-designing-a-basic-aws-network", "aws-vpc-endpoints"],
        related: ["aws-amazon-s3-fundamentals", "aws-designing-a-basic-aws-network"],
        recommended: ["aws-amazon-s3-fundamentals", "aws-s3-buckets-and-objects"]
      },
      {
        id: 38,
        order: 2,
        slug: "aws-amazon-s3-fundamentals",
        title: "Amazon S3 Fundamentals",
        shortTitle: "Amazon S3 Fundamentals",
        readingTime: 14,
        tags: ["aws", "amazon web services", "cloud computing", "aws storage", "amazon s3"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn the basics of Amazon Simple Storage Service (S3), the industry-leading object storage service.",
        prerequisites: ["aws-aws-storage-services-overview", "aws-designing-a-basic-aws-network"],
        related: ["aws-s3-buckets-and-objects", "aws-aws-storage-services-overview"],
        recommended: ["aws-s3-buckets-and-objects", "aws-s3-storage-classes"]
      },
      {
        id: 39,
        order: 3,
        slug: "aws-s3-buckets-and-objects",
        title: "S3 Buckets and Objects",
        shortTitle: "S3 Buckets and Objects",
        readingTime: 15,
        tags: ["aws", "amazon web services", "cloud computing", "aws storage", "amazon s3"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the hierarchy of S3, including how buckets and objects are structured and managed.",
        prerequisites: ["aws-amazon-s3-fundamentals", "aws-aws-storage-services-overview"],
        related: ["aws-s3-storage-classes", "aws-amazon-s3-fundamentals"],
        recommended: ["aws-s3-storage-classes", "aws-s3-versioning-and-lifecycle-policies"]
      },
      {
        id: 40,
        order: 4,
        slug: "aws-s3-storage-classes",
        title: "S3 Storage Classes",
        shortTitle: "S3 Storage Classes",
        readingTime: 8,
        tags: ["aws", "amazon web services", "cloud computing", "aws storage", "amazon s3"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the different S3 storage classes to optimize costs based on data access patterns.",
        prerequisites: ["aws-s3-buckets-and-objects", "aws-amazon-s3-fundamentals"],
        related: ["aws-s3-versioning-and-lifecycle-policies", "aws-s3-buckets-and-objects"],
        recommended: ["aws-s3-versioning-and-lifecycle-policies", "aws-s3-security-and-access-control"]
      },
      {
        id: 41,
        order: 5,
        slug: "aws-s3-versioning-and-lifecycle-policies",
        title: "S3 Versioning and Lifecycle Policies",
        shortTitle: "S3 Versioning and Lifecycle ...",
        readingTime: 9,
        tags: ["aws", "amazon web services", "cloud computing", "aws storage", "amazon s3"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to protect data from accidental deletion and automate data transitions using lifecycle policies.",
        prerequisites: ["aws-s3-storage-classes", "aws-s3-buckets-and-objects"],
        related: ["aws-s3-security-and-access-control", "aws-s3-storage-classes"],
        recommended: ["aws-s3-security-and-access-control", "aws-amazon-ebs"]
      },
      {
        id: 42,
        order: 6,
        slug: "aws-s3-security-and-access-control",
        title: "S3 Security and Access Control",
        shortTitle: "S3 Security and Access Contr...",
        readingTime: 10,
        tags: ["aws", "amazon web services", "cloud computing", "aws storage", "amazon s3"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master S3 security features, including bucket policies, IAM policies, and Block Public Access.",
        prerequisites: ["aws-s3-versioning-and-lifecycle-policies", "aws-s3-storage-classes"],
        related: ["aws-amazon-ebs", "aws-s3-versioning-and-lifecycle-policies"],
        recommended: ["aws-amazon-ebs", "aws-amazon-efs"]
      },
      {
        id: 43,
        order: 7,
        slug: "aws-amazon-ebs",
        title: "Amazon EBS",
        shortTitle: "Amazon EBS",
        readingTime: 11,
        tags: ["aws", "amazon web services", "cloud computing", "aws storage", "amazon s3"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand Amazon Elastic Block Store (EBS) and how it provides persistent block storage for EC2.",
        prerequisites: ["aws-s3-security-and-access-control", "aws-s3-versioning-and-lifecycle-policies"],
        related: ["aws-amazon-efs", "aws-s3-security-and-access-control"],
        recommended: ["aws-amazon-efs", "aws-ebs-vs-efs-vs-s3"]
      },
      {
        id: 44,
        order: 8,
        slug: "aws-amazon-efs",
        title: "Amazon EFS",
        shortTitle: "Amazon EFS",
        readingTime: 12,
        tags: ["aws", "amazon web services", "cloud computing", "aws storage", "amazon s3"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn about Amazon Elastic File System (EFS) for scalable, shared file storage across multiple EC2 instances.",
        prerequisites: ["aws-amazon-ebs", "aws-s3-security-and-access-control"],
        related: ["aws-ebs-vs-efs-vs-s3", "aws-amazon-ebs"],
        recommended: ["aws-ebs-vs-efs-vs-s3", "aws-choosing-the-right-aws-storage-service"]
      },
      {
        id: 45,
        order: 9,
        slug: "aws-ebs-vs-efs-vs-s3",
        title: "EBS vs EFS vs S3",
        shortTitle: "EBS vs EFS vs S3",
        readingTime: 13,
        tags: ["aws", "amazon web services", "cloud computing", "aws storage", "amazon s3"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Compare EBS, EFS, and S3 to determine the best storage solution for your specific use case.",
        prerequisites: ["aws-amazon-efs", "aws-amazon-ebs"],
        related: ["aws-choosing-the-right-aws-storage-service", "aws-amazon-efs"],
        recommended: ["aws-choosing-the-right-aws-storage-service", "aws-aws-database-services-overview"]
      },
      {
        id: 46,
        order: 10,
        slug: "aws-choosing-the-right-aws-storage-service",
        title: "Choosing the Right AWS Storage Service",
        shortTitle: "Choosing the Right AWS Stora...",
        readingTime: 14,
        tags: ["aws", "amazon web services", "cloud computing", "aws storage", "amazon s3"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Develop a decision framework for selecting the optimal AWS storage service for your application.",
        prerequisites: ["aws-ebs-vs-efs-vs-s3", "aws-amazon-efs"],
        related: ["aws-ebs-vs-efs-vs-s3", "aws-aws-database-services-overview"],
        recommended: ["aws-aws-database-services-overview", "aws-amazon-rds-fundamentals"]
      }
    ]
  },
  {
    id: "aws-databases",
    title: "AWS Databases",
    order: 6,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 47,
        order: 1,
        slug: "aws-aws-database-services-overview",
        title: "AWS Database Services Overview",
        shortTitle: "AWS Database Services Overvi...",
        readingTime: 15,
        tags: ["aws", "amazon web services", "cloud computing", "aws databases", "amazon rds"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get a high-level overview of the relational and non-relational database services offered by AWS.",
        prerequisites: ["aws-choosing-the-right-aws-storage-service", "aws-ebs-vs-efs-vs-s3"],
        related: ["aws-amazon-rds-fundamentals", "aws-choosing-the-right-aws-storage-service"],
        recommended: ["aws-amazon-rds-fundamentals", "aws-creating-and-connecting-to-an-rds-database"]
      },
      {
        id: 48,
        order: 2,
        slug: "aws-amazon-rds-fundamentals",
        title: "Amazon RDS Fundamentals",
        shortTitle: "Amazon RDS Fundamentals",
        readingTime: 8,
        tags: ["aws", "amazon web services", "cloud computing", "aws databases", "amazon rds"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn the basics of Amazon Relational Database Service (RDS) for managed SQL databases.",
        prerequisites: ["aws-aws-database-services-overview", "aws-choosing-the-right-aws-storage-service"],
        related: ["aws-creating-and-connecting-to-an-rds-database", "aws-aws-database-services-overview"],
        recommended: ["aws-creating-and-connecting-to-an-rds-database", "aws-rds-backups-snapshots-and-multi-az"]
      },
      {
        id: 49,
        order: 3,
        slug: "aws-creating-and-connecting-to-an-rds-database",
        title: "Creating and Connecting to an RDS Database",
        shortTitle: "Creating and Connecting to a...",
        readingTime: 9,
        tags: ["aws", "amazon web services", "cloud computing", "aws databases", "amazon rds"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Step-by-step guide to provisioning an RDS instance and connecting your application to it.",
        prerequisites: ["aws-amazon-rds-fundamentals", "aws-aws-database-services-overview"],
        related: ["aws-rds-backups-snapshots-and-multi-az", "aws-amazon-rds-fundamentals"],
        recommended: ["aws-rds-backups-snapshots-and-multi-az", "aws-amazon-aurora"]
      },
      {
        id: 50,
        order: 4,
        slug: "aws-rds-backups-snapshots-and-multi-az",
        title: "RDS Backups, Snapshots, and Multi-AZ",
        shortTitle: "RDS Backups, Snapshots, and ...",
        readingTime: 10,
        tags: ["aws", "amazon web services", "cloud computing", "aws databases", "amazon rds"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how RDS handles automated backups, manual snapshots, and high availability with Multi-AZ.",
        prerequisites: ["aws-creating-and-connecting-to-an-rds-database", "aws-amazon-rds-fundamentals"],
        related: ["aws-amazon-aurora", "aws-creating-and-connecting-to-an-rds-database"],
        recommended: ["aws-amazon-aurora", "aws-amazon-dynamodb-fundamentals"]
      },
      {
        id: 51,
        order: 5,
        slug: "aws-amazon-aurora",
        title: "Amazon Aurora",
        shortTitle: "Amazon Aurora",
        readingTime: 11,
        tags: ["aws", "amazon web services", "cloud computing", "aws databases", "amazon rds"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover Amazon Aurora, a MySQL and PostgreSQL-compatible relational database built for the cloud.",
        prerequisites: ["aws-rds-backups-snapshots-and-multi-az", "aws-creating-and-connecting-to-an-rds-database"],
        related: ["aws-amazon-dynamodb-fundamentals", "aws-rds-backups-snapshots-and-multi-az"],
        recommended: ["aws-amazon-dynamodb-fundamentals", "aws-dynamodb-tables-items-and-keys"]
      },
      {
        id: 52,
        order: 6,
        slug: "aws-amazon-dynamodb-fundamentals",
        title: "Amazon DynamoDB Fundamentals",
        shortTitle: "Amazon DynamoDB Fundamentals",
        readingTime: 12,
        tags: ["aws", "amazon web services", "cloud computing", "aws databases", "amazon dynamodb"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to Amazon DynamoDB, a fully managed, serverless NoSQL database service.",
        prerequisites: ["aws-amazon-aurora", "aws-rds-backups-snapshots-and-multi-az"],
        related: ["aws-dynamodb-tables-items-and-keys", "aws-amazon-aurora"],
        recommended: ["aws-dynamodb-tables-items-and-keys", "aws-dynamodb-indexes-and-capacity"]
      },
      {
        id: 53,
        order: 7,
        slug: "aws-dynamodb-tables-items-and-keys",
        title: "DynamoDB Tables, Items, and Keys",
        shortTitle: "DynamoDB Tables, Items, and ...",
        readingTime: 13,
        tags: ["aws", "amazon web services", "cloud computing", "aws databases", "amazon dynamodb"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn the core data model of DynamoDB, including tables, items, partition keys, and sort keys.",
        prerequisites: ["aws-amazon-dynamodb-fundamentals", "aws-amazon-aurora"],
        related: ["aws-dynamodb-indexes-and-capacity", "aws-amazon-dynamodb-fundamentals"],
        recommended: ["aws-dynamodb-indexes-and-capacity", "aws-rds-vs-dynamodb"]
      },
      {
        id: 54,
        order: 8,
        slug: "aws-dynamodb-indexes-and-capacity",
        title: "DynamoDB Indexes and Capacity",
        shortTitle: "DynamoDB Indexes and Capacity",
        readingTime: 14,
        tags: ["aws", "amazon web services", "cloud computing", "aws databases", "amazon dynamodb"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how to use Global Secondary Indexes (GSIs) and manage read/write capacity in DynamoDB.",
        prerequisites: ["aws-dynamodb-tables-items-and-keys", "aws-amazon-dynamodb-fundamentals"],
        related: ["aws-rds-vs-dynamodb", "aws-dynamodb-tables-items-and-keys"],
        recommended: ["aws-rds-vs-dynamodb", "aws-choosing-the-right-aws-database"]
      },
      {
        id: 55,
        order: 9,
        slug: "aws-rds-vs-dynamodb",
        title: "RDS vs DynamoDB",
        shortTitle: "RDS vs DynamoDB",
        readingTime: 15,
        tags: ["aws", "amazon web services", "cloud computing", "aws databases", "amazon rds"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Compare relational (RDS) and non-relational (DynamoDB) databases to choose the right fit for your data.",
        prerequisites: ["aws-dynamodb-indexes-and-capacity", "aws-dynamodb-tables-items-and-keys"],
        related: ["aws-choosing-the-right-aws-database", "aws-dynamodb-indexes-and-capacity"],
        recommended: ["aws-choosing-the-right-aws-database", "aws-what-is-serverless-computing"]
      },
      {
        id: 56,
        order: 10,
        slug: "aws-choosing-the-right-aws-database",
        title: "Choosing the Right AWS Database",
        shortTitle: "Choosing the Right AWS Datab...",
        readingTime: 8,
        tags: ["aws", "amazon web services", "cloud computing", "aws databases", "amazon rds"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Develop a decision framework for selecting the optimal AWS database service for your workload.",
        prerequisites: ["aws-rds-vs-dynamodb", "aws-dynamodb-indexes-and-capacity"],
        related: ["aws-rds-vs-dynamodb", "aws-what-is-serverless-computing"],
        recommended: ["aws-what-is-serverless-computing", "aws-aws-lambda-fundamentals"]
      }
    ]
  },
  {
    id: "aws-serverless-and-application-services",
    title: "AWS Serverless and Application Services",
    order: 7,
    difficulty: "Advanced",
    lessons: [
      {
        id: 57,
        order: 1,
        slug: "aws-what-is-serverless-computing",
        title: "What is Serverless Computing?",
        shortTitle: "What is Serverless Computing",
        readingTime: 9,
        tags: ["aws", "amazon web services", "cloud computing", "aws serverless", "aws lambda"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to the serverless computing paradigm and how it eliminates server management.",
        prerequisites: ["aws-choosing-the-right-aws-database", "aws-rds-vs-dynamodb"],
        related: ["aws-aws-lambda-fundamentals", "aws-choosing-the-right-aws-database"],
        recommended: ["aws-aws-lambda-fundamentals", "aws-lambda-functions-events-and-execution"]
      },
      {
        id: 58,
        order: 2,
        slug: "aws-aws-lambda-fundamentals",
        title: "AWS Lambda Fundamentals",
        shortTitle: "AWS Lambda Fundamentals",
        readingTime: 10,
        tags: ["aws", "amazon web services", "cloud computing", "aws serverless", "aws lambda"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn the basics of AWS Lambda, the core serverless compute service that runs code in response to events.",
        prerequisites: ["aws-what-is-serverless-computing", "aws-choosing-the-right-aws-database"],
        related: ["aws-lambda-functions-events-and-execution", "aws-what-is-serverless-computing"],
        recommended: ["aws-lambda-functions-events-and-execution", "aws-lambda-environment-variables-and-layers"]
      },
      {
        id: 59,
        order: 3,
        slug: "aws-lambda-functions-events-and-execution",
        title: "Lambda Functions, Events, and Execution",
        shortTitle: "Lambda Functions, Events, an...",
        readingTime: 11,
        tags: ["aws", "amazon web services", "cloud computing", "aws serverless", "aws lambda"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the lifecycle of a Lambda function, including triggers, event payloads, and execution contexts.",
        prerequisites: ["aws-aws-lambda-fundamentals", "aws-what-is-serverless-computing"],
        related: ["aws-lambda-environment-variables-and-layers", "aws-aws-lambda-fundamentals"],
        recommended: ["aws-lambda-environment-variables-and-layers", "aws-amazon-api-gateway"]
      },
      {
        id: 60,
        order: 4,
        slug: "aws-lambda-environment-variables-and-layers",
        title: "Lambda Environment Variables and Layers",
        shortTitle: "Lambda Environment Variables...",
        readingTime: 12,
        tags: ["aws", "amazon web services", "cloud computing", "aws serverless", "aws lambda"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to manage configuration and share code libraries across Lambda functions using environment variables and layers.",
        prerequisites: ["aws-lambda-functions-events-and-execution", "aws-aws-lambda-fundamentals"],
        related: ["aws-amazon-api-gateway", "aws-lambda-functions-events-and-execution"],
        recommended: ["aws-amazon-api-gateway", "aws-event-driven-architecture-with-eventbridge"]
      },
      {
        id: 61,
        order: 5,
        slug: "aws-amazon-api-gateway",
        title: "Amazon API Gateway",
        shortTitle: "Amazon API Gateway",
        readingTime: 13,
        tags: ["aws", "amazon web services", "cloud computing", "aws serverless", "aws lambda"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how to create, publish, and secure APIs at any scale using Amazon API Gateway.",
        prerequisites: ["aws-lambda-environment-variables-and-layers", "aws-lambda-functions-events-and-execution"],
        related: ["aws-event-driven-architecture-with-eventbridge", "aws-lambda-environment-variables-and-layers"],
        recommended: ["aws-event-driven-architecture-with-eventbridge", "aws-amazon-sns-and-pubsub-messaging"]
      },
      {
        id: 62,
        order: 6,
        slug: "aws-event-driven-architecture-with-eventbridge",
        title: "Event-Driven Architecture with EventBridge",
        shortTitle: "Event-Driven Architecture wi...",
        readingTime: 14,
        tags: ["aws", "amazon web services", "cloud computing", "aws serverless", "aws lambda"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to build scalable, decoupled applications using Amazon EventBridge as a central event bus.",
        prerequisites: ["aws-amazon-api-gateway", "aws-lambda-environment-variables-and-layers"],
        related: ["aws-amazon-sns-and-pubsub-messaging", "aws-amazon-api-gateway"],
        recommended: ["aws-amazon-sns-and-pubsub-messaging", "aws-amazon-sqs-and-message-queues"]
      },
      {
        id: 63,
        order: 7,
        slug: "aws-amazon-sns-and-pubsub-messaging",
        title: "Amazon SNS and Pub/Sub Messaging",
        shortTitle: "Amazon SNS and Pub/Sub Mes...",
        readingTime: 15,
        tags: ["aws", "amazon web services", "cloud computing", "aws serverless", "aws lambda"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand Amazon Simple Notification Service (SNS) for fan-out messaging and push notifications.",
        prerequisites: ["aws-event-driven-architecture-with-eventbridge", "aws-amazon-api-gateway"],
        related: ["aws-amazon-sqs-and-message-queues", "aws-event-driven-architecture-with-eventbridge"],
        recommended: ["aws-amazon-sqs-and-message-queues", "aws-building-a-serverless-application"]
      },
      {
        id: 64,
        order: 8,
        slug: "aws-amazon-sqs-and-message-queues",
        title: "Amazon SQS and Message Queues",
        shortTitle: "Amazon SQS and Message Queue...",
        readingTime: 8,
        tags: ["aws", "amazon web services", "cloud computing", "aws serverless", "aws lambda"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to use Amazon Simple Queue Service (SQS) to decouple and scale microservices and distributed systems.",
        prerequisites: ["aws-amazon-sns-and-pubsub-messaging", "aws-event-driven-architecture-with-eventbridge"],
        related: ["aws-building-a-serverless-application", "aws-amazon-sns-and-pubsub-messaging"],
        recommended: ["aws-building-a-serverless-application", "aws-serverless-architecture-patterns"]
      },
      {
        id: 65,
        order: 9,
        slug: "aws-building-a-serverless-application",
        title: "Building a Serverless Application",
        shortTitle: "Building a Serverless Applic...",
        readingTime: 9,
        tags: ["aws", "amazon web services", "cloud computing", "aws serverless", "aws lambda"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Put it all together by building a complete, event-driven serverless application on AWS.",
        prerequisites: ["aws-amazon-sqs-and-message-queues", "aws-amazon-sns-and-pubsub-messaging"],
        related: ["aws-serverless-architecture-patterns", "aws-amazon-sqs-and-message-queues"],
        recommended: ["aws-serverless-architecture-patterns", "aws-containers-on-aws"]
      },
      {
        id: 66,
        order: 10,
        slug: "aws-serverless-architecture-patterns",
        title: "Serverless Architecture Patterns",
        shortTitle: "Serverless Architecture Patt...",
        readingTime: 10,
        tags: ["aws", "amazon web services", "cloud computing", "aws serverless", "aws lambda"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore common serverless design patterns, including the Strangler Fig pattern and event sourcing.",
        prerequisites: ["aws-building-a-serverless-application", "aws-amazon-sqs-and-message-queues"],
        related: ["aws-building-a-serverless-application", "aws-containers-on-aws"],
        recommended: ["aws-containers-on-aws", "aws-amazon-ecs-fundamentals"]
      }
    ]
  },
  {
    id: "aws-containers-and-modern-compute",
    title: "AWS Containers and Modern Compute",
    order: 8,
    difficulty: "Advanced",
    lessons: [
      {
        id: 67,
        order: 1,
        slug: "aws-containers-on-aws",
        title: "Containers on AWS",
        shortTitle: "Containers on AWS",
        readingTime: 11,
        tags: ["aws", "amazon web services", "cloud computing", "aws containers", "amazon ecs"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to containerization and the managed container services available on AWS.",
        prerequisites: ["aws-serverless-architecture-patterns", "aws-building-a-serverless-application"],
        related: ["aws-amazon-ecs-fundamentals", "aws-serverless-architecture-patterns"],
        recommended: ["aws-amazon-ecs-fundamentals", "aws-ecs-tasks-services-and-clusters"]
      },
      {
        id: 68,
        order: 2,
        slug: "aws-amazon-ecs-fundamentals",
        title: "Amazon ECS Fundamentals",
        shortTitle: "Amazon ECS Fundamentals",
        readingTime: 12,
        tags: ["aws", "amazon web services", "cloud computing", "aws containers", "amazon ecs"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn the basics of Amazon Elastic Container Service (ECS) for running Docker containers.",
        prerequisites: ["aws-containers-on-aws", "aws-serverless-architecture-patterns"],
        related: ["aws-ecs-tasks-services-and-clusters", "aws-containers-on-aws"],
        recommended: ["aws-ecs-tasks-services-and-clusters", "aws-aws-fargate"]
      },
      {
        id: 69,
        order: 3,
        slug: "aws-ecs-tasks-services-and-clusters",
        title: "ECS Tasks, Services, and Clusters",
        shortTitle: "ECS Tasks, Services, and Clu...",
        readingTime: 13,
        tags: ["aws", "amazon web services", "cloud computing", "aws containers", "amazon ecs"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the core ECS architecture, including how tasks, services, and clusters interact.",
        prerequisites: ["aws-amazon-ecs-fundamentals", "aws-containers-on-aws"],
        related: ["aws-aws-fargate", "aws-amazon-ecs-fundamentals"],
        recommended: ["aws-aws-fargate", "aws-amazon-ecr"]
      },
      {
        id: 70,
        order: 4,
        slug: "aws-aws-fargate",
        title: "AWS Fargate",
        shortTitle: "AWS Fargate",
        readingTime: 14,
        tags: ["aws", "amazon web services", "cloud computing", "aws containers", "amazon ecs"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover AWS Fargate, the serverless compute engine for containers that removes the need to manage EC2 instances.",
        prerequisites: ["aws-ecs-tasks-services-and-clusters", "aws-amazon-ecs-fundamentals"],
        related: ["aws-amazon-ecr", "aws-ecs-tasks-services-and-clusters"],
        recommended: ["aws-amazon-ecr", "aws-amazon-eks-overview"]
      },
      {
        id: 71,
        order: 5,
        slug: "aws-amazon-ecr",
        title: "Amazon ECR",
        shortTitle: "Amazon ECR",
        readingTime: 15,
        tags: ["aws", "amazon web services", "cloud computing", "aws containers", "amazon ecs"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to store, manage, and deploy container images using Amazon Elastic Container Registry (ECR).",
        prerequisites: ["aws-aws-fargate", "aws-ecs-tasks-services-and-clusters"],
        related: ["aws-amazon-eks-overview", "aws-aws-fargate"],
        recommended: ["aws-amazon-eks-overview", "aws-ecs-vs-eks-vs-fargate"]
      },
      {
        id: 72,
        order: 6,
        slug: "aws-amazon-eks-overview",
        title: "Amazon EKS Overview",
        shortTitle: "Amazon EKS Overview",
        readingTime: 8,
        tags: ["aws", "amazon web services", "cloud computing", "aws containers", "amazon ecs"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to Amazon Elastic Kubernetes Service (EKS) for running managed Kubernetes clusters.",
        prerequisites: ["aws-amazon-ecr", "aws-aws-fargate"],
        related: ["aws-ecs-vs-eks-vs-fargate", "aws-amazon-ecr"],
        recommended: ["aws-ecs-vs-eks-vs-fargate", "aws-deploying-a-containerized-application-on-aws"]
      },
      {
        id: 73,
        order: 7,
        slug: "aws-ecs-vs-eks-vs-fargate",
        title: "ECS vs EKS vs Fargate",
        shortTitle: "ECS vs EKS vs Fargate",
        readingTime: 9,
        tags: ["aws", "amazon web services", "cloud computing", "aws containers", "amazon ecs"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Compare ECS, EKS, and Fargate to determine the best container orchestration strategy for your needs.",
        prerequisites: ["aws-amazon-eks-overview", "aws-amazon-ecr"],
        related: ["aws-deploying-a-containerized-application-on-aws", "aws-amazon-eks-overview"],
        recommended: ["aws-deploying-a-containerized-application-on-aws", "aws-aws-application-deployment-approaches"]
      },
      {
        id: 74,
        order: 8,
        slug: "aws-deploying-a-containerized-application-on-aws",
        title: "Deploying a Containerized Application on AWS",
        shortTitle: "Deploying a Containerized Ap...",
        readingTime: 10,
        tags: ["aws", "amazon web services", "cloud computing", "aws containers", "amazon ecs"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Step-by-step guide to deploying a Dockerized application using ECS and Fargate.",
        prerequisites: ["aws-ecs-vs-eks-vs-fargate", "aws-amazon-eks-overview"],
        related: ["aws-ecs-vs-eks-vs-fargate", "aws-aws-application-deployment-approaches"],
        recommended: ["aws-aws-application-deployment-approaches", "aws-elastic-beanstalk-fundamentals"]
      }
    ]
  },
  {
    id: "aws-deployment-and-infrastructure-as-code",
    title: "AWS Deployment and Infrastructure as Code",
    order: 9,
    difficulty: "Advanced",
    lessons: [
      {
        id: 75,
        order: 1,
        slug: "aws-aws-application-deployment-approaches",
        title: "AWS Application Deployment Approaches",
        shortTitle: "AWS Application Deployment A...",
        readingTime: 11,
        tags: ["aws", "amazon web services", "cloud computing", "aws deployment", "infrastructure as code"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the different strategies for deploying applications on AWS, from manual to fully automated.",
        prerequisites: ["aws-deploying-a-containerized-application-on-aws", "aws-ecs-vs-eks-vs-fargate"],
        related: ["aws-elastic-beanstalk-fundamentals", "aws-deploying-a-containerized-application-on-aws"],
        recommended: ["aws-elastic-beanstalk-fundamentals", "aws-aws-cloudformation"]
      },
      {
        id: 76,
        order: 2,
        slug: "aws-elastic-beanstalk-fundamentals",
        title: "Elastic Beanstalk Fundamentals",
        shortTitle: "Elastic Beanstalk Fundamenta...",
        readingTime: 12,
        tags: ["aws", "amazon web services", "cloud computing", "aws deployment", "infrastructure as code"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to use AWS Elastic Beanstalk for quick deployment and management of web applications.",
        prerequisites: ["aws-aws-application-deployment-approaches", "aws-deploying-a-containerized-application-on-aws"],
        related: ["aws-aws-cloudformation", "aws-aws-application-deployment-approaches"],
        recommended: ["aws-aws-cloudformation", "aws-cloudformation-templates-and-stacks"]
      },
      {
        id: 77,
        order: 3,
        slug: "aws-aws-cloudformation",
        title: "AWS CloudFormation",
        shortTitle: "AWS CloudFormation",
        readingTime: 13,
        tags: ["aws", "amazon web services", "cloud computing", "aws deployment", "infrastructure as code"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to AWS CloudFormation, the native Infrastructure as Code (IaC) service.",
        prerequisites: ["aws-elastic-beanstalk-fundamentals", "aws-aws-application-deployment-approaches"],
        related: ["aws-cloudformation-templates-and-stacks", "aws-elastic-beanstalk-fundamentals"],
        recommended: ["aws-cloudformation-templates-and-stacks", "aws-parameters-outputs-and-resources"]
      },
      {
        id: 78,
        order: 4,
        slug: "aws-cloudformation-templates-and-stacks",
        title: "CloudFormation Templates and Stacks",
        shortTitle: "CloudFormation Templates and...",
        readingTime: 14,
        tags: ["aws", "amazon web services", "cloud computing", "aws deployment", "infrastructure as code"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how to write YAML/JSON templates and manage resources using CloudFormation stacks.",
        prerequisites: ["aws-aws-cloudformation", "aws-elastic-beanstalk-fundamentals"],
        related: ["aws-parameters-outputs-and-resources", "aws-aws-cloudformation"],
        recommended: ["aws-parameters-outputs-and-resources", "aws-infrastructure-as-code-concepts"]
      },
      {
        id: 79,
        order: 5,
        slug: "aws-parameters-outputs-and-resources",
        title: "Parameters, Outputs, and Resources",
        shortTitle: "Parameters, Outputs, and Res...",
        readingTime: 15,
        tags: ["aws", "amazon web services", "cloud computing", "aws deployment", "infrastructure as code"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn the core components of a CloudFormation template to make your infrastructure dynamic and reusable.",
        prerequisites: ["aws-cloudformation-templates-and-stacks", "aws-aws-cloudformation"],
        related: ["aws-infrastructure-as-code-concepts", "aws-cloudformation-templates-and-stacks"],
        recommended: ["aws-infrastructure-as-code-concepts", "aws-aws-cli-fundamentals"]
      },
      {
        id: 80,
        order: 6,
        slug: "aws-infrastructure-as-code-concepts",
        title: "Infrastructure as Code Concepts",
        shortTitle: "Infrastructure as Code Conce...",
        readingTime: 8,
        tags: ["aws", "amazon web services", "cloud computing", "aws deployment", "infrastructure as code"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the core principles of IaC, including version control, idempotency, and declarative syntax.",
        prerequisites: ["aws-parameters-outputs-and-resources", "aws-cloudformation-templates-and-stacks"],
        related: ["aws-aws-cli-fundamentals", "aws-parameters-outputs-and-resources"],
        recommended: ["aws-aws-cli-fundamentals", "aws-aws-sdks-and-programmatic-access"]
      },
      {
        id: 81,
        order: 7,
        slug: "aws-aws-cli-fundamentals",
        title: "AWS CLI Fundamentals",
        shortTitle: "AWS CLI Fundamentals",
        readingTime: 9,
        tags: ["aws", "amazon web services", "cloud computing", "aws deployment", "infrastructure as code"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to interact with AWS services directly from your terminal using the AWS Command Line Interface.",
        prerequisites: ["aws-infrastructure-as-code-concepts", "aws-parameters-outputs-and-resources"],
        related: ["aws-aws-sdks-and-programmatic-access", "aws-infrastructure-as-code-concepts"],
        recommended: ["aws-aws-sdks-and-programmatic-access", "aws-terraform-on-aws"]
      },
      {
        id: 82,
        order: 8,
        slug: "aws-aws-sdks-and-programmatic-access",
        title: "AWS SDKs and Programmatic Access",
        shortTitle: "AWS SDKs and Programmatic Ac...",
        readingTime: 10,
        tags: ["aws", "amazon web services", "cloud computing", "aws deployment", "infrastructure as code"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how to integrate AWS services into your applications using AWS SDKs for various programming languages.",
        prerequisites: ["aws-aws-cli-fundamentals", "aws-infrastructure-as-code-concepts"],
        related: ["aws-terraform-on-aws", "aws-aws-cli-fundamentals"],
        recommended: ["aws-terraform-on-aws", "aws-infrastructure-automation-best-practices"]
      },
      {
        id: 83,
        order: 9,
        slug: "aws-terraform-on-aws",
        title: "Terraform on AWS",
        shortTitle: "Terraform on AWS",
        readingTime: 11,
        tags: ["aws", "amazon web services", "cloud computing", "aws deployment", "infrastructure as code"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to use HashiCorp Terraform, a popular third-party IaC tool, to provision AWS resources.",
        prerequisites: ["aws-aws-sdks-and-programmatic-access", "aws-aws-cli-fundamentals"],
        related: ["aws-infrastructure-automation-best-practices", "aws-aws-sdks-and-programmatic-access"],
        recommended: ["aws-infrastructure-automation-best-practices", "aws-aws-security-fundamentals"]
      },
      {
        id: 84,
        order: 10,
        slug: "aws-infrastructure-automation-best-practices",
        title: "Infrastructure Automation Best Practices",
        shortTitle: "Infrastructure Automation Be...",
        readingTime: 12,
        tags: ["aws", "amazon web services", "cloud computing", "aws deployment", "infrastructure as code"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Review best practices for automating infrastructure provisioning, including CI/CD integration and state management.",
        prerequisites: ["aws-terraform-on-aws", "aws-aws-sdks-and-programmatic-access"],
        related: ["aws-terraform-on-aws", "aws-aws-security-fundamentals"],
        recommended: ["aws-aws-security-fundamentals", "aws-aws-shared-responsibility-model"]
      }
    ]
  },
  {
    id: "aws-security-monitoring-and-cost-management",
    title: "AWS Security, Monitoring, and Cost Management",
    order: 10,
    difficulty: "Advanced",
    lessons: [
      {
        id: 85,
        order: 1,
        slug: "aws-aws-security-fundamentals",
        title: "AWS Security Fundamentals",
        shortTitle: "AWS Security Fundamentals",
        readingTime: 13,
        tags: ["aws", "amazon web services", "cloud computing", "aws monitoring", "aws security"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get a comprehensive overview of the core security principles and services in AWS.",
        prerequisites: ["aws-infrastructure-automation-best-practices", "aws-terraform-on-aws"],
        related: ["aws-aws-shared-responsibility-model", "aws-infrastructure-automation-best-practices"],
        recommended: ["aws-aws-shared-responsibility-model", "aws-data-encryption-and-aws-kms"]
      },
      {
        id: 86,
        order: 2,
        slug: "aws-aws-shared-responsibility-model",
        title: "AWS Shared Responsibility Model",
        shortTitle: "AWS Shared Responsibility Mo...",
        readingTime: 14,
        tags: ["aws", "amazon web services", "cloud computing", "aws monitoring", "aws security"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the division of security responsibilities between AWS and the customer.",
        prerequisites: ["aws-aws-security-fundamentals", "aws-infrastructure-automation-best-practices"],
        related: ["aws-data-encryption-and-aws-kms", "aws-aws-security-fundamentals"],
        recommended: ["aws-data-encryption-and-aws-kms", "aws-aws-secrets-manager"]
      },
      {
        id: 87,
        order: 3,
        slug: "aws-data-encryption-and-aws-kms",
        title: "Data Encryption and AWS KMS",
        shortTitle: "Data Encryption and AWS KMS",
        readingTime: 15,
        tags: ["aws", "amazon web services", "cloud computing", "aws monitoring", "aws security"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to protect data at rest and in transit using AWS Key Management Service (KMS).",
        prerequisites: ["aws-aws-shared-responsibility-model", "aws-aws-security-fundamentals"],
        related: ["aws-aws-secrets-manager", "aws-aws-shared-responsibility-model"],
        recommended: ["aws-aws-secrets-manager", "aws-amazon-cloudwatch"]
      },
      {
        id: 88,
        order: 4,
        slug: "aws-aws-secrets-manager",
        title: "AWS Secrets Manager",
        shortTitle: "AWS Secrets Manager",
        readingTime: 8,
        tags: ["aws", "amazon web services", "cloud computing", "aws monitoring", "aws security"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how to securely store, manage, and rotate database credentials and API keys using Secrets Manager.",
        prerequisites: ["aws-data-encryption-and-aws-kms", "aws-aws-shared-responsibility-model"],
        related: ["aws-amazon-cloudwatch", "aws-data-encryption-and-aws-kms"],
        recommended: ["aws-amazon-cloudwatch", "aws-aws-cloudtrail"]
      },
      {
        id: 89,
        order: 5,
        slug: "aws-amazon-cloudwatch",
        title: "Amazon CloudWatch",
        shortTitle: "Amazon CloudWatch",
        readingTime: 9,
        tags: ["aws", "amazon web services", "cloud computing", "aws monitoring", "aws security"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to monitor AWS resources and applications in real-time using Amazon CloudWatch.",
        prerequisites: ["aws-aws-secrets-manager", "aws-data-encryption-and-aws-kms"],
        related: ["aws-aws-cloudtrail", "aws-aws-secrets-manager"],
        recommended: ["aws-aws-cloudtrail", "aws-aws-config-and-compliance"]
      },
      {
        id: 90,
        order: 6,
        slug: "aws-aws-cloudtrail",
        title: "AWS CloudTrail",
        shortTitle: "AWS CloudTrail",
        readingTime: 10,
        tags: ["aws", "amazon web services", "cloud computing", "aws monitoring", "aws security"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how to enable governance, compliance, and operational auditing with AWS CloudTrail.",
        prerequisites: ["aws-amazon-cloudwatch", "aws-aws-secrets-manager"],
        related: ["aws-aws-config-and-compliance", "aws-amazon-cloudwatch"],
        recommended: ["aws-aws-config-and-compliance", "aws-aws-trusted-advisor"]
      },
      {
        id: 91,
        order: 7,
        slug: "aws-aws-config-and-compliance",
        title: "AWS Config and Compliance",
        shortTitle: "AWS Config and Compliance",
        readingTime: 11,
        tags: ["aws", "amazon web services", "cloud computing", "aws monitoring", "aws security"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to assess, audit, and evaluate the configurations of your AWS resources using AWS Config.",
        prerequisites: ["aws-aws-cloudtrail", "aws-amazon-cloudwatch"],
        related: ["aws-aws-trusted-advisor", "aws-aws-cloudtrail"],
        recommended: ["aws-aws-trusted-advisor", "aws-aws-pricing-and-cost-management"]
      },
      {
        id: 92,
        order: 8,
        slug: "aws-aws-trusted-advisor",
        title: "AWS Trusted Advisor",
        shortTitle: "AWS Trusted Advisor",
        readingTime: 12,
        tags: ["aws", "amazon web services", "cloud computing", "aws monitoring", "aws security"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how to use Trusted Advisor to optimize performance, security, and cost in your AWS environment.",
        prerequisites: ["aws-aws-config-and-compliance", "aws-aws-cloudtrail"],
        related: ["aws-aws-pricing-and-cost-management", "aws-aws-config-and-compliance"],
        recommended: ["aws-aws-pricing-and-cost-management", "aws-aws-well-architected-framework"]
      },
      {
        id: 93,
        order: 9,
        slug: "aws-aws-pricing-and-cost-management",
        title: "AWS Pricing and Cost Management",
        shortTitle: "AWS Pricing and Cost Managem...",
        readingTime: 13,
        tags: ["aws", "amazon web services", "cloud computing", "aws monitoring", "aws security"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn strategies and tools for monitoring, analyzing, and optimizing your AWS cloud spending.",
        prerequisites: ["aws-aws-trusted-advisor", "aws-aws-config-and-compliance"],
        related: ["aws-aws-well-architected-framework", "aws-aws-trusted-advisor"],
        recommended: ["aws-aws-well-architected-framework", "aws-aws-security-fundamentals"]
      },
      {
        id: 94,
        order: 10,
        slug: "aws-aws-well-architected-framework",
        title: "AWS Well-Architected Framework",
        shortTitle: "AWS Well-Architected Framewo...",
        readingTime: 14,
        tags: ["aws", "amazon web services", "cloud computing", "aws monitoring", "aws security"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the six pillars of the AWS Well-Architected Framework to build secure, high-performing, and resilient systems.",
        prerequisites: ["aws-aws-pricing-and-cost-management", "aws-aws-trusted-advisor"],
        related: ["aws-aws-pricing-and-cost-management", "aws-aws-security-fundamentals"],
        recommended: ["aws-aws-security-fundamentals", "aws-aws-shared-responsibility-model"]
      }
    ]
  }
];

export const resources = [
  {
    id: "aws-architecture-and-design",
    title: "AWS Architecture & Design",
    order: 1,
    items: [
      {
        id: 95,
        order: 1,
        slug: "aws-well-architected-framework-pillars",
        title: "AWS Well-Architected Framework Pillars",
        shortTitle: "Well-Architected",
        type: "article",
        readingTime: 12,
        tags: ["aws", "architecture", "well-architected framework", "best practices", "cloud design"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the five pillars of the AWS Well-Architected Framework to build secure, high-performing, resilient, and efficient infrastructure."
      },
      {
        id: 96,
        order: 2,
        slug: "aws-high-availability-fault-tolerance",
        title: "High Availability and Fault Tolerance",
        shortTitle: "HA & Fault Tolerance",
        type: "article",
        readingTime: 10,
        tags: ["aws", "high availability", "fault tolerance", "resilience", "architecture"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Design highly available and fault-tolerant systems on AWS using multi-AZ deployments, auto-recovery, and redundancy strategies."
      },
      {
        id: 97,
        order: 3,
        slug: "aws-scalability-elasticity",
        title: "Scalability and Elasticity",
        shortTitle: "Scalability",
        type: "article",
        readingTime: 10,
        tags: ["aws", "scalability", "elasticity", "auto scaling", "architecture", "performance"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to build scalable and elastic architectures that automatically adapt to changing demand using AWS services."
      },
      {
        id: 98,
        order: 4,
        slug: "aws-disaster-recovery-strategies",
        title: "AWS Disaster Recovery Strategies",
        shortTitle: "Disaster Recovery",
        type: "article",
        readingTime: 12,
        tags: ["aws", "disaster recovery", "dr", "backup", "resilience", "business continuity"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore AWS disaster recovery strategies from backup and restore to active-active architectures for business continuity."
      },
      {
        id: 99,
        order: 5,
        slug: "aws-designing-multi-tier-architectures",
        title: "Designing Multi-Tier AWS Architectures",
        shortTitle: "Multi-Tier Design",
        type: "article",
        readingTime: 12,
        tags: ["aws", "multi-tier", "architecture", "web app", "3-tier", "design"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Design robust multi-tier architectures on AWS separating presentation, application, and data layers for maintainability."
      },
    ]
  },

  {
    id: "aws-advanced-networking",
    title: "Advanced Networking",
    order: 2,
    items: [
      {
        id: 100,
        order: 1,
        slug: "aws-transit-gateway",
        title: "AWS Transit Gateway",
        shortTitle: "Transit Gateway",
        type: "article",
        readingTime: 10,
        tags: ["aws", "transit gateway", "networking", "vpc", "hybrid cloud", "connectivity"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Centralize VPC and on-premises connectivity using AWS Transit Gateway for scalable and manageable network architectures."
      },
      {
        id: 101,
        order: 2,
        slug: "aws-site-to-site-vpn-direct-connect",
        title: "Site-to-Site VPN and Direct Connect",
        shortTitle: "VPN & Direct Connect",
        type: "article",
        readingTime: 12,
        tags: ["aws", "vpn", "direct connect", "hybrid", "networking", "private connectivity"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Establish secure and dedicated network connections between on-premises data centers and AWS using Site-to-Site VPN and Direct Connect."
      },
      {
        id: 102,
        order: 3,
        slug: "aws-cloudfront-content-delivery",
        title: "CloudFront and Content Delivery",
        shortTitle: "CloudFront",
        type: "article",
        readingTime: 10,
        tags: ["aws", "cloudfront", "cdn", "content delivery", "edge", "performance"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Accelerate content delivery globally with AWS CloudFront, edge caching, and origin shield for low-latency user experiences."
      },
      {
        id: 103,
        order: 4,
        slug: "aws-global-accelerator",
        title: "AWS Global Accelerator",
        shortTitle: "Global Accelerator",
        type: "article",
        readingTime: 10,
        tags: ["aws", "global accelerator", "networking", "performance", "anycast", "routing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Improve global application availability and performance using AWS Global Accelerator with static IP addresses and intelligent routing."
      },
      {
        id: 104,
        order: 5,
        slug: "aws-advanced-route53-routing",
        title: "Advanced Route 53 Routing",
        shortTitle: "Route 53 Routing",
        type: "article",
        readingTime: 10,
        tags: ["aws", "route 53", "dns", "routing", "failover", "latency", "geolocation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Implement advanced DNS routing policies with Route 53 including latency-based, geolocation, weighted, and failover routing."
      },
    ]
  },

  {
    id: "aws-devops-and-automation",
    title: "DevOps & Automation on AWS",
    order: 3,
    items: [
      {
        id: 105,
        order: 1,
        slug: "aws-codepipeline-cicd",
        title: "AWS CodePipeline and CI/CD",
        shortTitle: "CodePipeline",
        type: "article",
        readingTime: 12,
        tags: ["aws", "codepipeline", "cicd", "devops", "automation", "deployment"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Build continuous integration and delivery pipelines with AWS CodePipeline integrated with CodeBuild, CodeDeploy, and third-party tools."
      },
      {
        id: 106,
        order: 2,
        slug: "aws-codebuild",
        title: "AWS CodeBuild",
        shortTitle: "CodeBuild",
        type: "article",
        readingTime: 10,
        tags: ["aws", "codebuild", "build", "ci", "devops", "compilation", "testing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Compile source code, run tests, and produce deployment-ready artifacts using AWS CodeBuild's fully managed build service."
      },
      {
        id: 107,
        order: 3,
        slug: "aws-codedeploy",
        title: "AWS CodeDeploy",
        shortTitle: "CodeDeploy",
        type: "article",
        readingTime: 10,
        tags: ["aws", "codedeploy", "deployment", "devops", "blue green", "in-place", "automation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Automate application deployments to EC2, Lambda, and ECS with AWS CodeDeploy supporting blue/green and rolling updates."
      },
      {
        id: 108,
        order: 4,
        slug: "aws-systems-manager",
        title: "AWS Systems Manager",
        shortTitle: "Systems Manager",
        type: "article",
        readingTime: 10,
        tags: ["aws", "systems manager", "ssm", "operations", "automation", "patching", "run command"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Manage AWS infrastructure at scale using Systems Manager for patching, automation, Session Manager, and operational insights."
      },
      {
        id: 109,
        order: 5,
        slug: "aws-devops-deployment-patterns",
        title: "AWS DevOps and Deployment Patterns",
        shortTitle: "DevOps Patterns",
        type: "article",
        readingTime: 12,
        tags: ["aws", "devops", "deployment patterns", "automation", "best practices", "infrastructure"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Apply proven DevOps and deployment patterns on AWS including GitOps, immutable infrastructure, and canary releases."
      },
    ]
  },

  {
    id: "aws-data-analytics-and-ai",
    title: "Data, Analytics & AI on AWS",
    order: 4,
    items: [
      {
        id: 110,
        order: 1,
        slug: "aws-amazon-redshift",
        title: "Amazon Redshift",
        shortTitle: "Redshift",
        type: "article",
        readingTime: 10,
        tags: ["aws", "redshift", "data warehouse", "analytics", "sql", "big data"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Analyze petabyte-scale data with Amazon Redshift, a fully managed cloud data warehouse optimized for complex queries."
      },
      {
        id: 111,
        order: 2,
        slug: "aws-glue",
        title: "AWS Glue",
        shortTitle: "Glue",
        type: "article",
        readingTime: 10,
        tags: ["aws", "glue", "etl", "data integration", "serverless", "analytics", "crawler"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Build serverless ETL pipelines and data catalogs with AWS Glue for preparing and transforming data across your lake and warehouse."
      },
      {
        id: 112,
        order: 3,
        slug: "aws-amazon-athena",
        title: "Amazon Athena",
        shortTitle: "Athena",
        type: "article",
        readingTime: 8,
        tags: ["aws", "athena", "serverless", "query", "s3", "analytics", "sql"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Run interactive SQL queries directly on data stored in Amazon S3 using serverless Athena without managing infrastructure."
      },
      {
        id: 113,
        order: 4,
        slug: "aws-amazon-sagemaker",
        title: "Amazon SageMaker",
        shortTitle: "SageMaker",
        type: "article",
        readingTime: 12,
        tags: ["aws", "sagemaker", "machine learning", "mlops", "ai", "model training"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Build, train, and deploy machine learning models at scale using Amazon SageMaker's fully managed ML platform."
      },
      {
        id: 114,
        order: 5,
        slug: "aws-generative-ai-services",
        title: "Generative AI Services on AWS",
        shortTitle: "Generative AI",
        type: "article",
        readingTime: 10,
        tags: ["aws", "generative ai", "bedrock", "ai", "machine learning", "foundation models"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore AWS generative AI services including Amazon Bedrock and foundation models for building intelligent applications."
      },
    ]
  },

  {
    id: "aws-specialized-topics",
    title: "Specialized AWS Topics",
    order: 5,
    items: [
      {
        id: 115,
        order: 1,
        slug: "aws-migration-strategies",
        title: "AWS Migration Strategies",
        shortTitle: "Migration Strategies",
        type: "article",
        readingTime: 12,
        tags: ["aws", "migration", "cloud migration", "6 r's", "strategy", "transformation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Plan and execute cloud migrations using AWS migration strategies and the 6 R's: Rehost, Replatform, Repurchase, Refactor, Retire, Retain."
      },
      {
        id: 116,
        order: 2,
        slug: "aws-backup-disaster-recovery",
        title: "AWS Backup and Disaster Recovery",
        shortTitle: "Backup & DR",
        type: "article",
        readingTime: 10,
        tags: ["aws", "backup", "disaster recovery", "aws backup", "resilience", "compliance"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Implement centralized backup and disaster recovery solutions using AWS Backup and cross-region replication strategies."
      },
      {
        id: 117,
        order: 3,
        slug: "aws-organizations-control-tower",
        title: "AWS Organizations and Control Tower",
        shortTitle: "Organizations & Control Tower",
        type: "article",
        readingTime: 12,
        tags: ["aws", "organizations", "control tower", "governance", "multi-account", "landing zone"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Govern multi-account AWS environments with AWS Organizations and Control Tower for centralized security, compliance, and cost management."
      },
      {
        id: 118,
        order: 4,
        slug: "aws-marketplace",
        title: "AWS Marketplace",
        shortTitle: "Marketplace",
        type: "article",
        readingTime: 8,
        tags: ["aws", "marketplace", "third-party", "software", "procurement", "saas"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover, purchase, and deploy third-party software and SaaS solutions seamlessly through the AWS Marketplace."
      },
      {
        id: 119,
        order: 5,
        slug: "aws-certification-exam-preparation",
        title: "AWS Certification and Exam Preparation",
        shortTitle: "Certification Prep",
        type: "article",
        readingTime: 10,
        tags: ["aws", "certification", "exam", "career", "cloud practitioner", "solutions architect", "preparation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Prepare for AWS certification exams with study strategies, practice tips, and resources for Solutions Architect, Developer, and SysOps tracks."
      },
    ]
  },
];