// ============================================================
// src/registry/lessons/pythonLessons.js
// STUB — same shape as htmlLessons.js, empty until you fill it in.
// lessonRegistry.js can safely import this right now without
// breaking anything; it'll just show 0 lessons for Python until
// you add sections here.
// ============================================================

import { STATUS } from "../../config/constants";

export const tutorialInfo = {
  id: "computer-vision",
  title: "Computer Vision Tutorial",
  shortTitle: "Computer Vision",
  category: "Artificial Intelligence and Machine Learning",
  description: "Master computer vision from beginner to advanced with a comprehensive tutorial covering image processing, image transformations, filtering, feature detection, OpenCV, image classification, object detection, image segmentation, OCR, face detection, object tracking, convolutional neural networks, transfer learning, and real-world computer vision applications.",
  icon: "computer-vision",
  difficulty: "Advanced", // course-level badge, separate from per-section defaults
  estimatedHours: 45,
  totalLessons: 97,
  version: "Latest Version",
  language: "English",
  path: "/computer-vision",
  authorId: "faiz",
  updatedAt: "2026-07-09",
  tags: ["computer vision", "computer vision tutorial", "cv", "artificial intelligence", "ai", "machine learning", "deep learning", "image processing", "digital image processing", "image analysis", "opencv", "python computer vision", "image classification", "object detection", "object recognition", "image segmentation", "semantic segmentation", "instance segmentation", "image recognition", "feature detection", "feature extraction", "edge detection", "face detection", "face recognition", "ocr", "optical character recognition", "object tracking", "cnn", "convolutional neural networks", "transfer learning", "image augmentation", "computer vision applications"],
  seo: {
    title: "Computer Vision Tutorial - Learn Computer Vision from Beginner to Advanced | DevSphere",
    description: "Learn computer vision from scratch with a complete tutorial covering image processing, OpenCV, image classification, object detection, segmentation, OCR, face recognition, object tracking, CNNs, transfer learning, and real-world computer vision projects.",
    keywords: ["Computer Vision Tutorial", "Computer Vision Tutorial for Beginners", "Learn Computer Vision", "Computer Vision Course", "Computer Vision for Beginners", "Computer Vision with Python", "Python Computer Vision", "Computer Vision Basics", "Computer Vision Fundamentals", "Computer Vision Programming", "Computer Vision Projects", "Artificial Intelligence", "AI Computer Vision", "Machine Learning Computer Vision", "Deep Learning Computer Vision", "Image Processing", "Digital Image Processing", "Image Processing with Python", "Image Analysis", "Image Transformation", "Image Filtering", "Image Enhancement", "Image Convolution", "Image Kernels", "Edge Detection", "Canny Edge Detection", "Contour Detection", "Feature Detection", "Feature Extraction", "Image Features", "OpenCV Tutorial", "OpenCV Python", "OpenCV Computer Vision", "OpenCV Image Processing", "Image Classification", "Image Classification with Python", "Image Recognition", "Object Detection", "Object Detection Tutorial", "Object Recognition", "Object Detection with Python", "YOLO Object Detection", "YOLO Tutorial", "Image Segmentation", "Semantic Segmentation", "Instance Segmentation", "Panoptic Segmentation", "Face Detection", "Face Recognition", "Face Recognition with Python", "Optical Character Recognition", "OCR Tutorial", "OCR with Python", "Object Tracking", "Computer Vision Object Tracking", "Motion Detection", "Background Subtraction", "Convolutional Neural Networks", "CNN Computer Vision", "CNN Image Classification", "Transfer Learning", "Image Augmentation", "Pretrained Models", "Vision Transformers", "Vision Transformer Tutorial", "Deep Learning for Computer Vision", "Computer Vision with TensorFlow", "Computer Vision with Keras", "Computer Vision with PyTorch", "Computer Vision Applications", "Real World Computer Vision", "Computer Vision Model Training", "Computer Vision Model Evaluation", "Computer Vision Model Deployment", "DevSphere"]
  }
};

export const sections = [
  {
    id: "introduction-to-computer-vision",
    title: "Introduction to Computer Vision",
    order: 1,
    difficulty: "Beginner",
    lessons: [
      {
        id: 1,
        order: 1,
        slug: "cv-what-is-computer-vision",
        title: "What is Computer Vision?",
        shortTitle: "What is Computer Vision",
        readingTime: 9,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get a comprehensive introduction to computer vision, its core concepts, and how it enables machines to interpret visual data.",
        prerequisites: [],
        related: ["cv-computer-vision-vs-image-processing-vs-machine-learning", "cv-setting-up-python-for-computer-vision"],
        recommended: ["cv-how-computer-vision-works", "cv-applications-of-computer-vision"]
      },
      {
        id: 2,
        order: 2,
        slug: "cv-computer-vision-vs-image-processing-vs-machine-learning",
        title: "Computer Vision vs Image Processing vs Machine Learning",
        shortTitle: "Computer Vision vs Image Pro...",
        readingTime: 10,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Clarify the distinctions between computer vision, traditional image processing, and machine learning approaches.",
        prerequisites: ["cv-what-is-computer-vision", "cv-how-computer-vision-works"],
        related: ["cv-how-computer-vision-works", "cv-what-is-computer-vision"],
        recommended: ["cv-applications-of-computer-vision", "cv-challenges-in-computer-vision"]
      },
      {
        id: 3,
        order: 3,
        slug: "cv-how-computer-vision-works",
        title: "How Computer Vision Works",
        shortTitle: "How Computer Vision Works",
        readingTime: 11,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the fundamental mechanics of how computer vision systems process and analyze visual information.",
        prerequisites: ["cv-computer-vision-vs-image-processing-vs-machine-learning", "cv-what-is-computer-vision"],
        related: ["cv-applications-of-computer-vision", "cv-computer-vision-vs-image-processing-vs-machine-learning"],
        recommended: ["cv-challenges-in-computer-vision", "cv-computer-vision-workflow-and-pipeline"]
      },
      {
        id: 4,
        order: 4,
        slug: "cv-applications-of-computer-vision",
        title: "Applications of Computer Vision",
        shortTitle: "Applications of Computer Vis...",
        readingTime: 12,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore real-world applications of computer vision across industries like healthcare, automotive, retail, and security.",
        prerequisites: ["cv-how-computer-vision-works", "cv-computer-vision-vs-image-processing-vs-machine-learning"],
        related: ["cv-challenges-in-computer-vision", "cv-how-computer-vision-works"],
        recommended: ["cv-computer-vision-workflow-and-pipeline", "cv-setting-up-python-for-computer-vision", "cv-numpy-for-image-data"]
      },
      {
        id: 5,
        order: 5,
        slug: "cv-challenges-in-computer-vision",
        title: "Challenges in Computer Vision",
        shortTitle: "Challenges in Computer Vision",
        readingTime: 13,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn about the inherent complexities of visual data, such as lighting variations, occlusion, and scale, that make CV challenging.",
        prerequisites: ["cv-applications-of-computer-vision", "cv-how-computer-vision-works"],
        related: ["cv-computer-vision-workflow-and-pipeline", "cv-applications-of-computer-vision"],
        recommended: ["cv-setting-up-python-for-computer-vision", "cv-numpy-for-image-data"]
      },
      {
        id: 6,
        order: 6,
        slug: "cv-computer-vision-workflow-and-pipeline",
        title: "Computer Vision Workflow and Pipeline",
        shortTitle: "Computer Vision Workflow and...",
        readingTime: 14,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the end-to-end computer vision pipeline, from data acquisition and preprocessing to model deployment.",
        prerequisites: ["cv-challenges-in-computer-vision", "cv-applications-of-computer-vision"],
        related: ["cv-challenges-in-computer-vision", "cv-setting-up-python-for-computer-vision"],
        recommended: ["cv-setting-up-python-for-computer-vision", "cv-numpy-for-image-data"]
      }
    ]
  },
  {
    id: "computer-vision-with-python",
    title: "Computer Vision with Python",
    order: 2,
    difficulty: "Beginner",
    lessons: [
      {
        id: 7,
        order: 1,
        slug: "cv-setting-up-python-for-computer-vision",
        title: "Setting Up Python for Computer Vision",
        shortTitle: "Setting Up Python for Comput...",
        readingTime: 15,
        tags: ["computer vision", "cv", "artificial intelligence", "python cv", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to configure your Python environment with essential libraries for computer vision development.",
        prerequisites: ["cv-computer-vision-workflow-and-pipeline", "cv-challenges-in-computer-vision"],
        related: ["cv-numpy-for-image-data", "cv-digital-images-and-pixels"],
        recommended: ["cv-introduction-to-pillow", "cv-introduction-to-opencv"]
      },
      {
        id: 8,
        order: 2,
        slug: "cv-numpy-for-image-data",
        title: "NumPy for Image Data",
        shortTitle: "NumPy for Image Data",
        readingTime: 8,
        tags: ["computer vision", "cv", "artificial intelligence", "python cv", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the use of NumPy arrays to represent and manipulate image data efficiently in Python.",
        prerequisites: ["cv-setting-up-python-for-computer-vision", "cv-introduction-to-pillow"],
        related: ["cv-introduction-to-pillow", "cv-setting-up-python-for-computer-vision"],
        recommended: ["cv-introduction-to-opencv", "cv-reading-and-displaying-images-with-opencv"]
      },
      {
        id: 9,
        order: 3,
        slug: "cv-introduction-to-pillow",
        title: "Introduction to Pillow",
        shortTitle: "Introduction to Pillow",
        readingTime: 9,
        tags: ["computer vision", "cv", "artificial intelligence", "python cv", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get started with the Python Imaging Library (Pillow) for basic image loading, manipulation, and saving.",
        prerequisites: ["cv-numpy-for-image-data", "cv-setting-up-python-for-computer-vision"],
        related: ["cv-introduction-to-opencv", "cv-numpy-for-image-data"],
        recommended: ["cv-reading-and-displaying-images-with-opencv", "cv-working-with-video-and-camera-input"]
      },
      {
        id: 10,
        order: 4,
        slug: "cv-introduction-to-opencv",
        title: "Introduction to OpenCV",
        shortTitle: "Introduction to OpenCV",
        readingTime: 10,
        tags: ["computer vision", "cv", "artificial intelligence", "python cv", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover OpenCV, the industry-standard library for real-time computer vision and image processing.",
        prerequisites: ["cv-introduction-to-pillow", "cv-numpy-for-image-data"],
        related: ["cv-reading-and-displaying-images-with-opencv", "cv-introduction-to-pillow"],
        recommended: ["cv-working-with-video-and-camera-input", "cv-digital-images-and-pixels", "cv-image-dimensions-resolution-and-channels"]
      },
      {
        id: 11,
        order: 5,
        slug: "cv-reading-and-displaying-images-with-opencv",
        title: "Reading and Displaying Images with OpenCV",
        shortTitle: "Reading and Displaying Image...",
        readingTime: 11,
        tags: ["computer vision", "cv", "artificial intelligence", "python cv", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to load, display, and save images using OpenCV's core functions.",
        prerequisites: ["cv-introduction-to-opencv", "cv-introduction-to-pillow"],
        related: ["cv-working-with-video-and-camera-input", "cv-introduction-to-opencv"],
        recommended: ["cv-digital-images-and-pixels", "cv-image-dimensions-resolution-and-channels"]
      },
      {
        id: 12,
        order: 6,
        slug: "cv-working-with-video-and-camera-input",
        title: "Working with Video and Camera Input",
        shortTitle: "Working with Video and Camer...",
        readingTime: 12,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how to capture, process, and display real-time video streams from webcams or video files.",
        prerequisites: ["cv-reading-and-displaying-images-with-opencv", "cv-introduction-to-opencv"],
        related: ["cv-reading-and-displaying-images-with-opencv", "cv-digital-images-and-pixels"],
        recommended: ["cv-digital-images-and-pixels", "cv-image-dimensions-resolution-and-channels"]
      }
    ]
  },
  {
    id: "image-fundamentals",
    title: "Image Fundamentals",
    order: 3,
    difficulty: "Beginner",
    lessons: [
      {
        id: 13,
        order: 1,
        slug: "cv-digital-images-and-pixels",
        title: "Digital Images and Pixels",
        shortTitle: "Digital Images and Pixels",
        readingTime: 13,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the fundamental concept of digital images as grids of pixels and how they represent visual information.",
        prerequisites: ["cv-working-with-video-and-camera-input", "cv-reading-and-displaying-images-with-opencv"],
        related: ["cv-image-dimensions-resolution-and-channels", "cv-image-resizing-and-scaling"],
        recommended: ["cv-rgb-grayscale-and-alpha-channels", "cv-color-spaces-rgb-hsv-and-lab"]
      },
      {
        id: 14,
        order: 2,
        slug: "cv-image-dimensions-resolution-and-channels",
        title: "Image Dimensions, Resolution and Channels",
        shortTitle: "Image Dimensions, Resolution...",
        readingTime: 14,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how image dimensions, resolution, and color channels affect image quality and processing requirements.",
        prerequisites: ["cv-digital-images-and-pixels", "cv-rgb-grayscale-and-alpha-channels"],
        related: ["cv-rgb-grayscale-and-alpha-channels", "cv-digital-images-and-pixels"],
        recommended: ["cv-color-spaces-rgb-hsv-and-lab", "cv-image-histograms"]
      },
      {
        id: 15,
        order: 3,
        slug: "cv-rgb-grayscale-and-alpha-channels",
        title: "RGB, Grayscale and Alpha Channels",
        shortTitle: "RGB, Grayscale and Alpha Cha...",
        readingTime: 15,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore different image modes, including RGB color, grayscale intensity, and alpha transparency channels.",
        prerequisites: ["cv-image-dimensions-resolution-and-channels", "cv-digital-images-and-pixels"],
        related: ["cv-color-spaces-rgb-hsv-and-lab", "cv-image-dimensions-resolution-and-channels"],
        recommended: ["cv-image-histograms", "cv-image-coordinates-and-regions-of-interest"]
      },
      {
        id: 16,
        order: 4,
        slug: "cv-color-spaces-rgb-hsv-and-lab",
        title: "Color Spaces: RGB, HSV and LAB",
        shortTitle: "Color Spaces RGB, HSV and LAB",
        readingTime: 8,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand various color spaces and when to use HSV or LAB over RGB for specific computer vision tasks.",
        prerequisites: ["cv-rgb-grayscale-and-alpha-channels", "cv-image-dimensions-resolution-and-channels"],
        related: ["cv-image-histograms", "cv-rgb-grayscale-and-alpha-channels"],
        recommended: ["cv-image-coordinates-and-regions-of-interest", "cv-image-formats-and-compression"]
      },
      {
        id: 17,
        order: 5,
        slug: "cv-image-histograms",
        title: "Image Histograms",
        shortTitle: "Image Histograms",
        readingTime: 9,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to analyze and visualize the distribution of pixel intensities using image histograms.",
        prerequisites: ["cv-color-spaces-rgb-hsv-and-lab", "cv-rgb-grayscale-and-alpha-channels"],
        related: ["cv-image-coordinates-and-regions-of-interest", "cv-color-spaces-rgb-hsv-and-lab"],
        recommended: ["cv-image-formats-and-compression", "cv-image-resizing-and-scaling", "cv-image-cropping-and-rotation"]
      },
      {
        id: 18,
        order: 6,
        slug: "cv-image-coordinates-and-regions-of-interest",
        title: "Image Coordinates and Regions of Interest",
        shortTitle: "Image Coordinates and Region...",
        readingTime: 10,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the coordinate system of digital images and how to extract specific Regions of Interest (ROI).",
        prerequisites: ["cv-image-histograms", "cv-color-spaces-rgb-hsv-and-lab"],
        related: ["cv-image-formats-and-compression", "cv-image-histograms"],
        recommended: ["cv-image-resizing-and-scaling", "cv-image-cropping-and-rotation"]
      },
      {
        id: 19,
        order: 7,
        slug: "cv-image-formats-and-compression",
        title: "Image Formats and Compression",
        shortTitle: "Image Formats and Compression",
        readingTime: 11,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand different image file formats (JPEG, PNG, etc.) and the trade-offs of various compression techniques.",
        prerequisites: ["cv-image-coordinates-and-regions-of-interest", "cv-image-histograms"],
        related: ["cv-image-coordinates-and-regions-of-interest", "cv-image-resizing-and-scaling"],
        recommended: ["cv-image-resizing-and-scaling", "cv-image-cropping-and-rotation"]
      }
    ]
  },
  {
    id: "image-preprocessing-and-enhancement",
    title: "Image Preprocessing and Enhancement",
    order: 4,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 20,
        order: 1,
        slug: "cv-image-resizing-and-scaling",
        title: "Image Resizing and Scaling",
        shortTitle: "Image Resizing and Scaling",
        readingTime: 12,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn techniques for resizing images while preserving aspect ratio and minimizing information loss.",
        prerequisites: ["cv-image-formats-and-compression", "cv-image-coordinates-and-regions-of-interest"],
        related: ["cv-image-cropping-and-rotation", "cv-introduction-to-image-filtering"],
        recommended: ["cv-image-translation-and-affine-transformations", "cv-image-blurring-and-smoothing"]
      },
      {
        id: 21,
        order: 2,
        slug: "cv-image-cropping-and-rotation",
        title: "Image Cropping and Rotation",
        shortTitle: "Image Cropping and Rotation",
        readingTime: 13,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master geometric transformations like cropping and rotating images for data alignment and augmentation.",
        prerequisites: ["cv-image-resizing-and-scaling", "cv-image-translation-and-affine-transformations"],
        related: ["cv-image-translation-and-affine-transformations", "cv-image-resizing-and-scaling"],
        recommended: ["cv-image-blurring-and-smoothing", "cv-image-sharpening-and-edge-enhancement"]
      },
      {
        id: 22,
        order: 3,
        slug: "cv-image-translation-and-affine-transformations",
        title: "Image Translation and Affine Transformations",
        shortTitle: "Image Translation and Affine...",
        readingTime: 14,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand affine transformations to translate, rotate, and scale images using transformation matrices.",
        prerequisites: ["cv-image-cropping-and-rotation", "cv-image-resizing-and-scaling"],
        related: ["cv-image-blurring-and-smoothing", "cv-image-cropping-and-rotation"],
        recommended: ["cv-image-sharpening-and-edge-enhancement", "cv-thresholding-and-binarization"]
      },
      {
        id: 23,
        order: 4,
        slug: "cv-image-blurring-and-smoothing",
        title: "Image Blurring and Smoothing",
        shortTitle: "Image Blurring and Smoothing",
        readingTime: 15,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to reduce image noise and smooth details using various blurring techniques.",
        prerequisites: ["cv-image-translation-and-affine-transformations", "cv-image-cropping-and-rotation"],
        related: ["cv-image-sharpening-and-edge-enhancement", "cv-image-translation-and-affine-transformations"],
        recommended: ["cv-thresholding-and-binarization", "cv-histogram-equalization"]
      },
      {
        id: 24,
        order: 5,
        slug: "cv-image-sharpening-and-edge-enhancement",
        title: "Image Sharpening and Edge Enhancement",
        shortTitle: "Image Sharpening and Edge En...",
        readingTime: 8,
        tags: ["computer vision", "cv", "artificial intelligence", "image preprocessing", "image filtering"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover methods to enhance image details and accentuate edges for better feature extraction.",
        prerequisites: ["cv-image-blurring-and-smoothing", "cv-image-translation-and-affine-transformations"],
        related: ["cv-thresholding-and-binarization", "cv-image-blurring-and-smoothing"],
        recommended: ["cv-histogram-equalization", "cv-morphological-operations"]
      },
      {
        id: 25,
        order: 6,
        slug: "cv-thresholding-and-binarization",
        title: "Thresholding and Binarization",
        shortTitle: "Thresholding and Binarization",
        readingTime: 9,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master thresholding techniques to convert grayscale images into binary images for segmentation.",
        prerequisites: ["cv-image-sharpening-and-edge-enhancement", "cv-image-blurring-and-smoothing"],
        related: ["cv-histogram-equalization", "cv-image-sharpening-and-edge-enhancement"],
        recommended: ["cv-morphological-operations", "cv-introduction-to-image-filtering", "cv-spatial-filtering"]
      },
      {
        id: 26,
        order: 7,
        slug: "cv-histogram-equalization",
        title: "Histogram Equalization",
        shortTitle: "Histogram Equalization",
        readingTime: 10,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to improve image contrast by redistributing pixel intensities using histogram equalization.",
        prerequisites: ["cv-thresholding-and-binarization", "cv-image-sharpening-and-edge-enhancement"],
        related: ["cv-morphological-operations", "cv-thresholding-and-binarization"],
        recommended: ["cv-introduction-to-image-filtering", "cv-spatial-filtering"]
      },
      {
        id: 27,
        order: 8,
        slug: "cv-morphological-operations",
        title: "Morphological Operations",
        shortTitle: "Morphological Operations",
        readingTime: 11,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore morphological operations like erosion and dilation to modify the shape of objects in binary images.",
        prerequisites: ["cv-histogram-equalization", "cv-thresholding-and-binarization"],
        related: ["cv-histogram-equalization", "cv-introduction-to-image-filtering"],
        recommended: ["cv-introduction-to-image-filtering", "cv-spatial-filtering"]
      }
    ]
  },
  {
    id: "image-filtering-and-edge-detection",
    title: "Image Filtering and Edge Detection",
    order: 5,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 28,
        order: 1,
        slug: "cv-introduction-to-image-filtering",
        title: "Introduction to Image Filtering",
        shortTitle: "Introduction to Image Filter...",
        readingTime: 12,
        tags: ["computer vision", "cv", "artificial intelligence", "image preprocessing", "image filtering"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to the concept of image filtering and its role in noise reduction and feature enhancement.",
        prerequisites: ["cv-morphological-operations", "cv-histogram-equalization"],
        related: ["cv-spatial-filtering", "cv-what-are-image-features"],
        recommended: ["cv-gaussian-and-median-filtering", "cv-bilateral-filtering"]
      },
      {
        id: 29,
        order: 2,
        slug: "cv-spatial-filtering",
        title: "Spatial Filtering",
        shortTitle: "Spatial Filtering",
        readingTime: 13,
        tags: ["computer vision", "cv", "artificial intelligence", "image preprocessing", "image filtering"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how spatial filters use convolution kernels to modify pixel values based on their neighbors.",
        prerequisites: ["cv-introduction-to-image-filtering", "cv-gaussian-and-median-filtering"],
        related: ["cv-gaussian-and-median-filtering", "cv-introduction-to-image-filtering"],
        recommended: ["cv-bilateral-filtering", "cv-sobel-and-scharr-edge-detection"]
      },
      {
        id: 30,
        order: 3,
        slug: "cv-gaussian-and-median-filtering",
        title: "Gaussian and Median Filtering",
        shortTitle: "Gaussian and Median Filtering",
        readingTime: 14,
        tags: ["computer vision", "cv", "artificial intelligence", "image preprocessing", "image filtering"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how Gaussian and median filters effectively remove different types of noise from images.",
        prerequisites: ["cv-spatial-filtering", "cv-introduction-to-image-filtering"],
        related: ["cv-bilateral-filtering", "cv-spatial-filtering"],
        recommended: ["cv-sobel-and-scharr-edge-detection", "cv-canny-edge-detection"]
      },
      {
        id: 31,
        order: 4,
        slug: "cv-bilateral-filtering",
        title: "Bilateral Filtering",
        shortTitle: "Bilateral Filtering",
        readingTime: 15,
        tags: ["computer vision", "cv", "artificial intelligence", "image preprocessing", "image filtering"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover bilateral filtering, a technique that smooths images while preserving sharp edges.",
        prerequisites: ["cv-gaussian-and-median-filtering", "cv-spatial-filtering"],
        related: ["cv-sobel-and-scharr-edge-detection", "cv-gaussian-and-median-filtering"],
        recommended: ["cv-canny-edge-detection", "cv-contours-and-shape-detection"]
      },
      {
        id: 32,
        order: 5,
        slug: "cv-sobel-and-scharr-edge-detection",
        title: "Sobel and Scharr Edge Detection",
        shortTitle: "Sobel and Scharr Edge Detect...",
        readingTime: 8,
        tags: ["computer vision", "cv", "artificial intelligence", "object detection", "image segmentation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master gradient-based edge detection using Sobel and Scharr operators to find object boundaries.",
        prerequisites: ["cv-bilateral-filtering", "cv-gaussian-and-median-filtering"],
        related: ["cv-canny-edge-detection", "cv-bilateral-filtering"],
        recommended: ["cv-contours-and-shape-detection", "cv-what-are-image-features", "cv-corners-and-interest-points"]
      },
      {
        id: 33,
        order: 6,
        slug: "cv-canny-edge-detection",
        title: "Canny Edge Detection",
        shortTitle: "Canny Edge Detection",
        readingTime: 9,
        tags: ["computer vision", "cv", "artificial intelligence", "object detection", "image segmentation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn the multi-stage Canny edge detection algorithm for robust and accurate edge extraction.",
        prerequisites: ["cv-sobel-and-scharr-edge-detection", "cv-bilateral-filtering"],
        related: ["cv-contours-and-shape-detection", "cv-sobel-and-scharr-edge-detection"],
        recommended: ["cv-what-are-image-features", "cv-corners-and-interest-points"]
      },
      {
        id: 34,
        order: 7,
        slug: "cv-contours-and-shape-detection",
        title: "Contours and Shape Detection",
        shortTitle: "Contours and Shape Detection",
        readingTime: 10,
        tags: ["computer vision", "cv", "artificial intelligence", "object detection", "image segmentation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how to find, draw, and analyze contours to detect shapes and objects in images.",
        prerequisites: ["cv-canny-edge-detection", "cv-sobel-and-scharr-edge-detection"],
        related: ["cv-canny-edge-detection", "cv-what-are-image-features"],
        recommended: ["cv-what-are-image-features", "cv-corners-and-interest-points"]
      }
    ]
  },
  {
    id: "feature-detection-and-description",
    title: "Feature Detection and Description",
    order: 6,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 35,
        order: 1,
        slug: "cv-what-are-image-features",
        title: "What are Image Features?",
        shortTitle: "What are Image Features",
        readingTime: 11,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to image features and why they are crucial for tasks like matching and recognition.",
        prerequisites: ["cv-contours-and-shape-detection", "cv-canny-edge-detection"],
        related: ["cv-corners-and-interest-points", "cv-template-matching"],
        recommended: ["cv-harris-corner-detection", "cv-sift-feature-detection"]
      },
      {
        id: 36,
        order: 2,
        slug: "cv-corners-and-interest-points",
        title: "Corners and Interest Points",
        shortTitle: "Corners and Interest Points",
        readingTime: 12,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn what makes a pixel an 'interest point' and why corners are valuable features in computer vision.",
        prerequisites: ["cv-what-are-image-features", "cv-harris-corner-detection"],
        related: ["cv-harris-corner-detection", "cv-what-are-image-features"],
        recommended: ["cv-sift-feature-detection", "cv-orb-feature-detection"]
      },
      {
        id: 37,
        order: 3,
        slug: "cv-harris-corner-detection",
        title: "Harris Corner Detection",
        shortTitle: "Harris Corner Detection",
        readingTime: 13,
        tags: ["computer vision", "cv", "artificial intelligence", "object detection", "image segmentation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the Harris Corner Detector algorithm for identifying robust corner points in images.",
        prerequisites: ["cv-corners-and-interest-points", "cv-what-are-image-features"],
        related: ["cv-sift-feature-detection", "cv-corners-and-interest-points"],
        recommended: ["cv-orb-feature-detection", "cv-local-binary-patterns"]
      },
      {
        id: 38,
        order: 4,
        slug: "cv-sift-feature-detection",
        title: "SIFT Feature Detection",
        shortTitle: "SIFT Feature Detection",
        readingTime: 14,
        tags: ["computer vision", "cv", "artificial intelligence", "object detection", "image segmentation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the Scale-Invariant Feature Transform (SIFT) for detecting and describing local features.",
        prerequisites: ["cv-harris-corner-detection", "cv-corners-and-interest-points"],
        related: ["cv-orb-feature-detection", "cv-harris-corner-detection"],
        recommended: ["cv-local-binary-patterns", "cv-feature-matching-with-opencv"]
      },
      {
        id: 39,
        order: 5,
        slug: "cv-orb-feature-detection",
        title: "ORB Feature Detection",
        shortTitle: "ORB Feature Detection",
        readingTime: 15,
        tags: ["computer vision", "cv", "artificial intelligence", "object detection", "image segmentation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn about ORB, a fast and efficient alternative to SIFT and SURF for feature detection.",
        prerequisites: ["cv-sift-feature-detection", "cv-harris-corner-detection"],
        related: ["cv-local-binary-patterns", "cv-sift-feature-detection"],
        recommended: ["cv-feature-matching-with-opencv", "cv-template-matching", "cv-hough-transform"]
      },
      {
        id: 40,
        order: 6,
        slug: "cv-local-binary-patterns",
        title: "Local Binary Patterns",
        shortTitle: "Local Binary Patterns",
        readingTime: 8,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand Local Binary Patterns (LBP) for efficient texture classification and feature description.",
        prerequisites: ["cv-orb-feature-detection", "cv-sift-feature-detection"],
        related: ["cv-feature-matching-with-opencv", "cv-orb-feature-detection"],
        recommended: ["cv-template-matching", "cv-hough-transform"]
      },
      {
        id: 41,
        order: 7,
        slug: "cv-feature-matching-with-opencv",
        title: "Feature Matching with OpenCV",
        shortTitle: "Feature Matching with OpenCV",
        readingTime: 9,
        tags: ["computer vision", "cv", "artificial intelligence", "python cv", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to match features between different images using OpenCV's matching algorithms.",
        prerequisites: ["cv-local-binary-patterns", "cv-orb-feature-detection"],
        related: ["cv-local-binary-patterns", "cv-template-matching"],
        recommended: ["cv-template-matching", "cv-hough-transform"]
      }
    ]
  },
  {
    id: "classical-computer-vision",
    title: "Classical Computer Vision",
    order: 7,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 42,
        order: 1,
        slug: "cv-template-matching",
        title: "Template Matching",
        shortTitle: "Template Matching",
        readingTime: 10,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover template matching, a simple method for finding areas of an image that match a template.",
        prerequisites: ["cv-feature-matching-with-opencv", "cv-local-binary-patterns"],
        related: ["cv-hough-transform", "cv-introduction-to-cnns-for-computer-vision"],
        recommended: ["cv-line-and-circle-detection", "cv-image-registration"]
      },
      {
        id: 43,
        order: 2,
        slug: "cv-hough-transform",
        title: "Hough Transform",
        shortTitle: "Hough Transform",
        readingTime: 11,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the Hough Transform technique for detecting simple shapes like lines and circles.",
        prerequisites: ["cv-template-matching", "cv-line-and-circle-detection"],
        related: ["cv-line-and-circle-detection", "cv-template-matching"],
        recommended: ["cv-image-registration", "cv-background-subtraction"]
      },
      {
        id: 44,
        order: 3,
        slug: "cv-line-and-circle-detection",
        title: "Line and Circle Detection",
        shortTitle: "Line and Circle Detection",
        readingTime: 12,
        tags: ["computer vision", "cv", "artificial intelligence", "object detection", "image segmentation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to apply the Hough Transform to detect lines and circles in real-world images.",
        prerequisites: ["cv-hough-transform", "cv-template-matching"],
        related: ["cv-image-registration", "cv-hough-transform"],
        recommended: ["cv-background-subtraction", "cv-optical-flow-basics"]
      },
      {
        id: 45,
        order: 4,
        slug: "cv-image-registration",
        title: "Image Registration",
        shortTitle: "Image Registration",
        readingTime: 13,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master image registration techniques to align multiple images of the same scene taken at different times.",
        prerequisites: ["cv-line-and-circle-detection", "cv-hough-transform"],
        related: ["cv-background-subtraction", "cv-line-and-circle-detection"],
        recommended: ["cv-optical-flow-basics", "cv-classical-object-detection-with-haar-cascades"]
      },
      {
        id: 46,
        order: 5,
        slug: "cv-background-subtraction",
        title: "Background Subtraction",
        shortTitle: "Background Subtraction",
        readingTime: 14,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to separate moving foreground objects from a static background in video sequences.",
        prerequisites: ["cv-image-registration", "cv-line-and-circle-detection"],
        related: ["cv-optical-flow-basics", "cv-image-registration"],
        recommended: ["cv-classical-object-detection-with-haar-cascades", "cv-introduction-to-cnns-for-computer-vision", "cv-convolution-operation-explained"]
      },
      {
        id: 47,
        order: 6,
        slug: "cv-optical-flow-basics",
        title: "Optical Flow Basics",
        shortTitle: "Optical Flow Basics",
        readingTime: 15,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the concept of optical flow for tracking the motion of objects between consecutive frames.",
        prerequisites: ["cv-background-subtraction", "cv-image-registration"],
        related: ["cv-classical-object-detection-with-haar-cascades", "cv-background-subtraction"],
        recommended: ["cv-introduction-to-cnns-for-computer-vision", "cv-convolution-operation-explained"]
      },
      {
        id: 48,
        order: 7,
        slug: "cv-classical-object-detection-with-haar-cascades",
        title: "Classical Object Detection with Haar Cascades",
        shortTitle: "Classical Object Detection w...",
        readingTime: 8,
        tags: ["computer vision", "cv", "artificial intelligence", "object detection", "image segmentation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the Viola-Jones algorithm and Haar cascades for real-time face and object detection.",
        prerequisites: ["cv-optical-flow-basics", "cv-background-subtraction"],
        related: ["cv-optical-flow-basics", "cv-introduction-to-cnns-for-computer-vision"],
        recommended: ["cv-introduction-to-cnns-for-computer-vision", "cv-convolution-operation-explained"]
      }
    ]
  },
  {
    id: "deep-learning-for-computer-vision",
    title: "Deep Learning for Computer Vision",
    order: 8,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 49,
        order: 1,
        slug: "cv-introduction-to-cnns-for-computer-vision",
        title: "Introduction to CNNs for Computer Vision",
        shortTitle: "Introduction to CNNs for Com...",
        readingTime: 9,
        tags: ["computer vision", "cv", "artificial intelligence", "deep learning", "neural networks"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to Convolutional Neural Networks (CNNs) and why they revolutionized computer vision.",
        prerequisites: ["cv-classical-object-detection-with-haar-cascades", "cv-optical-flow-basics"],
        related: ["cv-convolution-operation-explained", "cv-understanding-cnn-architectures"],
        recommended: ["cv-stride-padding-and-receptive-fields", "cv-pooling-layers"]
      },
      {
        id: 50,
        order: 2,
        slug: "cv-convolution-operation-explained",
        title: "Convolution Operation Explained",
        shortTitle: "Convolution Operation Explai...",
        readingTime: 10,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the mathematical convolution operation and how it extracts spatial features from images.",
        prerequisites: ["cv-introduction-to-cnns-for-computer-vision", "cv-stride-padding-and-receptive-fields"],
        related: ["cv-stride-padding-and-receptive-fields", "cv-introduction-to-cnns-for-computer-vision"],
        recommended: ["cv-pooling-layers", "cv-building-an-image-classification-model"]
      },
      {
        id: 51,
        order: 3,
        slug: "cv-stride-padding-and-receptive-fields",
        title: "Stride, Padding and Receptive Fields",
        shortTitle: "Stride, Padding and Receptiv...",
        readingTime: 11,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how stride, padding, and receptive fields control the spatial dimensions and context of CNNs.",
        prerequisites: ["cv-convolution-operation-explained", "cv-introduction-to-cnns-for-computer-vision"],
        related: ["cv-pooling-layers", "cv-convolution-operation-explained"],
        recommended: ["cv-building-an-image-classification-model", "cv-cnn-training-and-backpropagation"]
      },
      {
        id: 52,
        order: 4,
        slug: "cv-pooling-layers",
        title: "Pooling Layers",
        shortTitle: "Pooling Layers",
        readingTime: 12,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how pooling layers reduce spatial dimensions and provide translation invariance in CNNs.",
        prerequisites: ["cv-stride-padding-and-receptive-fields", "cv-convolution-operation-explained"],
        related: ["cv-building-an-image-classification-model", "cv-stride-padding-and-receptive-fields"],
        recommended: ["cv-cnn-training-and-backpropagation", "cv-data-augmentation"]
      },
      {
        id: 53,
        order: 5,
        slug: "cv-building-an-image-classification-model",
        title: "Building an Image Classification Model",
        shortTitle: "Building an Image Classifica...",
        readingTime: 13,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to architect and build a complete CNN for image classification tasks.",
        prerequisites: ["cv-pooling-layers", "cv-stride-padding-and-receptive-fields"],
        related: ["cv-cnn-training-and-backpropagation", "cv-pooling-layers"],
        recommended: ["cv-data-augmentation", "cv-cnn-regularization-and-dropout"]
      },
      {
        id: 54,
        order: 6,
        slug: "cv-cnn-training-and-backpropagation",
        title: "CNN Training and Backpropagation",
        shortTitle: "CNN Training and Backpropaga...",
        readingTime: 14,
        tags: ["computer vision", "cv", "artificial intelligence", "deep learning", "neural networks"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the training process of CNNs, including loss functions and backpropagation.",
        prerequisites: ["cv-building-an-image-classification-model", "cv-pooling-layers"],
        related: ["cv-data-augmentation", "cv-building-an-image-classification-model"],
        recommended: ["cv-cnn-regularization-and-dropout", "cv-evaluating-image-classification-models"]
      },
      {
        id: 55,
        order: 7,
        slug: "cv-data-augmentation",
        title: "Data Augmentation",
        shortTitle: "Data Augmentation",
        readingTime: 15,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master data augmentation techniques to artificially expand your dataset and prevent overfitting.",
        prerequisites: ["cv-cnn-training-and-backpropagation", "cv-building-an-image-classification-model"],
        related: ["cv-cnn-regularization-and-dropout", "cv-cnn-training-and-backpropagation"],
        recommended: ["cv-evaluating-image-classification-models", "cv-understanding-cnn-architectures", "cv-lenet-and-alexnet"]
      },
      {
        id: 56,
        order: 8,
        slug: "cv-cnn-regularization-and-dropout",
        title: "CNN Regularization and Dropout",
        shortTitle: "CNN Regularization and Dropout",
        readingTime: 8,
        tags: ["computer vision", "cv", "artificial intelligence", "deep learning", "neural networks"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to apply regularization and dropout to improve the generalization of your CNN models.",
        prerequisites: ["cv-data-augmentation", "cv-cnn-training-and-backpropagation"],
        related: ["cv-evaluating-image-classification-models", "cv-data-augmentation"],
        recommended: ["cv-understanding-cnn-architectures", "cv-lenet-and-alexnet"]
      },
      {
        id: 57,
        order: 9,
        slug: "cv-evaluating-image-classification-models",
        title: "Evaluating Image Classification Models",
        shortTitle: "Evaluating Image Classificat...",
        readingTime: 9,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the metrics and techniques used to evaluate the performance of image classification models.",
        prerequisites: ["cv-cnn-regularization-and-dropout", "cv-data-augmentation"],
        related: ["cv-cnn-regularization-and-dropout", "cv-understanding-cnn-architectures"],
        recommended: ["cv-understanding-cnn-architectures", "cv-lenet-and-alexnet"]
      }
    ]
  },
  {
    id: "modern-cnn-architectures-and-transfer-learning",
    title: "Modern CNN Architectures and Transfer Learning",
    order: 9,
    difficulty: "Advanced",
    lessons: [
      {
        id: 58,
        order: 1,
        slug: "cv-understanding-cnn-architectures",
        title: "Understanding CNN Architectures",
        shortTitle: "Understanding CNN Architectu...",
        readingTime: 10,
        tags: ["computer vision", "cv", "artificial intelligence", "deep learning", "neural networks"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the evolution of CNN architectures and the design principles behind modern networks.",
        prerequisites: ["cv-evaluating-image-classification-models", "cv-cnn-regularization-and-dropout"],
        related: ["cv-lenet-and-alexnet", "cv-introduction-to-object-detection"],
        recommended: ["cv-vgg-and-inception-networks", "cv-resnet-and-residual-connections"]
      },
      {
        id: 59,
        order: 2,
        slug: "cv-lenet-and-alexnet",
        title: "LeNet and AlexNet",
        shortTitle: "LeNet and AlexNet",
        readingTime: 11,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Study the pioneering LeNet and AlexNet architectures that laid the foundation for deep learning in vision.",
        prerequisites: ["cv-understanding-cnn-architectures", "cv-vgg-and-inception-networks"],
        related: ["cv-vgg-and-inception-networks", "cv-understanding-cnn-architectures"],
        recommended: ["cv-resnet-and-residual-connections", "cv-mobilenet-and-efficient-cnns"]
      },
      {
        id: 60,
        order: 3,
        slug: "cv-vgg-and-inception-networks",
        title: "VGG and Inception Networks",
        shortTitle: "VGG and Inception Networks",
        readingTime: 12,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the design of VGG's uniform architecture and Inception's multi-scale feature extraction.",
        prerequisites: ["cv-lenet-and-alexnet", "cv-understanding-cnn-architectures"],
        related: ["cv-resnet-and-residual-connections", "cv-lenet-and-alexnet"],
        recommended: ["cv-mobilenet-and-efficient-cnns", "cv-transfer-learning-for-computer-vision"]
      },
      {
        id: 61,
        order: 4,
        slug: "cv-resnet-and-residual-connections",
        title: "ResNet and Residual Connections",
        shortTitle: "ResNet and Residual Connecti...",
        readingTime: 13,
        tags: ["computer vision", "cv", "artificial intelligence", "deep learning", "neural networks"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how ResNet's residual connections solved the vanishing gradient problem in very deep networks.",
        prerequisites: ["cv-vgg-and-inception-networks", "cv-lenet-and-alexnet"],
        related: ["cv-mobilenet-and-efficient-cnns", "cv-vgg-and-inception-networks"],
        recommended: ["cv-transfer-learning-for-computer-vision", "cv-finetuning-pretrained-vision-models"]
      },
      {
        id: 62,
        order: 5,
        slug: "cv-mobilenet-and-efficient-cnns",
        title: "MobileNet and Efficient CNNs",
        shortTitle: "MobileNet and Efficient CNNs",
        readingTime: 14,
        tags: ["computer vision", "cv", "artificial intelligence", "deep learning", "neural networks"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover lightweight CNN architectures like MobileNet designed for mobile and edge devices.",
        prerequisites: ["cv-resnet-and-residual-connections", "cv-vgg-and-inception-networks"],
        related: ["cv-transfer-learning-for-computer-vision", "cv-resnet-and-residual-connections"],
        recommended: ["cv-finetuning-pretrained-vision-models", "cv-introduction-to-object-detection", "cv-object-detection-vs-image-classification"]
      },
      {
        id: 63,
        order: 6,
        slug: "cv-transfer-learning-for-computer-vision",
        title: "Transfer Learning for Computer Vision",
        shortTitle: "Transfer Learning for Comput...",
        readingTime: 15,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master transfer learning to leverage pretrained models for your specific computer vision tasks.",
        prerequisites: ["cv-mobilenet-and-efficient-cnns", "cv-resnet-and-residual-connections"],
        related: ["cv-finetuning-pretrained-vision-models", "cv-mobilenet-and-efficient-cnns"],
        recommended: ["cv-introduction-to-object-detection", "cv-object-detection-vs-image-classification"]
      },
      {
        id: 64,
        order: 7,
        slug: "cv-finetuning-pretrained-vision-models",
        title: "Fine-Tuning Pretrained Vision Models",
        shortTitle: "Fine-Tuning Pretrained Visio...",
        readingTime: 8,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn the best practices for fine-tuning pretrained models to achieve state-of-the-art results.",
        prerequisites: ["cv-transfer-learning-for-computer-vision", "cv-mobilenet-and-efficient-cnns"],
        related: ["cv-transfer-learning-for-computer-vision", "cv-introduction-to-object-detection"],
        recommended: ["cv-introduction-to-object-detection", "cv-object-detection-vs-image-classification"]
      }
    ]
  },
  {
    id: "object-detection",
    title: "Object Detection",
    order: 10,
    difficulty: "Advanced",
    lessons: [
      {
        id: 65,
        order: 1,
        slug: "cv-introduction-to-object-detection",
        title: "Introduction to Object Detection",
        shortTitle: "Introduction to Object Detec...",
        readingTime: 9,
        tags: ["computer vision", "cv", "artificial intelligence", "object detection", "image segmentation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to object detection, the task of locating and classifying multiple objects in an image.",
        prerequisites: ["cv-finetuning-pretrained-vision-models", "cv-transfer-learning-for-computer-vision"],
        related: ["cv-object-detection-vs-image-classification", "cv-introduction-to-image-segmentation"],
        recommended: ["cv-bounding-boxes-and-iou", "cv-rcnn-family"]
      },
      {
        id: 66,
        order: 2,
        slug: "cv-object-detection-vs-image-classification",
        title: "Object Detection vs Image Classification",
        shortTitle: "Object Detection vs Image Cl...",
        readingTime: 10,
        tags: ["computer vision", "cv", "artificial intelligence", "object detection", "image segmentation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the key differences between image classification and object detection tasks.",
        prerequisites: ["cv-introduction-to-object-detection", "cv-bounding-boxes-and-iou"],
        related: ["cv-bounding-boxes-and-iou", "cv-introduction-to-object-detection"],
        recommended: ["cv-rcnn-family", "cv-yolo-object-detection"]
      },
      {
        id: 67,
        order: 3,
        slug: "cv-bounding-boxes-and-iou",
        title: "Bounding Boxes and IoU",
        shortTitle: "Bounding Boxes and IoU",
        readingTime: 11,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn about bounding box representations and the Intersection over Union (IoU) metric.",
        prerequisites: ["cv-object-detection-vs-image-classification", "cv-introduction-to-object-detection"],
        related: ["cv-rcnn-family", "cv-object-detection-vs-image-classification"],
        recommended: ["cv-yolo-object-detection", "cv-singleshot-and-twostage-detectors"]
      },
      {
        id: 68,
        order: 4,
        slug: "cv-rcnn-family",
        title: "R-CNN Family",
        shortTitle: "R-CNN Family",
        readingTime: 12,
        tags: ["computer vision", "cv", "artificial intelligence", "deep learning", "neural networks"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the evolution of two-stage detectors, from R-CNN to Fast R-CNN and Faster R-CNN.",
        prerequisites: ["cv-bounding-boxes-and-iou", "cv-object-detection-vs-image-classification"],
        related: ["cv-yolo-object-detection", "cv-bounding-boxes-and-iou"],
        recommended: ["cv-singleshot-and-twostage-detectors", "cv-nonmaximum-suppression"]
      },
      {
        id: 69,
        order: 5,
        slug: "cv-yolo-object-detection",
        title: "YOLO Object Detection",
        shortTitle: "YOLO Object Detection",
        readingTime: 13,
        tags: ["computer vision", "cv", "artificial intelligence", "deep learning", "neural networks"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the You Only Look Once (YOLO) algorithm for fast, real-time object detection.",
        prerequisites: ["cv-rcnn-family", "cv-bounding-boxes-and-iou"],
        related: ["cv-singleshot-and-twostage-detectors", "cv-rcnn-family"],
        recommended: ["cv-nonmaximum-suppression", "cv-modern-object-detection-with-transformers"]
      },
      {
        id: 70,
        order: 6,
        slug: "cv-singleshot-and-twostage-detectors",
        title: "Single-Shot and Two-Stage Detectors",
        shortTitle: "Single-Shot and Two-Stage De...",
        readingTime: 14,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Compare the trade-offs between single-shot detectors (like SSD) and two-stage detectors.",
        prerequisites: ["cv-yolo-object-detection", "cv-rcnn-family"],
        related: ["cv-nonmaximum-suppression", "cv-yolo-object-detection"],
        recommended: ["cv-modern-object-detection-with-transformers", "cv-introduction-to-image-segmentation", "cv-semantic-vs-instance-segmentation"]
      },
      {
        id: 71,
        order: 7,
        slug: "cv-nonmaximum-suppression",
        title: "Non-Maximum Suppression",
        shortTitle: "Non-Maximum Suppression",
        readingTime: 15,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand Non-Maximum Suppression (NMS) for filtering duplicate bounding box predictions.",
        prerequisites: ["cv-singleshot-and-twostage-detectors", "cv-yolo-object-detection"],
        related: ["cv-modern-object-detection-with-transformers", "cv-singleshot-and-twostage-detectors"],
        recommended: ["cv-introduction-to-image-segmentation", "cv-semantic-vs-instance-segmentation"]
      },
      {
        id: 72,
        order: 8,
        slug: "cv-modern-object-detection-with-transformers",
        title: "Modern Object Detection with Transformers",
        shortTitle: "Modern Object Detection with...",
        readingTime: 8,
        tags: ["computer vision", "cv", "artificial intelligence", "deep learning", "neural networks"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how Vision Transformers (ViT) and DETR are reshaping the object detection landscape.",
        prerequisites: ["cv-nonmaximum-suppression", "cv-singleshot-and-twostage-detectors"],
        related: ["cv-nonmaximum-suppression", "cv-introduction-to-image-segmentation"],
        recommended: ["cv-introduction-to-image-segmentation", "cv-semantic-vs-instance-segmentation"]
      }
    ]
  },
  {
    id: "image-segmentation",
    title: "Image Segmentation",
    order: 11,
    difficulty: "Advanced",
    lessons: [
      {
        id: 73,
        order: 1,
        slug: "cv-introduction-to-image-segmentation",
        title: "Introduction to Image Segmentation",
        shortTitle: "Introduction to Image Segmen...",
        readingTime: 9,
        tags: ["computer vision", "cv", "artificial intelligence", "object detection", "image segmentation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to image segmentation, the task of partitioning an image into meaningful regions.",
        prerequisites: ["cv-modern-object-detection-with-transformers", "cv-nonmaximum-suppression"],
        related: ["cv-semantic-vs-instance-segmentation", "cv-introduction-to-video-processing"],
        recommended: ["cv-thresholdingbased-segmentation", "cv-region-and-edgebased-segmentation"]
      },
      {
        id: 74,
        order: 2,
        slug: "cv-semantic-vs-instance-segmentation",
        title: "Semantic vs Instance Segmentation",
        shortTitle: "Semantic vs Instance Segment...",
        readingTime: 10,
        tags: ["computer vision", "cv", "artificial intelligence", "object detection", "image segmentation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the difference between semantic segmentation (pixel-level classification) and instance segmentation.",
        prerequisites: ["cv-introduction-to-image-segmentation", "cv-thresholdingbased-segmentation"],
        related: ["cv-thresholdingbased-segmentation", "cv-introduction-to-image-segmentation"],
        recommended: ["cv-region-and-edgebased-segmentation", "cv-unet-architecture"]
      },
      {
        id: 75,
        order: 3,
        slug: "cv-thresholdingbased-segmentation",
        title: "Thresholding-Based Segmentation",
        shortTitle: "Thresholding-Based Segmentat...",
        readingTime: 11,
        tags: ["computer vision", "cv", "artificial intelligence", "object detection", "image segmentation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn simple segmentation techniques based on pixel intensity thresholding.",
        prerequisites: ["cv-semantic-vs-instance-segmentation", "cv-introduction-to-image-segmentation"],
        related: ["cv-region-and-edgebased-segmentation", "cv-semantic-vs-instance-segmentation"],
        recommended: ["cv-unet-architecture", "cv-mask-rcnn"]
      },
      {
        id: 76,
        order: 4,
        slug: "cv-region-and-edgebased-segmentation",
        title: "Region and Edge-Based Segmentation",
        shortTitle: "Region and Edge-Based Segmen...",
        readingTime: 12,
        tags: ["computer vision", "cv", "artificial intelligence", "object detection", "image segmentation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore classical segmentation methods that group pixels based on region similarity or edge boundaries.",
        prerequisites: ["cv-thresholdingbased-segmentation", "cv-semantic-vs-instance-segmentation"],
        related: ["cv-unet-architecture", "cv-thresholdingbased-segmentation"],
        recommended: ["cv-mask-rcnn", "cv-segmentation-evaluation-metrics"]
      },
      {
        id: 77,
        order: 5,
        slug: "cv-unet-architecture",
        title: "U-Net Architecture",
        shortTitle: "U-Net Architecture",
        readingTime: 13,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the U-Net architecture, the gold standard for biomedical and semantic image segmentation.",
        prerequisites: ["cv-region-and-edgebased-segmentation", "cv-thresholdingbased-segmentation"],
        related: ["cv-mask-rcnn", "cv-region-and-edgebased-segmentation"],
        recommended: ["cv-segmentation-evaluation-metrics", "cv-introduction-to-video-processing", "cv-reading-and-writing-video-with-opencv"]
      },
      {
        id: 78,
        order: 6,
        slug: "cv-mask-rcnn",
        title: "Mask R-CNN",
        shortTitle: "Mask R-CNN",
        readingTime: 14,
        tags: ["computer vision", "cv", "artificial intelligence", "deep learning", "neural networks"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how Mask R-CNN extends Faster R-CNN to perform high-quality instance segmentation.",
        prerequisites: ["cv-unet-architecture", "cv-region-and-edgebased-segmentation"],
        related: ["cv-segmentation-evaluation-metrics", "cv-unet-architecture"],
        recommended: ["cv-introduction-to-video-processing", "cv-reading-and-writing-video-with-opencv"]
      },
      {
        id: 79,
        order: 7,
        slug: "cv-segmentation-evaluation-metrics",
        title: "Segmentation Evaluation Metrics",
        shortTitle: "Segmentation Evaluation Metr...",
        readingTime: 15,
        tags: ["computer vision", "cv", "artificial intelligence", "object detection", "image segmentation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand metrics like IoU, Dice Coefficient, and Pixel Accuracy for evaluating segmentation models.",
        prerequisites: ["cv-mask-rcnn", "cv-unet-architecture"],
        related: ["cv-mask-rcnn", "cv-introduction-to-video-processing"],
        recommended: ["cv-introduction-to-video-processing", "cv-reading-and-writing-video-with-opencv"]
      }
    ]
  },
  {
    id: "video-processing-and-computer-vision",
    title: "Video Processing and Computer Vision",
    order: 12,
    difficulty: "Advanced",
    lessons: [
      {
        id: 80,
        order: 1,
        slug: "cv-introduction-to-video-processing",
        title: "Introduction to Video Processing",
        shortTitle: "Introduction to Video Proces...",
        readingTime: 8,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to video processing and the unique challenges of temporal data in computer vision.",
        prerequisites: ["cv-segmentation-evaluation-metrics", "cv-mask-rcnn"],
        related: ["cv-reading-and-writing-video-with-opencv", "cv-introduction-to-3d-computer-vision"],
        recommended: ["cv-object-tracking", "cv-optical-flow-for-motion-tracking"]
      },
      {
        id: 81,
        order: 2,
        slug: "cv-reading-and-writing-video-with-opencv",
        title: "Reading and Writing Video with OpenCV",
        shortTitle: "Reading and Writing Video wi...",
        readingTime: 9,
        tags: ["computer vision", "cv", "artificial intelligence", "python cv", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to read, process, and write video files using OpenCV's VideoCapture and VideoWriter.",
        prerequisites: ["cv-introduction-to-video-processing", "cv-object-tracking"],
        related: ["cv-object-tracking", "cv-introduction-to-video-processing"],
        recommended: ["cv-optical-flow-for-motion-tracking", "cv-multiobject-tracking"]
      },
      {
        id: 82,
        order: 3,
        slug: "cv-object-tracking",
        title: "Object Tracking",
        shortTitle: "Object Tracking",
        readingTime: 10,
        tags: ["computer vision", "cv", "artificial intelligence", "object detection", "image segmentation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the fundamentals of object tracking and how to follow objects across video frames.",
        prerequisites: ["cv-reading-and-writing-video-with-opencv", "cv-introduction-to-video-processing"],
        related: ["cv-optical-flow-for-motion-tracking", "cv-reading-and-writing-video-with-opencv"],
        recommended: ["cv-multiobject-tracking", "cv-realtime-computer-vision-applications"]
      },
      {
        id: 83,
        order: 4,
        slug: "cv-optical-flow-for-motion-tracking",
        title: "Optical Flow for Motion Tracking",
        shortTitle: "Optical Flow for Motion Trac...",
        readingTime: 11,
        tags: ["computer vision", "cv", "artificial intelligence", "object detection", "image segmentation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to use Lucas-Kanade and dense optical flow for robust motion tracking.",
        prerequisites: ["cv-object-tracking", "cv-reading-and-writing-video-with-opencv"],
        related: ["cv-multiobject-tracking", "cv-object-tracking"],
        recommended: ["cv-realtime-computer-vision-applications", "cv-introduction-to-3d-computer-vision", "cv-camera-calibration"]
      },
      {
        id: 84,
        order: 5,
        slug: "cv-multiobject-tracking",
        title: "Multi-Object Tracking",
        shortTitle: "Multi-Object Tracking",
        readingTime: 12,
        tags: ["computer vision", "cv", "artificial intelligence", "object detection", "image segmentation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the fundamentals of object tracking and how to follow objects across video frames.",
        prerequisites: ["cv-optical-flow-for-motion-tracking", "cv-object-tracking"],
        related: ["cv-realtime-computer-vision-applications", "cv-optical-flow-for-motion-tracking"],
        recommended: ["cv-introduction-to-3d-computer-vision", "cv-camera-calibration"]
      },
      {
        id: 85,
        order: 6,
        slug: "cv-realtime-computer-vision-applications",
        title: "Real-Time Computer Vision Applications",
        shortTitle: "Real-Time Computer Vision Ap...",
        readingTime: 13,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how to optimize computer vision pipelines for real-time performance in live applications.",
        prerequisites: ["cv-multiobject-tracking", "cv-optical-flow-for-motion-tracking"],
        related: ["cv-multiobject-tracking", "cv-introduction-to-3d-computer-vision"],
        recommended: ["cv-introduction-to-3d-computer-vision", "cv-camera-calibration"]
      }
    ]
  },
  {
    id: "3d-computer-vision-and-advanced-vision",
    title: "3D Computer Vision and Advanced Vision",
    order: 13,
    difficulty: "Advanced",
    lessons: [
      {
        id: 86,
        order: 1,
        slug: "cv-introduction-to-3d-computer-vision",
        title: "Introduction to 3D Computer Vision",
        shortTitle: "Introduction to 3D Computer ...",
        readingTime: 14,
        tags: ["computer vision", "cv", "artificial intelligence", "3d computer vision", "depth estimation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to 3D computer vision and how machines perceive depth and 3D structure.",
        prerequisites: ["cv-realtime-computer-vision-applications", "cv-multiobject-tracking"],
        related: ["cv-camera-calibration", "cv-building-an-image-classification-system"],
        recommended: ["cv-stereo-vision-and-depth-estimation", "cv-depth-maps-and-point-clouds"]
      },
      {
        id: 87,
        order: 2,
        slug: "cv-camera-calibration",
        title: "Camera Calibration",
        shortTitle: "Camera Calibration",
        readingTime: 15,
        tags: ["computer vision", "cv", "artificial intelligence", "3d computer vision", "depth estimation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to calibrate cameras to correct lens distortion and estimate intrinsic parameters.",
        prerequisites: ["cv-introduction-to-3d-computer-vision", "cv-stereo-vision-and-depth-estimation"],
        related: ["cv-stereo-vision-and-depth-estimation", "cv-introduction-to-3d-computer-vision"],
        recommended: ["cv-depth-maps-and-point-clouds", "cv-pose-estimation"]
      },
      {
        id: 88,
        order: 3,
        slug: "cv-stereo-vision-and-depth-estimation",
        title: "Stereo Vision and Depth Estimation",
        shortTitle: "Stereo Vision and Depth Esti...",
        readingTime: 8,
        tags: ["computer vision", "cv", "artificial intelligence", "3d computer vision", "depth estimation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how stereo vision uses multiple cameras to estimate depth and 3D geometry.",
        prerequisites: ["cv-camera-calibration", "cv-introduction-to-3d-computer-vision"],
        related: ["cv-depth-maps-and-point-clouds", "cv-camera-calibration"],
        recommended: ["cv-pose-estimation", "cv-introduction-to-vision-transformers"]
      },
      {
        id: 89,
        order: 4,
        slug: "cv-depth-maps-and-point-clouds",
        title: "Depth Maps and Point Clouds",
        shortTitle: "Depth Maps and Point Clouds",
        readingTime: 9,
        tags: ["computer vision", "cv", "artificial intelligence", "3d computer vision", "depth estimation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to generate and process depth maps and 3D point clouds from visual data.",
        prerequisites: ["cv-stereo-vision-and-depth-estimation", "cv-camera-calibration"],
        related: ["cv-pose-estimation", "cv-stereo-vision-and-depth-estimation"],
        recommended: ["cv-introduction-to-vision-transformers", "cv-building-an-image-classification-system", "cv-face-detection-and-recognition-system"]
      },
      {
        id: 90,
        order: 5,
        slug: "cv-pose-estimation",
        title: "Pose Estimation",
        shortTitle: "Pose Estimation",
        readingTime: 10,
        tags: ["computer vision", "cv", "artificial intelligence", "3d computer vision", "depth estimation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore human pose estimation techniques for detecting and tracking body keypoints.",
        prerequisites: ["cv-depth-maps-and-point-clouds", "cv-stereo-vision-and-depth-estimation"],
        related: ["cv-introduction-to-vision-transformers", "cv-depth-maps-and-point-clouds"],
        recommended: ["cv-building-an-image-classification-system", "cv-face-detection-and-recognition-system"]
      },
      {
        id: 91,
        order: 6,
        slug: "cv-introduction-to-vision-transformers",
        title: "Introduction to Vision Transformers",
        shortTitle: "Introduction to Vision Trans...",
        readingTime: 11,
        tags: ["computer vision", "cv", "artificial intelligence", "deep learning", "neural networks"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover Vision Transformers (ViT) and how self-attention is applied to image patches.",
        prerequisites: ["cv-pose-estimation", "cv-depth-maps-and-point-clouds"],
        related: ["cv-pose-estimation", "cv-building-an-image-classification-system"],
        recommended: ["cv-building-an-image-classification-system", "cv-face-detection-and-recognition-system"]
      }
    ]
  },
  {
    id: "computer-vision-projects-and-practice",
    title: "Computer Vision Projects and Practice",
    order: 14,
    difficulty: "Advanced",
    lessons: [
      {
        id: 92,
        order: 1,
        slug: "cv-building-an-image-classification-system",
        title: "Building an Image Classification System",
        shortTitle: "Building an Image Classifica...",
        readingTime: 12,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Apply your knowledge to build a complete, end-to-end image classification system from scratch.",
        prerequisites: ["cv-introduction-to-vision-transformers", "cv-pose-estimation"],
        related: ["cv-face-detection-and-recognition-system", "cv-introduction-to-vision-transformers"],
        recommended: ["cv-realtime-object-detection-system", "cv-image-segmentation-project"]
      },
      {
        id: 93,
        order: 2,
        slug: "cv-face-detection-and-recognition-system",
        title: "Face Detection and Recognition System",
        shortTitle: "Face Detection and Recogniti...",
        readingTime: 13,
        tags: ["computer vision", "cv", "artificial intelligence", "object detection", "image segmentation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Build a robust face detection and recognition pipeline using modern computer vision techniques.",
        prerequisites: ["cv-building-an-image-classification-system", "cv-realtime-object-detection-system"],
        related: ["cv-realtime-object-detection-system", "cv-building-an-image-classification-system"],
        recommended: ["cv-image-segmentation-project", "cv-realtime-object-tracking-project"]
      },
      {
        id: 94,
        order: 3,
        slug: "cv-realtime-object-detection-system",
        title: "Real-Time Object Detection System",
        shortTitle: "Real-Time Object Detection S...",
        readingTime: 14,
        tags: ["computer vision", "cv", "artificial intelligence", "object detection", "image segmentation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Develop a real-time object detection system optimized for live video streams.",
        prerequisites: ["cv-face-detection-and-recognition-system", "cv-building-an-image-classification-system"],
        related: ["cv-image-segmentation-project", "cv-face-detection-and-recognition-system"],
        recommended: ["cv-realtime-object-tracking-project", "cv-endtoend-computer-vision-project"]
      },
      {
        id: 95,
        order: 4,
        slug: "cv-image-segmentation-project",
        title: "Image Segmentation Project",
        shortTitle: "Image Segmentation Project",
        readingTime: 15,
        tags: ["computer vision", "cv", "artificial intelligence", "object detection", "image segmentation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Complete a hands-on project implementing semantic or instance segmentation on a real-world dataset.",
        prerequisites: ["cv-realtime-object-detection-system", "cv-face-detection-and-recognition-system"],
        related: ["cv-realtime-object-tracking-project", "cv-realtime-object-detection-system"],
        recommended: ["cv-endtoend-computer-vision-project", "cv-pose-estimation", "cv-introduction-to-vision-transformers"]
      },
      {
        id: 96,
        order: 5,
        slug: "cv-realtime-object-tracking-project",
        title: "Real-Time Object Tracking Project",
        shortTitle: "Real-Time Object Tracking Pr...",
        readingTime: 8,
        tags: ["computer vision", "cv", "artificial intelligence", "object detection", "image segmentation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the fundamentals of object tracking and how to follow objects across video frames.",
        prerequisites: ["cv-image-segmentation-project", "cv-realtime-object-detection-system"],
        related: ["cv-endtoend-computer-vision-project", "cv-image-segmentation-project"],
        recommended: ["cv-pose-estimation", "cv-introduction-to-vision-transformers"]
      },
      {
        id: 97,
        order: 6,
        slug: "cv-endtoend-computer-vision-project",
        title: "End-to-End Computer Vision Project",
        shortTitle: "End-to-End Computer Vision P...",
        readingTime: 9,
        tags: ["computer vision", "cv", "artificial intelligence", "computer vision fundamentals", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Bring everything together to design, train, and deploy a complete, production-ready computer vision application.",
        prerequisites: ["cv-realtime-object-tracking-project", "cv-image-segmentation-project"],
        related: ["cv-realtime-object-tracking-project", "cv-introduction-to-vision-transformers"],
        recommended: ["cv-pose-estimation", "cv-introduction-to-vision-transformers"]
      }
    ]
  }
];

export const resources = [
  {
    id: "computer-vision-concepts",
    title: "Computer Vision Concepts",
    order: 1,
    items: [
      {
        id: 98,
        order: 1,
        slug: "cv-image-formation-and-camera-models",
        title: "Image Formation and Camera Models",
        shortTitle: "Image Formation",
        type: "article",
        readingTime: 12,
        tags: ["computer vision", "camera models", "image formation", "optics", "pinhole camera", "fundamentals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how images are formed through camera models, lens optics, and the pinhole camera model in computer vision."
      },
      {
        id: 99,
        order: 2,
        slug: "cv-perspective-and-geometric-transformations",
        title: "Perspective and Geometric Transformations",
        shortTitle: "Geometric Transforms",
        type: "article",
        readingTime: 10,
        tags: ["computer vision", "perspective", "geometric transformations", "homography", "affine", "rotation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn about perspective projection, affine transformations, and geometric warping applied to images and scenes."
      },
      {
        id: 100,
        order: 3,
        slug: "cv-sampling-and-quantization",
        title: "Sampling and Quantization",
        shortTitle: "Sampling & Quantization",
        type: "article",
        readingTime: 10,
        tags: ["computer vision", "sampling", "quantization", "digitization", "resolution", "image processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore how continuous visual signals are converted into discrete digital images through sampling and quantization."
      },
      {
        id: 101,
        order: 4,
        slug: "cv-fourier-transform-image-processing",
        title: "Fourier Transform in Image Processing",
        shortTitle: "Fourier Transform",
        type: "article",
        readingTime: 12,
        tags: ["computer vision", "fourier transform", "frequency domain", "image processing", "filtering", "dft"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the Fourier transform for analyzing image frequencies, filtering, and understanding spatial versus frequency domain representations."
      },
      {
        id: 102,
        order: 5,
        slug: "cv-image-noise-and-restoration",
        title: "Image Noise and Restoration",
        shortTitle: "Noise & Restoration",
        type: "article",
        readingTime: 10,
        tags: ["computer vision", "noise", "image restoration", "denoising", "deblurring", "image quality"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Study common image noise types and restoration techniques to recover clean images from degraded observations."
      },
    ]
  },

  {
    id: "computer-vision-mathematics",
    title: "Computer Vision Mathematics",
    order: 2,
    items: [
      {
        id: 103,
        order: 1,
        slug: "cv-linear-algebra-for-computer-vision",
        title: "Linear Algebra for Computer Vision",
        shortTitle: "Linear Algebra",
        type: "article",
        readingTime: 12,
        tags: ["computer vision", "linear algebra", "matrices", "vectors", "eigenvalues", "svd", "mathematics"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Essential linear algebra concepts including matrices, eigenvalues, and SVD that form the mathematical backbone of computer vision."
      },
      {
        id: 104,
        order: 2,
        slug: "cv-probability-and-statistics-for-vision",
        title: "Probability and Statistics for Vision",
        shortTitle: "Probability & Stats",
        type: "article",
        readingTime: 10,
        tags: ["computer vision", "probability", "statistics", "bayesian", "distributions", "uncertainty", "mathematics"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Apply probability theory and statistical methods to model uncertainty, noise, and variability in visual data."
      },
      {
        id: 105,
        order: 3,
        slug: "cv-convolution-mathematics",
        title: "Convolution Mathematics",
        shortTitle: "Convolution Math",
        type: "article",
        readingTime: 10,
        tags: ["computer vision", "convolution", "kernels", "filters", "mathematics", "image processing", "cnn"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Deep dive into the mathematical foundations of convolution, kernels, and filtering operations used in image processing and CNNs."
      },
      {
        id: 106,
        order: 4,
        slug: "cv-optimization-for-vision-models",
        title: "Optimization for Vision Models",
        shortTitle: "Optimization",
        type: "article",
        readingTime: 12,
        tags: ["computer vision", "optimization", "gradient descent", "loss functions", "training", "mathematics"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand optimization algorithms and loss landscapes that drive the training of deep computer vision models."
      },
      {
        id: 107,
        order: 5,
        slug: "cv-geometry-and-coordinate-systems",
        title: "Geometry and Coordinate Systems",
        shortTitle: "Geometry & Coordinates",
        type: "article",
        readingTime: 10,
        tags: ["computer vision", "geometry", "coordinate systems", "3d vision", "world coordinates", "camera coordinates"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn about 2D and 3D coordinate systems, camera calibration, and geometric reasoning essential for visual perception."
      },
    ]
  },

  {
    id: "computer-vision-tools-and-ecosystem",
    title: "Computer Vision Tools and Ecosystem",
    order: 3,
    items: [
      {
        id: 108,
        order: 1,
        slug: "cv-opencv-ecosystem",
        title: "OpenCV Ecosystem",
        shortTitle: "OpenCV",
        type: "article",
        readingTime: 10,
        tags: ["computer vision", "opencv", "libraries", "image processing", "ecosystem", "c++", "python"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the OpenCV library ecosystem for image manipulation, feature detection, video processing, and real-time vision applications."
      },
      {
        id: 109,
        order: 2,
        slug: "cv-pytorch-for-computer-vision",
        title: "PyTorch for Computer Vision",
        shortTitle: "PyTorch Vision",
        type: "article",
        readingTime: 12,
        tags: ["computer vision", "pytorch", "deep learning", "torchvision", "framework", "cnn"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Leverage PyTorch and TorchVision to build, train, and deploy convolutional neural networks for computer vision tasks."
      },
      {
        id: 110,
        order: 3,
        slug: "cv-tensorflow-and-keras-for-vision",
        title: "TensorFlow and Keras for Vision",
        shortTitle: "TensorFlow & Keras",
        type: "article",
        readingTime: 12,
        tags: ["computer vision", "tensorflow", "keras", "deep learning", "framework", "tf-vision"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Use TensorFlow and Keras to construct vision pipelines, transfer learning workflows, and production-ready image models."
      },
      {
        id: 111,
        order: 4,
        slug: "cv-albumentations-for-image-augmentation",
        title: "Albumentations for Image Augmentation",
        shortTitle: "Albumentations",
        type: "article",
        readingTime: 8,
        tags: ["computer vision", "albumentations", "data augmentation", "image augmentation", "preprocessing", "training"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master Albumentations for fast, flexible, and GPU-accelerated image augmentation to improve model generalization."
      },
      {
        id: 112,
        order: 5,
        slug: "cv-hugging-face-vision-models",
        title: "Hugging Face Vision Models",
        shortTitle: "Hugging Face Vision",
        type: "article",
        readingTime: 10,
        tags: ["computer vision", "hugging face", "transformers", "pretrained models", "vision models", "ecosystem"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover pretrained vision models and tools on Hugging Face for classification, detection, segmentation, and multimodal tasks."
      },
    ]
  },

  {
    id: "advanced-and-emerging-topics",
    title: "Advanced and Emerging Topics",
    order: 4,
    items: [
      {
        id: 113,
        order: 1,
        slug: "cv-vision-transformers-and-attention",
        title: "Vision Transformers and Attention",
        shortTitle: "Vision Transformers",
        type: "article",
        readingTime: 14,
        tags: ["computer vision", "vision transformers", "vit", "attention", "transformers", "advanced"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand Vision Transformers (ViT) and attention mechanisms that are reshaping modern computer vision architectures."
      },
      {
        id: 114,
        order: 2,
        slug: "cv-generative-models-for-images",
        title: "Generative Models for Images",
        shortTitle: "Generative Models",
        type: "article",
        readingTime: 12,
        tags: ["computer vision", "generative models", "gan", "vae", "image generation", "advanced"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore GANs, VAEs, and other generative architectures for synthesizing realistic images and creative visual content."
      },
      {
        id: 115,
        order: 3,
        slug: "cv-diffusion-models-for-computer-vision",
        title: "Diffusion Models for Computer Vision",
        shortTitle: "Diffusion Models",
        type: "article",
        readingTime: 14,
        tags: ["computer vision", "diffusion models", "generative ai", "image synthesis", "stable diffusion", "advanced"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how diffusion models generate high-quality images through iterative denoising and their impact on visual AI."
      },
      {
        id: 116,
        order: 4,
        slug: "cv-multimodal-vision-language-models",
        title: "Multimodal Vision-Language Models",
        shortTitle: "Vision-Language Models",
        type: "article",
        readingTime: 12,
        tags: ["computer vision", "multimodal", "vision-language", "clip", "llava", "advanced", "nlp"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Study multimodal models that jointly understand images and text, enabling zero-shot recognition and visual question answering."
      },
      {
        id: 117,
        order: 5,
        slug: "cv-zero-shot-computer-vision",
        title: "Zero-Shot Computer Vision",
        shortTitle: "Zero-Shot Vision",
        type: "article",
        readingTime: 10,
        tags: ["computer vision", "zero-shot", "generalization", "clip", "open vocabulary", "advanced"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover zero-shot and open-vocabulary computer vision techniques that recognize objects without task-specific training data."
      },
    ]
  },

  {
    id: "industry-research-and-practice",
    title: "Industry, Research and Practice",
    order: 5,
    items: [
      {
        id: 118,
        order: 1,
        slug: "cv-datasets-and-benchmarks",
        title: "Computer Vision Datasets and Benchmarks",
        shortTitle: "Datasets & Benchmarks",
        type: "article",
        readingTime: 10,
        tags: ["computer vision", "datasets", "benchmarks", "imagenet", "coco", "evaluation", "industry"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Overview of essential computer vision datasets and benchmarks like ImageNet, COCO, and Pascal VOC for model evaluation."
      },
      {
        id: 119,
        order: 2,
        slug: "cv-model-deployment-and-optimization",
        title: "Model Deployment and Optimization",
        shortTitle: "Deployment & Optimization",
        type: "article",
        readingTime: 12,
        tags: ["computer vision", "deployment", "optimization", "tensorrt", "onnx", "quantization", "production"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn strategies for optimizing and deploying vision models using quantization, pruning, and inference acceleration tools."
      },
      {
        id: 120,
        order: 3,
        slug: "cv-edge-ai-and-real-time-vision",
        title: "Edge AI and Real-Time Vision",
        shortTitle: "Edge AI Vision",
        type: "article",
        readingTime: 10,
        tags: ["computer vision", "edge ai", "real-time", "embedded", "iot", "mobile vision", "inference"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Build efficient computer vision systems for edge devices, mobile phones, and embedded hardware with real-time constraints."
      },
      {
        id: 121,
        order: 4,
        slug: "cv-bias-privacy-and-ethics",
        title: "Bias, Privacy and Ethics in Computer Vision",
        shortTitle: "Bias & Ethics",
        type: "article",
        readingTime: 10,
        tags: ["computer vision", "bias", "privacy", "ethics", "fairness", "facial recognition", "responsible ai"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Address fairness, privacy risks, and ethical concerns in computer vision systems including surveillance and facial recognition."
      },
      {
        id: 122,
        order: 5,
        slug: "cv-research-and-career-paths",
        title: "Computer Vision Research and Career Paths",
        shortTitle: "Research & Career",
        type: "article",
        readingTime: 10,
        tags: ["computer vision", "career", "research", "roadmap", "industry", "academia", "skills"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Navigate career opportunities and research directions in computer vision from autonomous vehicles to medical imaging and robotics."
      },
    ]
  },
];