// ============================================================
// src/registry/lessons/pythonLessons.js
// STUB — same shape as htmlLessons.js, empty until you fill it in.
// lessonRegistry.js can safely import this right now without
// breaking anything; it'll just show 0 lessons for Python until
// you add sections here.
// ============================================================

import { STATUS } from "../../config/constants";

export const tutorialInfo = {
  id: "linux",
  title: "Linux Tutorial",
  shortTitle: "Linux",
  category: "DevOps",
  description: "Master Linux from beginner to advanced with a comprehensive tutorial covering the Linux command line, filesystem, file permissions, users and groups, processes, packages, networking, SSH, Bash scripting, services, logs, storage, security, system administration, troubleshooting, and practical Linux server management.",
  icon: "linux",
  difficulty: "Advanced", // course-level badge, separate from per-section defaults
  estimatedHours: 47,
  totalLessons: 91,
  version: "Latest Version",
  language: "English",
  path: "/linux",
  authorId: "faiz",
  updatedAt: "2026-07-09",
  tags: ["linux", "linux tutorial", "linux for beginners", "linux command line", "linux terminal", "linux commands", "linux administration", "linux system administration", "linux server", "linux server administration", "bash", "bash scripting", "shell scripting", "linux filesystem", "linux file permissions", "linux users", "linux groups", "linux processes", "linux networking", "ssh", "linux security", "package management", "systemd", "linux services", "linux logs", "linux storage", "linux troubleshooting", "devops", "server management", "unix"],
  seo: {
    title: "Linux Tutorial - Learn Linux from Beginner to Advanced | DevSphere",
    description: "Learn Linux from scratch with a complete tutorial covering terminal commands, filesystem, permissions, users, processes, Bash scripting, networking, SSH, package management, services, storage, security, troubleshooting, and Linux system administration.",
    keywords: ["Linux Tutorial", "Linux Tutorial for Beginners", "Learn Linux", "Linux Course", "Linux for Beginners", "Linux Training", "Linux Basics", "Linux Fundamentals", "Linux Programming", "Linux Administration", "Linux System Administration", "Linux System Administrator", "Linux Server", "Linux Server Administration", "Linux Command Line", "Linux Command Line Tutorial", "Linux Terminal", "Linux Terminal Commands", "Linux Commands", "Linux Commands for Beginners", "Linux CLI", "Linux Shell", "Linux Shell Tutorial", "Bash Tutorial", "Bash Scripting", "Bash Script Tutorial", "Shell Scripting", "Shell Scripting Tutorial", "Linux Filesystem", "Linux File System", "Linux File Management", "Linux Directory Structure", "Linux File Permissions", "Linux Permissions", "chmod", "chown", "Linux Users", "Linux User Management", "Linux Groups", "Linux Group Management", "Linux Processes", "Linux Process Management", "Linux Jobs and Processes", "Linux Signals", "Linux Package Management", "Linux Package Manager", "apt Linux", "dnf Linux", "yum Linux", "Linux Software Installation", "Linux Environment Variables", "Linux PATH", "Linux Networking", "Linux Network Commands", "Linux Network Configuration", "Linux TCP IP", "Linux DNS", "Linux SSH", "SSH Tutorial", "SSH Linux", "Linux Remote Access", "Linux Systemd", "Systemd Tutorial", "Linux Services", "Linux Service Management", "Linux Logs", "Linux Log Management", "Linux journalctl", "Linux Storage", "Linux Disk Management", "Linux Partitions", "Linux File Systems", "Linux Mount", "Linux Security", "Linux Security Tutorial", "Linux Firewall", "Linux Server Security", "Linux Troubleshooting", "Linux Debugging", "Linux Monitoring", "Linux Cron", "Linux Crontab", "Linux Automation", "Linux DevOps", "Linux for DevOps", "Linux Docker", "Linux Kubernetes", "Linux Cloud Server", "Linux Server Management", "Linux Administration Commands", "Linux Best Practices", "Linux Projects", "Linux Practical Tutorial", "DevSphere"]
  }
};

export const sections = [
  {
    id: "linux-fundamentals",
    title: "Linux Fundamentals",
    order: 1,
    difficulty: "Beginner",
    lessons: [
      {
        id: 1,
        order: 1,
        slug: "linux-what-is-linux",
        title: "What is Linux?",
        shortTitle: "What is Linux",
        readingTime: 9,
        tags: ["linux", "linux tutorial", "devops", "linux command line", "linux terminal"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get a comprehensive introduction to Linux, understanding its history, philosophy, and why it powers the modern internet.",
        prerequisites: [],
        related: ["linux-linux-vs-unix-vs-windows", "linux-navigating-the-linux-file-system"],
        recommended: ["linux-linux-distributions-and-popular-distros", "linux-linux-architecture-kernel-shell-and-utilities"]
      },
      {
        id: 2,
        order: 2,
        slug: "linux-linux-vs-unix-vs-windows",
        title: "Linux vs Unix vs Windows",
        shortTitle: "Linux vs Unix vs Windows",
        readingTime: 10,
        tags: ["linux", "linux tutorial", "devops", "linux command line", "linux terminal"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Compare Linux with Unix and Windows to understand the key architectural and philosophical differences.",
        prerequisites: ["linux-what-is-linux", "linux-linux-distributions-and-popular-distros"],
        related: ["linux-linux-distributions-and-popular-distros", "linux-what-is-linux"],
        recommended: ["linux-linux-distributions-and-popular-distros", "linux-linux-architecture-kernel-shell-and-utilities"]
      },
      {
        id: 3,
        order: 3,
        slug: "linux-linux-distributions-and-popular-distros",
        title: "Linux Distributions and Popular Distros",
        shortTitle: "Linux Distributions and Popula...",
        readingTime: 11,
        tags: ["linux", "linux tutorial", "devops", "linux command line", "linux terminal"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the ecosystem of Linux distributions (distros) and learn how to choose the right one for your needs.",
        prerequisites: ["linux-linux-vs-unix-vs-windows", "linux-what-is-linux"],
        related: ["linux-linux-architecture-kernel-shell-and-utilities", "linux-linux-vs-unix-vs-windows"],
        recommended: ["linux-linux-architecture-kernel-shell-and-utilities", "linux-linux-desktop-vs-server"]
      },
      {
        id: 4,
        order: 4,
        slug: "linux-linux-architecture-kernel-shell-and-utilities",
        title: "Linux Architecture: Kernel, Shell, and Utilities",
        shortTitle: "Linux Architecture Kernel She...",
        readingTime: 12,
        tags: ["linux", "linux tutorial", "devops", "linux command line", "linux terminal"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Deep dive into the core components of Linux: the kernel, the shell, and the user-space utilities.",
        prerequisites: ["linux-linux-distributions-and-popular-distros", "linux-linux-vs-unix-vs-windows"],
        related: ["linux-linux-desktop-vs-server", "linux-linux-distributions-and-popular-distros"],
        recommended: ["linux-linux-desktop-vs-server", "linux-installing-linux-with-a-virtual-machine"]
      },
      {
        id: 5,
        order: 5,
        slug: "linux-linux-desktop-vs-server",
        title: "Linux Desktop vs Server",
        shortTitle: "Linux Desktop vs Server",
        readingTime: 13,
        tags: ["linux", "linux tutorial", "devops", "linux command line", "linux terminal"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the differences between desktop and server Linux environments and their specific use cases.",
        prerequisites: ["linux-linux-architecture-kernel-shell-and-utilities", "linux-linux-distributions-and-popular-distros"],
        related: ["linux-installing-linux-with-a-virtual-machine", "linux-linux-architecture-kernel-shell-and-utilities"],
        recommended: ["linux-installing-linux-with-a-virtual-machine", "linux-using-the-linux-terminal"]
      },
      {
        id: 6,
        order: 6,
        slug: "linux-installing-linux-with-a-virtual-machine",
        title: "Installing Linux with a Virtual Machine",
        shortTitle: "Installing Linux with a Virtu...",
        readingTime: 14,
        tags: ["linux", "linux tutorial", "devops", "linux command line", "linux terminal"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to safely install and configure a Linux distribution using a virtual machine for practice.",
        prerequisites: ["linux-linux-desktop-vs-server", "linux-linux-architecture-kernel-shell-and-utilities"],
        related: ["linux-using-the-linux-terminal", "linux-linux-desktop-vs-server"],
        recommended: ["linux-using-the-linux-terminal", "linux-understanding-commands-and-command-structure"]
      },
      {
        id: 7,
        order: 7,
        slug: "linux-using-the-linux-terminal",
        title: "Using the Linux Terminal",
        shortTitle: "Using the Linux Terminal",
        readingTime: 15,
        tags: ["linux", "linux tutorial", "devops", "linux command line", "linux terminal"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the basics of interacting with the Linux command line interface (CLI) efficiently.",
        prerequisites: ["linux-installing-linux-with-a-virtual-machine", "linux-linux-desktop-vs-server"],
        related: ["linux-understanding-commands-and-command-structure", "linux-installing-linux-with-a-virtual-machine"],
        recommended: ["linux-understanding-commands-and-command-structure", "linux-navigating-the-linux-file-system"]
      },
      {
        id: 8,
        order: 8,
        slug: "linux-understanding-commands-and-command-structure",
        title: "Understanding Commands and Command Structure",
        shortTitle: "Understanding Commands and Co...",
        readingTime: 8,
        tags: ["linux", "linux tutorial", "devops", "linux command line", "linux terminal"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn the standard structure of Linux commands, including options, arguments, and flags.",
        prerequisites: ["linux-using-the-linux-terminal", "linux-installing-linux-with-a-virtual-machine"],
        related: ["linux-using-the-linux-terminal", "linux-navigating-the-linux-file-system"],
        recommended: ["linux-navigating-the-linux-file-system", "linux-pwd-ls-and-cd-commands"]
      }
    ]
  },
  {
    id: "linux-command-line-basics",
    title: "Linux Command Line Basics",
    order: 2,
    difficulty: "Beginner",
    lessons: [
      {
        id: 9,
        order: 1,
        slug: "linux-navigating-the-linux-file-system",
        title: "Navigating the Linux File System",
        shortTitle: "Navigating the Linux File Sys...",
        readingTime: 9,
        tags: ["linux", "linux tutorial", "devops", "linux filesystem", "linux file management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the hierarchical structure of the Linux filesystem and how to move around it.",
        prerequisites: ["linux-understanding-commands-and-command-structure", "linux-using-the-linux-terminal"],
        related: ["linux-pwd-ls-and-cd-commands", "linux-understanding-commands-and-command-structure"],
        recommended: ["linux-pwd-ls-and-cd-commands", "linux-creating-files-and-directories"]
      },
      {
        id: 10,
        order: 2,
        slug: "linux-pwd-ls-and-cd-commands",
        title: "pwd, ls, and cd Commands",
        shortTitle: "pwd, ls, and cd Commands",
        readingTime: 10,
        tags: ["linux", "linux tutorial", "devops", "linux filesystem", "linux file management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the most essential navigation commands: print working directory, list, and change directory.",
        prerequisites: ["linux-navigating-the-linux-file-system", "linux-understanding-commands-and-command-structure"],
        related: ["linux-creating-files-and-directories", "linux-navigating-the-linux-file-system"],
        recommended: ["linux-creating-files-and-directories", "linux-copying-moving-and-renaming-files"]
      },
      {
        id: 11,
        order: 3,
        slug: "linux-creating-files-and-directories",
        title: "Creating Files and Directories",
        shortTitle: "Creating Files and Directories",
        readingTime: 11,
        tags: ["linux", "linux tutorial", "devops", "linux filesystem", "linux file management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to create new files and directories using commands like touch and mkdir.",
        prerequisites: ["linux-pwd-ls-and-cd-commands", "linux-navigating-the-linux-file-system"],
        related: ["linux-copying-moving-and-renaming-files", "linux-pwd-ls-and-cd-commands"],
        recommended: ["linux-copying-moving-and-renaming-files", "linux-removing-files-and-directories"]
      },
      {
        id: 12,
        order: 4,
        slug: "linux-copying-moving-and-renaming-files",
        title: "Copying, Moving, and Renaming Files",
        shortTitle: "Copying, Moving, and Renaming...",
        readingTime: 12,
        tags: ["linux", "linux tutorial", "devops", "linux filesystem", "linux file management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how to use cp and mv to duplicate, relocate, and rename files and directories.",
        prerequisites: ["linux-creating-files-and-directories", "linux-pwd-ls-and-cd-commands"],
        related: ["linux-removing-files-and-directories", "linux-creating-files-and-directories"],
        recommended: ["linux-removing-files-and-directories", "linux-viewing-file-contents"]
      },
      {
        id: 13,
        order: 5,
        slug: "linux-removing-files-and-directories",
        title: "Removing Files and Directories",
        shortTitle: "Removing Files and Directories",
        readingTime: 13,
        tags: ["linux", "linux tutorial", "devops", "linux filesystem", "linux file management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to safely delete files and directories using rm and rmdir, including recursive deletion.",
        prerequisites: ["linux-copying-moving-and-renaming-files", "linux-creating-files-and-directories"],
        related: ["linux-viewing-file-contents", "linux-copying-moving-and-renaming-files"],
        recommended: ["linux-viewing-file-contents", "linux-using-echo-printf-and-touch"]
      },
      {
        id: 14,
        order: 6,
        slug: "linux-viewing-file-contents",
        title: "Viewing File Contents",
        shortTitle: "Viewing File Contents",
        readingTime: 14,
        tags: ["linux", "linux tutorial", "devops", "linux filesystem", "linux file management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover various commands like cat, less, and more to read file contents directly in the terminal.",
        prerequisites: ["linux-removing-files-and-directories", "linux-copying-moving-and-renaming-files"],
        related: ["linux-using-echo-printf-and-touch", "linux-removing-files-and-directories"],
        recommended: ["linux-using-echo-printf-and-touch", "linux-getting-help-with-man---help-and-info"]
      },
      {
        id: 15,
        order: 7,
        slug: "linux-using-echo-printf-and-touch",
        title: "Using echo, printf, and touch",
        shortTitle: "Using echo, printf, and touch",
        readingTime: 15,
        tags: ["linux", "linux tutorial", "devops", "linux filesystem", "linux file management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to output text, format strings, and update file timestamps using these fundamental utilities.",
        prerequisites: ["linux-viewing-file-contents", "linux-removing-files-and-directories"],
        related: ["linux-getting-help-with-man---help-and-info", "linux-viewing-file-contents"],
        recommended: ["linux-getting-help-with-man---help-and-info", "linux-linux-file-system-hierarchy"]
      },
      {
        id: 16,
        order: 8,
        slug: "linux-getting-help-with-man---help-and-info",
        title: "Getting Help with man, --help, and info",
        shortTitle: "Getting Help with man, --help...",
        readingTime: 8,
        tags: ["linux", "linux tutorial", "devops", "linux filesystem", "linux file management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the built-in Linux documentation systems to find help and usage examples for any command.",
        prerequisites: ["linux-using-echo-printf-and-touch", "linux-viewing-file-contents"],
        related: ["linux-using-echo-printf-and-touch", "linux-linux-file-system-hierarchy"],
        recommended: ["linux-linux-file-system-hierarchy", "linux-absolute-vs-relative-paths"]
      }
    ]
  },
  {
    id: "files-directories-and-text-processing",
    title: "Files, Directories, and Text Processing",
    order: 3,
    difficulty: "Beginner",
    lessons: [
      {
        id: 17,
        order: 1,
        slug: "linux-linux-file-system-hierarchy",
        title: "Linux File System Hierarchy",
        shortTitle: "Linux File System Hierarchy",
        readingTime: 9,
        tags: ["linux", "linux tutorial", "devops", "linux filesystem", "linux file management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the standard Linux directory structure (FHS) and the purpose of directories like /etc, /var, and /home.",
        prerequisites: ["linux-getting-help-with-man---help-and-info", "linux-using-echo-printf-and-touch"],
        related: ["linux-absolute-vs-relative-paths", "linux-getting-help-with-man---help-and-info"],
        recommended: ["linux-absolute-vs-relative-paths", "linux-file-types-and-file-metadata"]
      },
      {
        id: 18,
        order: 2,
        slug: "linux-absolute-vs-relative-paths",
        title: "Absolute vs Relative Paths",
        shortTitle: "Absolute vs Relative Paths",
        readingTime: 10,
        tags: ["linux", "linux tutorial", "devops", "linux filesystem", "linux file management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the difference between absolute and relative paths and when to use each.",
        prerequisites: ["linux-linux-file-system-hierarchy", "linux-getting-help-with-man---help-and-info"],
        related: ["linux-file-types-and-file-metadata", "linux-linux-file-system-hierarchy"],
        recommended: ["linux-file-types-and-file-metadata", "linux-hard-links-and-symbolic-links"]
      },
      {
        id: 19,
        order: 3,
        slug: "linux-file-types-and-file-metadata",
        title: "File Types and File Metadata",
        shortTitle: "File Types and File Metadata",
        readingTime: 11,
        tags: ["linux", "linux tutorial", "devops", "linux filesystem", "linux file management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to identify file types and view metadata using the file and stat commands.",
        prerequisites: ["linux-absolute-vs-relative-paths", "linux-linux-file-system-hierarchy"],
        related: ["linux-hard-links-and-symbolic-links", "linux-absolute-vs-relative-paths"],
        recommended: ["linux-hard-links-and-symbolic-links", "linux-wildcards-and-filename-expansion"]
      },
      {
        id: 20,
        order: 4,
        slug: "linux-hard-links-and-symbolic-links",
        title: "Hard Links and Symbolic Links",
        shortTitle: "Hard Links and Symbolic Links",
        readingTime: 12,
        tags: ["linux", "linux tutorial", "devops", "linux filesystem", "linux file management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the difference between hard links and symbolic (soft) links and how to create them.",
        prerequisites: ["linux-file-types-and-file-metadata", "linux-absolute-vs-relative-paths"],
        related: ["linux-wildcards-and-filename-expansion", "linux-file-types-and-file-metadata"],
        recommended: ["linux-wildcards-and-filename-expansion", "linux-searching-with-find-and-locate"]
      },
      {
        id: 21,
        order: 5,
        slug: "linux-wildcards-and-filename-expansion",
        title: "Wildcards and Filename Expansion",
        shortTitle: "Wildcards and Filename Expansion",
        readingTime: 13,
        tags: ["linux", "linux tutorial", "devops", "linux filesystem", "linux file management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the use of globbing characters like *, ?, and [] to match and manipulate multiple files.",
        prerequisites: ["linux-hard-links-and-symbolic-links", "linux-file-types-and-file-metadata"],
        related: ["linux-searching-with-find-and-locate", "linux-hard-links-and-symbolic-links"],
        recommended: ["linux-searching-with-find-and-locate", "linux-text-processing-with-grep-sort-and-uniq"]
      },
      {
        id: 22,
        order: 6,
        slug: "linux-searching-with-find-and-locate",
        title: "Searching with find and locate",
        shortTitle: "Searching with find and locate",
        readingTime: 14,
        tags: ["linux", "linux tutorial", "devops", "linux filesystem", "linux file management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn powerful techniques for locating files and directories based on name, size, time, and permissions.",
        prerequisites: ["linux-wildcards-and-filename-expansion", "linux-hard-links-and-symbolic-links"],
        related: ["linux-text-processing-with-grep-sort-and-uniq", "linux-wildcards-and-filename-expansion"],
        recommended: ["linux-text-processing-with-grep-sort-and-uniq", "linux-processing-text-with-cut-tr-head-and-tail"]
      },
      {
        id: 23,
        order: 7,
        slug: "linux-text-processing-with-grep-sort-and-uniq",
        title: "Text Processing with grep, sort, and uniq",
        shortTitle: "Text Processing with grep, so...",
        readingTime: 15,
        tags: ["linux", "linux tutorial", "devops", "linux filesystem", "linux file management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how to search, filter, sort, and deduplicate text data using these essential command-line tools.",
        prerequisites: ["linux-searching-with-find-and-locate", "linux-wildcards-and-filename-expansion"],
        related: ["linux-processing-text-with-cut-tr-head-and-tail", "linux-searching-with-find-and-locate"],
        recommended: ["linux-processing-text-with-cut-tr-head-and-tail", "linux-sed-and-awk-fundamentals"]
      },
      {
        id: 24,
        order: 8,
        slug: "linux-processing-text-with-cut-tr-head-and-tail",
        title: "Processing Text with cut, tr, head, and tail",
        shortTitle: "Processing Text with cut, tr,...",
        readingTime: 8,
        tags: ["linux", "linux tutorial", "devops", "linux filesystem", "linux file management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to extract columns, translate characters, and view the beginning or end of files.",
        prerequisites: ["linux-text-processing-with-grep-sort-and-uniq", "linux-searching-with-find-and-locate"],
        related: ["linux-sed-and-awk-fundamentals", "linux-text-processing-with-grep-sort-and-uniq"],
        recommended: ["linux-sed-and-awk-fundamentals", "linux-combining-commands-with-pipes"]
      },
      {
        id: 25,
        order: 9,
        slug: "linux-sed-and-awk-fundamentals",
        title: "sed and awk Fundamentals",
        shortTitle: "sed and awk Fundamentals",
        readingTime: 9,
        tags: ["linux", "linux tutorial", "devops", "linux filesystem", "linux file management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to sed and awk, the powerful stream editor and text processing languages of Linux.",
        prerequisites: ["linux-processing-text-with-cut-tr-head-and-tail", "linux-text-processing-with-grep-sort-and-uniq"],
        related: ["linux-combining-commands-with-pipes", "linux-processing-text-with-cut-tr-head-and-tail"],
        recommended: ["linux-combining-commands-with-pipes", "linux-linux-users-and-groups"]
      },
      {
        id: 26,
        order: 10,
        slug: "linux-combining-commands-with-pipes",
        title: "Combining Commands with Pipes",
        shortTitle: "Combining Commands with Pipes",
        readingTime: 10,
        tags: ["linux", "linux tutorial", "devops", "linux filesystem", "linux file management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the pipe operator (|) to chain multiple commands together for complex data processing.",
        prerequisites: ["linux-sed-and-awk-fundamentals", "linux-processing-text-with-cut-tr-head-and-tail"],
        related: ["linux-sed-and-awk-fundamentals", "linux-linux-users-and-groups"],
        recommended: ["linux-linux-users-and-groups", "linux-file-ownership"]
      }
    ]
  },
  {
    id: "permissions-users-and-ownership",
    title: "Permissions, Users, and Ownership",
    order: 4,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 27,
        order: 1,
        slug: "linux-linux-users-and-groups",
        title: "Linux Users and Groups",
        shortTitle: "Linux Users and Groups",
        readingTime: 11,
        tags: ["linux", "linux tutorial", "devops", "linux users", "linux groups"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how Linux manages user accounts and groups for access control and resource sharing.",
        prerequisites: ["linux-combining-commands-with-pipes", "linux-sed-and-awk-fundamentals"],
        related: ["linux-file-ownership", "linux-combining-commands-with-pipes"],
        recommended: ["linux-file-ownership", "linux-understanding-linux-file-permissions"]
      },
      {
        id: 28,
        order: 2,
        slug: "linux-file-ownership",
        title: "File Ownership",
        shortTitle: "File Ownership",
        readingTime: 12,
        tags: ["linux", "linux tutorial", "devops", "linux users", "linux groups"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how every file and directory in Linux is owned by a specific user and group.",
        prerequisites: ["linux-linux-users-and-groups", "linux-combining-commands-with-pipes"],
        related: ["linux-understanding-linux-file-permissions", "linux-linux-users-and-groups"],
        recommended: ["linux-understanding-linux-file-permissions", "linux-reading-permission-notation"]
      },
      {
        id: 29,
        order: 3,
        slug: "linux-understanding-linux-file-permissions",
        title: "Understanding Linux File Permissions",
        shortTitle: "Understanding Linux File Perm...",
        readingTime: 13,
        tags: ["linux", "linux tutorial", "devops", "linux security", "linux file permissions"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Deep dive into the read, write, and execute permissions that govern access to files and directories.",
        prerequisites: ["linux-file-ownership", "linux-linux-users-and-groups"],
        related: ["linux-reading-permission-notation", "linux-file-ownership"],
        recommended: ["linux-reading-permission-notation", "linux-changing-permissions-with-chmod"]
      },
      {
        id: 30,
        order: 4,
        slug: "linux-reading-permission-notation",
        title: "Reading Permission Notation",
        shortTitle: "Reading Permission Notation",
        readingTime: 14,
        tags: ["linux", "linux tutorial", "devops", "linux security", "linux file permissions"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to interpret the symbolic (rwxr-xr--) and octal (755) permission notations.",
        prerequisites: ["linux-understanding-linux-file-permissions", "linux-file-ownership"],
        related: ["linux-changing-permissions-with-chmod", "linux-understanding-linux-file-permissions"],
        recommended: ["linux-changing-permissions-with-chmod", "linux-changing-ownership-with-chown-and-chgrp"]
      },
      {
        id: 31,
        order: 5,
        slug: "linux-changing-permissions-with-chmod",
        title: "Changing Permissions with chmod",
        shortTitle: "Changing Permissions with chmod",
        readingTime: 15,
        tags: ["linux", "linux tutorial", "devops", "linux security", "linux file permissions"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the chmod command to modify file and directory permissions using both symbolic and octal modes.",
        prerequisites: ["linux-reading-permission-notation", "linux-understanding-linux-file-permissions"],
        related: ["linux-changing-ownership-with-chown-and-chgrp", "linux-reading-permission-notation"],
        recommended: ["linux-changing-ownership-with-chown-and-chgrp", "linux-special-permissions-suid-sgid-and-sticky-bit"]
      },
      {
        id: 32,
        order: 6,
        slug: "linux-changing-ownership-with-chown-and-chgrp",
        title: "Changing Ownership with chown and chgrp",
        shortTitle: "Changing Ownership with chown...",
        readingTime: 8,
        tags: ["linux", "linux tutorial", "devops", "linux security", "linux file permissions"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to transfer file and directory ownership to different users and groups.",
        prerequisites: ["linux-changing-permissions-with-chmod", "linux-reading-permission-notation"],
        related: ["linux-special-permissions-suid-sgid-and-sticky-bit", "linux-changing-permissions-with-chmod"],
        recommended: ["linux-special-permissions-suid-sgid-and-sticky-bit", "linux-sudo-and-privilege-management"]
      },
      {
        id: 33,
        order: 7,
        slug: "linux-special-permissions-suid-sgid-and-sticky-bit",
        title: "Special Permissions: SUID, SGID, and Sticky Bit",
        shortTitle: "Special Permissions SUID, SGI...",
        readingTime: 9,
        tags: ["linux", "linux tutorial", "devops", "linux security", "linux file permissions"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand advanced permission bits that allow execution with owner privileges or protect shared directories.",
        prerequisites: ["linux-changing-ownership-with-chown-and-chgrp", "linux-changing-permissions-with-chmod"],
        related: ["linux-sudo-and-privilege-management", "linux-changing-ownership-with-chown-and-chgrp"],
        recommended: ["linux-sudo-and-privilege-management", "linux-what-is-a-shell"]
      },
      {
        id: 34,
        order: 8,
        slug: "linux-sudo-and-privilege-management",
        title: "sudo and Privilege Management",
        shortTitle: "sudo and Privilege Management",
        readingTime: 10,
        tags: ["linux", "linux tutorial", "devops", "linux security", "linux file permissions"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to safely execute commands with superuser privileges using sudo and the /etc/sudoers file.",
        prerequisites: ["linux-special-permissions-suid-sgid-and-sticky-bit", "linux-changing-ownership-with-chown-and-chgrp"],
        related: ["linux-special-permissions-suid-sgid-and-sticky-bit", "linux-what-is-a-shell"],
        recommended: ["linux-what-is-a-shell", "linux-bash-and-the-bash-shell"]
      }
    ]
  },
  {
    id: "shell-and-environment",
    title: "Shell and Environment",
    order: 5,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 35,
        order: 1,
        slug: "linux-what-is-a-shell",
        title: "What is a Shell?",
        shortTitle: "What is a Shell",
        readingTime: 11,
        tags: ["linux", "linux tutorial", "devops", "bash scripting", "shell scripting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to the concept of a shell as the command-line interpreter between the user and the kernel.",
        prerequisites: ["linux-sudo-and-privilege-management", "linux-special-permissions-suid-sgid-and-sticky-bit"],
        related: ["linux-bash-and-the-bash-shell", "linux-sudo-and-privilege-management"],
        recommended: ["linux-bash-and-the-bash-shell", "linux-environment-variables"]
      },
      {
        id: 36,
        order: 2,
        slug: "linux-bash-and-the-bash-shell",
        title: "Bash and the Bash Shell",
        shortTitle: "Bash and the Bash Shell",
        readingTime: 12,
        tags: ["linux", "linux tutorial", "devops", "bash scripting", "shell scripting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore Bash (Bourne Again SHell), the default and most widely used shell in Linux distributions.",
        prerequisites: ["linux-what-is-a-shell", "linux-sudo-and-privilege-management"],
        related: ["linux-environment-variables", "linux-what-is-a-shell"],
        recommended: ["linux-environment-variables", "linux-shell-variables-and-variable-expansion"]
      },
      {
        id: 37,
        order: 3,
        slug: "linux-environment-variables",
        title: "Environment Variables",
        shortTitle: "Environment Variables",
        readingTime: 13,
        tags: ["linux", "linux tutorial", "devops", "bash scripting", "shell scripting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how environment variables store system-wide configuration and how to view or set them.",
        prerequisites: ["linux-bash-and-the-bash-shell", "linux-what-is-a-shell"],
        related: ["linux-shell-variables-and-variable-expansion", "linux-bash-and-the-bash-shell"],
        recommended: ["linux-shell-variables-and-variable-expansion", "linux-path-and-command-resolution"]
      },
      {
        id: 38,
        order: 4,
        slug: "linux-shell-variables-and-variable-expansion",
        title: "Shell Variables and Variable Expansion",
        shortTitle: "Shell Variables and Variable ...",
        readingTime: 14,
        tags: ["linux", "linux tutorial", "devops", "bash scripting", "shell scripting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to define, use, and expand local shell variables within your terminal session.",
        prerequisites: ["linux-environment-variables", "linux-bash-and-the-bash-shell"],
        related: ["linux-path-and-command-resolution", "linux-environment-variables"],
        recommended: ["linux-path-and-command-resolution", "linux-input-output-and-error-streams"]
      },
      {
        id: 39,
        order: 5,
        slug: "linux-path-and-command-resolution",
        title: "PATH and Command Resolution",
        shortTitle: "PATH and Command Resolution",
        readingTime: 15,
        tags: ["linux", "linux tutorial", "devops", "bash scripting", "shell scripting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how the PATH variable determines where the shell looks for executable commands.",
        prerequisites: ["linux-shell-variables-and-variable-expansion", "linux-environment-variables"],
        related: ["linux-input-output-and-error-streams", "linux-shell-variables-and-variable-expansion"],
        recommended: ["linux-input-output-and-error-streams", "linux-redirection-with----and-2"]
      },
      {
        id: 40,
        order: 6,
        slug: "linux-input-output-and-error-streams",
        title: "Input, Output, and Error Streams",
        shortTitle: "Input, Output, and Error Stre...",
        readingTime: 8,
        tags: ["linux", "linux tutorial", "devops", "bash scripting", "shell scripting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the standard input (stdin), output (stdout), and error (stderr) streams in Linux.",
        prerequisites: ["linux-path-and-command-resolution", "linux-shell-variables-and-variable-expansion"],
        related: ["linux-redirection-with----and-2", "linux-path-and-command-resolution"],
        recommended: ["linux-redirection-with----and-2", "linux-command-substitution-and-quoting"]
      },
      {
        id: 41,
        order: 7,
        slug: "linux-redirection-with----and-2",
        title: "Redirection with >, >>, <, and 2>",
        shortTitle: "Redirection with >, >>, <, an...",
        readingTime: 9,
        tags: ["linux", "linux tutorial", "devops", "bash scripting", "shell scripting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master stream redirection to save command output to files or feed files as input to commands.",
        prerequisites: ["linux-input-output-and-error-streams", "linux-path-and-command-resolution"],
        related: ["linux-command-substitution-and-quoting", "linux-input-output-and-error-streams"],
        recommended: ["linux-command-substitution-and-quoting", "linux-command-history-and-aliases"]
      },
      {
        id: 42,
        order: 8,
        slug: "linux-command-substitution-and-quoting",
        title: "Command Substitution and Quoting",
        shortTitle: "Command Substitution and Quot...",
        readingTime: 10,
        tags: ["linux", "linux tutorial", "devops", "bash scripting", "shell scripting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to use the output of one command as an argument for another, and how to handle spaces with quotes.",
        prerequisites: ["linux-redirection-with----and-2", "linux-input-output-and-error-streams"],
        related: ["linux-command-history-and-aliases", "linux-redirection-with----and-2"],
        recommended: ["linux-command-history-and-aliases", "linux-understanding-linux-processes"]
      },
      {
        id: 43,
        order: 9,
        slug: "linux-command-history-and-aliases",
        title: "Command History and Aliases",
        shortTitle: "Command History and Aliases",
        readingTime: 11,
        tags: ["linux", "linux tutorial", "devops", "bash scripting", "shell scripting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how to recall previous commands and create custom shortcuts using aliases.",
        prerequisites: ["linux-command-substitution-and-quoting", "linux-redirection-with----and-2"],
        related: ["linux-command-substitution-and-quoting", "linux-understanding-linux-processes"],
        recommended: ["linux-understanding-linux-processes", "linux-viewing-processes-with-ps"]
      }
    ]
  },
  {
    id: "processes-and-system-management",
    title: "Processes and System Management",
    order: 6,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 44,
        order: 1,
        slug: "linux-understanding-linux-processes",
        title: "Understanding Linux Processes",
        shortTitle: "Understanding Linux Processes",
        readingTime: 12,
        tags: ["linux", "linux tutorial", "devops", "linux processes", "systemd"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to the concept of processes, PIDs, and how Linux manages executing programs.",
        prerequisites: ["linux-command-history-and-aliases", "linux-command-substitution-and-quoting"],
        related: ["linux-viewing-processes-with-ps", "linux-command-history-and-aliases"],
        recommended: ["linux-viewing-processes-with-ps", "linux-monitoring-processes-with-top-and-htop"]
      },
      {
        id: 45,
        order: 2,
        slug: "linux-viewing-processes-with-ps",
        title: "Viewing Processes with ps",
        shortTitle: "Viewing Processes with ps",
        readingTime: 13,
        tags: ["linux", "linux tutorial", "devops", "linux processes", "systemd"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to take a snapshot of currently running processes using the ps command.",
        prerequisites: ["linux-understanding-linux-processes", "linux-command-history-and-aliases"],
        related: ["linux-monitoring-processes-with-top-and-htop", "linux-understanding-linux-processes"],
        recommended: ["linux-monitoring-processes-with-top-and-htop", "linux-foreground-and-background-processes"]
      },
      {
        id: 46,
        order: 3,
        slug: "linux-monitoring-processes-with-top-and-htop",
        title: "Monitoring Processes with top and htop",
        shortTitle: "Monitoring Processes with top...",
        readingTime: 14,
        tags: ["linux", "linux tutorial", "devops", "linux processes", "systemd"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master real-time system monitoring tools to track CPU, memory, and process activity.",
        prerequisites: ["linux-viewing-processes-with-ps", "linux-understanding-linux-processes"],
        related: ["linux-foreground-and-background-processes", "linux-viewing-processes-with-ps"],
        recommended: ["linux-foreground-and-background-processes", "linux-signals-and-the-kill-command"]
      },
      {
        id: 47,
        order: 4,
        slug: "linux-foreground-and-background-processes",
        title: "Foreground and Background Processes",
        shortTitle: "Foreground and Background Pro...",
        readingTime: 15,
        tags: ["linux", "linux tutorial", "devops", "linux processes", "systemd"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how to run commands in the background and bring them to the foreground.",
        prerequisites: ["linux-monitoring-processes-with-top-and-htop", "linux-viewing-processes-with-ps"],
        related: ["linux-signals-and-the-kill-command", "linux-monitoring-processes-with-top-and-htop"],
        recommended: ["linux-signals-and-the-kill-command", "linux-process-priority-with-nice-and-renice"]
      },
      {
        id: 48,
        order: 5,
        slug: "linux-signals-and-the-kill-command",
        title: "Signals and the kill Command",
        shortTitle: "Signals and the kill Command",
        readingTime: 8,
        tags: ["linux", "linux tutorial", "devops", "linux processes", "systemd"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to send signals (like SIGTERM and SIGKILL) to gracefully or forcefully terminate processes.",
        prerequisites: ["linux-foreground-and-background-processes", "linux-monitoring-processes-with-top-and-htop"],
        related: ["linux-process-priority-with-nice-and-renice", "linux-foreground-and-background-processes"],
        recommended: ["linux-process-priority-with-nice-and-renice", "linux-jobs-jobs-bg-and-fg"]
      },
      {
        id: 49,
        order: 6,
        slug: "linux-process-priority-with-nice-and-renice",
        title: "Process Priority with nice and renice",
        shortTitle: "Process Priority with nice an...",
        readingTime: 9,
        tags: ["linux", "linux tutorial", "devops", "linux processes", "systemd"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how to adjust the scheduling priority of processes to optimize system resource allocation.",
        prerequisites: ["linux-signals-and-the-kill-command", "linux-foreground-and-background-processes"],
        related: ["linux-jobs-jobs-bg-and-fg", "linux-signals-and-the-kill-command"],
        recommended: ["linux-jobs-jobs-bg-and-fg", "linux-linux-boot-process-and-system-startup"]
      },
      {
        id: 50,
        order: 7,
        slug: "linux-jobs-jobs-bg-and-fg",
        title: "Jobs, jobs, bg, and fg",
        shortTitle: "Jobs, jobs, bg, and fg",
        readingTime: 10,
        tags: ["linux", "linux tutorial", "devops", "linux processes", "systemd"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master shell job control to manage multiple background and foreground tasks within a single terminal.",
        prerequisites: ["linux-process-priority-with-nice-and-renice", "linux-signals-and-the-kill-command"],
        related: ["linux-linux-boot-process-and-system-startup", "linux-process-priority-with-nice-and-renice"],
        recommended: ["linux-linux-boot-process-and-system-startup", "linux-introduction-to-systemd"]
      },
      {
        id: 51,
        order: 8,
        slug: "linux-linux-boot-process-and-system-startup",
        title: "Linux Boot Process and System Startup",
        shortTitle: "Linux Boot Process and System...",
        readingTime: 11,
        tags: ["linux", "linux tutorial", "devops", "linux processes", "systemd"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the stages of the Linux boot process, from BIOS/UEFI to the initialization of user space.",
        prerequisites: ["linux-jobs-jobs-bg-and-fg", "linux-process-priority-with-nice-and-renice"],
        related: ["linux-introduction-to-systemd", "linux-jobs-jobs-bg-and-fg"],
        recommended: ["linux-introduction-to-systemd", "linux-managing-services-with-systemctl"]
      },
      {
        id: 52,
        order: 9,
        slug: "linux-introduction-to-systemd",
        title: "Introduction to systemd",
        shortTitle: "Introduction to systemd",
        readingTime: 12,
        tags: ["linux", "linux tutorial", "devops", "linux processes", "systemd"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to systemd, the modern init system and service manager used by most Linux distributions.",
        prerequisites: ["linux-linux-boot-process-and-system-startup", "linux-jobs-jobs-bg-and-fg"],
        related: ["linux-managing-services-with-systemctl", "linux-linux-boot-process-and-system-startup"],
        recommended: ["linux-managing-services-with-systemctl", "linux-understanding-linux-packages"]
      },
      {
        id: 53,
        order: 10,
        slug: "linux-managing-services-with-systemctl",
        title: "Managing Services with systemctl",
        shortTitle: "Managing Services with system...",
        readingTime: 13,
        tags: ["linux", "linux tutorial", "devops", "linux processes", "systemd"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to start, stop, enable, and check the status of system services using systemctl.",
        prerequisites: ["linux-introduction-to-systemd", "linux-linux-boot-process-and-system-startup"],
        related: ["linux-introduction-to-systemd", "linux-understanding-linux-packages"],
        recommended: ["linux-understanding-linux-packages", "linux-package-managers-and-repositories"]
      }
    ]
  },
  {
    id: "software-and-package-management",
    title: "Software and Package Management",
    order: 7,
    difficulty: "Advanced",
    lessons: [
      {
        id: 54,
        order: 1,
        slug: "linux-understanding-linux-packages",
        title: "Understanding Linux Packages",
        shortTitle: "Understanding Linux Packages",
        readingTime: 14,
        tags: ["linux", "linux tutorial", "devops", "package management", "linux software installation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand what software packages are and how they bundle applications with their dependencies.",
        prerequisites: ["linux-managing-services-with-systemctl", "linux-introduction-to-systemd"],
        related: ["linux-package-managers-and-repositories", "linux-managing-services-with-systemctl"],
        recommended: ["linux-package-managers-and-repositories", "linux-apt-package-management"]
      },
      {
        id: 55,
        order: 2,
        slug: "linux-package-managers-and-repositories",
        title: "Package Managers and Repositories",
        shortTitle: "Package Managers and Reposito...",
        readingTime: 15,
        tags: ["linux", "linux tutorial", "devops", "package management", "linux software installation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the concept of centralized software repositories and the package managers that interact with them.",
        prerequisites: ["linux-understanding-linux-packages", "linux-managing-services-with-systemctl"],
        related: ["linux-apt-package-management", "linux-understanding-linux-packages"],
        recommended: ["linux-apt-package-management", "linux-dnfyum-package-management"]
      },
      {
        id: 56,
        order: 3,
        slug: "linux-apt-package-management",
        title: "APT Package Management",
        shortTitle: "APT Package Management",
        readingTime: 8,
        tags: ["linux", "linux tutorial", "devops", "package management", "linux software installation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the Advanced Package Tool (APT) used in Debian, Ubuntu, and related distributions.",
        prerequisites: ["linux-package-managers-and-repositories", "linux-understanding-linux-packages"],
        related: ["linux-dnfyum-package-management", "linux-package-managers-and-repositories"],
        recommended: ["linux-dnfyum-package-management", "linux-installing-updating-and-removing-packages"]
      },
      {
        id: 57,
        order: 4,
        slug: "linux-dnfyum-package-management",
        title: "DNF/YUM Package Management",
        shortTitle: "DNF/YUM Package Management",
        readingTime: 9,
        tags: ["linux", "linux tutorial", "devops", "package management", "linux software installation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to manage software packages on Red Hat, Fedora, and CentOS using DNF or YUM.",
        prerequisites: ["linux-apt-package-management", "linux-package-managers-and-repositories"],
        related: ["linux-installing-updating-and-removing-packages", "linux-apt-package-management"],
        recommended: ["linux-installing-updating-and-removing-packages", "linux-searching-packages-and-managing-dependencies"]
      },
      {
        id: 58,
        order: 5,
        slug: "linux-installing-updating-and-removing-packages",
        title: "Installing, Updating, and Removing Packages",
        shortTitle: "Installing, Updating, and Rem...",
        readingTime: 10,
        tags: ["linux", "linux tutorial", "devops", "package management", "linux software installation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover the essential commands for installing new software, updating existing packages, and removing them.",
        prerequisites: ["linux-dnfyum-package-management", "linux-apt-package-management"],
        related: ["linux-searching-packages-and-managing-dependencies", "linux-dnfyum-package-management"],
        recommended: ["linux-searching-packages-and-managing-dependencies", "linux-working-with-deb-and-rpm-packages"]
      },
      {
        id: 59,
        order: 6,
        slug: "linux-searching-packages-and-managing-dependencies",
        title: "Searching Packages and Managing Dependencies",
        shortTitle: "Searching Packages and Managing...",
        readingTime: 11,
        tags: ["linux", "linux tutorial", "devops", "package management", "linux software installation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to search for available software and understand how package managers resolve dependencies.",
        prerequisites: ["linux-installing-updating-and-removing-packages", "linux-dnfyum-package-management"],
        related: ["linux-working-with-deb-and-rpm-packages", "linux-installing-updating-and-removing-packages"],
        recommended: ["linux-working-with-deb-and-rpm-packages", "linux-software-installation-and-repository-configuration"]
      },
      {
        id: 60,
        order: 7,
        slug: "linux-working-with-deb-and-rpm-packages",
        title: "Working with .deb and .rpm Packages",
        shortTitle: "Working with .deb and .rpm Pa...",
        readingTime: 12,
        tags: ["linux", "linux tutorial", "devops", "package management", "linux software installation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how to manually install, query, and extract low-level .deb and .rpm package files.",
        prerequisites: ["linux-searching-packages-and-managing-dependencies", "linux-installing-updating-and-removing-packages"],
        related: ["linux-software-installation-and-repository-configuration", "linux-searching-packages-and-managing-dependencies"],
        recommended: ["linux-software-installation-and-repository-configuration", "linux-linux-networking-fundamentals"]
      },
      {
        id: 61,
        order: 8,
        slug: "linux-software-installation-and-repository-configuration",
        title: "Software Installation and Repository Configuration",
        shortTitle: "Software Installation and Rep...",
        readingTime: 13,
        tags: ["linux", "linux tutorial", "devops", "package management", "linux software installation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to add third-party repositories (PPAs) and configure package sources safely.",
        prerequisites: ["linux-working-with-deb-and-rpm-packages", "linux-searching-packages-and-managing-dependencies"],
        related: ["linux-working-with-deb-and-rpm-packages", "linux-linux-networking-fundamentals"],
        recommended: ["linux-linux-networking-fundamentals", "linux-network-interfaces-and-ip-addresses"]
      }
    ]
  },
  {
    id: "linux-networking-and-remote-access",
    title: "Linux Networking and Remote Access",
    order: 8,
    difficulty: "Advanced",
    lessons: [
      {
        id: 62,
        order: 1,
        slug: "linux-linux-networking-fundamentals",
        title: "Linux Networking Fundamentals",
        shortTitle: "Linux Networking Fundamentals",
        readingTime: 14,
        tags: ["linux", "linux tutorial", "devops", "linux networking", "linux remote access"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to the OSI model, TCP/IP, and how Linux handles network communication.",
        prerequisites: ["linux-software-installation-and-repository-configuration", "linux-working-with-deb-and-rpm-packages"],
        related: ["linux-network-interfaces-and-ip-addresses", "linux-software-installation-and-repository-configuration"],
        recommended: ["linux-network-interfaces-and-ip-addresses", "linux-using-the-ip-command"]
      },
      {
        id: 63,
        order: 2,
        slug: "linux-network-interfaces-and-ip-addresses",
        title: "Network Interfaces and IP Addresses",
        shortTitle: "Network Interfaces and IP Add...",
        readingTime: 15,
        tags: ["linux", "linux tutorial", "devops", "linux networking", "linux remote access"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to identify, configure, and manage network interfaces and IP addresses in Linux.",
        prerequisites: ["linux-linux-networking-fundamentals", "linux-software-installation-and-repository-configuration"],
        related: ["linux-using-the-ip-command", "linux-linux-networking-fundamentals"],
        recommended: ["linux-using-the-ip-command", "linux-testing-connectivity-with-ping"]
      },
      {
        id: 64,
        order: 3,
        slug: "linux-using-the-ip-command",
        title: "Using the ip Command",
        shortTitle: "Using the ip Command",
        readingTime: 8,
        tags: ["linux", "linux tutorial", "devops", "linux networking", "linux remote access"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the modern ip command (iproute2) for managing network interfaces, routes, and addresses.",
        prerequisites: ["linux-network-interfaces-and-ip-addresses", "linux-linux-networking-fundamentals"],
        related: ["linux-testing-connectivity-with-ping", "linux-network-interfaces-and-ip-addresses"],
        recommended: ["linux-testing-connectivity-with-ping", "linux-dns-and-hostname-resolution"]
      },
      {
        id: 65,
        order: 4,
        slug: "linux-testing-connectivity-with-ping",
        title: "Testing Connectivity with ping",
        shortTitle: "Testing Connectivity with ping",
        readingTime: 9,
        tags: ["linux", "linux tutorial", "devops", "linux networking", "linux remote access"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to use ping and other basic tools to test network connectivity and latency.",
        prerequisites: ["linux-using-the-ip-command", "linux-network-interfaces-and-ip-addresses"],
        related: ["linux-dns-and-hostname-resolution", "linux-using-the-ip-command"],
        recommended: ["linux-dns-and-hostname-resolution", "linux-inspecting-network-connections"]
      },
      {
        id: 66,
        order: 5,
        slug: "linux-dns-and-hostname-resolution",
        title: "DNS and Hostname Resolution",
        shortTitle: "DNS and Hostname Resolution",
        readingTime: 10,
        tags: ["linux", "linux tutorial", "devops", "linux networking", "linux remote access"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how Linux resolves hostnames to IP addresses using DNS and the /etc/hosts file.",
        prerequisites: ["linux-testing-connectivity-with-ping", "linux-using-the-ip-command"],
        related: ["linux-inspecting-network-connections", "linux-testing-connectivity-with-ping"],
        recommended: ["linux-inspecting-network-connections", "linux-ports-and-sockets"]
      },
      {
        id: 67,
        order: 6,
        slug: "linux-inspecting-network-connections",
        title: "Inspecting Network Connections",
        shortTitle: "Inspecting Network Connections",
        readingTime: 11,
        tags: ["linux", "linux tutorial", "devops", "linux networking", "linux remote access"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how to use netstat and ss to view active network connections and listening ports.",
        prerequisites: ["linux-dns-and-hostname-resolution", "linux-testing-connectivity-with-ping"],
        related: ["linux-ports-and-sockets", "linux-dns-and-hostname-resolution"],
        recommended: ["linux-ports-and-sockets", "linux-ssh-connecting-to-remote-linux-servers"]
      },
      {
        id: 68,
        order: 7,
        slug: "linux-ports-and-sockets",
        title: "Ports and Sockets",
        shortTitle: "Ports and Sockets",
        readingTime: 12,
        tags: ["linux", "linux tutorial", "devops", "linux networking", "linux remote access"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the concept of network ports and sockets, and how applications bind to them.",
        prerequisites: ["linux-inspecting-network-connections", "linux-dns-and-hostname-resolution"],
        related: ["linux-ssh-connecting-to-remote-linux-servers", "linux-inspecting-network-connections"],
        recommended: ["linux-ssh-connecting-to-remote-linux-servers", "linux-secure-file-transfer-with-scp-and-rsync"]
      },
      {
        id: 69,
        order: 8,
        slug: "linux-ssh-connecting-to-remote-linux-servers",
        title: "SSH: Connecting to Remote Linux Servers",
        shortTitle: "SSH Connecting to Remote Linu...",
        readingTime: 13,
        tags: ["linux", "linux tutorial", "devops", "linux networking", "linux remote access"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master Secure Shell (SSH) for secure, encrypted remote access to Linux servers.",
        prerequisites: ["linux-ports-and-sockets", "linux-inspecting-network-connections"],
        related: ["linux-secure-file-transfer-with-scp-and-rsync", "linux-ports-and-sockets"],
        recommended: ["linux-secure-file-transfer-with-scp-and-rsync", "linux-basic-network-troubleshooting"]
      },
      {
        id: 70,
        order: 9,
        slug: "linux-secure-file-transfer-with-scp-and-rsync",
        title: "Secure File Transfer with scp and rsync",
        shortTitle: "Secure File Transfer with scp...",
        readingTime: 14,
        tags: ["linux", "linux tutorial", "devops", "linux networking", "linux remote access"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to securely copy files between local and remote systems using scp and rsync.",
        prerequisites: ["linux-ssh-connecting-to-remote-linux-servers", "linux-ports-and-sockets"],
        related: ["linux-basic-network-troubleshooting", "linux-ssh-connecting-to-remote-linux-servers"],
        recommended: ["linux-basic-network-troubleshooting", "linux-introduction-to-bash-scripting"]
      },
      {
        id: 71,
        order: 10,
        slug: "linux-basic-network-troubleshooting",
        title: "Basic Network Troubleshooting",
        shortTitle: "Basic Network Troubleshooting",
        readingTime: 15,
        tags: ["linux", "linux tutorial", "devops", "linux networking", "linux remote access"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Develop a systematic approach to diagnosing and resolving common Linux network connectivity issues.",
        prerequisites: ["linux-secure-file-transfer-with-scp-and-rsync", "linux-ssh-connecting-to-remote-linux-servers"],
        related: ["linux-secure-file-transfer-with-scp-and-rsync", "linux-introduction-to-bash-scripting"],
        recommended: ["linux-introduction-to-bash-scripting", "linux-creating-and-executing-bash-scripts"]
      }
    ]
  },
  {
    id: "bash-scripting-and-automation",
    title: "Bash Scripting and Automation",
    order: 9,
    difficulty: "Advanced",
    lessons: [
      {
        id: 72,
        order: 1,
        slug: "linux-introduction-to-bash-scripting",
        title: "Introduction to Bash Scripting",
        shortTitle: "Introduction to Bash Scripting",
        readingTime: 8,
        tags: ["linux", "linux tutorial", "devops", "bash scripting", "shell scripting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to Bash scripting as a way to automate repetitive command-line tasks.",
        prerequisites: ["linux-basic-network-troubleshooting", "linux-secure-file-transfer-with-scp-and-rsync"],
        related: ["linux-creating-and-executing-bash-scripts", "linux-basic-network-troubleshooting"],
        recommended: ["linux-creating-and-executing-bash-scripts", "linux-shebangs-and-script-permissions"]
      },
      {
        id: 73,
        order: 2,
        slug: "linux-creating-and-executing-bash-scripts",
        title: "Creating and Executing Bash Scripts",
        shortTitle: "Creating and Executing Bash S...",
        readingTime: 9,
        tags: ["linux", "linux tutorial", "devops", "bash scripting", "shell scripting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn the basics of writing a Bash script and making it executable.",
        prerequisites: ["linux-introduction-to-bash-scripting", "linux-basic-network-troubleshooting"],
        related: ["linux-shebangs-and-script-permissions", "linux-introduction-to-bash-scripting"],
        recommended: ["linux-shebangs-and-script-permissions", "linux-variables-and-user-input"]
      },
      {
        id: 74,
        order: 3,
        slug: "linux-shebangs-and-script-permissions",
        title: "Shebangs and Script Permissions",
        shortTitle: "Shebangs and Script Permissions",
        readingTime: 10,
        tags: ["linux", "linux tutorial", "devops", "bash scripting", "shell scripting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the purpose of the shebang (#!) line and how to set correct execution permissions.",
        prerequisites: ["linux-creating-and-executing-bash-scripts", "linux-introduction-to-bash-scripting"],
        related: ["linux-variables-and-user-input", "linux-creating-and-executing-bash-scripts"],
        recommended: ["linux-variables-and-user-input", "linux-conditional-statements"]
      },
      {
        id: 75,
        order: 4,
        slug: "linux-variables-and-user-input",
        title: "Variables and User Input",
        shortTitle: "Variables and User Input",
        readingTime: 11,
        tags: ["linux", "linux tutorial", "devops", "bash scripting", "shell scripting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to define variables and capture user input using the read command in Bash.",
        prerequisites: ["linux-shebangs-and-script-permissions", "linux-creating-and-executing-bash-scripts"],
        related: ["linux-conditional-statements", "linux-shebangs-and-script-permissions"],
        recommended: ["linux-conditional-statements", "linux-loops-in-bash"]
      },
      {
        id: 76,
        order: 5,
        slug: "linux-conditional-statements",
        title: "Conditional Statements",
        shortTitle: "Conditional Statements",
        readingTime: 12,
        tags: ["linux", "linux tutorial", "devops", "bash scripting", "shell scripting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master if, elif, and else statements to add logical decision-making to your scripts.",
        prerequisites: ["linux-variables-and-user-input", "linux-shebangs-and-script-permissions"],
        related: ["linux-loops-in-bash", "linux-variables-and-user-input"],
        recommended: ["linux-loops-in-bash", "linux-functions-in-bash"]
      },
      {
        id: 77,
        order: 6,
        slug: "linux-loops-in-bash",
        title: "Loops in Bash",
        shortTitle: "Loops in Bash",
        readingTime: 13,
        tags: ["linux", "linux tutorial", "devops", "bash scripting", "shell scripting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to use for, while, and until loops to iterate over data and repeat tasks.",
        prerequisites: ["linux-conditional-statements", "linux-variables-and-user-input"],
        related: ["linux-functions-in-bash", "linux-conditional-statements"],
        recommended: ["linux-functions-in-bash", "linux-arrays-and-special-variables"]
      },
      {
        id: 78,
        order: 7,
        slug: "linux-functions-in-bash",
        title: "Functions in Bash",
        shortTitle: "Functions in Bash",
        readingTime: 14,
        tags: ["linux", "linux tutorial", "devops", "bash scripting", "shell scripting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how to organize your code into reusable functions with parameters and return values.",
        prerequisites: ["linux-loops-in-bash", "linux-conditional-statements"],
        related: ["linux-arrays-and-special-variables", "linux-loops-in-bash"],
        recommended: ["linux-arrays-and-special-variables", "linux-exit-statuses-and-error-handling"]
      },
      {
        id: 79,
        order: 8,
        slug: "linux-arrays-and-special-variables",
        title: "Arrays and Special Variables",
        shortTitle: "Arrays and Special Variables",
        readingTime: 15,
        tags: ["linux", "linux tutorial", "devops", "bash scripting", "shell scripting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how to work with arrays and utilize special Bash variables like $@, $#, and $?",
        prerequisites: ["linux-functions-in-bash", "linux-loops-in-bash"],
        related: ["linux-exit-statuses-and-error-handling", "linux-functions-in-bash"],
        recommended: ["linux-exit-statuses-and-error-handling", "linux-automating-tasks-with-cron-jobs"]
      },
      {
        id: 80,
        order: 9,
        slug: "linux-exit-statuses-and-error-handling",
        title: "Exit Statuses and Error Handling",
        shortTitle: "Exit Statuses and Error Handl...",
        readingTime: 8,
        tags: ["linux", "linux tutorial", "devops", "bash scripting", "shell scripting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to check command success using exit codes and implement robust error handling.",
        prerequisites: ["linux-arrays-and-special-variables", "linux-functions-in-bash"],
        related: ["linux-automating-tasks-with-cron-jobs", "linux-arrays-and-special-variables"],
        recommended: ["linux-automating-tasks-with-cron-jobs", "linux-managing-users-and-groups"]
      },
      {
        id: 81,
        order: 10,
        slug: "linux-automating-tasks-with-cron-jobs",
        title: "Automating Tasks with Cron Jobs",
        shortTitle: "Automating Tasks with Cron Jobs",
        readingTime: 9,
        tags: ["linux", "linux tutorial", "devops", "bash scripting", "shell scripting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the cron daemon and crontab syntax to schedule scripts and commands to run automatically.",
        prerequisites: ["linux-exit-statuses-and-error-handling", "linux-arrays-and-special-variables"],
        related: ["linux-exit-statuses-and-error-handling", "linux-managing-users-and-groups"],
        recommended: ["linux-managing-users-and-groups", "linux-managing-disk-space-and-file-systems"]
      }
    ]
  },
  {
    id: "linux-administration-security-and-troubleshooting",
    title: "Linux Administration, Security, and Troubleshooting",
    order: 10,
    difficulty: "Advanced",
    lessons: [
      {
        id: 82,
        order: 1,
        slug: "linux-managing-users-and-groups",
        title: "Managing Users and Groups",
        shortTitle: "Managing Users and Groups",
        readingTime: 10,
        tags: ["linux", "linux tutorial", "devops", "linux users", "linux groups"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn advanced user and group management commands like useradd, usermod, and groupdel.",
        prerequisites: ["linux-automating-tasks-with-cron-jobs", "linux-exit-statuses-and-error-handling"],
        related: ["linux-managing-disk-space-and-file-systems", "linux-automating-tasks-with-cron-jobs"],
        recommended: ["linux-managing-disk-space-and-file-systems", "linux-mounting-and-unmounting-file-systems"]
      },
      {
        id: 83,
        order: 2,
        slug: "linux-managing-disk-space-and-file-systems",
        title: "Managing Disk Space and File Systems",
        shortTitle: "Managing Disk Space and File ...",
        readingTime: 11,
        tags: ["linux", "linux tutorial", "devops", "linux storage", "linux administration"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how to monitor disk usage with df and du, and manage partitions with fdisk or parted.",
        prerequisites: ["linux-managing-users-and-groups", "linux-automating-tasks-with-cron-jobs"],
        related: ["linux-mounting-and-unmounting-file-systems", "linux-managing-users-and-groups"],
        recommended: ["linux-mounting-and-unmounting-file-systems", "linux-linux-logs-and-the-journalctl-command"]
      },
      {
        id: 84,
        order: 3,
        slug: "linux-mounting-and-unmounting-file-systems",
        title: "Mounting and Unmounting File Systems",
        shortTitle: "Mounting and Unmounting File ...",
        readingTime: 12,
        tags: ["linux", "linux tutorial", "devops", "linux storage", "linux administration"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to attach and detach storage devices using the mount and umount commands, and configure /etc/fstab.",
        prerequisites: ["linux-managing-disk-space-and-file-systems", "linux-managing-users-and-groups"],
        related: ["linux-linux-logs-and-the-journalctl-command", "linux-managing-disk-space-and-file-systems"],
        recommended: ["linux-linux-logs-and-the-journalctl-command", "linux-monitoring-cpu-memory-and-disk-usage"]
      },
      {
        id: 85,
        order: 4,
        slug: "linux-linux-logs-and-the-journalctl-command",
        title: "Linux Logs and the journalctl Command",
        shortTitle: "Linux Logs and the journalctl...",
        readingTime: 13,
        tags: ["linux", "linux tutorial", "devops", "linux administration", "linux troubleshooting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the systemd journal and learn how to query, filter, and analyze system logs.",
        prerequisites: ["linux-mounting-and-unmounting-file-systems", "linux-managing-disk-space-and-file-systems"],
        related: ["linux-monitoring-cpu-memory-and-disk-usage", "linux-mounting-and-unmounting-file-systems"],
        recommended: ["linux-monitoring-cpu-memory-and-disk-usage", "linux-managing-services-on-remote-servers"]
      },
      {
        id: 86,
        order: 5,
        slug: "linux-monitoring-cpu-memory-and-disk-usage",
        title: "Monitoring CPU, Memory, and Disk Usage",
        shortTitle: "Monitoring CPU, Memory, and D...",
        readingTime: 14,
        tags: ["linux", "linux tutorial", "devops", "linux administration", "linux troubleshooting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to use tools like vmstat, iostat, and free to monitor system resource utilization.",
        prerequisites: ["linux-linux-logs-and-the-journalctl-command", "linux-mounting-and-unmounting-file-systems"],
        related: ["linux-managing-services-on-remote-servers", "linux-linux-logs-and-the-journalctl-command"],
        recommended: ["linux-managing-services-on-remote-servers", "linux-linux-security-fundamentals"]
      },
      {
        id: 87,
        order: 6,
        slug: "linux-managing-services-on-remote-servers",
        title: "Managing Services on Remote Servers",
        shortTitle: "Managing Services on Remote S...",
        readingTime: 15,
        tags: ["linux", "linux tutorial", "devops", "linux administration", "linux troubleshooting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand best practices for safely starting, stopping, and restarting services on production servers.",
        prerequisites: ["linux-monitoring-cpu-memory-and-disk-usage", "linux-linux-logs-and-the-journalctl-command"],
        related: ["linux-linux-security-fundamentals", "linux-monitoring-cpu-memory-and-disk-usage"],
        recommended: ["linux-linux-security-fundamentals", "linux-firewall-basics-with-ufw-and-firewalld"]
      },
      {
        id: 88,
        order: 7,
        slug: "linux-linux-security-fundamentals",
        title: "Linux Security Fundamentals",
        shortTitle: "Linux Security Fundamentals",
        readingTime: 8,
        tags: ["linux", "linux tutorial", "devops", "linux security", "linux administration"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore core Linux security concepts, including principle of least privilege and secure configurations.",
        prerequisites: ["linux-managing-services-on-remote-servers", "linux-monitoring-cpu-memory-and-disk-usage"],
        related: ["linux-firewall-basics-with-ufw-and-firewalld", "linux-managing-services-on-remote-servers"],
        recommended: ["linux-firewall-basics-with-ufw-and-firewalld", "linux-diagnosing-common-linux-problems"]
      },
      {
        id: 89,
        order: 8,
        slug: "linux-firewall-basics-with-ufw-and-firewalld",
        title: "Firewall Basics with ufw and firewalld",
        shortTitle: "Firewall Basics with ufw and ...",
        readingTime: 9,
        tags: ["linux", "linux tutorial", "devops", "linux security", "linux administration"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to configure and manage host-based firewalls using ufw (Ubuntu) or firewalld (RHEL).",
        prerequisites: ["linux-linux-security-fundamentals", "linux-managing-services-on-remote-servers"],
        related: ["linux-diagnosing-common-linux-problems", "linux-linux-security-fundamentals"],
        recommended: ["linux-diagnosing-common-linux-problems", "linux-linux-server-troubleshooting-workflow"]
      },
      {
        id: 90,
        order: 9,
        slug: "linux-diagnosing-common-linux-problems",
        title: "Diagnosing Common Linux Problems",
        shortTitle: "Diagnosing Common Linux Probl...",
        readingTime: 10,
        tags: ["linux", "linux tutorial", "devops", "linux administration", "linux troubleshooting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Develop troubleshooting skills to identify and resolve common Linux system and application issues.",
        prerequisites: ["linux-firewall-basics-with-ufw-and-firewalld", "linux-linux-security-fundamentals"],
        related: ["linux-linux-server-troubleshooting-workflow", "linux-firewall-basics-with-ufw-and-firewalld"],
        recommended: ["linux-linux-server-troubleshooting-workflow", "linux-managing-users-and-groups"]
      },
      {
        id: 91,
        order: 10,
        slug: "linux-linux-server-troubleshooting-workflow",
        title: "Linux Server Troubleshooting Workflow",
        shortTitle: "Linux Server Troubleshooting ...",
        readingTime: 11,
        tags: ["linux", "linux tutorial", "devops", "linux administration", "linux troubleshooting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master a systematic, step-by-step workflow for diagnosing and resolving complex Linux server problems.",
        prerequisites: ["linux-diagnosing-common-linux-problems", "linux-firewall-basics-with-ufw-and-firewalld"],
        related: ["linux-diagnosing-common-linux-problems", "linux-managing-users-and-groups"],
        recommended: ["linux-managing-users-and-groups", "linux-managing-disk-space-and-file-systems"]
      }
    ]
  }
];

export const resources = [
  {
    id: "linux-tools-and-productivity",
    title: "Linux Tools & Productivity",
    order: 1,
    items: [
      {
        id: 92,
        order: 1,
        slug: "linux-vim-essentials",
        title: "Vim Essentials",
        shortTitle: "Vim Essentials",
        type: "article",
        readingTime: 10,
        tags: ["linux", "vim", "editor", "productivity", "cli"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn essential Vim commands and workflows for efficient text editing directly from the terminal."
      },
      {
        id: 93,
        order: 2,
        slug: "linux-nano-editor",
        title: "Nano Editor",
        shortTitle: "Nano Editor",
        type: "article",
        readingTime: 8,
        tags: ["linux", "nano", "editor", "beginner", "cli", "text editing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get started with the Nano editor for simple and intuitive file editing in Linux environments."
      },
      {
        id: 94,
        order: 3,
        slug: "linux-tmux-terminal-multiplexing",
        title: "tmux for Terminal Multiplexing",
        shortTitle: "tmux",
        type: "article",
        readingTime: 10,
        tags: ["linux", "tmux", "terminal", "multiplexing", "productivity", "cli"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master tmux to manage multiple terminal sessions, windows, and panes from a single screen."
      },
      {
        id: 95,
        order: 4,
        slug: "linux-useful-command-line-utilities",
        title: "Useful Command-Line Utilities",
        shortTitle: "CLI Utilities",
        type: "article",
        readingTime: 10,
        tags: ["linux", "cli", "utilities", "productivity", "tools", "command line"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover powerful command-line utilities that boost productivity and streamline daily Linux tasks."
      },
    ]
  },

  {
    id: "advanced-shell-and-text-processing",
    title: "Advanced Shell & Text Processing",
    order: 2,
    items: [
      {
        id: 96,
        order: 1,
        slug: "linux-regular-expressions",
        title: "Regular Expressions in Linux",
        shortTitle: "Regex",
        type: "article",
        readingTime: 12,
        tags: ["linux", "regex", "text processing", "bash", "advanced", "pattern matching"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand regex syntax and patterns for advanced text matching and manipulation in Linux."
      },
      {
        id: 97,
        order: 2,
        slug: "linux-advanced-grep-sed-awk",
        title: "Advanced grep, sed, and awk",
        shortTitle: "grep, sed, awk",
        type: "article",
        readingTime: 14,
        tags: ["linux", "grep", "sed", "awk", "text processing", "advanced"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Dive deep into grep, sed, and awk for sophisticated text filtering, substitution, and reporting."
      },
      {
        id: 98,
        order: 3,
        slug: "linux-bash-traps-signal-handling",
        title: "Bash Traps and Signal Handling",
        shortTitle: "Signal Handling",
        type: "article",
        readingTime: 10,
        tags: ["linux", "bash", "signals", "traps", "scripting", "advanced"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to handle Unix signals and use bash traps for robust script execution and cleanup."
      },
      {
        id: 99,
        order: 4,
        slug: "linux-advanced-bash-parameter-expansion",
        title: "Advanced Bash Parameter Expansion",
        shortTitle: "Parameter Expansion",
        type: "article",
        readingTime: 10,
        tags: ["linux", "bash", "scripting", "advanced", "variables", "shell"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore advanced parameter expansion techniques for efficient and flexible bash scripting."
      },
    ]
  },

  {
    id: "linux-filesystems-and-storage",
    title: "Linux Filesystems & Storage",
    order: 3,
    items: [
      {
        id: 100,
        order: 1,
        slug: "linux-inodes-and-file-metadata",
        title: "Inodes and File Metadata",
        shortTitle: "Inodes",
        type: "article",
        readingTime: 10,
        tags: ["linux", "filesystem", "inodes", "metadata", "storage", "internals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand inodes, file metadata, and the Linux filesystem structure at a fundamental level."
      },
      {
        id: 101,
        order: 2,
        slug: "linux-disk-partitioning-filesystem-types",
        title: "Disk Partitioning and Filesystem Types",
        shortTitle: "Partitioning",
        type: "article",
        readingTime: 12,
        tags: ["linux", "partitioning", "filesystem", "fdisk", "storage", "ext4", "xfs"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn disk partitioning strategies and filesystem types like ext4, XFS, and Btrfs."
      },
      {
        id: 102,
        order: 3,
        slug: "linux-df-du-disk-usage",
        title: "df, du, and Disk Usage Analysis",
        shortTitle: "Disk Usage",
        type: "article",
        readingTime: 8,
        tags: ["linux", "df", "du", "storage", "analysis", "filesystem", "capacity"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Analyze disk usage with df and du to identify storage consumption and optimize capacity."
      },
      {
        id: 103,
        order: 4,
        slug: "linux-lvm-logical-volumes",
        title: "LVM and Logical Volumes",
        shortTitle: "LVM",
        type: "article",
        readingTime: 12,
        tags: ["linux", "lvm", "logical volumes", "storage", "advanced", "volume management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Manage flexible storage with Logical Volume Manager for resizing, snapshots, and volume groups."
      },
      {
        id: 104,
        order: 5,
        slug: "linux-file-compression-archiving",
        title: "File Compression and Archiving with tar, gzip, and zip",
        shortTitle: "Compression",
        type: "article",
        readingTime: 10,
        tags: ["linux", "tar", "gzip", "zip", "compression", "archiving", "backup"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Compress and archive files efficiently using tar, gzip, bzip2, and zip utilities."
      },
    ]
  },

  {
    id: "linux-performance-and-diagnostics",
    title: "Linux Performance & Diagnostics",
    order: 4,
    items: [
      {
        id: 105,
        order: 1,
        slug: "linux-performance-monitoring",
        title: "Linux Performance Monitoring",
        shortTitle: "Performance Monitoring",
        type: "article",
        readingTime: 12,
        tags: ["linux", "performance", "monitoring", "diagnostics", "system", "top", "htop"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Monitor system performance using top, htop, vmstat, and other essential Linux diagnostic tools."
      },
      {
        id: 106,
        order: 2,
        slug: "linux-memory-swap-management",
        title: "Memory and Swap Management",
        shortTitle: "Memory & Swap",
        type: "article",
        readingTime: 10,
        tags: ["linux", "memory", "swap", "ram", "performance", "vm", "tuning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand RAM usage, swap space, and memory tuning to prevent system slowdowns."
      },
      {
        id: 107,
        order: 3,
        slug: "linux-cpu-load-average-analysis",
        title: "CPU and Load Average Analysis",
        shortTitle: "CPU & Load",
        type: "article",
        readingTime: 10,
        tags: ["linux", "cpu", "load average", "performance", "monitoring", "uptime"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Interpret CPU metrics and load averages to diagnose performance bottlenecks."
      },
      {
        id: 108,
        order: 4,
        slug: "linux-advanced-network-diagnostics",
        title: "Advanced Network Diagnostics",
        shortTitle: "Network Diagnostics",
        type: "article",
        readingTime: 12,
        tags: ["linux", "networking", "diagnostics", "netstat", "ss", "tcpdump", "troubleshooting"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Troubleshoot network issues with advanced tools like ss, netstat, tcpdump, and nmap."
      },
      {
        id: 109,
        order: 5,
        slug: "linux-system-logging-log-analysis",
        title: "System Logging and Log Analysis",
        shortTitle: "Logging",
        type: "article",
        readingTime: 10,
        tags: ["linux", "logging", "syslog", "journalctl", "log analysis", "auditing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Navigate system logs with journalctl and rsyslog for effective debugging and audit trails."
      },
    ]
  },

  {
    id: "linux-for-devops-and-cloud",
    title: "Linux for DevOps & Cloud",
    order: 5,
    items: [
      {
        id: 110,
        order: 1,
        slug: "linux-for-docker-and-containers",
        title: "Linux for Docker and Containers",
        shortTitle: "Docker & Containers",
        type: "article",
        readingTime: 10,
        tags: ["linux", "docker", "containers", "devops", "namespaces", "cgroups"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand Linux kernel features like namespaces and cgroups that power containerization."
      },
      {
        id: 111,
        order: 2,
        slug: "linux-for-kubernetes",
        title: "Linux for Kubernetes",
        shortTitle: "Kubernetes",
        type: "article",
        readingTime: 12,
        tags: ["linux", "kubernetes", "k8s", "devops", "cloud", "orchestration"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the Linux foundations essential for running and managing Kubernetes clusters."
      },
      {
        id: 112,
        order: 3,
        slug: "linux-in-cloud-and-virtual-machines",
        title: "Linux in Cloud and Virtual Machines",
        shortTitle: "Cloud & VMs",
        type: "article",
        readingTime: 10,
        tags: ["linux", "cloud", "vm", "virtualization", "aws", "azure", "gcp"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Deploy and manage Linux instances across cloud providers and virtualized environments."
      },
      {
        id: 113,
        order: 4,
        slug: "linux-server-hardening",
        title: "Linux Server Hardening",
        shortTitle: "Server Hardening",
        type: "article",
        readingTime: 12,
        tags: ["linux", "security", "hardening", "server", "devops", "best practices", "ssh"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Apply security best practices to harden Linux servers against unauthorized access and threats."
      },
      {
        id: 114,
        order: 5,
        slug: "linux-automation-and-infrastructure-management",
        title: "Linux Automation and Infrastructure Management",
        shortTitle: "Automation",
        type: "article",
        readingTime: 12,
        tags: ["linux", "automation", "ansible", "puppet", "infrastructure", "devops", "iac"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Automate Linux administration with Ansible, Puppet, and infrastructure-as-code tools."
      },
    ]
  },
];