// ============================================================
// src/registry/lessons/nodejsLessons.js
// STUB — same shape as htmlLessons.js, empty until you fill it in.
// lessonRegistry.js can safely import this right now without
// breaking anything; it'll just show 0 lessons for Node.js until
// you add sections here.
// ============================================================

import { STATUS } from "../../config/constants";

export const tutorialInfo = {
  id: "microservices",
  title: "Microservices Tutorial",
  shortTitle: "Microservices",
  category: "Backend",
  description: "Master microservices architecture from fundamentals to advanced concepts with comprehensive tutorials covering service decomposition, API gateways, service discovery, inter-service communication, databases, messaging, Docker, Kubernetes, authentication, resilience, observability, testing, deployment, scalability, and real-world distributed systems.",
  icon: "microservices",
  difficulty: "Advanced", // course-level badge, separate from per-section defaults
  estimatedHours: 42,
  totalLessons: 82,
  version: "Latest",
  language: "English",
  path: "/microservices",
  authorId: "faiz",
  updatedAt: "2026-07-09",
  tags: ["microservices", "microservices architecture", "distributed systems", "backend", "system design", "service architecture", "api gateway", "service discovery", "inter service communication", "event driven architecture", "message queues", "docker", "kubernetes", "containers", "rest api", "grpc", "authentication", "authorization", "database per service", "caching", "resilience", "fault tolerance", "observability", "monitoring", "logging", "tracing", "testing", "deployment", "scalability", "nodejs"],
  seo: {
    title: "Microservices Tutorial - Complete Backend Development Guide | DevSphere",
    description: "Learn microservices architecture from scratch with a complete guide to service design, API gateways, service discovery, communication, Docker, Kubernetes, messaging, security, databases, resilience, observability, testing, deployment, and scalable distributed systems.", 
    keywords: ["Microservices Tutorial", "Microservices Architecture Tutorial", "Learn Microservices", "Microservices Course", "Microservices for Beginners", "Advanced Microservices", "Microservices Architecture", "Microservice Architecture", "Distributed Systems", "Distributed Systems Tutorial", "Backend Architecture", "System Design", "Microservices Design Patterns", "Microservices Patterns", "Monolith vs Microservices", "Microservices vs Monolith", "Service Decomposition", "API Gateway", "API Gateway Pattern", "Service Discovery", "Service Registry", "Inter Service Communication", "Microservices Communication", "REST Microservices", "gRPC Microservices", "Event Driven Architecture", "Event Driven Microservices", "Message Queue", "Message Broker", "Kafka Microservices", "RabbitMQ Microservices", "Database per Service", "Microservices Database", "Distributed Transactions", "Saga Pattern", "CQRS", "Microservices Authentication", "Microservices Authorization", "Microservices Security", "Docker Microservices", "Docker and Microservices", "Kubernetes Microservices", "Kubernetes Architecture", "Containerized Microservices", "Microservices Deployment", "Microservices Scalability", "Scalable Microservices", "Microservices Resilience", "Fault Tolerance", "Circuit Breaker Pattern", "Retry Pattern", "Observability", "Microservices Monitoring", "Distributed Tracing", "Microservices Logging", "Microservices Testing", "Microservices CI CD", "Microservices DevOps", "Node.js Microservices", "Production Microservices", "Real World Microservices", "DevSphere"]
  }
};

export const sections = [
  {
    id: "introduction-to-microservices",
    title: "Introduction to Microservices",
    order: 1,
    difficulty: "Beginner",
    lessons: [
      {
        id: 1,
        order: 1,
        slug: "microservices-what-are-microservices",
        title: "What are Microservices?",
        shortTitle: "What are Microservices",
        readingTime: 11,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the fundamental concepts of microservices and how they differ from traditional monolithic architectures.",
        prerequisites: [],
        related: ["microservices-why-microservices", "microservices-serviceoriented-architecture-soa-vs-microservices"],
        recommended: ["microservices-monolith-vs-microservices", "microservices-characteristics-of-microservices"]
      },
      {
        id: 2,
        order: 2,
        slug: "microservices-why-microservices",
        title: "Why Microservices?",
        shortTitle: "Why Microservices",
        readingTime: 12,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the key reasons and business drivers behind adopting a microservices architecture for modern scalable applications.",
        prerequisites: ["microservices-what-are-microservices"],
        related: ["microservices-monolith-vs-microservices", "microservices-what-are-microservices"],
        recommended: ["microservices-characteristics-of-microservices", "microservices-serviceoriented-architecture-soa-vs-microservices"]
      },
      {
        id: 3,
        order: 3,
        slug: "microservices-monolith-vs-microservices",
        title: "Monolith vs Microservices",
        shortTitle: "Monolith vs Microservices",
        readingTime: 13,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Compare monolithic and microservices architectures to understand the trade-offs in scalability, deployment, and development.",
        prerequisites: ["microservices-why-microservices", "microservices-what-are-microservices"],
        related: ["microservices-characteristics-of-microservices", "microservices-why-microservices"],
        recommended: ["microservices-advantages-of-microservices", "microservices-what-are-microservices"]
      },
      {
        id: 4,
        order: 4,
        slug: "microservices-characteristics-of-microservices",
        title: "Characteristics of Microservices",
        shortTitle: "Characteristics of Microserv...",
        readingTime: 14,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn the defining characteristics of microservices, including decentralization, independent deployment, and bounded contexts.",
        prerequisites: ["microservices-monolith-vs-microservices", "microservices-why-microservices"],
        related: ["microservices-advantages-of-microservices", "microservices-monolith-vs-microservices"],
        recommended: ["microservices-challenges-of-microservices", "microservices-why-microservices"]
      },
      {
        id: 5,
        order: 5,
        slug: "microservices-advantages-of-microservices",
        title: "Advantages of Microservices",
        shortTitle: "Advantages of Microservices",
        readingTime: 15,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover the major advantages of microservices, such as improved scalability, technology diversity, and fault isolation.",
        prerequisites: ["microservices-characteristics-of-microservices", "microservices-monolith-vs-microservices"],
        related: ["microservices-challenges-of-microservices", "microservices-characteristics-of-microservices"],
        recommended: ["microservices-when-to-use-microservices", "microservices-monolith-vs-microservices"]
      },
      {
        id: 6,
        order: 6,
        slug: "microservices-challenges-of-microservices",
        title: "Challenges of Microservices",
        shortTitle: "Challenges of Microservices",
        readingTime: 10,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Identify common challenges in microservices, including distributed data management, network latency, and operational complexity.",
        prerequisites: ["microservices-advantages-of-microservices", "microservices-characteristics-of-microservices"],
        related: ["microservices-when-to-use-microservices", "microservices-advantages-of-microservices"],
        recommended: ["microservices-realworld-examples-of-microservices", "microservices-characteristics-of-microservices"]
      },
      {
        id: 7,
        order: 7,
        slug: "microservices-when-to-use-microservices",
        title: "When to Use Microservices",
        shortTitle: "When to Use Microservices",
        readingTime: 11,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Determine the right scenarios and organizational readiness required to successfully adopt a microservices architecture.",
        prerequisites: ["microservices-challenges-of-microservices", "microservices-advantages-of-microservices"],
        related: ["microservices-realworld-examples-of-microservices", "microservices-challenges-of-microservices"],
        recommended: ["microservices-advantages-of-microservices", "microservices-serviceoriented-architecture-soa-vs-microservices"]
      },
      {
        id: 8,
        order: 8,
        slug: "microservices-realworld-examples-of-microservices",
        title: "Real-World Examples of Microservices",
        shortTitle: "Real-World Examples of Micro...",
        readingTime: 12,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore real-world examples of companies like Netflix, Amazon, and Uber successfully implementing microservices.",
        prerequisites: ["microservices-when-to-use-microservices", "microservices-challenges-of-microservices"],
        related: ["microservices-when-to-use-microservices", "microservices-serviceoriented-architecture-soa-vs-microservices"],
        recommended: ["microservices-challenges-of-microservices", "microservices-microservice-components"]
      }
    ]
  },
  {
    id: "microservice-architecture",
    title: "Microservice Architecture",
    order: 2,
    difficulty: "Beginner",
    lessons: [
      {
        id: 9,
        order: 1,
        slug: "microservices-serviceoriented-architecture-soa-vs-microservices",
        title: "Service-Oriented Architecture (SOA) vs Microservices",
        shortTitle: "Service-Oriented Architectur...",
        readingTime: 13,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of service-oriented architecture (soa) vs microservices to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-realworld-examples-of-microservices", "microservices-when-to-use-microservices"],
        related: ["microservices-microservice-components", "microservices-database-per-service-pattern"],
        recommended: ["microservices-service-boundaries", "microservices-database-per-service-pattern"]
      },
      {
        id: 10,
        order: 2,
        slug: "microservices-microservice-components",
        title: "Microservice Components",
        shortTitle: "Microservice Components",
        readingTime: 14,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of microservice components to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-serviceoriented-architecture-soa-vs-microservices"],
        related: ["microservices-service-boundaries", "microservices-serviceoriented-architecture-soa-vs-microservices"],
        recommended: ["microservices-domaindriven-design-ddd-basics", "microservices-database-per-service-pattern"]
      },
      {
        id: 11,
        order: 3,
        slug: "microservices-service-boundaries",
        title: "Service Boundaries",
        shortTitle: "Service Boundaries",
        readingTime: 15,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of service boundaries to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-microservice-components", "microservices-serviceoriented-architecture-soa-vs-microservices"],
        related: ["microservices-domaindriven-design-ddd-basics", "microservices-microservice-components"],
        recommended: ["microservices-bounded-context", "microservices-serviceoriented-architecture-soa-vs-microservices"]
      },
      {
        id: 12,
        order: 4,
        slug: "microservices-domaindriven-design-ddd-basics",
        title: "Domain-Driven Design (DDD) Basics",
        shortTitle: "Domain-Driven Design DDD Bas...",
        readingTime: 10,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of domain-driven design (ddd) basics to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-service-boundaries", "microservices-microservice-components"],
        related: ["microservices-bounded-context", "microservices-service-boundaries"],
        recommended: ["microservices-single-responsibility-principle", "microservices-microservice-components"]
      },
      {
        id: 13,
        order: 5,
        slug: "microservices-bounded-context",
        title: "Bounded Context",
        shortTitle: "Bounded Context",
        readingTime: 11,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of bounded context to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-domaindriven-design-ddd-basics", "microservices-service-boundaries"],
        related: ["microservices-single-responsibility-principle", "microservices-domaindriven-design-ddd-basics"],
        recommended: ["microservices-database-per-service-pattern", "microservices-service-boundaries"]
      },
      {
        id: 14,
        order: 6,
        slug: "microservices-single-responsibility-principle",
        title: "Single Responsibility Principle",
        shortTitle: "Single Responsibility Princi...",
        readingTime: 12,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of single responsibility principle to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-bounded-context", "microservices-domaindriven-design-ddd-basics"],
        related: ["microservices-database-per-service-pattern", "microservices-bounded-context"],
        recommended: ["microservices-domaindriven-design-ddd-basics", "microservices-database-per-service-pattern"]
      },
      {
        id: 15,
        order: 7,
        slug: "microservices-database-per-service-pattern",
        title: "Database per Service Pattern",
        shortTitle: "Database per Service Pattern",
        readingTime: 13,
        tags: ["microservices", "backend", "architecture", "database", "data management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Deep dive into the Database per Service Pattern and how it solves or creates challenges in distributed microservice systems.",
        prerequisites: ["microservices-single-responsibility-principle", "microservices-bounded-context"],
        related: ["microservices-single-responsibility-principle", "microservices-database-per-service"],
        recommended: ["microservices-bounded-context", "microservices-synchronous-communication"]
      }
    ]
  },
  {
    id: "communication-between-services",
    title: "Communication Between Services",
    order: 3,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 16,
        order: 1,
        slug: "microservices-synchronous-communication",
        title: "Synchronous Communication",
        shortTitle: "Synchronous Communication",
        readingTime: 14,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of synchronous communication to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-database-per-service-pattern", "microservices-single-responsibility-principle"],
        related: ["microservices-asynchronous-communication", "microservices-database-per-service"],
        recommended: ["microservices-rest-apis", "microservices-asynchronous-communication"]
      },
      {
        id: 17,
        order: 2,
        slug: "microservices-asynchronous-communication",
        title: "Asynchronous Communication",
        shortTitle: "Asynchronous Communication",
        readingTime: 15,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of asynchronous communication to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-synchronous-communication"],
        related: ["microservices-rest-apis", "microservices-synchronous-communication"],
        recommended: ["microservices-grpc", "microservices-rest-apis"]
      },
      {
        id: 18,
        order: 3,
        slug: "microservices-rest-apis",
        title: "REST APIs",
        shortTitle: "REST APIs",
        readingTime: 10,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of rest apis to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-asynchronous-communication", "microservices-synchronous-communication"],
        related: ["microservices-grpc", "microservices-asynchronous-communication"],
        recommended: ["microservices-message-queues", "microservices-synchronous-communication"]
      },
      {
        id: 19,
        order: 4,
        slug: "microservices-grpc",
        title: "gRPC",
        shortTitle: "gRPC",
        readingTime: 11,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of grpc to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-rest-apis", "microservices-asynchronous-communication"],
        related: ["microservices-message-queues", "microservices-rest-apis"],
        recommended: ["microservices-eventdriven-architecture", "microservices-asynchronous-communication"]
      },
      {
        id: 20,
        order: 5,
        slug: "microservices-message-queues",
        title: "Message Queues",
        shortTitle: "Message Queues",
        readingTime: 12,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of message queues to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-grpc", "microservices-rest-apis"],
        related: ["microservices-eventdriven-architecture", "microservices-grpc"],
        recommended: ["microservices-publishsubscribe-pattern", "microservices-rest-apis"]
      },
      {
        id: 21,
        order: 6,
        slug: "microservices-eventdriven-architecture",
        title: "Event-Driven Architecture",
        shortTitle: "Event-Driven Architecture",
        readingTime: 13,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of event-driven architecture to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-message-queues", "microservices-grpc"],
        related: ["microservices-publishsubscribe-pattern", "microservices-message-queues"],
        recommended: ["microservices-requestreply-pattern", "microservices-grpc"]
      },
      {
        id: 22,
        order: 7,
        slug: "microservices-publishsubscribe-pattern",
        title: "Publish-Subscribe Pattern",
        shortTitle: "Publish-Subscribe Pattern",
        readingTime: 14,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Deep dive into the Publish-Subscribe Pattern and how it solves or creates challenges in distributed microservice systems.",
        prerequisites: ["microservices-eventdriven-architecture", "microservices-message-queues"],
        related: ["microservices-requestreply-pattern", "microservices-eventdriven-architecture"],
        recommended: ["microservices-message-queues", "microservices-database-per-service"]
      },
      {
        id: 23,
        order: 8,
        slug: "microservices-requestreply-pattern",
        title: "Request-Reply Pattern",
        shortTitle: "Request-Reply Pattern",
        readingTime: 15,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Deep dive into the Request-Reply Pattern and how it solves or creates challenges in distributed microservice systems.",
        prerequisites: ["microservices-publishsubscribe-pattern", "microservices-eventdriven-architecture"],
        related: ["microservices-publishsubscribe-pattern", "microservices-database-per-service"],
        recommended: ["microservices-eventdriven-architecture", "microservices-database-per-service"]
      }
    ]
  },
  {
    id: "data-management",
    title: "Data Management",
    order: 4,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 24,
        order: 1,
        slug: "microservices-database-per-service",
        title: "Database per Service",
        shortTitle: "Database per Service",
        readingTime: 10,
        tags: ["microservices", "backend", "architecture", "database", "data management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of database per service to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-requestreply-pattern", "microservices-publishsubscribe-pattern"],
        related: ["microservices-shared-database-antipattern", "microservices-authentication-in-microservices"],
        recommended: ["microservices-distributed-transactions", "microservices-shared-database-antipattern"]
      },
      {
        id: 25,
        order: 2,
        slug: "microservices-shared-database-antipattern",
        title: "Shared Database Anti-Pattern",
        shortTitle: "Shared Database Anti-Pattern",
        readingTime: 11,
        tags: ["microservices", "backend", "architecture", "database", "data management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Deep dive into the Shared Database Anti-Pattern and how it solves or creates challenges in distributed microservice systems.",
        prerequisites: ["microservices-database-per-service"],
        related: ["microservices-distributed-transactions", "microservices-database-per-service"],
        recommended: ["microservices-saga-pattern", "microservices-database-per-service"]
      },
      {
        id: 26,
        order: 3,
        slug: "microservices-distributed-transactions",
        title: "Distributed Transactions",
        shortTitle: "Distributed Transactions",
        readingTime: 12,
        tags: ["microservices", "backend", "architecture", "database", "data management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of distributed transactions to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-shared-database-antipattern", "microservices-database-per-service"],
        related: ["microservices-saga-pattern", "microservices-shared-database-antipattern"],
        recommended: ["microservices-event-sourcing", "microservices-database-per-service"]
      },
      {
        id: 27,
        order: 4,
        slug: "microservices-saga-pattern",
        title: "Saga Pattern",
        shortTitle: "Saga Pattern",
        readingTime: 13,
        tags: ["microservices", "backend", "architecture", "database", "data management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Deep dive into the Saga Pattern and how it solves or creates challenges in distributed microservice systems.",
        prerequisites: ["microservices-distributed-transactions", "microservices-shared-database-antipattern"],
        related: ["microservices-event-sourcing", "microservices-distributed-transactions"],
        recommended: ["microservices-cqrs-command-query-responsibility-segregation", "microservices-shared-database-antipattern"]
      },
      {
        id: 28,
        order: 5,
        slug: "microservices-event-sourcing",
        title: "Event Sourcing",
        shortTitle: "Event Sourcing",
        readingTime: 14,
        tags: ["microservices", "backend", "architecture", "database", "data management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of event sourcing to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-saga-pattern", "microservices-distributed-transactions"],
        related: ["microservices-cqrs-command-query-responsibility-segregation", "microservices-saga-pattern"],
        recommended: ["microservices-data-consistency", "microservices-distributed-transactions"]
      },
      {
        id: 29,
        order: 6,
        slug: "microservices-cqrs-command-query-responsibility-segregation",
        title: "CQRS (Command Query Responsibility Segregation)",
        shortTitle: "CQRS Command Query Responsib...",
        readingTime: 15,
        tags: ["microservices", "backend", "architecture", "database", "data management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of cqrs (command query responsibility segregation) to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-event-sourcing", "microservices-saga-pattern"],
        related: ["microservices-data-consistency", "microservices-event-sourcing"],
        recommended: ["microservices-handling-distributed-data", "microservices-saga-pattern"]
      },
      {
        id: 30,
        order: 7,
        slug: "microservices-data-consistency",
        title: "Data Consistency",
        shortTitle: "Data Consistency",
        readingTime: 10,
        tags: ["microservices", "backend", "architecture", "database", "data management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of data consistency to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-cqrs-command-query-responsibility-segregation", "microservices-event-sourcing"],
        related: ["microservices-handling-distributed-data", "microservices-cqrs-command-query-responsibility-segregation"],
        recommended: ["microservices-event-sourcing", "microservices-authentication-in-microservices"]
      },
      {
        id: 31,
        order: 8,
        slug: "microservices-handling-distributed-data",
        title: "Handling Distributed Data",
        shortTitle: "Handling Distributed Data",
        readingTime: 11,
        tags: ["microservices", "backend", "architecture", "database", "data management"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of handling distributed data to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-data-consistency", "microservices-cqrs-command-query-responsibility-segregation"],
        related: ["microservices-data-consistency", "microservices-authentication-in-microservices"],
        recommended: ["microservices-cqrs-command-query-responsibility-segregation", "microservices-authentication-in-microservices"]
      }
    ]
  },
  {
    id: "service-discovery-api-gateway",
    title: "Service Discovery & API Gateway",
    order: 5,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 32,
        order: 1,
        slug: "microservices-service-discovery",
        title: "Service Discovery",
        shortTitle: "Service Discovery",
        readingTime: 12,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of service discovery to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-handling-distributed-data", "microservices-data-consistency"],
        related: ["microservices-clientside-discovery", "microservices-circuit-breaker-pattern"],
        recommended: ["microservices-serverside-discovery", "microservices-clientside-discovery"]
      },
      {
        id: 33,
        order: 2,
        slug: "microservices-clientside-discovery",
        title: "Client-Side Discovery",
        shortTitle: "Client-Side Discovery",
        readingTime: 13,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of client-side discovery to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-service-discovery"],
        related: ["microservices-serverside-discovery", "microservices-service-discovery"],
        recommended: ["microservices-api-gateway", "microservices-service-discovery"]
      },
      {
        id: 34,
        order: 3,
        slug: "microservices-serverside-discovery",
        title: "Server-Side Discovery",
        shortTitle: "Server-Side Discovery",
        readingTime: 14,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of server-side discovery to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-clientside-discovery", "microservices-service-discovery"],
        related: ["microservices-api-gateway", "microservices-clientside-discovery"],
        recommended: ["microservices-gateway-routing", "microservices-service-discovery"]
      },
      {
        id: 35,
        order: 4,
        slug: "microservices-api-gateway",
        title: "API Gateway",
        shortTitle: "API Gateway",
        readingTime: 15,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of api gateway to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-serverside-discovery", "microservices-clientside-discovery"],
        related: ["microservices-gateway-routing", "microservices-serverside-discovery"],
        recommended: ["microservices-load-balancing", "microservices-clientside-discovery"]
      },
      {
        id: 36,
        order: 5,
        slug: "microservices-gateway-routing",
        title: "Gateway Routing",
        shortTitle: "Gateway Routing",
        readingTime: 10,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of gateway routing to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-api-gateway", "microservices-serverside-discovery"],
        related: ["microservices-load-balancing", "microservices-api-gateway"],
        recommended: ["microservices-reverse-proxy", "microservices-serverside-discovery"]
      },
      {
        id: 37,
        order: 6,
        slug: "microservices-load-balancing",
        title: "Load Balancing",
        shortTitle: "Load Balancing",
        readingTime: 11,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of load balancing to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-gateway-routing", "microservices-api-gateway"],
        related: ["microservices-reverse-proxy", "microservices-gateway-routing"],
        recommended: ["microservices-api-gateway", "microservices-circuit-breaker-pattern"]
      },
      {
        id: 38,
        order: 7,
        slug: "microservices-reverse-proxy",
        title: "Reverse Proxy",
        shortTitle: "Reverse Proxy",
        readingTime: 12,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of reverse proxy to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-load-balancing", "microservices-gateway-routing"],
        related: ["microservices-load-balancing", "microservices-circuit-breaker-pattern"],
        recommended: ["microservices-gateway-routing", "microservices-circuit-breaker-pattern"]
      }
    ]
  },
  {
    id: "security",
    title: "Security",
    order: 6,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 39,
        order: 1,
        slug: "microservices-authentication-in-microservices",
        title: "Authentication in Microservices",
        shortTitle: "Authentication in Microservi...",
        readingTime: 13,
        tags: ["microservices", "backend", "architecture", "security", "authentication"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of authentication in microservices to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-reverse-proxy", "microservices-load-balancing"],
        related: ["microservices-authorization", "microservices-containers-with-docker"],
        recommended: ["microservices-jwt-between-services", "microservices-authorization"]
      },
      {
        id: 40,
        order: 2,
        slug: "microservices-authorization",
        title: "Authorization",
        shortTitle: "Authorization",
        readingTime: 14,
        tags: ["microservices", "backend", "architecture", "security", "authentication"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of authorization to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-authentication-in-microservices"],
        related: ["microservices-jwt-between-services", "microservices-authentication-in-microservices"],
        recommended: ["microservices-oauth-20", "microservices-authentication-in-microservices"]
      },
      {
        id: 41,
        order: 3,
        slug: "microservices-jwt-between-services",
        title: "JWT Between Services",
        shortTitle: "JWT Between Services",
        readingTime: 15,
        tags: ["microservices", "backend", "architecture", "security", "authentication"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of jwt between services to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-authorization", "microservices-authentication-in-microservices"],
        related: ["microservices-oauth-20", "microservices-authorization"],
        recommended: ["microservices-api-security", "microservices-authentication-in-microservices"]
      },
      {
        id: 42,
        order: 4,
        slug: "microservices-oauth-20",
        title: "OAuth 2.0",
        shortTitle: "OAuth 2.0",
        readingTime: 10,
        tags: ["microservices", "backend", "architecture", "security", "authentication"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of oauth 2.0 to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-jwt-between-services", "microservices-authorization"],
        related: ["microservices-api-security", "microservices-jwt-between-services"],
        recommended: ["microservices-secrets-management", "microservices-authorization"]
      },
      {
        id: 43,
        order: 5,
        slug: "microservices-api-security",
        title: "API Security",
        shortTitle: "API Security",
        readingTime: 11,
        tags: ["microservices", "backend", "architecture", "security", "authentication"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of api security to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-oauth-20", "microservices-jwt-between-services"],
        related: ["microservices-secrets-management", "microservices-oauth-20"],
        recommended: ["microservices-jwt-between-services", "microservices-containers-with-docker"]
      },
      {
        id: 44,
        order: 6,
        slug: "microservices-secrets-management",
        title: "Secrets Management",
        shortTitle: "Secrets Management",
        readingTime: 12,
        tags: ["microservices", "backend", "architecture", "security", "authentication"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of secrets management to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-api-security", "microservices-oauth-20"],
        related: ["microservices-api-security", "microservices-containers-with-docker"],
        recommended: ["microservices-oauth-20", "microservices-containers-with-docker"]
      }
    ]
  },
  {
    id: "reliability-resilience",
    title: "Reliability & Resilience",
    order: 7,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 45,
        order: 1,
        slug: "microservices-circuit-breaker-pattern",
        title: "Circuit Breaker Pattern",
        shortTitle: "Circuit Breaker Pattern",
        readingTime: 13,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Deep dive into the Circuit Breaker Pattern and how it solves or creates challenges in distributed microservice systems.",
        prerequisites: ["microservices-secrets-management", "microservices-api-security"],
        related: ["microservices-retry-pattern", "microservices-logging"],
        recommended: ["microservices-timeout-pattern", "microservices-retry-pattern"]
      },
      {
        id: 46,
        order: 2,
        slug: "microservices-retry-pattern",
        title: "Retry Pattern",
        shortTitle: "Retry Pattern",
        readingTime: 14,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Deep dive into the Retry Pattern and how it solves or creates challenges in distributed microservice systems.",
        prerequisites: ["microservices-circuit-breaker-pattern"],
        related: ["microservices-timeout-pattern", "microservices-circuit-breaker-pattern"],
        recommended: ["microservices-bulkhead-pattern", "microservices-circuit-breaker-pattern"]
      },
      {
        id: 47,
        order: 3,
        slug: "microservices-timeout-pattern",
        title: "Timeout Pattern",
        shortTitle: "Timeout Pattern",
        readingTime: 15,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Deep dive into the Timeout Pattern and how it solves or creates challenges in distributed microservice systems.",
        prerequisites: ["microservices-retry-pattern", "microservices-circuit-breaker-pattern"],
        related: ["microservices-bulkhead-pattern", "microservices-retry-pattern"],
        recommended: ["microservices-rate-limiting", "microservices-circuit-breaker-pattern"]
      },
      {
        id: 48,
        order: 4,
        slug: "microservices-bulkhead-pattern",
        title: "Bulkhead Pattern",
        shortTitle: "Bulkhead Pattern",
        readingTime: 10,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Deep dive into the Bulkhead Pattern and how it solves or creates challenges in distributed microservice systems.",
        prerequisites: ["microservices-timeout-pattern", "microservices-retry-pattern"],
        related: ["microservices-rate-limiting", "microservices-timeout-pattern"],
        recommended: ["microservices-fault-tolerance", "microservices-retry-pattern"]
      },
      {
        id: 49,
        order: 5,
        slug: "microservices-rate-limiting",
        title: "Rate Limiting",
        shortTitle: "Rate Limiting",
        readingTime: 11,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of rate limiting to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-bulkhead-pattern", "microservices-timeout-pattern"],
        related: ["microservices-fault-tolerance", "microservices-bulkhead-pattern"],
        recommended: ["microservices-graceful-degradation", "microservices-timeout-pattern"]
      },
      {
        id: 50,
        order: 6,
        slug: "microservices-fault-tolerance",
        title: "Fault Tolerance",
        shortTitle: "Fault Tolerance",
        readingTime: 12,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of fault tolerance to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-rate-limiting", "microservices-bulkhead-pattern"],
        related: ["microservices-graceful-degradation", "microservices-rate-limiting"],
        recommended: ["microservices-bulkhead-pattern", "microservices-logging"]
      },
      {
        id: 51,
        order: 7,
        slug: "microservices-graceful-degradation",
        title: "Graceful Degradation",
        shortTitle: "Graceful Degradation",
        readingTime: 13,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of graceful degradation to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-fault-tolerance", "microservices-rate-limiting"],
        related: ["microservices-fault-tolerance", "microservices-logging"],
        recommended: ["microservices-rate-limiting", "microservices-logging"]
      }
    ]
  },
  {
    id: "deployment-scalability",
    title: "Deployment & Scalability",
    order: 8,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 52,
        order: 1,
        slug: "microservices-containers-with-docker",
        title: "Containers with Docker",
        shortTitle: "Containers with Docker",
        readingTime: 14,
        tags: ["microservices", "backend", "architecture", "docker", "kubernetes"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of containers with docker to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-graceful-degradation", "microservices-fault-tolerance"],
        related: ["microservices-kubernetes-basics", "microservices-designing-an-ecommerce-system"],
        recommended: ["microservices-scaling-microservices", "microservices-kubernetes-basics"]
      },
      {
        id: 53,
        order: 2,
        slug: "microservices-kubernetes-basics",
        title: "Kubernetes Basics",
        shortTitle: "Kubernetes Basics",
        readingTime: 15,
        tags: ["microservices", "backend", "architecture", "docker", "kubernetes"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of kubernetes basics to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-containers-with-docker"],
        related: ["microservices-scaling-microservices", "microservices-containers-with-docker"],
        recommended: ["microservices-service-mesh", "microservices-containers-with-docker"]
      },
      {
        id: 54,
        order: 3,
        slug: "microservices-scaling-microservices",
        title: "Scaling Microservices",
        shortTitle: "Scaling Microservices",
        readingTime: 10,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of scaling microservices to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-kubernetes-basics", "microservices-containers-with-docker"],
        related: ["microservices-service-mesh", "microservices-kubernetes-basics"],
        recommended: ["microservices-cicd-for-microservices", "microservices-containers-with-docker"]
      },
      {
        id: 55,
        order: 4,
        slug: "microservices-service-mesh",
        title: "Service Mesh",
        shortTitle: "Service Mesh",
        readingTime: 11,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of service mesh to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-scaling-microservices", "microservices-kubernetes-basics"],
        related: ["microservices-cicd-for-microservices", "microservices-scaling-microservices"],
        recommended: ["microservices-bluegreen-deployment", "microservices-kubernetes-basics"]
      },
      {
        id: 56,
        order: 5,
        slug: "microservices-cicd-for-microservices",
        title: "CI/CD for Microservices",
        shortTitle: "CI/CD for Microservices",
        readingTime: 12,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of ci/cd for microservices to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-service-mesh", "microservices-scaling-microservices"],
        related: ["microservices-bluegreen-deployment", "microservices-service-mesh"],
        recommended: ["microservices-canary-deployment", "microservices-scaling-microservices"]
      },
      {
        id: 57,
        order: 6,
        slug: "microservices-bluegreen-deployment",
        title: "Blue-Green Deployment",
        shortTitle: "Blue-Green Deployment",
        readingTime: 13,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of blue-green deployment to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-cicd-for-microservices", "microservices-service-mesh"],
        related: ["microservices-canary-deployment", "microservices-cicd-for-microservices"],
        recommended: ["microservices-service-mesh", "microservices-designing-an-ecommerce-system"]
      },
      {
        id: 58,
        order: 7,
        slug: "microservices-canary-deployment",
        title: "Canary Deployment",
        shortTitle: "Canary Deployment",
        readingTime: 14,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of canary deployment to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-bluegreen-deployment", "microservices-cicd-for-microservices"],
        related: ["microservices-bluegreen-deployment", "microservices-designing-an-ecommerce-system"],
        recommended: ["microservices-cicd-for-microservices", "microservices-designing-an-ecommerce-system"]
      }
    ]
  },
  {
    id: "monitoring-observability",
    title: "Monitoring & Observability",
    order: 9,
    difficulty: "Advanced",
    lessons: [
      {
        id: 59,
        order: 1,
        slug: "microservices-logging",
        title: "Logging",
        shortTitle: "Logging",
        readingTime: 15,
        tags: ["microservices", "backend", "architecture", "observability", "monitoring"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of logging to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-canary-deployment", "microservices-bluegreen-deployment"],
        related: ["microservices-centralized-logging", "microservices-strangler-fig-pattern"],
        recommended: ["microservices-metrics", "microservices-centralized-logging"]
      },
      {
        id: 60,
        order: 2,
        slug: "microservices-centralized-logging",
        title: "Centralized Logging",
        shortTitle: "Centralized Logging",
        readingTime: 10,
        tags: ["microservices", "backend", "architecture", "observability", "monitoring"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of centralized logging to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-logging"],
        related: ["microservices-metrics", "microservices-logging"],
        recommended: ["microservices-distributed-tracing", "microservices-logging"]
      },
      {
        id: 61,
        order: 3,
        slug: "microservices-metrics",
        title: "Metrics",
        shortTitle: "Metrics",
        readingTime: 11,
        tags: ["microservices", "backend", "architecture", "observability", "monitoring"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of metrics to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-centralized-logging", "microservices-logging"],
        related: ["microservices-distributed-tracing", "microservices-centralized-logging"],
        recommended: ["microservices-health-checks", "microservices-logging"]
      },
      {
        id: 62,
        order: 4,
        slug: "microservices-distributed-tracing",
        title: "Distributed Tracing",
        shortTitle: "Distributed Tracing",
        readingTime: 12,
        tags: ["microservices", "backend", "architecture", "observability", "monitoring"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of distributed tracing to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-metrics", "microservices-centralized-logging"],
        related: ["microservices-health-checks", "microservices-metrics"],
        recommended: ["microservices-monitoring-tools", "microservices-centralized-logging"]
      },
      {
        id: 63,
        order: 5,
        slug: "microservices-health-checks",
        title: "Health Checks",
        shortTitle: "Health Checks",
        readingTime: 13,
        tags: ["microservices", "backend", "architecture", "observability", "monitoring"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of health checks to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-distributed-tracing", "microservices-metrics"],
        related: ["microservices-monitoring-tools", "microservices-distributed-tracing"],
        recommended: ["microservices-metrics", "microservices-strangler-fig-pattern"]
      },
      {
        id: 64,
        order: 6,
        slug: "microservices-monitoring-tools",
        title: "Monitoring Tools",
        shortTitle: "Monitoring Tools",
        readingTime: 14,
        tags: ["microservices", "backend", "architecture", "observability", "monitoring"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of monitoring tools to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-health-checks", "microservices-distributed-tracing"],
        related: ["microservices-health-checks", "microservices-strangler-fig-pattern"],
        recommended: ["microservices-distributed-tracing", "microservices-strangler-fig-pattern"]
      }
    ]
  },
  {
    id: "building-a-real-microservice-system",
    title: "Building a Real Microservice System",
    order: 10,
    difficulty: "Advanced",
    lessons: [
      {
        id: 65,
        order: 1,
        slug: "microservices-designing-an-ecommerce-system",
        title: "Designing an E-commerce System",
        shortTitle: "Designing an E-commerce System",
        readingTime: 15,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of designing an e-commerce system to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-monitoring-tools", "microservices-health-checks"],
        related: ["microservices-user-service", "microservices-microservices-design-questions"],
        recommended: ["microservices-product-service", "microservices-user-service"]
      },
      {
        id: 66,
        order: 2,
        slug: "microservices-user-service",
        title: "User Service",
        shortTitle: "User Service",
        readingTime: 10,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to design and implement the User Service with proper boundaries, APIs, and data management.",
        prerequisites: ["microservices-designing-an-ecommerce-system"],
        related: ["microservices-product-service", "microservices-designing-an-ecommerce-system"],
        recommended: ["microservices-order-service", "microservices-designing-an-ecommerce-system"]
      },
      {
        id: 67,
        order: 3,
        slug: "microservices-product-service",
        title: "Product Service",
        shortTitle: "Product Service",
        readingTime: 11,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to design and implement the Product Service with proper boundaries, APIs, and data management.",
        prerequisites: ["microservices-user-service", "microservices-designing-an-ecommerce-system"],
        related: ["microservices-order-service", "microservices-user-service"],
        recommended: ["microservices-payment-service", "microservices-designing-an-ecommerce-system"]
      },
      {
        id: 68,
        order: 4,
        slug: "microservices-order-service",
        title: "Order Service",
        shortTitle: "Order Service",
        readingTime: 12,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to design and implement the Order Service with proper boundaries, APIs, and data management.",
        prerequisites: ["microservices-product-service", "microservices-user-service"],
        related: ["microservices-payment-service", "microservices-product-service"],
        recommended: ["microservices-notification-service", "microservices-user-service"]
      },
      {
        id: 69,
        order: 5,
        slug: "microservices-payment-service",
        title: "Payment Service",
        shortTitle: "Payment Service",
        readingTime: 13,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to design and implement the Payment Service with proper boundaries, APIs, and data management.",
        prerequisites: ["microservices-order-service", "microservices-product-service"],
        related: ["microservices-notification-service", "microservices-order-service"],
        recommended: ["microservices-api-gateway-integration", "microservices-product-service"]
      },
      {
        id: 70,
        order: 6,
        slug: "microservices-notification-service",
        title: "Notification Service",
        shortTitle: "Notification Service",
        readingTime: 14,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to design and implement the Notification Service with proper boundaries, APIs, and data management.",
        prerequisites: ["microservices-payment-service", "microservices-order-service"],
        related: ["microservices-api-gateway-integration", "microservices-payment-service"],
        recommended: ["microservices-production-architecture", "microservices-order-service"]
      },
      {
        id: 71,
        order: 7,
        slug: "microservices-api-gateway-integration",
        title: "API Gateway Integration",
        shortTitle: "API Gateway Integration",
        readingTime: 15,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of api gateway integration to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-notification-service", "microservices-payment-service"],
        related: ["microservices-production-architecture", "microservices-notification-service"],
        recommended: ["microservices-payment-service", "microservices-microservices-design-questions"]
      },
      {
        id: 72,
        order: 8,
        slug: "microservices-production-architecture",
        title: "Production Architecture",
        shortTitle: "Production Architecture",
        readingTime: 10,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of production architecture to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-api-gateway-integration", "microservices-notification-service"],
        related: ["microservices-api-gateway-integration", "microservices-microservices-design-questions"],
        recommended: ["microservices-notification-service", "microservices-microservices-design-questions"]
      }
    ]
  },
  {
    id: "advanced-microservice-patterns",
    title: "Advanced Microservice Patterns",
    order: 11,
    difficulty: "Advanced",
    lessons: [
      {
        id: 73,
        order: 1,
        slug: "microservices-strangler-fig-pattern",
        title: "Strangler Fig Pattern",
        shortTitle: "Strangler Fig Pattern",
        readingTime: 11,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Deep dive into the Strangler Fig Pattern and how it solves or creates challenges in distributed microservice systems.",
        prerequisites: ["microservices-production-architecture", "microservices-api-gateway-integration"],
        related: ["microservices-sidecar-pattern", "microservices-choreography-vs-orchestration"],
        recommended: ["microservices-backend-for-frontend-bff", "microservices-sidecar-pattern"]
      },
      {
        id: 74,
        order: 2,
        slug: "microservices-sidecar-pattern",
        title: "Sidecar Pattern",
        shortTitle: "Sidecar Pattern",
        readingTime: 12,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Deep dive into the Sidecar Pattern and how it solves or creates challenges in distributed microservice systems.",
        prerequisites: ["microservices-strangler-fig-pattern"],
        related: ["microservices-backend-for-frontend-bff", "microservices-strangler-fig-pattern"],
        recommended: ["microservices-service-mesh", "microservices-strangler-fig-pattern"]
      },
      {
        id: 75,
        order: 3,
        slug: "microservices-backend-for-frontend-bff",
        title: "Backend for Frontend (BFF)",
        shortTitle: "Backend for Frontend BFF",
        readingTime: 13,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of backend for frontend (bff) to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-sidecar-pattern", "microservices-strangler-fig-pattern"],
        related: ["microservices-service-mesh", "microservices-sidecar-pattern"],
        recommended: ["microservices-choreography-vs-orchestration", "microservices-strangler-fig-pattern"]
      },
      {
        id: 76,
        order: 4,
        slug: "microservices-service-mesh",
        title: "Service Mesh",
        shortTitle: "Service Mesh",
        readingTime: 14,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of service mesh to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-backend-for-frontend-bff", "microservices-sidecar-pattern"],
        related: ["microservices-choreography-vs-orchestration", "microservices-backend-for-frontend-bff"],
        recommended: ["microservices-antipatterns-in-microservices", "microservices-sidecar-pattern"]
      },
      {
        id: 77,
        order: 5,
        slug: "microservices-choreography-vs-orchestration",
        title: "Choreography vs Orchestration",
        shortTitle: "Choreography vs Orchestration",
        readingTime: 15,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of choreography vs orchestration to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-service-mesh", "microservices-backend-for-frontend-bff"],
        related: ["microservices-antipatterns-in-microservices", "microservices-service-mesh"],
        recommended: ["microservices-backend-for-frontend-bff", "microservices-antipatterns-in-microservices"]
      },
      {
        id: 78,
        order: 6,
        slug: "microservices-antipatterns-in-microservices",
        title: "Anti-Patterns in Microservices",
        shortTitle: "Anti-Patterns in Microservices",
        readingTime: 10,
        tags: ["microservices", "backend", "architecture", "system design", "distributed systems"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Deep dive into the Anti-Patterns in Microservices and how it solves or creates challenges in distributed microservice systems.",
        prerequisites: ["microservices-choreography-vs-orchestration", "microservices-service-mesh"],
        related: ["microservices-choreography-vs-orchestration", "microservices-microservices-design-questions"],
        recommended: ["microservices-service-mesh", "microservices-microservices-design-questions"]
      }
    ]
  },
  {
    id: "career-interview",
    title: "Career & Interview",
    order: 12,
    difficulty: "Advanced",
    lessons: [
      {
        id: 79,
        order: 1,
        slug: "microservices-microservices-design-questions",
        title: "Microservices Design Questions",
        shortTitle: "Microservices Design Questions",
        readingTime: 11,
        tags: ["microservices", "backend", "architecture", "interview", "career"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of microservices design questions to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-antipatterns-in-microservices", "microservices-choreography-vs-orchestration"],
        related: ["microservices-common-interview-questions", "microservices-system-design-interviews"],
        recommended: ["microservices-system-design-interviews", "microservices-common-interview-questions"]
      },
      {
        id: 80,
        order: 2,
        slug: "microservices-common-interview-questions",
        title: "Common Interview Questions",
        shortTitle: "Common Interview Questions",
        readingTime: 12,
        tags: ["microservices", "backend", "architecture", "interview", "career"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of common interview questions to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-microservices-design-questions"],
        related: ["microservices-system-design-interviews", "microservices-microservices-design-questions"],
        recommended: ["microservices-production-best-practices", "microservices-microservices-design-questions"]
      },
      {
        id: 81,
        order: 3,
        slug: "microservices-system-design-interviews",
        title: "System Design Interviews",
        shortTitle: "System Design Interviews",
        readingTime: 13,
        tags: ["microservices", "backend", "architecture", "interview", "career"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of system design interviews to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-common-interview-questions", "microservices-microservices-design-questions"],
        related: ["microservices-production-best-practices", "microservices-common-interview-questions"],
        recommended: ["microservices-microservices-design-questions", "microservices-production-best-practices"]
      },
      {
        id: 82,
        order: 4,
        slug: "microservices-production-best-practices",
        title: "Production Best Practices",
        shortTitle: "Production Best Practices",
        readingTime: 14,
        tags: ["microservices", "backend", "architecture", "interview", "career"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the concepts of production best practices to build robust, scalable, and maintainable microservice systems.",
        prerequisites: ["microservices-system-design-interviews", "microservices-common-interview-questions"],
        related: ["microservices-system-design-interviews", "microservices-antipatterns-in-microservices"],
        recommended: ["microservices-common-interview-questions", "microservices-antipatterns-in-microservices"]
      }
    ]
  }
];

export const resources = [
  {
    id: "microservices-in-production",
    title: "Microservices in Production",
    order: 1,
    items: [
      {
        id: 83,
        order: 1,
        slug: "microservices-how-companies-design-microservice-systems",
        title: "How companies design microservice systems",
        shortTitle: "How companies design microse...",
        type: "article",
        readingTime: 10,
        tags: ["microservices", "backend", "production", "real world"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore how leading tech companies design, structure, and scale their microservice systems in real-world production environments."
      },
      {
        id: 84,
        order: 2,
        slug: "microservices-microservices-in-startups-vs-enterprises",
        title: "Microservices in startups vs enterprises",
        shortTitle: "Microservices in startups vs...",
        type: "article",
        readingTime: 12,
        tags: ["microservices", "backend", "production", "real world"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the key differences in microservices adoption, organizational readiness, and implementation between agile startups and large enterprises."
      },
      {
        id: 85,
        order: 3,
        slug: "microservices-real-production-architectures",
        title: "Real production architectures",
        shortTitle: "Real production architectures",
        type: "article",
        readingTime: 14,
        tags: ["microservices", "backend", "production", "architecture"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn from real-world production architectures and discover how they handle massive traffic, failures, and horizontal scaling."
      },
      {
        id: 86,
        order: 4,
        slug: "microservices-team-ownership-and-service-boundaries",
        title: "Team ownership and service boundaries",
        shortTitle: "Team ownership and service b...",
        type: "article",
        readingTime: 12,
        tags: ["microservices", "backend", "production", "best practices"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how to define clear team ownership and service boundaries to ensure independent, efficient, and conflict-free development."
      }
    ]
  },
  {
    id: "microservices-best-practices",
    title: "Microservices Best Practices",
    order: 2,
    items: [
      {
        id: 87,
        order: 1,
        slug: "microservices-designing-scalable-services",
        title: "Designing scalable services",
        shortTitle: "Designing scalable services",
        type: "article",
        readingTime: 10,
        tags: ["microservices", "backend", "best practices", "architecture"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the core principles of designing highly scalable, resilient, and maintainable microservices from the ground up."
      },
      {
        id: 88,
        order: 2,
        slug: "microservices-service-communication-strategies",
        title: "Service communication strategies",
        shortTitle: "Service communication strate...",
        type: "article",
        readingTime: 12,
        tags: ["microservices", "backend", "best practices", "communication"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Evaluate and choose the right service communication strategies, including synchronous REST/gRPC and asynchronous message brokers."
      },
      {
        id: 89,
        order: 3,
        slug: "microservices-database-design-for-microservices",
        title: "Database design for microservices",
        shortTitle: "Database design for microser...",
        type: "article",
        readingTime: 14,
        tags: ["microservices", "backend", "database", "best practices"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn best practices for database design in microservices, including the database-per-service pattern and managing distributed data."
      },
      {
        id: 90,
        order: 4,
        slug: "microservices-clean-api-design",
        title: "Clean API design",
        shortTitle: "Clean API design",
        type: "article",
        readingTime: 10,
        tags: ["microservices", "backend", "api", "best practices"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Follow industry guidelines for designing clean, consistent, versioned, and developer-friendly APIs for your microservices."
      }
    ]
  },
  {
    id: "common-microservices-mistakes",
    title: "Common Microservices Mistakes",
    order: 3,
    items: [
      {
        id: 91,
        order: 1,
        slug: "microservices-splitting-services-too-early",
        title: "Splitting services too early",
        shortTitle: "Splitting services too early",
        type: "article",
        readingTime: 10,
        tags: ["microservices", "backend", "mistakes", "common issues"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Avoid the common pitfall of splitting services too early before truly understanding the domain boundaries and business requirements."
      },
      {
        id: 92,
        order: 2,
        slug: "microservices-shared-database-antipattern",
        title: "Shared database anti-pattern",
        shortTitle: "Shared database anti-pattern",
        type: "article",
        readingTime: 12,
        tags: ["microservices", "backend", "database", "mistakes"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand why the shared database anti-pattern tightly couples services and completely undermines the core benefits of microservices."
      },
      {
        id: 93,
        order: 3,
        slug: "microservices-excessive-interservice-communication",
        title: "Excessive inter-service communication",
        shortTitle: "Excessive inter-service comm...",
        type: "article",
        readingTime: 12,
        tags: ["microservices", "backend", "mistakes", "performance"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to avoid excessive inter-service communication (chatty services) that leads to tight coupling, network latency, and cascading failures."
      },
      {
        id: 94,
        order: 4,
        slug: "microservices-ignoring-monitoring-and-observability",
        title: "Ignoring monitoring and observability",
        shortTitle: "Ignoring monitoring and obse...",
        type: "article",
        readingTime: 14,
        tags: ["microservices", "backend", "mistakes", "observability"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover why ignoring monitoring, logging, and distributed tracing is a critical mistake that makes debugging distributed systems nearly impossible."
      }
    ]
  },
  {
    id: "cloud-devops-guide",
    title: "Cloud & DevOps Guide",
    order: 4,
    items: [
      {
        id: 95,
        order: 1,
        slug: "microservices-docker-and-kubernetes-basics",
        title: "Docker and Kubernetes basics",
        shortTitle: "Docker and Kubernetes basics",
        type: "article",
        readingTime: 12,
        tags: ["microservices", "backend", "devops", "docker", "kubernetes"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get a solid foundation in Docker and Kubernetes for containerizing, orchestrating, and managing microservices at scale."
      },
      {
        id: 96,
        order: 2,
        slug: "microservices-cicd-pipelines",
        title: "CI/CD pipelines",
        shortTitle: "CI/CD pipelines",
        type: "article",
        readingTime: 12,
        tags: ["microservices", "backend", "devops", "cicd", "deployment"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to build robust, automated CI/CD pipelines tailored for independent, frequent, and safe microservice deployments."
      },
      {
        id: 97,
        order: 3,
        slug: "microservices-monitoring-and-logging",
        title: "Monitoring and logging",
        shortTitle: "Monitoring and logging",
        type: "article",
        readingTime: 14,
        tags: ["microservices", "backend", "devops", "observability", "logging"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Set up comprehensive monitoring, metrics, and centralized logging to maintain complete visibility across your distributed services."
      },
      {
        id: 98,
        order: 4,
        slug: "microservices-production-deployment-strategies",
        title: "Production deployment strategies",
        shortTitle: "Production deployment strate...",
        type: "article",
        readingTime: 14,
        tags: ["microservices", "backend", "devops", "deployment", "production"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore advanced, zero-downtime production deployment strategies like blue-green, canary, and feature flag deployments."
      }
    ]
  },
  {
    id: "microservices-career-guide",
    title: "Microservices Career Guide",
    order: 5,
    items: [
      {
        id: 99,
        order: 1,
        slug: "microservices-skills-companies-expect",
        title: "Skills companies expect",
        shortTitle: "Skills companies expect",
        type: "article",
        readingTime: 10,
        tags: ["microservices", "backend", "career", "interview"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn the specific microservices, distributed systems, and system design skills that top tech companies expect from backend candidates."
      },
      {
        id: 100,
        order: 2,
        slug: "microservices-system-design-interview-preparation",
        title: "System design interview preparation",
        shortTitle: "System design interview prep...",
        type: "article",
        readingTime: 15,
        tags: ["microservices", "backend", "career", "system design", "interview"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Prepare for system design interviews with a strong focus on microservices architecture, trade-offs, and scalability patterns."
      },
      {
        id: 101,
        order: 3,
        slug: "microservices-building-portfolioworthy-distributed-systems",
        title: "Building portfolio-worthy distributed systems",
        shortTitle: "Building portfolio-worthy di...",
        type: "article",
        readingTime: 14,
        tags: ["microservices", "backend", "career", "projects", "portfolio"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get actionable ideas for building portfolio-worthy distributed systems that clearly demonstrate your real-world backend engineering skills."
      },
      {
        id: 102,
        order: 4,
        slug: "microservices-realworld-microservice-case-studies",
        title: "Real-world microservice case studies",
        shortTitle: "Real-world microservice case...",
        type: "article",
        readingTime: 16,
        tags: ["microservices", "backend", "career", "real world", "case studies"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Study real-world microservice case studies from top tech companies to understand how theoretical concepts apply in practice."
      }
    ]
  }
];