// ============================================================
// src/registry/lessons/pythonLessons.js
// STUB — same shape as htmlLessons.js, empty until you fill it in.
// lessonRegistry.js can safely import this right now without
// breaking anything; it'll just show 0 lessons for Python until
// you add sections here.
// ============================================================

import { STATUS } from "../../config/constants";

export const tutorialInfo = {
  id: "mysql",
  title: "MySQL Tutorial",
  shortTitle: "MySQL",
  category: "Databases",
  description: "Master MySQL from beginner to advanced with a comprehensive tutorial covering SQL fundamentals, database design, tables, data types, CRUD operations, filtering, sorting, joins, subqueries, functions, views, indexes, transactions, stored procedures, triggers, database security, performance optimization, backups, and practical database management.",
  icon: "mysql",
  difficulty: "Advanced", // course-level badge, separate from per-section defaults
  estimatedHours: 42,
  totalLessons: 96,
  version: "MySQL 9.7 LTS",
  language: "English",
  path: "/mysql",
  authorId: "faiz",
  updatedAt: "2026-07-09",
  tags: ["mysql", "mysql tutorial", "mysql database", "sql", "sql tutorial", "relational database", "database", "database management", "database design", "mysql queries", "mysql commands", "crud", "select", "insert", "update", "delete", "mysql joins", "mysql subqueries", "mysql functions", "mysql views", "mysql indexes", "mysql transactions", "stored procedures", "mysql triggers", "mysql security", "mysql optimization", "mysql performance", "mysql backup", "mysql administration", "mysql with python", "mysql with nodejs", "mysql projects"],
  seo: {
    title: "MySQL Tutorial - Learn MySQL from Beginner to Advanced | DevSphere",
    description: "Learn MySQL from scratch with a complete tutorial covering SQL, database design, CRUD operations, queries, joins, subqueries, functions, views, indexes, transactions, stored procedures, triggers, security, optimization, backups, and real-world database development.",
    keywords: ["MySQL Tutorial", "MySQL Tutorial for Beginners", "Learn MySQL", "MySQL Course", "MySQL for Beginners", "MySQL Training", "MySQL Basics", "MySQL Fundamentals", "MySQL Database Tutorial", "MySQL Database", "MySQL Programming", "MySQL Commands", "MySQL Command Line", "MySQL Workbench", "SQL Tutorial", "SQL Tutorial for Beginners", "Learn SQL", "SQL Course", "SQL Basics", "SQL Fundamentals", "SQL Programming", "SQL Queries", "SQL Commands", "Relational Database", "Relational Database Tutorial", "Database Management System", "RDBMS", "Database Design", "Database Design Tutorial", "Database Schema", "MySQL Database Design", "MySQL Tables", "MySQL Data Types", "MySQL Primary Key", "MySQL Foreign Key", "MySQL Constraints", "MySQL CRUD", "MySQL CRUD Operations", "MySQL SELECT", "MySQL INSERT", "MySQL UPDATE", "MySQL DELETE", "MySQL WHERE Clause", "MySQL ORDER BY", "MySQL GROUP BY", "MySQL HAVING", "MySQL DISTINCT", "MySQL LIMIT", "MySQL Joins", "MySQL JOIN Tutorial", "MySQL INNER JOIN", "MySQL LEFT JOIN", "MySQL RIGHT JOIN", "MySQL CROSS JOIN", "MySQL Self Join", "MySQL Subquery", "MySQL Subqueries Tutorial", "MySQL CTE", "MySQL Common Table Expressions", "MySQL Functions", "MySQL String Functions", "MySQL Date Functions", "MySQL Aggregate Functions", "MySQL Views", "MySQL View Tutorial", "MySQL Indexes", "MySQL Index Tutorial", "MySQL Database Indexing", "MySQL Transactions", "MySQL Transaction Tutorial", "MySQL ACID", "MySQL Commit Rollback", "MySQL Stored Procedures", "MySQL Stored Procedure Tutorial", "MySQL Triggers", "MySQL Trigger Tutorial", "MySQL Events", "MySQL Cursors", "MySQL Window Functions", "MySQL JSON", "MySQL JSON Data", "MySQL Performance Optimization", "MySQL Query Optimization", "MySQL Performance Tuning", "MySQL EXPLAIN", "MySQL Security", "MySQL User Management", "MySQL Privileges", "MySQL Backup", "MySQL Restore", "MySQL Database Administration", "MySQL Replication", "MySQL High Availability", "MySQL with Python", "Python MySQL", "MySQL with Node.js", "Node.js MySQL", "MySQL API", "MySQL Backend Development", "MySQL Projects", "MySQL Database Projects", "MySQL Best Practices", "DevSphere"]
  }
};

export const sections = [
  {
    id: "getting-started-with-mysql",
    title: "Getting Started with MySQL",
    order: 1,
    difficulty: "Beginner",
    lessons: [
      {
        id: 1,
        order: 1,
        slug: "mysql-what-is-mysql",
        title: "What is MySQL?",
        shortTitle: "What is MySQL",
        readingTime: 9,
        tags: ["mysql", "database", "sql", "mysql fundamentals", "relational database"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get a comprehensive introduction to MySQL, understanding what it is and why it's the world's most popular open-source relational database.",
        prerequisites: [],
        related: ["mysql-mysql-vs-sql-understanding-the-difference", "mysql-creating-and-managing-databases"],
        recommended: ["mysql-how-mysql-works", "mysql-installing-mysql-on-windows"]
      },
      {
        id: 2,
        order: 2,
        slug: "mysql-mysql-vs-sql-understanding-the-difference",
        title: "MySQL vs SQL: Understanding the Difference",
        shortTitle: "MySQL vs SQL Understanding t...",
        readingTime: 10,
        tags: ["mysql", "database", "sql", "mysql fundamentals", "relational database"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Clarify the common confusion between MySQL (the database system) and SQL (the query language used to interact with it).",
        prerequisites: ["mysql-what-is-mysql", "mysql-how-mysql-works"],
        related: ["mysql-how-mysql-works", "mysql-what-is-mysql"],
        recommended: ["mysql-how-mysql-works", "mysql-installing-mysql-on-windows"]
      },
      {
        id: 3,
        order: 3,
        slug: "mysql-how-mysql-works",
        title: "How MySQL Works",
        shortTitle: "How MySQL Works",
        readingTime: 11,
        tags: ["mysql", "database", "sql", "mysql fundamentals", "relational database"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the underlying architecture and mechanics of how MySQL processes queries and manages data.",
        prerequisites: ["mysql-mysql-vs-sql-understanding-the-difference", "mysql-what-is-mysql"],
        related: ["mysql-installing-mysql-on-windows", "mysql-mysql-vs-sql-understanding-the-difference"],
        recommended: ["mysql-installing-mysql-on-windows", "mysql-installing-mysql-on-linux-and-macos"]
      },
      {
        id: 4,
        order: 4,
        slug: "mysql-installing-mysql-on-windows",
        title: "Installing MySQL on Windows",
        shortTitle: "Installing MySQL on Windows",
        readingTime: 12,
        tags: ["mysql", "database", "sql", "mysql setup", "database administration"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Step-by-step guide to downloading, installing, and configuring MySQL on a Windows operating system.",
        prerequisites: ["mysql-how-mysql-works", "mysql-mysql-vs-sql-understanding-the-difference"],
        related: ["mysql-installing-mysql-on-linux-and-macos", "mysql-how-mysql-works"],
        recommended: ["mysql-installing-mysql-on-linux-and-macos", "mysql-mysql-server-client-and-workbench"]
      },
      {
        id: 5,
        order: 5,
        slug: "mysql-installing-mysql-on-linux-and-macos",
        title: "Installing MySQL on Linux and macOS",
        shortTitle: "Installing MySQL on Linux an...",
        readingTime: 13,
        tags: ["mysql", "database", "sql", "mysql setup", "database administration"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to set up and configure MySQL on Linux distributions and macOS environments.",
        prerequisites: ["mysql-installing-mysql-on-windows", "mysql-how-mysql-works"],
        related: ["mysql-mysql-server-client-and-workbench", "mysql-installing-mysql-on-windows"],
        recommended: ["mysql-mysql-server-client-and-workbench", "mysql-connecting-to-mysql"]
      },
      {
        id: 6,
        order: 6,
        slug: "mysql-mysql-server-client-and-workbench",
        title: "MySQL Server, Client, and Workbench",
        shortTitle: "MySQL Server, Client, and Wo...",
        readingTime: 14,
        tags: ["mysql", "database", "sql", "mysql setup", "database administration"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the different components of the MySQL ecosystem, including the server daemon, command-line client, and GUI Workbench.",
        prerequisites: ["mysql-installing-mysql-on-linux-and-macos", "mysql-installing-mysql-on-windows"],
        related: ["mysql-connecting-to-mysql", "mysql-installing-mysql-on-linux-and-macos"],
        recommended: ["mysql-connecting-to-mysql", "mysql-your-first-mysql-database-and-query"]
      },
      {
        id: 7,
        order: 7,
        slug: "mysql-connecting-to-mysql",
        title: "Connecting to MySQL",
        shortTitle: "Connecting to MySQL",
        readingTime: 15,
        tags: ["mysql", "database", "sql", "mysql setup", "database administration"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to establish secure connections to your MySQL server using various clients and connection strings.",
        prerequisites: ["mysql-mysql-server-client-and-workbench", "mysql-installing-mysql-on-linux-and-macos"],
        related: ["mysql-your-first-mysql-database-and-query", "mysql-mysql-server-client-and-workbench"],
        recommended: ["mysql-your-first-mysql-database-and-query", "mysql-creating-and-managing-databases"]
      },
      {
        id: 8,
        order: 8,
        slug: "mysql-your-first-mysql-database-and-query",
        title: "Your First MySQL Database and Query",
        shortTitle: "Your First MySQL Database an...",
        readingTime: 8,
        tags: ["mysql", "database", "sql", "mysql fundamentals", "relational database"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Write your very first SQL query to create a database and retrieve data, getting hands-on experience immediately.",
        prerequisites: ["mysql-connecting-to-mysql", "mysql-mysql-server-client-and-workbench"],
        related: ["mysql-connecting-to-mysql", "mysql-creating-and-managing-databases"],
        recommended: ["mysql-creating-and-managing-databases", "mysql-understanding-tables-rows-and-columns"]
      }
    ]
  },
  {
    id: "databases-tables-and-data-types",
    title: "Databases, Tables, and Data Types",
    order: 2,
    difficulty: "Beginner",
    lessons: [
      {
        id: 9,
        order: 1,
        slug: "mysql-creating-and-managing-databases",
        title: "Creating and Managing Databases",
        shortTitle: "Creating and Managing Databa...",
        readingTime: 9,
        tags: ["mysql", "database", "sql", "database design", "sql fundamentals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the CREATE, ALTER, and DROP commands for managing database schemas in MySQL.",
        prerequisites: ["mysql-your-first-mysql-database-and-query", "mysql-connecting-to-mysql"],
        related: ["mysql-understanding-tables-rows-and-columns", "mysql-your-first-mysql-database-and-query"],
        recommended: ["mysql-understanding-tables-rows-and-columns", "mysql-creating-tables-with-create-table"]
      },
      {
        id: 10,
        order: 2,
        slug: "mysql-understanding-tables-rows-and-columns",
        title: "Understanding Tables, Rows, and Columns",
        shortTitle: "Understanding Tables, Rows, ...",
        readingTime: 10,
        tags: ["mysql", "database", "sql", "database design", "sql fundamentals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Grasp the fundamental structure of relational databases: how tables organize data into rows and columns.",
        prerequisites: ["mysql-creating-and-managing-databases", "mysql-your-first-mysql-database-and-query"],
        related: ["mysql-creating-tables-with-create-table", "mysql-creating-and-managing-databases"],
        recommended: ["mysql-creating-tables-with-create-table", "mysql-mysql-data-types"]
      },
      {
        id: 11,
        order: 3,
        slug: "mysql-creating-tables-with-create-table",
        title: "Creating Tables with CREATE TABLE",
        shortTitle: "Creating Tables with CREATE ...",
        readingTime: 11,
        tags: ["mysql", "database", "sql", "database design", "sql fundamentals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn the syntax and best practices for defining new tables and their structures in MySQL.",
        prerequisites: ["mysql-understanding-tables-rows-and-columns", "mysql-creating-and-managing-databases"],
        related: ["mysql-mysql-data-types", "mysql-understanding-tables-rows-and-columns"],
        recommended: ["mysql-mysql-data-types", "mysql-numeric-data-types"]
      },
      {
        id: 12,
        order: 4,
        slug: "mysql-mysql-data-types",
        title: "MySQL Data Types",
        shortTitle: "MySQL Data Types",
        readingTime: 12,
        tags: ["mysql", "database", "sql", "mysql data types", "database design"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get a high-level overview of the various data types available in MySQL and how to choose the right one.",
        prerequisites: ["mysql-creating-tables-with-create-table", "mysql-understanding-tables-rows-and-columns"],
        related: ["mysql-numeric-data-types", "mysql-creating-tables-with-create-table"],
        recommended: ["mysql-numeric-data-types", "mysql-string-and-text-data-types"]
      },
      {
        id: 13,
        order: 5,
        slug: "mysql-numeric-data-types",
        title: "Numeric Data Types",
        shortTitle: "Numeric Data Types",
        readingTime: 13,
        tags: ["mysql", "database", "sql", "mysql data types", "database design"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Deep dive into INT, DECIMAL, FLOAT, and other numeric data types for storing precise mathematical values.",
        prerequisites: ["mysql-mysql-data-types", "mysql-creating-tables-with-create-table"],
        related: ["mysql-string-and-text-data-types", "mysql-mysql-data-types"],
        recommended: ["mysql-string-and-text-data-types", "mysql-date-and-time-data-types"]
      },
      {
        id: 14,
        order: 6,
        slug: "mysql-string-and-text-data-types",
        title: "String and Text Data Types",
        shortTitle: "String and Text Data Types",
        readingTime: 14,
        tags: ["mysql", "database", "sql", "mysql data types", "database design"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the differences between CHAR, VARCHAR, TEXT, and other string storage options in MySQL.",
        prerequisites: ["mysql-numeric-data-types", "mysql-mysql-data-types"],
        related: ["mysql-date-and-time-data-types", "mysql-numeric-data-types"],
        recommended: ["mysql-date-and-time-data-types", "mysql-boolean-enum-json-and-other-useful-types"]
      },
      {
        id: 15,
        order: 7,
        slug: "mysql-date-and-time-data-types",
        title: "Date and Time Data Types",
        shortTitle: "Date and Time Data Types",
        readingTime: 15,
        tags: ["mysql", "database", "sql", "mysql data types", "database design"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to store and manipulate dates and times using DATE, TIME, DATETIME, and TIMESTAMP.",
        prerequisites: ["mysql-string-and-text-data-types", "mysql-numeric-data-types"],
        related: ["mysql-boolean-enum-json-and-other-useful-types", "mysql-string-and-text-data-types"],
        recommended: ["mysql-boolean-enum-json-and-other-useful-types", "mysql-the-select-statement"]
      },
      {
        id: 16,
        order: 8,
        slug: "mysql-boolean-enum-json-and-other-useful-types",
        title: "Boolean, ENUM, JSON, and Other Useful Types",
        shortTitle: "Boolean, ENUM, JSON, and Oth...",
        readingTime: 8,
        tags: ["mysql", "database", "sql", "mysql data types", "database design"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore specialized data types like BOOLEAN, ENUM, SET, and the powerful JSON data type.",
        prerequisites: ["mysql-date-and-time-data-types", "mysql-string-and-text-data-types"],
        related: ["mysql-date-and-time-data-types", "mysql-the-select-statement"],
        recommended: ["mysql-the-select-statement", "mysql-selecting-specific-columns"]
      }
    ]
  },
  {
    id: "basic-sql-queries",
    title: "Basic SQL Queries",
    order: 3,
    difficulty: "Beginner",
    lessons: [
      {
        id: 17,
        order: 1,
        slug: "mysql-the-select-statement",
        title: "The SELECT Statement",
        shortTitle: "The SELECT Statement",
        readingTime: 9,
        tags: ["mysql", "database", "sql", "sql queries", "data retrieval"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the foundational SELECT statement used to retrieve data from one or more tables.",
        prerequisites: ["mysql-boolean-enum-json-and-other-useful-types", "mysql-date-and-time-data-types"],
        related: ["mysql-selecting-specific-columns", "mysql-boolean-enum-json-and-other-useful-types"],
        recommended: ["mysql-selecting-specific-columns", "mysql-distinct-values"]
      },
      {
        id: 18,
        order: 2,
        slug: "mysql-selecting-specific-columns",
        title: "Selecting Specific Columns",
        shortTitle: "Selecting Specific Columns",
        readingTime: 10,
        tags: ["mysql", "database", "sql", "sql queries", "data retrieval"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to optimize your queries by selecting only the specific columns you need, rather than using SELECT *.",
        prerequisites: ["mysql-the-select-statement", "mysql-boolean-enum-json-and-other-useful-types"],
        related: ["mysql-distinct-values", "mysql-the-select-statement"],
        recommended: ["mysql-distinct-values", "mysql-filtering-data-with-where"]
      },
      {
        id: 19,
        order: 3,
        slug: "mysql-distinct-values",
        title: "DISTINCT Values",
        shortTitle: "DISTINCT Values",
        readingTime: 11,
        tags: ["mysql", "database", "sql", "sql queries", "data retrieval"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how to use the DISTINCT keyword to eliminate duplicate rows from your query results.",
        prerequisites: ["mysql-selecting-specific-columns", "mysql-the-select-statement"],
        related: ["mysql-filtering-data-with-where", "mysql-selecting-specific-columns"],
        recommended: ["mysql-filtering-data-with-where", "mysql-comparison-and-logical-operators"]
      },
      {
        id: 20,
        order: 4,
        slug: "mysql-filtering-data-with-where",
        title: "Filtering Data with WHERE",
        shortTitle: "Filtering Data with WHERE",
        readingTime: 12,
        tags: ["mysql", "database", "sql", "sql queries", "data retrieval"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to filter query results based on specific conditions using the WHERE clause.",
        prerequisites: ["mysql-distinct-values", "mysql-selecting-specific-columns"],
        related: ["mysql-comparison-and-logical-operators", "mysql-distinct-values"],
        recommended: ["mysql-comparison-and-logical-operators", "mysql-in-between-and-like"]
      },
      {
        id: 21,
        order: 5,
        slug: "mysql-comparison-and-logical-operators",
        title: "Comparison and Logical Operators",
        shortTitle: "Comparison and Logical Opera...",
        readingTime: 13,
        tags: ["mysql", "database", "sql", "sql queries", "data retrieval"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master operators like =, <>, >, <, AND, OR, and NOT to build complex filtering conditions.",
        prerequisites: ["mysql-filtering-data-with-where", "mysql-distinct-values"],
        related: ["mysql-in-between-and-like", "mysql-filtering-data-with-where"],
        recommended: ["mysql-in-between-and-like", "mysql-null-and-is-null"]
      },
      {
        id: 22,
        order: 6,
        slug: "mysql-in-between-and-like",
        title: "IN, BETWEEN, and LIKE",
        shortTitle: "IN, BETWEEN, and LIKE",
        readingTime: 14,
        tags: ["mysql", "database", "sql", "sql queries", "data retrieval"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore powerful filtering operators for matching lists of values, ranges, and pattern matching with wildcards.",
        prerequisites: ["mysql-comparison-and-logical-operators", "mysql-filtering-data-with-where"],
        related: ["mysql-null-and-is-null", "mysql-comparison-and-logical-operators"],
        recommended: ["mysql-null-and-is-null", "mysql-sorting-and-limiting-results-with-order-by-and-limit"]
      },
      {
        id: 23,
        order: 7,
        slug: "mysql-null-and-is-null",
        title: "NULL and IS NULL",
        shortTitle: "NULL and IS NULL",
        readingTime: 15,
        tags: ["mysql", "database", "sql", "sql queries", "data retrieval"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the concept of NULL in SQL and how to properly check for missing or unknown values.",
        prerequisites: ["mysql-in-between-and-like", "mysql-comparison-and-logical-operators"],
        related: ["mysql-sorting-and-limiting-results-with-order-by-and-limit", "mysql-in-between-and-like"],
        recommended: ["mysql-sorting-and-limiting-results-with-order-by-and-limit", "mysql-insert-into"]
      },
      {
        id: 24,
        order: 8,
        slug: "mysql-sorting-and-limiting-results-with-order-by-and-limit",
        title: "Sorting and Limiting Results with ORDER BY and LIMIT",
        shortTitle: "Sorting and Limiting Results...",
        readingTime: 8,
        tags: ["mysql", "database", "sql", "sql queries", "data retrieval"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to sort your query results and restrict the number of rows returned for pagination or top-N queries.",
        prerequisites: ["mysql-null-and-is-null", "mysql-in-between-and-like"],
        related: ["mysql-null-and-is-null", "mysql-insert-into"],
        recommended: ["mysql-insert-into", "mysql-inserting-multiple-rows"]
      }
    ]
  },
  {
    id: "inserting-updating-and-deleting-data",
    title: "Inserting, Updating, and Deleting Data",
    order: 4,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 25,
        order: 1,
        slug: "mysql-insert-into",
        title: "INSERT INTO",
        shortTitle: "INSERT INTO",
        readingTime: 9,
        tags: ["mysql", "database", "sql", "data manipulation", "crud operations"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the basic syntax for adding new rows of data into your MySQL tables.",
        prerequisites: ["mysql-sorting-and-limiting-results-with-order-by-and-limit", "mysql-null-and-is-null"],
        related: ["mysql-inserting-multiple-rows", "mysql-sorting-and-limiting-results-with-order-by-and-limit"],
        recommended: ["mysql-inserting-multiple-rows", "mysql-insert-into-select"]
      },
      {
        id: 26,
        order: 2,
        slug: "mysql-inserting-multiple-rows",
        title: "Inserting Multiple Rows",
        shortTitle: "Inserting Multiple Rows",
        readingTime: 10,
        tags: ["mysql", "database", "sql", "data manipulation", "crud operations"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to efficiently insert multiple records in a single INSERT statement to improve performance.",
        prerequisites: ["mysql-insert-into", "mysql-sorting-and-limiting-results-with-order-by-and-limit"],
        related: ["mysql-insert-into-select", "mysql-insert-into"],
        recommended: ["mysql-insert-into-select", "mysql-updating-data-with-update"]
      },
      {
        id: 27,
        order: 3,
        slug: "mysql-insert-into-select",
        title: "INSERT INTO SELECT",
        shortTitle: "INSERT INTO SELECT",
        readingTime: 11,
        tags: ["mysql", "database", "sql", "data manipulation", "crud operations"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how to copy data from one table and insert it into another using a single query.",
        prerequisites: ["mysql-inserting-multiple-rows", "mysql-insert-into"],
        related: ["mysql-updating-data-with-update", "mysql-inserting-multiple-rows"],
        recommended: ["mysql-updating-data-with-update", "mysql-update-with-conditions"]
      },
      {
        id: 28,
        order: 4,
        slug: "mysql-updating-data-with-update",
        title: "Updating Data with UPDATE",
        shortTitle: "Updating Data with UPDATE",
        readingTime: 12,
        tags: ["mysql", "database", "sql", "data manipulation", "crud operations"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to modify existing records in your database using the UPDATE statement.",
        prerequisites: ["mysql-insert-into-select", "mysql-inserting-multiple-rows"],
        related: ["mysql-update-with-conditions", "mysql-insert-into-select"],
        recommended: ["mysql-update-with-conditions", "mysql-deleting-data-with-delete"]
      },
      {
        id: 29,
        order: 5,
        slug: "mysql-update-with-conditions",
        title: "UPDATE with Conditions",
        shortTitle: "UPDATE with Conditions",
        readingTime: 13,
        tags: ["mysql", "database", "sql", "data manipulation", "crud operations"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the critical importance of the WHERE clause when updating data to avoid accidental mass updates.",
        prerequisites: ["mysql-updating-data-with-update", "mysql-insert-into-select"],
        related: ["mysql-deleting-data-with-delete", "mysql-updating-data-with-update"],
        recommended: ["mysql-deleting-data-with-delete", "mysql-truncate-vs-delete-vs-drop"]
      },
      {
        id: 30,
        order: 6,
        slug: "mysql-deleting-data-with-delete",
        title: "Deleting Data with DELETE",
        shortTitle: "Deleting Data with DELETE",
        readingTime: 14,
        tags: ["mysql", "database", "sql", "data manipulation", "crud operations"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to safely remove specific rows from a table using the DELETE statement.",
        prerequisites: ["mysql-update-with-conditions", "mysql-updating-data-with-update"],
        related: ["mysql-truncate-vs-delete-vs-drop", "mysql-update-with-conditions"],
        recommended: ["mysql-truncate-vs-delete-vs-drop", "mysql-handling-duplicates-with-insert-ignore-and-on-duplicate-key-update"]
      },
      {
        id: 31,
        order: 7,
        slug: "mysql-truncate-vs-delete-vs-drop",
        title: "TRUNCATE vs DELETE vs DROP",
        shortTitle: "TRUNCATE vs DELETE vs DROP",
        readingTime: 15,
        tags: ["mysql", "database", "sql", "data manipulation", "crud operations"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the crucial differences between these three commands and when to use each for data removal.",
        prerequisites: ["mysql-deleting-data-with-delete", "mysql-update-with-conditions"],
        related: ["mysql-handling-duplicates-with-insert-ignore-and-on-duplicate-key-update", "mysql-deleting-data-with-delete"],
        recommended: ["mysql-handling-duplicates-with-insert-ignore-and-on-duplicate-key-update", "mysql-understanding-mysql-functions"]
      },
      {
        id: 32,
        order: 8,
        slug: "mysql-handling-duplicates-with-insert-ignore-and-on-duplicate-key-update",
        title: "Handling Duplicates with INSERT IGNORE and ON DUPLICATE KEY UPDATE",
        shortTitle: "Handling Duplicates with INS...",
        readingTime: 8,
        tags: ["mysql", "database", "sql", "data manipulation", "crud operations"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master advanced insertion techniques to gracefully handle primary key or unique constraint violations.",
        prerequisites: ["mysql-truncate-vs-delete-vs-drop", "mysql-deleting-data-with-delete"],
        related: ["mysql-truncate-vs-delete-vs-drop", "mysql-understanding-mysql-functions"],
        recommended: ["mysql-understanding-mysql-functions", "mysql-aggregate-functions-count-sum-avg-min-and-max"]
      }
    ]
  },
  {
    id: "sql-functions-and-data-transformation",
    title: "SQL Functions and Data Transformation",
    order: 5,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 33,
        order: 1,
        slug: "mysql-understanding-mysql-functions",
        title: "Understanding MySQL Functions",
        shortTitle: "Understanding MySQL Functions",
        readingTime: 9,
        tags: ["mysql", "database", "sql", "sql functions", "data transformation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get an overview of built-in MySQL functions that allow you to manipulate and transform data directly in your queries.",
        prerequisites: ["mysql-handling-duplicates-with-insert-ignore-and-on-duplicate-key-update", "mysql-truncate-vs-delete-vs-drop"],
        related: ["mysql-aggregate-functions-count-sum-avg-min-and-max", "mysql-handling-duplicates-with-insert-ignore-and-on-duplicate-key-update"],
        recommended: ["mysql-aggregate-functions-count-sum-avg-min-and-max", "mysql-group-by"]
      },
      {
        id: 34,
        order: 2,
        slug: "mysql-aggregate-functions-count-sum-avg-min-and-max",
        title: "Aggregate Functions: COUNT, SUM, AVG, MIN, and MAX",
        shortTitle: "Aggregate Functions COUNT, S...",
        readingTime: 10,
        tags: ["mysql", "database", "sql", "sql functions", "data transformation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to perform calculations on a set of values to return a single summary value.",
        prerequisites: ["mysql-understanding-mysql-functions", "mysql-handling-duplicates-with-insert-ignore-and-on-duplicate-key-update"],
        related: ["mysql-group-by", "mysql-understanding-mysql-functions"],
        recommended: ["mysql-group-by", "mysql-having"]
      },
      {
        id: 35,
        order: 3,
        slug: "mysql-group-by",
        title: "GROUP BY",
        shortTitle: "GROUP BY",
        readingTime: 11,
        tags: ["mysql", "database", "sql", "sql functions", "data transformation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how to group rows that have the same values into summary rows, typically used with aggregate functions.",
        prerequisites: ["mysql-aggregate-functions-count-sum-avg-min-and-max", "mysql-understanding-mysql-functions"],
        related: ["mysql-having", "mysql-aggregate-functions-count-sum-avg-min-and-max"],
        recommended: ["mysql-having", "mysql-string-functions"]
      },
      {
        id: 36,
        order: 4,
        slug: "mysql-having",
        title: "HAVING",
        shortTitle: "HAVING",
        readingTime: 12,
        tags: ["mysql", "database", "sql", "sql functions", "data transformation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to filter grouped results, serving as the WHERE clause equivalent for GROUP BY operations.",
        prerequisites: ["mysql-group-by", "mysql-aggregate-functions-count-sum-avg-min-and-max"],
        related: ["mysql-string-functions", "mysql-group-by"],
        recommended: ["mysql-string-functions", "mysql-numeric-and-mathematical-functions"]
      },
      {
        id: 37,
        order: 5,
        slug: "mysql-string-functions",
        title: "String Functions",
        shortTitle: "String Functions",
        readingTime: 13,
        tags: ["mysql", "database", "sql", "sql functions", "data transformation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore functions like CONCAT, SUBSTRING, LENGTH, and REPLACE for manipulating text data.",
        prerequisites: ["mysql-having", "mysql-group-by"],
        related: ["mysql-numeric-and-mathematical-functions", "mysql-having"],
        recommended: ["mysql-numeric-and-mathematical-functions", "mysql-date-and-time-functions"]
      },
      {
        id: 38,
        order: 6,
        slug: "mysql-numeric-and-mathematical-functions",
        title: "Numeric and Mathematical Functions",
        shortTitle: "Numeric and Mathematical Fun...",
        readingTime: 14,
        tags: ["mysql", "database", "sql", "sql functions", "data transformation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover built-in functions for rounding, absolute values, and other mathematical operations.",
        prerequisites: ["mysql-string-functions", "mysql-having"],
        related: ["mysql-date-and-time-functions", "mysql-string-functions"],
        recommended: ["mysql-date-and-time-functions", "mysql-case-ifnull-coalesce-and-conditional-expressions"]
      },
      {
        id: 39,
        order: 7,
        slug: "mysql-date-and-time-functions",
        title: "Date and Time Functions",
        shortTitle: "Date and Time Functions",
        readingTime: 15,
        tags: ["mysql", "database", "sql", "sql functions", "data transformation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to extract, format, and calculate differences between dates and times using MySQL functions.",
        prerequisites: ["mysql-numeric-and-mathematical-functions", "mysql-string-functions"],
        related: ["mysql-case-ifnull-coalesce-and-conditional-expressions", "mysql-numeric-and-mathematical-functions"],
        recommended: ["mysql-case-ifnull-coalesce-and-conditional-expressions", "mysql-understanding-sql-joins"]
      },
      {
        id: 40,
        order: 8,
        slug: "mysql-case-ifnull-coalesce-and-conditional-expressions",
        title: "CASE, IFNULL, COALESCE, and Conditional Expressions",
        shortTitle: "CASE, IFNULL, COALESCE, and ...",
        readingTime: 8,
        tags: ["mysql", "database", "sql", "sql functions", "data transformation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master conditional logic within your SQL queries to handle nulls and implement if-then-else logic.",
        prerequisites: ["mysql-date-and-time-functions", "mysql-numeric-and-mathematical-functions"],
        related: ["mysql-date-and-time-functions", "mysql-understanding-sql-joins"],
        recommended: ["mysql-understanding-sql-joins", "mysql-inner-join"]
      }
    ]
  },
  {
    id: "joins-and-combining-data",
    title: "Joins and Combining Data",
    order: 6,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 41,
        order: 1,
        slug: "mysql-understanding-sql-joins",
        title: "Understanding SQL Joins",
        shortTitle: "Understanding SQL Joins",
        readingTime: 9,
        tags: ["mysql", "database", "sql", "sql joins", "relational database"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get a comprehensive introduction to how SQL joins combine rows from two or more tables based on a related column.",
        prerequisites: ["mysql-case-ifnull-coalesce-and-conditional-expressions", "mysql-date-and-time-functions"],
        related: ["mysql-inner-join", "mysql-case-ifnull-coalesce-and-conditional-expressions"],
        recommended: ["mysql-inner-join", "mysql-left-join"]
      },
      {
        id: 42,
        order: 2,
        slug: "mysql-inner-join",
        title: "INNER JOIN",
        shortTitle: "INNER JOIN",
        readingTime: 10,
        tags: ["mysql", "database", "sql", "sql joins", "relational database"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to retrieve records that have matching values in both tables being joined.",
        prerequisites: ["mysql-understanding-sql-joins", "mysql-case-ifnull-coalesce-and-conditional-expressions"],
        related: ["mysql-left-join", "mysql-understanding-sql-joins"],
        recommended: ["mysql-left-join", "mysql-right-join"]
      },
      {
        id: 43,
        order: 3,
        slug: "mysql-left-join",
        title: "LEFT JOIN",
        shortTitle: "LEFT JOIN",
        readingTime: 11,
        tags: ["mysql", "database", "sql", "sql joins", "relational database"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how to return all records from the left table, and the matched records from the right table.",
        prerequisites: ["mysql-inner-join", "mysql-understanding-sql-joins"],
        related: ["mysql-right-join", "mysql-inner-join"],
        recommended: ["mysql-right-join", "mysql-cross-join"]
      },
      {
        id: 44,
        order: 4,
        slug: "mysql-right-join",
        title: "RIGHT JOIN",
        shortTitle: "RIGHT JOIN",
        readingTime: 12,
        tags: ["mysql", "database", "sql", "sql joins", "relational database"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to return all records from the right table, and the matched records from the left table.",
        prerequisites: ["mysql-left-join", "mysql-inner-join"],
        related: ["mysql-cross-join", "mysql-left-join"],
        recommended: ["mysql-cross-join", "mysql-self-join"]
      },
      {
        id: 45,
        order: 5,
        slug: "mysql-cross-join",
        title: "CROSS JOIN",
        shortTitle: "CROSS JOIN",
        readingTime: 13,
        tags: ["mysql", "database", "sql", "sql joins", "relational database"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the Cartesian product of two tables, returning all possible combinations of rows.",
        prerequisites: ["mysql-right-join", "mysql-left-join"],
        related: ["mysql-self-join", "mysql-right-join"],
        recommended: ["mysql-self-join", "mysql-joining-multiple-tables"]
      },
      {
        id: 46,
        order: 6,
        slug: "mysql-self-join",
        title: "SELF JOIN",
        shortTitle: "SELF JOIN",
        readingTime: 14,
        tags: ["mysql", "database", "sql", "sql joins", "relational database"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how to join a table to itself, useful for querying hierarchical data or comparing rows within the same table.",
        prerequisites: ["mysql-cross-join", "mysql-right-join"],
        related: ["mysql-joining-multiple-tables", "mysql-cross-join"],
        recommended: ["mysql-joining-multiple-tables", "mysql-update-join-and-delete-join"]
      },
      {
        id: 47,
        order: 7,
        slug: "mysql-joining-multiple-tables",
        title: "Joining Multiple Tables",
        shortTitle: "Joining Multiple Tables",
        readingTime: 15,
        tags: ["mysql", "database", "sql", "sql joins", "relational database"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to chain multiple JOIN clauses together to retrieve data from three or more related tables.",
        prerequisites: ["mysql-self-join", "mysql-cross-join"],
        related: ["mysql-update-join-and-delete-join", "mysql-self-join"],
        recommended: ["mysql-update-join-and-delete-join", "mysql-introduction-to-subqueries"]
      },
      {
        id: 48,
        order: 8,
        slug: "mysql-update-join-and-delete-join",
        title: "UPDATE JOIN and DELETE JOIN",
        shortTitle: "UPDATE JOIN and DELETE JOIN",
        readingTime: 8,
        tags: ["mysql", "database", "sql", "sql joins", "relational database"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master advanced techniques for updating or deleting records in one table based on conditions in a joined table.",
        prerequisites: ["mysql-joining-multiple-tables", "mysql-self-join"],
        related: ["mysql-joining-multiple-tables", "mysql-introduction-to-subqueries"],
        recommended: ["mysql-introduction-to-subqueries", "mysql-scalar-and-single-row-subqueries"]
      }
    ]
  },
  {
    id: "subqueries-set-operations-and-ctes",
    title: "Subqueries, Set Operations, and CTEs",
    order: 7,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 49,
        order: 1,
        slug: "mysql-introduction-to-subqueries",
        title: "Introduction to Subqueries",
        shortTitle: "Introduction to Subqueries",
        readingTime: 9,
        tags: ["mysql", "database", "sql", "advanced sql", "subqueries"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to subqueries (nested queries) and how they can be used within SELECT, INSERT, UPDATE, or DELETE statements.",
        prerequisites: ["mysql-update-join-and-delete-join", "mysql-joining-multiple-tables"],
        related: ["mysql-scalar-and-single-row-subqueries", "mysql-update-join-and-delete-join"],
        recommended: ["mysql-scalar-and-single-row-subqueries", "mysql-multi-row-subqueries-with-in-any-and-all"]
      },
      {
        id: 50,
        order: 2,
        slug: "mysql-scalar-and-single-row-subqueries",
        title: "Scalar and Single-Row Subqueries",
        shortTitle: "Scalar and Single-Row Subque...",
        readingTime: 10,
        tags: ["mysql", "database", "sql", "advanced sql", "subqueries"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to write subqueries that return exactly one column and one row, often used in WHERE clauses.",
        prerequisites: ["mysql-introduction-to-subqueries", "mysql-update-join-and-delete-join"],
        related: ["mysql-multi-row-subqueries-with-in-any-and-all", "mysql-introduction-to-subqueries"],
        recommended: ["mysql-multi-row-subqueries-with-in-any-and-all", "mysql-correlated-subqueries"]
      },
      {
        id: 51,
        order: 3,
        slug: "mysql-multi-row-subqueries-with-in-any-and-all",
        title: "Multi-Row Subqueries with IN, ANY, and ALL",
        shortTitle: "Multi-Row Subqueries with IN...",
        readingTime: 11,
        tags: ["mysql", "database", "sql", "advanced sql", "subqueries"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how to handle subqueries that return multiple rows using specialized comparison operators.",
        prerequisites: ["mysql-scalar-and-single-row-subqueries", "mysql-introduction-to-subqueries"],
        related: ["mysql-correlated-subqueries", "mysql-scalar-and-single-row-subqueries"],
        recommended: ["mysql-correlated-subqueries", "mysql-exists-and-not-exists"]
      },
      {
        id: 52,
        order: 4,
        slug: "mysql-correlated-subqueries",
        title: "Correlated Subqueries",
        shortTitle: "Correlated Subqueries",
        readingTime: 12,
        tags: ["mysql", "database", "sql", "advanced sql", "subqueries"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore subqueries that reference columns from the outer query, executing once for each row processed by the outer query.",
        prerequisites: ["mysql-multi-row-subqueries-with-in-any-and-all", "mysql-scalar-and-single-row-subqueries"],
        related: ["mysql-exists-and-not-exists", "mysql-multi-row-subqueries-with-in-any-and-all"],
        recommended: ["mysql-exists-and-not-exists", "mysql-union-and-union-all"]
      },
      {
        id: 53,
        order: 5,
        slug: "mysql-exists-and-not-exists",
        title: "EXISTS and NOT EXISTS",
        shortTitle: "EXISTS and NOT EXISTS",
        readingTime: 13,
        tags: ["mysql", "database", "sql", "advanced sql", "subqueries"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to use EXISTS to test for the existence of any record in a subquery, often more efficient than IN.",
        prerequisites: ["mysql-correlated-subqueries", "mysql-multi-row-subqueries-with-in-any-and-all"],
        related: ["mysql-union-and-union-all", "mysql-correlated-subqueries"],
        recommended: ["mysql-union-and-union-all", "mysql-intersect-and-except"]
      },
      {
        id: 54,
        order: 6,
        slug: "mysql-union-and-union-all",
        title: "UNION and UNION ALL",
        shortTitle: "UNION and UNION ALL",
        readingTime: 14,
        tags: ["mysql", "database", "sql", "advanced sql", "complex queries"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how to combine the result sets of two or more SELECT statements vertically.",
        prerequisites: ["mysql-exists-and-not-exists", "mysql-correlated-subqueries"],
        related: ["mysql-intersect-and-except", "mysql-exists-and-not-exists"],
        recommended: ["mysql-intersect-and-except", "mysql-common-table-expressions-ctes"]
      },
      {
        id: 55,
        order: 7,
        slug: "mysql-intersect-and-except",
        title: "INTERSECT and EXCEPT",
        shortTitle: "INTERSECT and EXCEPT",
        readingTime: 15,
        tags: ["mysql", "database", "sql", "advanced sql", "complex queries"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn set operations for finding common rows or differences between two query result sets.",
        prerequisites: ["mysql-union-and-union-all", "mysql-exists-and-not-exists"],
        related: ["mysql-common-table-expressions-ctes", "mysql-union-and-union-all"],
        recommended: ["mysql-common-table-expressions-ctes", "mysql-understanding-database-relationships"]
      },
      {
        id: 56,
        order: 8,
        slug: "mysql-common-table-expressions-ctes",
        title: "Common Table Expressions (CTEs)",
        shortTitle: "Common Table Expressions (CT...",
        readingTime: 8,
        tags: ["mysql", "database", "sql", "advanced sql", "complex queries"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the WITH clause to create temporary, named result sets that improve query readability and maintainability.",
        prerequisites: ["mysql-intersect-and-except", "mysql-union-and-union-all"],
        related: ["mysql-intersect-and-except", "mysql-understanding-database-relationships"],
        recommended: ["mysql-understanding-database-relationships", "mysql-primary-keys"]
      }
    ]
  },
  {
    id: "database-design-and-constraints",
    title: "Database Design and Constraints",
    order: 8,
    difficulty: "Advanced",
    lessons: [
      {
        id: 57,
        order: 1,
        slug: "mysql-understanding-database-relationships",
        title: "Understanding Database Relationships",
        shortTitle: "Understanding Database Relat...",
        readingTime: 9,
        tags: ["mysql", "database", "sql", "database design", "data integrity"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn about one-to-one, one-to-many, and many-to-many relationships in relational database design.",
        prerequisites: ["mysql-common-table-expressions-ctes", "mysql-intersect-and-except"],
        related: ["mysql-primary-keys", "mysql-common-table-expressions-ctes"],
        recommended: ["mysql-primary-keys", "mysql-foreign-keys"]
      },
      {
        id: 58,
        order: 2,
        slug: "mysql-primary-keys",
        title: "Primary Keys",
        shortTitle: "Primary Keys",
        readingTime: 10,
        tags: ["mysql", "database", "sql", "database design", "data integrity"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the role of primary keys in uniquely identifying each record in a database table.",
        prerequisites: ["mysql-understanding-database-relationships", "mysql-common-table-expressions-ctes"],
        related: ["mysql-foreign-keys", "mysql-understanding-database-relationships"],
        recommended: ["mysql-foreign-keys", "mysql-unique-not-null-default-and-check-constraints"]
      },
      {
        id: 59,
        order: 3,
        slug: "mysql-foreign-keys",
        title: "Foreign Keys",
        shortTitle: "Foreign Keys",
        readingTime: 11,
        tags: ["mysql", "database", "sql", "database design", "data integrity"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how foreign keys establish and enforce links between data in two tables.",
        prerequisites: ["mysql-primary-keys", "mysql-understanding-database-relationships"],
        related: ["mysql-unique-not-null-default-and-check-constraints", "mysql-primary-keys"],
        recommended: ["mysql-unique-not-null-default-and-check-constraints", "mysql-composite-keys"]
      },
      {
        id: 60,
        order: 4,
        slug: "mysql-unique-not-null-default-and-check-constraints",
        title: "UNIQUE, NOT NULL, DEFAULT, and CHECK Constraints",
        shortTitle: "UNIQUE, NOT NULL, DEFAULT, a...",
        readingTime: 12,
        tags: ["mysql", "database", "sql", "database design", "data integrity"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore various column-level constraints used to enforce data integrity and business rules.",
        prerequisites: ["mysql-foreign-keys", "mysql-primary-keys"],
        related: ["mysql-composite-keys", "mysql-foreign-keys"],
        recommended: ["mysql-composite-keys", "mysql-auto_increment-and-generated-values"]
      },
      {
        id: 61,
        order: 5,
        slug: "mysql-composite-keys",
        title: "Composite Keys",
        shortTitle: "Composite Keys",
        readingTime: 13,
        tags: ["mysql", "database", "sql", "database design", "data integrity"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how to use a combination of two or more columns to uniquely identify a record.",
        prerequisites: ["mysql-unique-not-null-default-and-check-constraints", "mysql-foreign-keys"],
        related: ["mysql-auto_increment-and-generated-values", "mysql-unique-not-null-default-and-check-constraints"],
        recommended: ["mysql-auto_increment-and-generated-values", "mysql-normalization-and-database-design"]
      },
      {
        id: 62,
        order: 6,
        slug: "mysql-auto_increment-and-generated-values",
        title: "AUTO_INCREMENT and Generated Values",
        shortTitle: "AUTO_INCREMENT and Generated...",
        readingTime: 14,
        tags: ["mysql", "database", "sql", "database design", "data integrity"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to automatically generate unique numeric identifiers for new rows.",
        prerequisites: ["mysql-composite-keys", "mysql-unique-not-null-default-and-check-constraints"],
        related: ["mysql-normalization-and-database-design", "mysql-composite-keys"],
        recommended: ["mysql-normalization-and-database-design", "mysql-cascading-actions-and-referential-integrity"]
      },
      {
        id: 63,
        order: 7,
        slug: "mysql-normalization-and-database-design",
        title: "Normalization and Database Design",
        shortTitle: "Normalization and Database D...",
        readingTime: 15,
        tags: ["mysql", "database", "sql", "database design", "data integrity"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the principles of database normalization (1NF, 2NF, 3NF) to reduce redundancy and improve data integrity.",
        prerequisites: ["mysql-auto_increment-and-generated-values", "mysql-composite-keys"],
        related: ["mysql-cascading-actions-and-referential-integrity", "mysql-auto_increment-and-generated-values"],
        recommended: ["mysql-cascading-actions-and-referential-integrity", "mysql-window-functions-in-mysql"]
      },
      {
        id: 64,
        order: 8,
        slug: "mysql-cascading-actions-and-referential-integrity",
        title: "Cascading Actions and Referential Integrity",
        shortTitle: "Cascading Actions and Refere...",
        readingTime: 8,
        tags: ["mysql", "database", "sql", "database design", "data integrity"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how ON DELETE and ON UPDATE CASCADE maintain consistency across related tables.",
        prerequisites: ["mysql-normalization-and-database-design", "mysql-auto_increment-and-generated-values"],
        related: ["mysql-normalization-and-database-design", "mysql-window-functions-in-mysql"],
        recommended: ["mysql-window-functions-in-mysql", "mysql-row_number-rank-and-dense_rank"]
      }
    ]
  },
  {
    id: "advanced-querying",
    title: "Advanced Querying",
    order: 9,
    difficulty: "Advanced",
    lessons: [
      {
        id: 65,
        order: 1,
        slug: "mysql-window-functions-in-mysql",
        title: "Window Functions in MySQL",
        shortTitle: "Window Functions in MySQL",
        readingTime: 9,
        tags: ["mysql", "database", "sql", "advanced sql", "window functions"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to window functions, which perform calculations across a set of table rows related to the current row.",
        prerequisites: ["mysql-cascading-actions-and-referential-integrity", "mysql-normalization-and-database-design"],
        related: ["mysql-row_number-rank-and-dense_rank", "mysql-cascading-actions-and-referential-integrity"],
        recommended: ["mysql-row_number-rank-and-dense_rank", "mysql-lead-and-lag"]
      },
      {
        id: 66,
        order: 2,
        slug: "mysql-row_number-rank-and-dense_rank",
        title: "ROW_NUMBER, RANK, and DENSE_RANK",
        shortTitle: "ROW_NUMBER, RANK, and DENSE_...",
        readingTime: 10,
        tags: ["mysql", "database", "sql", "advanced sql", "window functions"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to assign a unique rank or row number to each row within a partition of a result set.",
        prerequisites: ["mysql-window-functions-in-mysql", "mysql-cascading-actions-and-referential-integrity"],
        related: ["mysql-lead-and-lag", "mysql-window-functions-in-mysql"],
        recommended: ["mysql-lead-and-lag", "mysql-partition-by"]
      },
      {
        id: 67,
        order: 3,
        slug: "mysql-lead-and-lag",
        title: "LEAD and LAG",
        shortTitle: "LEAD and LAG",
        readingTime: 11,
        tags: ["mysql", "database", "sql", "advanced sql", "window functions"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how to access data from subsequent or preceding rows in the same result set without a self-join.",
        prerequisites: ["mysql-row_number-rank-and-dense_rank", "mysql-window-functions-in-mysql"],
        related: ["mysql-partition-by", "mysql-row_number-rank-and-dense_rank"],
        recommended: ["mysql-partition-by", "mysql-advanced-group-by-and-rollup"]
      },
      {
        id: 68,
        order: 4,
        slug: "mysql-partition-by",
        title: "PARTITION BY",
        shortTitle: "PARTITION BY",
        readingTime: 12,
        tags: ["mysql", "database", "sql", "advanced sql", "window functions"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how to divide the result set into partitions to which the window function is applied.",
        prerequisites: ["mysql-lead-and-lag", "mysql-row_number-rank-and-dense_rank"],
        related: ["mysql-advanced-group-by-and-rollup", "mysql-lead-and-lag"],
        recommended: ["mysql-advanced-group-by-and-rollup", "mysql-derived-tables"]
      },
      {
        id: 69,
        order: 5,
        slug: "mysql-advanced-group-by-and-rollup",
        title: "Advanced GROUP BY and ROLLUP",
        shortTitle: "Advanced GROUP BY and ROLLUP",
        readingTime: 13,
        tags: ["mysql", "database", "sql", "advanced sql", "data analysis"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to generate subtotals and grand totals in your grouped query results using ROLLUP.",
        prerequisites: ["mysql-partition-by", "mysql-lead-and-lag"],
        related: ["mysql-derived-tables", "mysql-partition-by"],
        recommended: ["mysql-derived-tables", "mysql-recursive-ctes"]
      },
      {
        id: 70,
        order: 6,
        slug: "mysql-derived-tables",
        title: "Derived Tables",
        shortTitle: "Derived Tables",
        readingTime: 14,
        tags: ["mysql", "database", "sql", "advanced sql", "complex queries"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the use of subqueries in the FROM clause to create temporary tables for complex queries.",
        prerequisites: ["mysql-advanced-group-by-and-rollup", "mysql-partition-by"],
        related: ["mysql-recursive-ctes", "mysql-advanced-group-by-and-rollup"],
        recommended: ["mysql-recursive-ctes", "mysql-writing-complex-sql-queries"]
      },
      {
        id: 71,
        order: 7,
        slug: "mysql-recursive-ctes",
        title: "Recursive CTEs",
        shortTitle: "Recursive CTEs",
        readingTime: 15,
        tags: ["mysql", "database", "sql", "advanced sql", "complex queries"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore how to use recursive Common Table Expressions to query hierarchical or tree-structured data.",
        prerequisites: ["mysql-derived-tables", "mysql-advanced-group-by-and-rollup"],
        related: ["mysql-writing-complex-sql-queries", "mysql-derived-tables"],
        recommended: ["mysql-writing-complex-sql-queries", "mysql-understanding-mysql-views"]
      },
      {
        id: 72,
        order: 8,
        slug: "mysql-writing-complex-sql-queries",
        title: "Writing Complex SQL Queries",
        shortTitle: "Writing Complex SQL Queries",
        readingTime: 8,
        tags: ["mysql", "database", "sql", "advanced sql", "complex queries"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Bring together joins, subqueries, window functions, and CTEs to solve advanced data retrieval challenges.",
        prerequisites: ["mysql-recursive-ctes", "mysql-derived-tables"],
        related: ["mysql-recursive-ctes", "mysql-understanding-mysql-views"],
        recommended: ["mysql-understanding-mysql-views", "mysql-creating-updating-and-dropping-views"]
      }
    ]
  },
  {
    id: "views-indexes-and-performance",
    title: "Views, Indexes, and Performance",
    order: 10,
    difficulty: "Advanced",
    lessons: [
      {
        id: 73,
        order: 1,
        slug: "mysql-understanding-mysql-views",
        title: "Understanding MySQL Views",
        shortTitle: "Understanding MySQL Views",
        readingTime: 9,
        tags: ["mysql", "database", "sql", "database performance", "query optimization"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn what views are and how they act as virtual tables based on the result set of an SQL statement.",
        prerequisites: ["mysql-writing-complex-sql-queries", "mysql-recursive-ctes"],
        related: ["mysql-creating-updating-and-dropping-views", "mysql-writing-complex-sql-queries"],
        recommended: ["mysql-creating-updating-and-dropping-views", "mysql-introduction-to-mysql-indexes"]
      },
      {
        id: 74,
        order: 2,
        slug: "mysql-creating-updating-and-dropping-views",
        title: "Creating, Updating, and Dropping Views",
        shortTitle: "Creating, Updating, and Drop...",
        readingTime: 10,
        tags: ["mysql", "database", "sql", "database performance", "query optimization"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the DDL commands for managing views and simplifying complex queries for end users.",
        prerequisites: ["mysql-understanding-mysql-views", "mysql-writing-complex-sql-queries"],
        related: ["mysql-introduction-to-mysql-indexes", "mysql-understanding-mysql-views"],
        recommended: ["mysql-introduction-to-mysql-indexes", "mysql-creating-and-managing-indexes"]
      },
      {
        id: 75,
        order: 3,
        slug: "mysql-introduction-to-mysql-indexes",
        title: "Introduction to MySQL Indexes",
        shortTitle: "Introduction to MySQL Indexes",
        readingTime: 11,
        tags: ["mysql", "database", "sql", "database performance", "query optimization"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get a foundational understanding of what indexes are and how they speed up data retrieval operations.",
        prerequisites: ["mysql-creating-updating-and-dropping-views", "mysql-understanding-mysql-views"],
        related: ["mysql-creating-and-managing-indexes", "mysql-creating-updating-and-dropping-views"],
        recommended: ["mysql-creating-and-managing-indexes", "mysql-composite-and-unique-indexes"]
      },
      {
        id: 76,
        order: 4,
        slug: "mysql-creating-and-managing-indexes",
        title: "Creating and Managing Indexes",
        shortTitle: "Creating and Managing Indexes",
        readingTime: 12,
        tags: ["mysql", "database", "sql", "database performance", "query optimization"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn the syntax for adding, viewing, and removing indexes on your database tables.",
        prerequisites: ["mysql-introduction-to-mysql-indexes", "mysql-creating-updating-and-dropping-views"],
        related: ["mysql-composite-and-unique-indexes", "mysql-introduction-to-mysql-indexes"],
        recommended: ["mysql-composite-and-unique-indexes", "mysql-how-indexes-improve-query-performance"]
      },
      {
        id: 77,
        order: 5,
        slug: "mysql-composite-and-unique-indexes",
        title: "Composite and Unique Indexes",
        shortTitle: "Composite and Unique Indexes",
        readingTime: 13,
        tags: ["mysql", "database", "sql", "database performance", "query optimization"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore how to create indexes on multiple columns and enforce uniqueness across a combination of columns.",
        prerequisites: ["mysql-creating-and-managing-indexes", "mysql-introduction-to-mysql-indexes"],
        related: ["mysql-how-indexes-improve-query-performance", "mysql-creating-and-managing-indexes"],
        recommended: ["mysql-how-indexes-improve-query-performance", "mysql-explain-and-query-execution-plans"]
      },
      {
        id: 78,
        order: 6,
        slug: "mysql-how-indexes-improve-query-performance",
        title: "How Indexes Improve Query Performance",
        shortTitle: "How Indexes Improve Query Pe...",
        readingTime: 14,
        tags: ["mysql", "database", "sql", "database performance", "query optimization"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the internal mechanics of B-Tree indexes and how they reduce disk I/O during query execution.",
        prerequisites: ["mysql-composite-and-unique-indexes", "mysql-creating-and-managing-indexes"],
        related: ["mysql-explain-and-query-execution-plans", "mysql-composite-and-unique-indexes"],
        recommended: ["mysql-explain-and-query-execution-plans", "mysql-mysql-query-optimization-basics"]
      },
      {
        id: 79,
        order: 7,
        slug: "mysql-explain-and-query-execution-plans",
        title: "EXPLAIN and Query Execution Plans",
        shortTitle: "EXPLAIN and Query Execution ...",
        readingTime: 15,
        tags: ["mysql", "database", "sql", "database performance", "query optimization"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to use the EXPLAIN statement to analyze how MySQL executes your queries and identify bottlenecks.",
        prerequisites: ["mysql-how-indexes-improve-query-performance", "mysql-composite-and-unique-indexes"],
        related: ["mysql-mysql-query-optimization-basics", "mysql-how-indexes-improve-query-performance"],
        recommended: ["mysql-mysql-query-optimization-basics", "mysql-understanding-mysql-transactions"]
      },
      {
        id: 80,
        order: 8,
        slug: "mysql-mysql-query-optimization-basics",
        title: "MySQL Query Optimization Basics",
        shortTitle: "MySQL Query Optimization Bas...",
        readingTime: 8,
        tags: ["mysql", "database", "sql", "database performance", "query optimization"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover fundamental strategies for rewriting queries and structuring tables to achieve optimal performance.",
        prerequisites: ["mysql-explain-and-query-execution-plans", "mysql-how-indexes-improve-query-performance"],
        related: ["mysql-explain-and-query-execution-plans", "mysql-understanding-mysql-transactions"],
        recommended: ["mysql-understanding-mysql-transactions", "mysql-commit-and-rollback"]
      }
    ]
  },
  {
    id: "transactions-stored-programs-and-automation",
    title: "Transactions, Stored Programs, and Automation",
    order: 11,
    difficulty: "Advanced",
    lessons: [
      {
        id: 81,
        order: 1,
        slug: "mysql-understanding-mysql-transactions",
        title: "Understanding MySQL Transactions",
        shortTitle: "Understanding MySQL Transact...",
        readingTime: 9,
        tags: ["mysql", "database", "sql", "database programming", "transactions"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to the ACID properties and how transactions group multiple SQL statements into a single logical unit.",
        prerequisites: ["mysql-mysql-query-optimization-basics", "mysql-explain-and-query-execution-plans"],
        related: ["mysql-commit-and-rollback", "mysql-mysql-query-optimization-basics"],
        recommended: ["mysql-commit-and-rollback", "mysql-transaction-isolation-levels"]
      },
      {
        id: 82,
        order: 2,
        slug: "mysql-commit-and-rollback",
        title: "COMMIT and ROLLBACK",
        shortTitle: "COMMIT and ROLLBACK",
        readingTime: 10,
        tags: ["mysql", "database", "sql", "database programming", "transactions"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to permanently save changes or undo them in the event of an error during a transaction.",
        prerequisites: ["mysql-understanding-mysql-transactions", "mysql-mysql-query-optimization-basics"],
        related: ["mysql-transaction-isolation-levels", "mysql-understanding-mysql-transactions"],
        recommended: ["mysql-transaction-isolation-levels", "mysql-locks-and-concurrency"]
      },
      {
        id: 83,
        order: 3,
        slug: "mysql-transaction-isolation-levels",
        title: "Transaction Isolation Levels",
        shortTitle: "Transaction Isolation Levels",
        readingTime: 11,
        tags: ["mysql", "database", "sql", "database programming", "transactions"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the different isolation levels (Read Uncommitted, Read Committed, Repeatable Read, Serializable) and their trade-offs.",
        prerequisites: ["mysql-commit-and-rollback", "mysql-understanding-mysql-transactions"],
        related: ["mysql-locks-and-concurrency", "mysql-commit-and-rollback"],
        recommended: ["mysql-locks-and-concurrency", "mysql-stored-procedures"]
      },
      {
        id: 84,
        order: 4,
        slug: "mysql-locks-and-concurrency",
        title: "Locks and Concurrency",
        shortTitle: "Locks and Concurrency",
        readingTime: 12,
        tags: ["mysql", "database", "sql", "database programming", "transactions"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore how MySQL uses shared and exclusive locks to manage concurrent access to data and prevent conflicts.",
        prerequisites: ["mysql-transaction-isolation-levels", "mysql-commit-and-rollback"],
        related: ["mysql-stored-procedures", "mysql-transaction-isolation-levels"],
        recommended: ["mysql-stored-procedures", "mysql-stored-functions"]
      },
      {
        id: 85,
        order: 5,
        slug: "mysql-stored-procedures",
        title: "Stored Procedures",
        shortTitle: "Stored Procedures",
        readingTime: 13,
        tags: ["mysql", "database", "sql", "database programming", "transactions"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to write and execute reusable blocks of SQL code stored directly in the database.",
        prerequisites: ["mysql-locks-and-concurrency", "mysql-transaction-isolation-levels"],
        related: ["mysql-stored-functions", "mysql-locks-and-concurrency"],
        recommended: ["mysql-stored-functions", "mysql-triggers"]
      },
      {
        id: 86,
        order: 6,
        slug: "mysql-stored-functions",
        title: "Stored Functions",
        shortTitle: "Stored Functions",
        readingTime: 14,
        tags: ["mysql", "database", "sql", "database programming", "transactions"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how to create custom functions that return a single value and can be used in SQL expressions.",
        prerequisites: ["mysql-stored-procedures", "mysql-locks-and-concurrency"],
        related: ["mysql-triggers", "mysql-stored-procedures"],
        recommended: ["mysql-triggers", "mysql-cursors-and-error-handling"]
      },
      {
        id: 87,
        order: 7,
        slug: "mysql-triggers",
        title: "Triggers",
        shortTitle: "Triggers",
        readingTime: 15,
        tags: ["mysql", "database", "sql", "database programming", "transactions"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how to automate actions by defining triggers that fire in response to INSERT, UPDATE, or DELETE events.",
        prerequisites: ["mysql-stored-functions", "mysql-stored-procedures"],
        related: ["mysql-cursors-and-error-handling", "mysql-stored-functions"],
        recommended: ["mysql-cursors-and-error-handling", "mysql-mysql-user-accounts-and-privileges"]
      },
      {
        id: 88,
        order: 8,
        slug: "mysql-cursors-and-error-handling",
        title: "Cursors and Error Handling",
        shortTitle: "Cursors and Error Handling",
        readingTime: 8,
        tags: ["mysql", "database", "sql", "database programming", "transactions"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master advanced procedural SQL techniques for iterating over result sets and handling exceptions gracefully.",
        prerequisites: ["mysql-triggers", "mysql-stored-functions"],
        related: ["mysql-triggers", "mysql-mysql-user-accounts-and-privileges"],
        recommended: ["mysql-mysql-user-accounts-and-privileges", "mysql-create-user-grant-and-revoke"]
      }
    ]
  },
  {
    id: "security-json-importexport-and-administration",
    title: "Security, JSON, Import/Export, and Administration",
    order: 12,
    difficulty: "Advanced",
    lessons: [
      {
        id: 89,
        order: 1,
        slug: "mysql-mysql-user-accounts-and-privileges",
        title: "MySQL User Accounts and Privileges",
        shortTitle: "MySQL User Accounts and Priv...",
        readingTime: 9,
        tags: ["mysql", "database", "sql", "database security", "database administration"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to create user accounts and manage the principle of least privilege in MySQL.",
        prerequisites: ["mysql-cursors-and-error-handling", "mysql-triggers"],
        related: ["mysql-create-user-grant-and-revoke", "mysql-cursors-and-error-handling"],
        recommended: ["mysql-create-user-grant-and-revoke", "mysql-mysql-security-best-practices"]
      },
      {
        id: 90,
        order: 2,
        slug: "mysql-create-user-grant-and-revoke",
        title: "CREATE USER, GRANT, and REVOKE",
        shortTitle: "CREATE USER, GRANT, and REVO...",
        readingTime: 10,
        tags: ["mysql", "database", "sql", "database security", "database administration"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the specific SQL commands used to provision and restrict database access for users.",
        prerequisites: ["mysql-mysql-user-accounts-and-privileges", "mysql-cursors-and-error-handling"],
        related: ["mysql-mysql-security-best-practices", "mysql-mysql-user-accounts-and-privileges"],
        recommended: ["mysql-mysql-security-best-practices", "mysql-preventing-sql-injection"]
      },
      {
        id: 91,
        order: 3,
        slug: "mysql-mysql-security-best-practices",
        title: "MySQL Security Best Practices",
        shortTitle: "MySQL Security Best Practices",
        readingTime: 11,
        tags: ["mysql", "database", "sql", "database security", "database administration"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore essential security configurations, including password policies, SSL/TLS, and network access controls.",
        prerequisites: ["mysql-create-user-grant-and-revoke", "mysql-mysql-user-accounts-and-privileges"],
        related: ["mysql-preventing-sql-injection", "mysql-create-user-grant-and-revoke"],
        recommended: ["mysql-preventing-sql-injection", "mysql-working-with-json-data"]
      },
      {
        id: 92,
        order: 4,
        slug: "mysql-preventing-sql-injection",
        title: "Preventing SQL Injection",
        shortTitle: "Preventing SQL Injection",
        readingTime: 12,
        tags: ["mysql", "database", "sql", "database security", "database administration"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the mechanics of SQL injection attacks and how to prevent them using prepared statements.",
        prerequisites: ["mysql-mysql-security-best-practices", "mysql-create-user-grant-and-revoke"],
        related: ["mysql-working-with-json-data", "mysql-mysql-security-best-practices"],
        recommended: ["mysql-working-with-json-data", "mysql-importing-and-exporting-mysql-data"]
      },
      {
        id: 93,
        order: 5,
        slug: "mysql-working-with-json-data",
        title: "Working with JSON Data",
        shortTitle: "Working with JSON Data",
        readingTime: 13,
        tags: ["mysql", "database", "sql", "database administration", "best practices"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to store, query, and manipulate JSON documents natively within MySQL.",
        prerequisites: ["mysql-preventing-sql-injection", "mysql-mysql-security-best-practices"],
        related: ["mysql-importing-and-exporting-mysql-data", "mysql-preventing-sql-injection"],
        recommended: ["mysql-importing-and-exporting-mysql-data", "mysql-backup-and-restore-basics"]
      },
      {
        id: 94,
        order: 6,
        slug: "mysql-importing-and-exporting-mysql-data",
        title: "Importing and Exporting MySQL Data",
        shortTitle: "Importing and Exporting MySQ...",
        readingTime: 14,
        tags: ["mysql", "database", "sql", "database administration", "best practices"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the tools and commands for moving data in and out of MySQL using CSV and SQL dump files.",
        prerequisites: ["mysql-working-with-json-data", "mysql-preventing-sql-injection"],
        related: ["mysql-backup-and-restore-basics", "mysql-working-with-json-data"],
        recommended: ["mysql-backup-and-restore-basics", "mysql-mysql-administration-and-troubleshooting"]
      },
      {
        id: 95,
        order: 7,
        slug: "mysql-backup-and-restore-basics",
        title: "Backup and Restore Basics",
        shortTitle: "Backup and Restore Basics",
        readingTime: 15,
        tags: ["mysql", "database", "sql", "database administration", "best practices"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to use mysqldump and other utilities to create reliable backups of your databases.",
        prerequisites: ["mysql-importing-and-exporting-mysql-data", "mysql-working-with-json-data"],
        related: ["mysql-mysql-administration-and-troubleshooting", "mysql-importing-and-exporting-mysql-data"],
        recommended: ["mysql-mysql-administration-and-troubleshooting", "mysql-mysql-user-accounts-and-privileges"]
      },
      {
        id: 96,
        order: 8,
        slug: "mysql-mysql-administration-and-troubleshooting",
        title: "MySQL Administration and Troubleshooting",
        shortTitle: "MySQL Administration and Tro...",
        readingTime: 8,
        tags: ["mysql", "database", "sql", "database administration", "best practices"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Develop the skills to monitor server health, read error logs, and resolve common MySQL operational issues.",
        prerequisites: ["mysql-backup-and-restore-basics", "mysql-importing-and-exporting-mysql-data"],
        related: ["mysql-backup-and-restore-basics", "mysql-mysql-user-accounts-and-privileges"],
        recommended: ["mysql-mysql-user-accounts-and-privileges", "mysql-create-user-grant-and-revoke"]
      }
    ]
  }
];

export const resources = [
  {
    id: "mysql-tools-and-development",
    title: "MySQL Tools & Development",
    order: 1,
    items: [
      {
        id: 97,
        order: 1,
        slug: "mysql-workbench-guide",
        title: "MySQL Workbench Guide",
        shortTitle: "Workbench",
        type: "article",
        readingTime: 10,
        tags: ["mysql", "workbench", "gui", "database design", "development", "tools"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master MySQL Workbench for visual database design, SQL development, administration, and performance monitoring."
      },
      {
        id: 98,
        order: 2,
        slug: "mysql-command-line",
        title: "Using MySQL from the Command Line",
        shortTitle: "Command Line",
        type: "article",
        readingTime: 10,
        tags: ["mysql", "cli", "command line", "mysql client", "terminal", "administration"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn essential MySQL command-line client operations for database administration, querying, and scripting without a GUI."
      },
      {
        id: 99,
        order: 3,
        slug: "mysql-vs-code-integration",
        title: "Connecting MySQL with VS Code",
        shortTitle: "VS Code",
        type: "article",
        readingTime: 8,
        tags: ["mysql", "vscode", "ide", "extensions", "development", "productivity"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Set up and use VS Code extensions to connect, query, and manage MySQL databases directly from your code editor."
      },
      {
        id: 100,
        order: 4,
        slug: "mysql-client-tools",
        title: "Useful MySQL Client Tools",
        shortTitle: "Client Tools",
        type: "article",
        readingTime: 8,
        tags: ["mysql", "tools", "clients", "adminer", "dbeaver", "phpmyadmin", "development"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore popular MySQL client tools like DBeaver, Adminer, and phpMyAdmin for efficient database management and querying."
      },
    ]
  },

  {
    id: "mysql-with-programming-languages",
    title: "MySQL with Programming Languages",
    order: 2,
    items: [
      {
        id: 101,
        order: 1,
        slug: "mysql-python-connection",
        title: "Connecting MySQL with Python",
        shortTitle: "Python",
        type: "article",
        readingTime: 10,
        tags: ["mysql", "python", "connector", "pymysql", "sqlalchemy", "backend"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Connect and interact with MySQL databases from Python using MySQL Connector, PyMySQL, and SQLAlchemy ORM."
      },
      {
        id: 102,
        order: 2,
        slug: "mysql-nodejs-connection",
        title: "Connecting MySQL with Node.js",
        shortTitle: "Node.js",
        type: "article",
        readingTime: 10,
        tags: ["mysql", "nodejs", "javascript", "mysql2", "backend", "api"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Integrate MySQL into Node.js applications using the mysql2 package for async queries, pooling, and connection management."
      },
      {
        id: 103,
        order: 3,
        slug: "mysql-java-connection",
        title: "Connecting MySQL with Java",
        shortTitle: "Java",
        type: "article",
        readingTime: 10,
        tags: ["mysql", "java", "jdbc", "spring", "backend", "enterprise"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Use JDBC and connection pooling to integrate MySQL with Java and Spring Boot applications securely and efficiently."
      },
      {
        id: 104,
        order: 4,
        slug: "mysql-php-connection",
        title: "Connecting MySQL with PHP",
        shortTitle: "PHP",
        type: "article",
        readingTime: 10,
        tags: ["mysql", "php", "pdo", "mysqli", "web development", "lamp"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Connect PHP applications to MySQL using PDO and MySQLi for secure database interactions and prepared statements."
      },
    ]
  },

  {
    id: "practical-mysql-recipes",
    title: "Practical MySQL Recipes",
    order: 3,
    items: [
      {
        id: 105,
        order: 1,
        slug: "mysql-common-queries-patterns",
        title: "Common MySQL Queries and Patterns",
        shortTitle: "Common Queries",
        type: "article",
        readingTime: 10,
        tags: ["mysql", "sql", "queries", "patterns", "recipes", "best practices"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "A collection of commonly used MySQL query patterns for filtering, aggregation, joins, and conditional logic."
      },
      {
        id: 106,
        order: 2,
        slug: "mysql-duplicate-records",
        title: "Finding and Removing Duplicate Records",
        shortTitle: "Duplicate Records",
        type: "article",
        readingTime: 8,
        tags: ["mysql", "duplicates", "data cleaning", "cte", "group by", "maintenance"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Identify and eliminate duplicate records using self-joins, CTEs, and DELETE operations while preserving data integrity."
      },
      {
        id: 107,
        order: 3,
        slug: "mysql-dates-pagination",
        title: "Working with Dates and Pagination",
        shortTitle: "Dates & Pagination",
        type: "article",
        readingTime: 10,
        tags: ["mysql", "dates", "pagination", "limit", "offset", "datetime", "queries"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Handle date manipulations and implement efficient result set pagination in MySQL for scalable data retrieval."
      },
      {
        id: 108,
        order: 4,
        slug: "mysql-common-operations",
        title: "Frequently Used Database Operations",
        shortTitle: "Common Operations",
        type: "article",
        readingTime: 10,
        tags: ["mysql", "operations", "maintenance", "import", "export", "batch", "routines"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Reference guide for frequently performed MySQL operations including bulk imports, exports, updates, and routine maintenance tasks."
      },
    ]
  },

  {
    id: "advanced-mysql-concepts",
    title: "Advanced MySQL Concepts",
    order: 4,
    items: [
      {
        id: 109,
        order: 1,
        slug: "mysql-storage-engines-innodb",
        title: "Storage Engines and InnoDB",
        shortTitle: "Storage Engines",
        type: "article",
        readingTime: 12,
        tags: ["mysql", "storage engines", "innodb", "myisam", "architecture", "advanced"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand MySQL storage engines with deep focus on InnoDB architecture, transactions, and ACID compliance."
      },
      {
        id: 110,
        order: 2,
        slug: "mysql-character-sets-collations",
        title: "Character Sets and Collations",
        shortTitle: "Charsets & Collations",
        type: "article",
        readingTime: 10,
        tags: ["mysql", "character sets", "collations", "utf8", "encoding", "internationalization"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Configure and manage character sets and collations to ensure proper text encoding, sorting, and multilingual support."
      },
      {
        id: 111,
        order: 3,
        slug: "mysql-full-text-search",
        title: "Full-Text Search",
        shortTitle: "Full-Text Search",
        type: "article",
        readingTime: 10,
        tags: ["mysql", "full-text search", "indexing", "search", "match against", "advanced"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Implement powerful full-text search capabilities in MySQL using FULLTEXT indexes and MATCH ... AGAINST syntax."
      },
      {
        id: 112,
        order: 4,
        slug: "mysql-table-partitioning",
        title: "Table Partitioning",
        shortTitle: "Partitioning",
        type: "article",
        readingTime: 12,
        tags: ["mysql", "partitioning", "performance", "scaling", "large tables", "advanced"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Improve query performance and manage large datasets by implementing range, list, hash, and key table partitioning strategies."
      },
    ]
  },

  {
    id: "mysql-production-and-career",
    title: "MySQL Production & Career",
    order: 5,
    items: [
      {
        id: 113,
        order: 1,
        slug: "mysql-performance-tuning-checklist",
        title: "MySQL Performance Tuning Checklist",
        shortTitle: "Performance Tuning",
        type: "article",
        readingTime: 12,
        tags: ["mysql", "performance", "tuning", "optimization", "indexing", "production", "monitoring"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "A comprehensive checklist for diagnosing and tuning MySQL performance including indexing, configuration, and query optimization."
      },
      {
        id: 114,
        order: 2,
        slug: "mysql-backup-recovery",
        title: "MySQL Backup and Recovery Strategies",
        shortTitle: "Backup & Recovery",
        type: "article",
        readingTime: 10,
        tags: ["mysql", "backup", "recovery", "mysqldump", "xtrabackup", "disaster recovery", "production"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Implement robust backup and recovery strategies using mysqldump, Percona XtraBackup, and point-in-time recovery techniques."
      },
      {
        id: 115,
        order: 3,
        slug: "mysql-backend-development",
        title: "MySQL for Backend Development",
        shortTitle: "Backend Development",
        type: "article",
        readingTime: 10,
        tags: ["mysql", "backend", "database design", "api", "web development", "architecture"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to design schemas, manage connections, and optimize queries when using MySQL as the database layer in backend applications."
      },
      {
        id: 116,
        order: 4,
        slug: "mysql-interview-preparation",
        title: "MySQL Interview Preparation",
        shortTitle: "Interview Prep",
        type: "article",
        readingTime: 12,
        tags: ["mysql", "interview", "career", "dba", "backend", "sql", "preparation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Prepare for MySQL technical interviews with commonly asked questions on indexing, normalization, transactions, and optimization."
      },
    ]
  },
];