// ============================================================
// src/registry/lessons/pythonLessons.js
// STUB — same shape as htmlLessons.js, empty until you fill it in.
// lessonRegistry.js can safely import this right now without
// breaking anything; it'll just show 0 lessons for Python until
// you add sections here.
// ============================================================

import { STATUS } from "../../config/constants";

export const tutorialInfo = {
  id: "natural-language-processing",
  title: "NLP Tutorial",
  shortTitle: "Natural Language Processing",
  category: "Artificial Intelligence and Machine Learning",
  description: "Master Natural Language Processing from beginner to advanced with a comprehensive tutorial covering text preprocessing, tokenization, stemming, lemmatization, feature extraction, text classification, sentiment analysis, word embeddings, sequence models, attention mechanisms, transformers, large language models, information retrieval, and real-world NLP applications.",
  icon: "natural-language-processing",
  difficulty: "Advanced", // course-level badge, separate from per-section defaults
  estimatedHours: 44,
  totalLessons: 85,
  version: "Latest Version",
  language: "English",
  path: "/natural-language-processing",
  authorId: "faiz",
  updatedAt: "2026-07-09",
  tags: ["natural language processing", "nlp", "nlp tutorial", "artificial intelligence", "ai", "machine learning", "deep learning", "text processing", "text analysis", "tokenization", "text classification", "sentiment analysis", "named entity recognition", "ner", "part of speech tagging", "word embeddings", "word2vec", "glove", "sequence models", "rnn", "lstm", "gru", "attention", "transformers", "large language models", "llms", "natural language understanding", "natural language generation", "text generation", "information retrieval", "question answering", "machine translation", "text summarization", "chatbots", "python nlp", "nltk", "spacy", "hugging face"],
  seo: {
    title: "Natural Language Processing Tutorial - Learn NLP from Beginner to Advanced | DevSphere",
    description: "Learn Natural Language Processing from scratch with a complete NLP tutorial covering text preprocessing, tokenization, sentiment analysis, text classification, NER, word embeddings, RNNs, LSTMs, attention, transformers, LLMs, NLP applications, and real-world projects.",
    keywords: ["Natural Language Processing Tutorial", "NLP Tutorial", "NLP Tutorial for Beginners", "Learn NLP", "Learn Natural Language Processing", "NLP Course", "Natural Language Processing Course", "NLP for Beginners", "Natural Language Processing with Python", "Python NLP", "NLP Programming", "NLP Basics", "NLP Fundamentals", "Natural Language Processing Basics", "Natural Language Processing with Machine Learning", "Natural Language Processing with Deep Learning", "Text Processing", "Text Analysis", "Text Mining", "Text Preprocessing", "NLP Text Preprocessing", "Tokenization", "NLP Tokenization", "Sentence Tokenization", "Word Tokenization", "Stemming", "Lemmatization", "Stop Words", "NLP Feature Extraction", "Bag of Words", "TF IDF", "TF-IDF", "N Grams", "Text Classification", "Text Classification NLP", "Sentiment Analysis", "Sentiment Analysis with Python", "Spam Detection", "Named Entity Recognition", "NER", "Part of Speech Tagging", "POS Tagging", "Language Detection", "Word Embeddings", "Word Embedding Tutorial", "Word2Vec", "GloVe", "FastText", "Sentence Embeddings", "Semantic Similarity", "Sequence Models", "RNN NLP", "LSTM NLP", "GRU NLP", "Attention Mechanism", "Self Attention", "Transformer NLP", "Transformer Architecture", "Transformers Tutorial", "Large Language Models", "LLM Tutorial", "LLMs", "Natural Language Understanding", "NLU", "Natural Language Generation", "NLG", "Text Generation", "Text Summarization", "Machine Translation", "Question Answering", "Information Retrieval", "NLP Chatbot", "Chatbot Development", "NLP Applications", "NLP Projects", "NLP Projects with Python", "NLTK Tutorial", "spaCy Tutorial", "Hugging Face NLP", "Hugging Face Transformers", "NLP with PyTorch", "NLP with TensorFlow", "NLP Model Training", "NLP Model Evaluation", "NLP Model Deployment", "DevSphere"]
  }
};

export const sections = [
  {
    id: "introduction-to-natural-language-processing",
    title: "Introduction to Natural Language Processing",
    order: 1,
    difficulty: "Beginner",
    lessons: [
      {
        id: 1,
        order: 1,
        slug: "nlp-what-is-natural-language-processing",
        title: "What is Natural Language Processing?",
        shortTitle: "What is Natural Language Pro...",
        readingTime: 9,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get a comprehensive introduction to Natural Language Processing, its core concepts, and how it bridges the gap between human communication and computer understanding.",
        prerequisites: [],
        related: ["nlp-why-is-nlp-important", "nlp-understanding-human-language"],
        recommended: ["nlp-nlp-vs-nlu-vs-nlg", "nlp-applications-of-nlp"]
      },
      {
        id: 2,
        order: 2,
        slug: "nlp-why-is-nlp-important",
        title: "Why is NLP Important?",
        shortTitle: "Why is NLP Important",
        readingTime: 10,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the critical role of NLP in modern technology, from search engines and virtual assistants to automated customer support and data analysis.",
        prerequisites: ["nlp-what-is-natural-language-processing", "nlp-nlp-vs-nlu-vs-nlg"],
        related: ["nlp-nlp-vs-nlu-vs-nlg", "nlp-what-is-natural-language-processing"],
        recommended: ["nlp-nlp-vs-nlu-vs-nlg", "nlp-applications-of-nlp"]
      },
      {
        id: 3,
        order: 3,
        slug: "nlp-nlp-vs-nlu-vs-nlg",
        title: "NLP vs NLU vs NLG",
        shortTitle: "NLP vs NLU vs NLG",
        readingTime: 11,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Clarify the distinctions between Natural Language Processing, Natural Language Understanding, and Natural Language Generation.",
        prerequisites: ["nlp-why-is-nlp-important", "nlp-what-is-natural-language-processing"],
        related: ["nlp-applications-of-nlp", "nlp-why-is-nlp-important"],
        recommended: ["nlp-applications-of-nlp", "nlp-challenges-in-natural-language-processing"]
      },
      {
        id: 4,
        order: 4,
        slug: "nlp-applications-of-nlp",
        title: "Applications of NLP",
        shortTitle: "Applications of NLP",
        readingTime: 12,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore real-world applications of NLP across various industries, including healthcare, finance, marketing, and technology.",
        prerequisites: ["nlp-nlp-vs-nlu-vs-nlg", "nlp-why-is-nlp-important"],
        related: ["nlp-challenges-in-natural-language-processing", "nlp-nlp-vs-nlu-vs-nlg"],
        recommended: ["nlp-challenges-in-natural-language-processing", "nlp-nlp-pipeline-and-its-major-stages"]
      },
      {
        id: 5,
        order: 5,
        slug: "nlp-challenges-in-natural-language-processing",
        title: "Challenges in Natural Language Processing",
        shortTitle: "Challenges in Natural Language...",
        readingTime: 13,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn about the inherent complexities of human language, such as ambiguity, sarcasm, and context, that make NLP a challenging field.",
        prerequisites: ["nlp-applications-of-nlp", "nlp-nlp-vs-nlu-vs-nlg"],
        related: ["nlp-nlp-pipeline-and-its-major-stages", "nlp-applications-of-nlp"],
        recommended: ["nlp-nlp-pipeline-and-its-major-stages", "nlp-understanding-human-language"]
      },
      {
        id: 6,
        order: 6,
        slug: "nlp-nlp-pipeline-and-its-major-stages",
        title: "NLP Pipeline and Its Major Stages",
        shortTitle: "NLP Pipeline and Its Major Sta...",
        readingTime: 14,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the standard NLP pipeline, from raw text ingestion and preprocessing to feature extraction, modeling, and evaluation.",
        prerequisites: ["nlp-challenges-in-natural-language-processing", "nlp-applications-of-nlp"],
        related: ["nlp-challenges-in-natural-language-processing", "nlp-understanding-human-language"],
        recommended: ["nlp-understanding-human-language", "nlp-words-sentences-and-documents"]
      }
    ]
  },
  {
    id: "linguistics-and-text-fundamentals",
    title: "Linguistics and Text Fundamentals",
    order: 2,
    difficulty: "Beginner",
    lessons: [
      {
        id: 7,
        order: 1,
        slug: "nlp-understanding-human-language",
        title: "Understanding Human Language",
        shortTitle: "Understanding Human Language",
        readingTime: 15,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Dive into the foundational concepts of linguistics that underpin all natural language processing techniques.",
        prerequisites: ["nlp-nlp-pipeline-and-its-major-stages", "nlp-challenges-in-natural-language-processing"],
        related: ["nlp-words-sentences-and-documents", "nlp-nlp-pipeline-and-its-major-stages"],
        recommended: ["nlp-words-sentences-and-documents", "nlp-morphology-and-word-structure"]
      },
      {
        id: 8,
        order: 2,
        slug: "nlp-words-sentences-and-documents",
        title: "Words, Sentences, and Documents",
        shortTitle: "Words, Sentences, and Documents",
        readingTime: 8,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how text is hierarchically structured and how NLP systems parse and interpret these different levels of granularity.",
        prerequisites: ["nlp-understanding-human-language", "nlp-nlp-pipeline-and-its-major-stages"],
        related: ["nlp-morphology-and-word-structure", "nlp-understanding-human-language"],
        recommended: ["nlp-morphology-and-word-structure", "nlp-syntax-and-grammar"]
      },
      {
        id: 9,
        order: 3,
        slug: "nlp-morphology-and-word-structure",
        title: "Morphology and Word Structure",
        shortTitle: "Morphology and Word Structure",
        readingTime: 9,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore how words are formed and how morphological analysis helps NLP models understand word variations and roots.",
        prerequisites: ["nlp-words-sentences-and-documents", "nlp-understanding-human-language"],
        related: ["nlp-syntax-and-grammar", "nlp-words-sentences-and-documents"],
        recommended: ["nlp-syntax-and-grammar", "nlp-semantics-and-meaning"]
      },
      {
        id: 10,
        order: 4,
        slug: "nlp-syntax-and-grammar",
        title: "Syntax and Grammar",
        shortTitle: "Syntax and Grammar",
        readingTime: 10,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the rules governing sentence structure and how syntactic parsing is used to extract meaning from text.",
        prerequisites: ["nlp-morphology-and-word-structure", "nlp-words-sentences-and-documents"],
        related: ["nlp-semantics-and-meaning", "nlp-morphology-and-word-structure"],
        recommended: ["nlp-semantics-and-meaning", "nlp-pragmatics-and-context"]
      },
      {
        id: 11,
        order: 5,
        slug: "nlp-semantics-and-meaning",
        title: "Semantics and Meaning",
        shortTitle: "Semantics and Meaning",
        readingTime: 11,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Delve into how NLP systems interpret the literal meaning of words and sentences in context.",
        prerequisites: ["nlp-syntax-and-grammar", "nlp-morphology-and-word-structure"],
        related: ["nlp-pragmatics-and-context", "nlp-syntax-and-grammar"],
        recommended: ["nlp-pragmatics-and-context", "nlp-introduction-to-text-preprocessing"]
      },
      {
        id: 12,
        order: 6,
        slug: "nlp-pragmatics-and-context",
        title: "Pragmatics and Context",
        shortTitle: "Pragmatics and Context",
        readingTime: 12,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how NLP models attempt to capture implied meaning, intent, and context beyond the literal words used.",
        prerequisites: ["nlp-semantics-and-meaning", "nlp-syntax-and-grammar"],
        related: ["nlp-semantics-and-meaning", "nlp-introduction-to-text-preprocessing"],
        recommended: ["nlp-introduction-to-text-preprocessing", "nlp-text-cleaning-and-normalization"]
      }
    ]
  },
  {
    id: "text-preprocessing",
    title: "Text Preprocessing",
    order: 3,
    difficulty: "Beginner",
    lessons: [
      {
        id: 13,
        order: 1,
        slug: "nlp-introduction-to-text-preprocessing",
        title: "Introduction to Text Preprocessing",
        shortTitle: "Introduction to Text Preproces...",
        readingTime: 13,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text preprocessing", "nlp fundamentals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to the crucial first step in any NLP project: preparing raw text for machine learning algorithms.",
        prerequisites: ["nlp-pragmatics-and-context", "nlp-semantics-and-meaning"],
        related: ["nlp-text-cleaning-and-normalization", "nlp-pragmatics-and-context"],
        recommended: ["nlp-text-cleaning-and-normalization", "nlp-tokenization"]
      },
      {
        id: 14,
        order: 2,
        slug: "nlp-text-cleaning-and-normalization",
        title: "Text Cleaning and Normalization",
        shortTitle: "Text Cleaning and Normalization",
        readingTime: 14,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text preprocessing", "nlp fundamentals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master techniques for removing noise, handling special characters, and standardizing text formats for consistent processing.",
        prerequisites: ["nlp-introduction-to-text-preprocessing", "nlp-pragmatics-and-context"],
        related: ["nlp-tokenization", "nlp-introduction-to-text-preprocessing"],
        recommended: ["nlp-tokenization", "nlp-sentence-and-word-tokenization"]
      },
      {
        id: 15,
        order: 3,
        slug: "nlp-tokenization",
        title: "Tokenization",
        shortTitle: "Tokenization",
        readingTime: 15,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text preprocessing", "nlp fundamentals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn the fundamental process of breaking down text into smaller, manageable units called tokens.",
        prerequisites: ["nlp-text-cleaning-and-normalization", "nlp-introduction-to-text-preprocessing"],
        related: ["nlp-sentence-and-word-tokenization", "nlp-text-cleaning-and-normalization"],
        recommended: ["nlp-sentence-and-word-tokenization", "nlp-stop-words-removal"]
      },
      {
        id: 16,
        order: 4,
        slug: "nlp-sentence-and-word-tokenization",
        title: "Sentence and Word Tokenization",
        shortTitle: "Sentence and Word Tokenization",
        readingTime: 8,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text preprocessing", "nlp fundamentals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the specific algorithms and challenges involved in splitting text into sentences and individual words.",
        prerequisites: ["nlp-tokenization", "nlp-text-cleaning-and-normalization"],
        related: ["nlp-stop-words-removal", "nlp-tokenization"],
        recommended: ["nlp-stop-words-removal", "nlp-stemming-and-lemmatization"]
      },
      {
        id: 17,
        order: 5,
        slug: "nlp-stop-words-removal",
        title: "Stop Words Removal",
        shortTitle: "Stop Words Removal",
        readingTime: 9,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text preprocessing", "nlp fundamentals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how to filter out common, low-information words to reduce dimensionality and improve model performance.",
        prerequisites: ["nlp-sentence-and-word-tokenization", "nlp-tokenization"],
        related: ["nlp-stemming-and-lemmatization", "nlp-sentence-and-word-tokenization"],
        recommended: ["nlp-stemming-and-lemmatization", "nlp-part-of-speech-tagging"]
      },
      {
        id: 18,
        order: 6,
        slug: "nlp-stemming-and-lemmatization",
        title: "Stemming and Lemmatization",
        shortTitle: "Stemming and Lemmatization",
        readingTime: 10,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text preprocessing", "nlp fundamentals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Compare and apply techniques for reducing words to their base or root form to normalize text data.",
        prerequisites: ["nlp-stop-words-removal", "nlp-sentence-and-word-tokenization"],
        related: ["nlp-part-of-speech-tagging", "nlp-stop-words-removal"],
        recommended: ["nlp-part-of-speech-tagging", "nlp-introduction-to-regular-expressions-in-nlp"]
      },
      {
        id: 19,
        order: 7,
        slug: "nlp-part-of-speech-tagging",
        title: "Part-of-Speech Tagging",
        shortTitle: "Part-of-Speech Tagging",
        readingTime: 11,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text preprocessing", "nlp fundamentals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to assign grammatical categories to words, a crucial step for syntactic analysis and feature engineering.",
        prerequisites: ["nlp-stemming-and-lemmatization", "nlp-stop-words-removal"],
        related: ["nlp-stemming-and-lemmatization", "nlp-introduction-to-regular-expressions-in-nlp"],
        recommended: ["nlp-introduction-to-regular-expressions-in-nlp", "nlp-regex-patterns-and-character-classes"]
      }
    ]
  },
  {
    id: "regular-expressions-and-text-processing",
    title: "Regular Expressions and Text Processing",
    order: 4,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 20,
        order: 1,
        slug: "nlp-introduction-to-regular-expressions-in-nlp",
        title: "Introduction to Regular Expressions in NLP",
        shortTitle: "Introduction to Regular Expres...",
        readingTime: 12,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text preprocessing", "nlp fundamentals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get started with regular expressions, a powerful tool for pattern matching and text manipulation in NLP.",
        prerequisites: ["nlp-part-of-speech-tagging", "nlp-stemming-and-lemmatization"],
        related: ["nlp-regex-patterns-and-character-classes", "nlp-part-of-speech-tagging"],
        recommended: ["nlp-regex-patterns-and-character-classes", "nlp-searching-and-extracting-text-with-regex"]
      },
      {
        id: 21,
        order: 2,
        slug: "nlp-regex-patterns-and-character-classes",
        title: "Regex Patterns and Character Classes",
        shortTitle: "Regex Patterns and Character C...",
        readingTime: 13,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text preprocessing", "nlp fundamentals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the syntax of regular expressions to define complex search patterns for text extraction.",
        prerequisites: ["nlp-introduction-to-regular-expressions-in-nlp", "nlp-part-of-speech-tagging"],
        related: ["nlp-searching-and-extracting-text-with-regex", "nlp-introduction-to-regular-expressions-in-nlp"],
        recommended: ["nlp-searching-and-extracting-text-with-regex", "nlp-text-replacement-and-cleaning-with-regex"]
      },
      {
        id: 22,
        order: 3,
        slug: "nlp-searching-and-extracting-text-with-regex",
        title: "Searching and Extracting Text with Regex",
        shortTitle: "Searching and Extracting Text ...",
        readingTime: 14,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text preprocessing", "nlp fundamentals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn practical techniques for finding and extracting specific information from unstructured text using regex.",
        prerequisites: ["nlp-regex-patterns-and-character-classes", "nlp-introduction-to-regular-expressions-in-nlp"],
        related: ["nlp-text-replacement-and-cleaning-with-regex", "nlp-regex-patterns-and-character-classes"],
        recommended: ["nlp-text-replacement-and-cleaning-with-regex", "nlp-extracting-structured-information-from-text"]
      },
      {
        id: 23,
        order: 4,
        slug: "nlp-text-replacement-and-cleaning-with-regex",
        title: "Text Replacement and Cleaning with Regex",
        shortTitle: "Text Replacement and Cleaning ...",
        readingTime: 15,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text preprocessing", "nlp fundamentals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how to use regular expressions to clean, format, and standardize messy text data efficiently.",
        prerequisites: ["nlp-searching-and-extracting-text-with-regex", "nlp-regex-patterns-and-character-classes"],
        related: ["nlp-extracting-structured-information-from-text", "nlp-searching-and-extracting-text-with-regex"],
        recommended: ["nlp-extracting-structured-information-from-text", "nlp-practical-text-preprocessing-with-python"]
      },
      {
        id: 24,
        order: 5,
        slug: "nlp-extracting-structured-information-from-text",
        title: "Extracting Structured Information from Text",
        shortTitle: "Extracting Structured Informat...",
        readingTime: 8,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text preprocessing", "nlp fundamentals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how to parse unstructured text and convert it into structured formats like JSON or CSV using regex.",
        prerequisites: ["nlp-text-replacement-and-cleaning-with-regex", "nlp-searching-and-extracting-text-with-regex"],
        related: ["nlp-practical-text-preprocessing-with-python", "nlp-text-replacement-and-cleaning-with-regex"],
        recommended: ["nlp-practical-text-preprocessing-with-python", "nlp-why-text-representation-is-necessary"]
      },
      {
        id: 25,
        order: 6,
        slug: "nlp-practical-text-preprocessing-with-python",
        title: "Practical Text Preprocessing with Python",
        shortTitle: "Practical Text Preprocessing w...",
        readingTime: 9,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text preprocessing", "nlp fundamentals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Apply your knowledge by building a complete text preprocessing pipeline using Python and popular NLP libraries.",
        prerequisites: ["nlp-extracting-structured-information-from-text", "nlp-text-replacement-and-cleaning-with-regex"],
        related: ["nlp-extracting-structured-information-from-text", "nlp-why-text-representation-is-necessary"],
        recommended: ["nlp-why-text-representation-is-necessary", "nlp-one-hot-encoding"]
      }
    ]
  },
  {
    id: "text-representation",
    title: "Text Representation",
    order: 5,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 26,
        order: 1,
        slug: "nlp-why-text-representation-is-necessary",
        title: "Why Text Representation is Necessary",
        shortTitle: "Why Text Representation is Nec...",
        readingTime: 10,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand why machine learning models require numerical representations of text and the challenges involved.",
        prerequisites: ["nlp-practical-text-preprocessing-with-python", "nlp-extracting-structured-information-from-text"],
        related: ["nlp-one-hot-encoding", "nlp-practical-text-preprocessing-with-python"],
        recommended: ["nlp-one-hot-encoding", "nlp-bag-of-words"]
      },
      {
        id: 27,
        order: 2,
        slug: "nlp-one-hot-encoding",
        title: "One-Hot Encoding",
        shortTitle: "One-Hot Encoding",
        readingTime: 11,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn the simplest form of text representation and its limitations in capturing semantic meaning.",
        prerequisites: ["nlp-why-text-representation-is-necessary", "nlp-practical-text-preprocessing-with-python"],
        related: ["nlp-bag-of-words", "nlp-why-text-representation-is-necessary"],
        recommended: ["nlp-bag-of-words", "nlp-n-gram-representation"]
      },
      {
        id: 28,
        order: 3,
        slug: "nlp-bag-of-words",
        title: "Bag of Words",
        shortTitle: "Bag of Words",
        readingTime: 12,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the Bag of Words model, a foundational technique for representing text as word frequency vectors.",
        prerequisites: ["nlp-one-hot-encoding", "nlp-why-text-representation-is-necessary"],
        related: ["nlp-n-gram-representation", "nlp-one-hot-encoding"],
        recommended: ["nlp-n-gram-representation", "nlp-tf-idf"]
      },
      {
        id: 29,
        order: 4,
        slug: "nlp-n-gram-representation",
        title: "N-Gram Representation",
        shortTitle: "N-Gram Representation",
        readingTime: 13,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore how N-grams capture local word order and context, improving upon the basic Bag of Words model.",
        prerequisites: ["nlp-bag-of-words", "nlp-one-hot-encoding"],
        related: ["nlp-tf-idf", "nlp-bag-of-words"],
        recommended: ["nlp-tf-idf", "nlp-comparing-classical-text-representations"]
      },
      {
        id: 30,
        order: 5,
        slug: "nlp-tf-idf",
        title: "TF-IDF",
        shortTitle: "TF-IDF",
        readingTime: 14,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand Term Frequency-Inverse Document Frequency, a powerful statistical measure for evaluating word importance.",
        prerequisites: ["nlp-n-gram-representation", "nlp-bag-of-words"],
        related: ["nlp-comparing-classical-text-representations", "nlp-n-gram-representation"],
        recommended: ["nlp-comparing-classical-text-representations", "nlp-what-is-a-language-model"]
      },
      {
        id: 31,
        order: 6,
        slug: "nlp-comparing-classical-text-representations",
        title: "Comparing Classical Text Representations",
        shortTitle: "Comparing Classical Text Repre...",
        readingTime: 15,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Compare the strengths and weaknesses of different classical text representation techniques to choose the right one for your task.",
        prerequisites: ["nlp-tf-idf", "nlp-n-gram-representation"],
        related: ["nlp-tf-idf", "nlp-what-is-a-language-model"],
        recommended: ["nlp-what-is-a-language-model", "nlp-unigram-bigram-and-n-gram-language-models"]
      }
    ]
  },
  {
    id: "statistical-language-models",
    title: "Statistical Language Models",
    order: 6,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 32,
        order: 1,
        slug: "nlp-what-is-a-language-model",
        title: "What is a Language Model?",
        shortTitle: "What is a Language Model?",
        readingTime: 8,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to language models and their fundamental role in predicting the probability of word sequences.",
        prerequisites: ["nlp-comparing-classical-text-representations", "nlp-tf-idf"],
        related: ["nlp-unigram-bigram-and-n-gram-language-models", "nlp-comparing-classical-text-representations"],
        recommended: ["nlp-unigram-bigram-and-n-gram-language-models", "nlp-probability-in-language-modeling"]
      },
      {
        id: 33,
        order: 2,
        slug: "nlp-unigram-bigram-and-n-gram-language-models",
        title: "Unigram, Bigram, and N-Gram Language Models",
        shortTitle: "Unigram, Bigram, and N-Gram La...",
        readingTime: 9,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to build and evaluate simple statistical language models based on word co-occurrence frequencies.",
        prerequisites: ["nlp-what-is-a-language-model", "nlp-comparing-classical-text-representations"],
        related: ["nlp-probability-in-language-modeling", "nlp-what-is-a-language-model"],
        recommended: ["nlp-probability-in-language-modeling", "nlp-smoothing-techniques"]
      },
      {
        id: 34,
        order: 3,
        slug: "nlp-probability-in-language-modeling",
        title: "Probability in Language Modeling",
        shortTitle: "Probability in Language Modeli...",
        readingTime: 10,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the mathematical foundations of probability theory as applied to natural language modeling.",
        prerequisites: ["nlp-unigram-bigram-and-n-gram-language-models", "nlp-what-is-a-language-model"],
        related: ["nlp-smoothing-techniques", "nlp-unigram-bigram-and-n-gram-language-models"],
        recommended: ["nlp-smoothing-techniques", "nlp-perplexity-and-language-model-evaluation"]
      },
      {
        id: 35,
        order: 4,
        slug: "nlp-smoothing-techniques",
        title: "Smoothing Techniques",
        shortTitle: "Smoothing Techniques",
        readingTime: 11,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how smoothing techniques like Laplace and Kneser-Ney solve the zero-probability problem in N-gram models.",
        prerequisites: ["nlp-probability-in-language-modeling", "nlp-unigram-bigram-and-n-gram-language-models"],
        related: ["nlp-perplexity-and-language-model-evaluation", "nlp-probability-in-language-modeling"],
        recommended: ["nlp-perplexity-and-language-model-evaluation", "nlp-limitations-of-statistical-language-models"]
      },
      {
        id: 36,
        order: 5,
        slug: "nlp-perplexity-and-language-model-evaluation",
        title: "Perplexity and Language Model Evaluation",
        shortTitle: "Perplexity and Language Model ...",
        readingTime: 12,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to use perplexity as a key metric to evaluate and compare the performance of different language models.",
        prerequisites: ["nlp-smoothing-techniques", "nlp-probability-in-language-modeling"],
        related: ["nlp-limitations-of-statistical-language-models", "nlp-smoothing-techniques"],
        recommended: ["nlp-limitations-of-statistical-language-models", "nlp-introduction-to-word-embeddings"]
      },
      {
        id: 37,
        order: 6,
        slug: "nlp-limitations-of-statistical-language-models",
        title: "Limitations of Statistical Language Models",
        shortTitle: "Limitations of Statistical Lan...",
        readingTime: 13,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the scalability and sparsity issues that led to the development of neural language models.",
        prerequisites: ["nlp-perplexity-and-language-model-evaluation", "nlp-smoothing-techniques"],
        related: ["nlp-perplexity-and-language-model-evaluation", "nlp-introduction-to-word-embeddings"],
        recommended: ["nlp-introduction-to-word-embeddings", "nlp-word2vec"]
      }
    ]
  },
  {
    id: "word-embeddings",
    title: "Word Embeddings",
    order: 7,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 38,
        order: 1,
        slug: "nlp-introduction-to-word-embeddings",
        title: "Introduction to Word Embeddings",
        shortTitle: "Introduction to Word Embedding...",
        readingTime: 14,
        tags: ["natural language processing", "nlp", "artificial intelligence", "word embeddings", "deep learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to dense vector representations of words that capture semantic and syntactic relationships.",
        prerequisites: ["nlp-limitations-of-statistical-language-models", "nlp-perplexity-and-language-model-evaluation"],
        related: ["nlp-word2vec", "nlp-limitations-of-statistical-language-models"],
        recommended: ["nlp-word2vec", "nlp-cbow-and-skip-gram"]
      },
      {
        id: 39,
        order: 2,
        slug: "nlp-word2vec",
        title: "Word2Vec",
        shortTitle: "Word2Vec",
        readingTime: 15,
        tags: ["natural language processing", "nlp", "artificial intelligence", "word embeddings", "deep learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the Word2Vec algorithm, a groundbreaking technique for learning high-quality word embeddings from large corpora.",
        prerequisites: ["nlp-introduction-to-word-embeddings", "nlp-limitations-of-statistical-language-models"],
        related: ["nlp-cbow-and-skip-gram", "nlp-introduction-to-word-embeddings"],
        recommended: ["nlp-cbow-and-skip-gram", "nlp-glove"]
      },
      {
        id: 40,
        order: 3,
        slug: "nlp-cbow-and-skip-gram",
        title: "CBOW and Skip-Gram",
        shortTitle: "CBOW and Skip-Gram",
        readingTime: 8,
        tags: ["natural language processing", "nlp", "artificial intelligence", "word embeddings", "deep learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Compare the Continuous Bag of Words and Skip-Gram architectures used in training Word2Vec models.",
        prerequisites: ["nlp-word2vec", "nlp-introduction-to-word-embeddings"],
        related: ["nlp-glove", "nlp-word2vec"],
        recommended: ["nlp-glove", "nlp-fasttext"]
      },
      {
        id: 41,
        order: 4,
        slug: "nlp-glove",
        title: "GloVe",
        shortTitle: "GloVe",
        readingTime: 9,
        tags: ["natural language processing", "nlp", "artificial intelligence", "word embeddings", "deep learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand Global Vectors for Word Representation, an alternative embedding method that leverages global co-occurrence statistics.",
        prerequisites: ["nlp-cbow-and-skip-gram", "nlp-word2vec"],
        related: ["nlp-fasttext", "nlp-cbow-and-skip-gram"],
        recommended: ["nlp-fasttext", "nlp-contextual-vs-static-word-embeddings"]
      },
      {
        id: 42,
        order: 5,
        slug: "nlp-fasttext",
        title: "FastText",
        shortTitle: "FastText",
        readingTime: 10,
        tags: ["natural language processing", "nlp", "artificial intelligence", "word embeddings", "deep learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how FastText improves upon Word2Vec by incorporating subword information to handle out-of-vocabulary words.",
        prerequisites: ["nlp-glove", "nlp-cbow-and-skip-gram"],
        related: ["nlp-contextual-vs-static-word-embeddings", "nlp-glove"],
        recommended: ["nlp-contextual-vs-static-word-embeddings", "nlp-nlp-with-machine-learning"]
      },
      {
        id: 43,
        order: 6,
        slug: "nlp-contextual-vs-static-word-embeddings",
        title: "Contextual vs Static Word Embeddings",
        shortTitle: "Contextual vs Static Word Embe...",
        readingTime: 11,
        tags: ["natural language processing", "nlp", "artificial intelligence", "word embeddings", "deep learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the evolution from static embeddings like Word2Vec to dynamic, context-aware embeddings like BERT.",
        prerequisites: ["nlp-fasttext", "nlp-glove"],
        related: ["nlp-fasttext", "nlp-nlp-with-machine-learning"],
        recommended: ["nlp-nlp-with-machine-learning", "nlp-text-classification"]
      }
    ]
  },
  {
    id: "classical-machine-learning-for-nlp",
    title: "Classical Machine Learning for NLP",
    order: 8,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 44,
        order: 1,
        slug: "nlp-nlp-with-machine-learning",
        title: "NLP with Machine Learning",
        shortTitle: "NLP with Machine Learning",
        readingTime: 12,
        tags: ["natural language processing", "nlp", "artificial intelligence", "nlp fundamentals", "machine learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore how classical machine learning algorithms are applied to solve various natural language processing tasks.",
        prerequisites: ["nlp-contextual-vs-static-word-embeddings", "nlp-fasttext"],
        related: ["nlp-text-classification", "nlp-contextual-vs-static-word-embeddings"],
        recommended: ["nlp-text-classification", "nlp-naive-bayes-for-text-classification"]
      },
      {
        id: 45,
        order: 2,
        slug: "nlp-text-classification",
        title: "Text Classification",
        shortTitle: "Text Classification",
        readingTime: 13,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text classification", "nlp applications"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn the fundamentals of text classification, a core NLP task for categorizing documents into predefined classes.",
        prerequisites: ["nlp-nlp-with-machine-learning", "nlp-contextual-vs-static-word-embeddings"],
        related: ["nlp-naive-bayes-for-text-classification", "nlp-nlp-with-machine-learning"],
        recommended: ["nlp-naive-bayes-for-text-classification", "nlp-logistic-regression-for-nlp"]
      },
      {
        id: 46,
        order: 3,
        slug: "nlp-naive-bayes-for-text-classification",
        title: "Naive Bayes for Text Classification",
        shortTitle: "Naive Bayes for Text Classific...",
        readingTime: 14,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text classification", "nlp applications"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how the Naive Bayes algorithm uses probability to perform fast and effective text classification.",
        prerequisites: ["nlp-text-classification", "nlp-nlp-with-machine-learning"],
        related: ["nlp-logistic-regression-for-nlp", "nlp-text-classification"],
        recommended: ["nlp-logistic-regression-for-nlp", "nlp-support-vector-machines-for-nlp"]
      },
      {
        id: 47,
        order: 4,
        slug: "nlp-logistic-regression-for-nlp",
        title: "Logistic Regression for NLP",
        shortTitle: "Logistic Regression for NLP",
        readingTime: 15,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text classification", "nlp applications"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to apply logistic regression with TF-IDF features for binary and multiclass text classification.",
        prerequisites: ["nlp-naive-bayes-for-text-classification", "nlp-text-classification"],
        related: ["nlp-support-vector-machines-for-nlp", "nlp-naive-bayes-for-text-classification"],
        recommended: ["nlp-support-vector-machines-for-nlp", "nlp-feature-selection-for-text-data"]
      },
      {
        id: 48,
        order: 5,
        slug: "nlp-support-vector-machines-for-nlp",
        title: "Support Vector Machines for NLP",
        shortTitle: "Support Vector Machines for NL...",
        readingTime: 8,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text classification", "nlp applications"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover how Support Vector Machines can be used to find optimal hyperplanes for separating text data in high-dimensional spaces.",
        prerequisites: ["nlp-logistic-regression-for-nlp", "nlp-naive-bayes-for-text-classification"],
        related: ["nlp-feature-selection-for-text-data", "nlp-logistic-regression-for-nlp"],
        recommended: ["nlp-feature-selection-for-text-data", "nlp-why-sequence-models-are-needed"]
      },
      {
        id: 49,
        order: 6,
        slug: "nlp-feature-selection-for-text-data",
        title: "Feature Selection for Text Data",
        shortTitle: "Feature Selection for Text Dat...",
        readingTime: 9,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text classification", "nlp applications"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master techniques for selecting the most informative features to reduce dimensionality and improve model performance.",
        prerequisites: ["nlp-support-vector-machines-for-nlp", "nlp-logistic-regression-for-nlp"],
        related: ["nlp-support-vector-machines-for-nlp", "nlp-why-sequence-models-are-needed"],
        recommended: ["nlp-why-sequence-models-are-needed", "nlp-recurrent-neural-networks-for-nlp"]
      }
    ]
  },
  {
    id: "sequence-models-for-nlp",
    title: "Sequence Models for NLP",
    order: 9,
    difficulty: "Advanced",
    lessons: [
      {
        id: 50,
        order: 1,
        slug: "nlp-why-sequence-models-are-needed",
        title: "Why Sequence Models are Needed",
        shortTitle: "Why Sequence Models are Needed",
        readingTime: 10,
        tags: ["natural language processing", "nlp", "artificial intelligence", "sequence models", "deep learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the limitations of feedforward networks and why sequence models are essential for processing ordered data like text.",
        prerequisites: ["nlp-feature-selection-for-text-data", "nlp-support-vector-machines-for-nlp"],
        related: ["nlp-recurrent-neural-networks-for-nlp", "nlp-feature-selection-for-text-data"],
        recommended: ["nlp-recurrent-neural-networks-for-nlp", "nlp-long-short-term-memory-networks"]
      },
      {
        id: 51,
        order: 2,
        slug: "nlp-recurrent-neural-networks-for-nlp",
        title: "Recurrent Neural Networks for NLP",
        shortTitle: "Recurrent Neural Networks for ...",
        readingTime: 11,
        tags: ["natural language processing", "nlp", "artificial intelligence", "sequence models", "deep learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to RNNs and how their hidden state allows them to maintain a memory of previous inputs in a sequence.",
        prerequisites: ["nlp-why-sequence-models-are-needed", "nlp-feature-selection-for-text-data"],
        related: ["nlp-long-short-term-memory-networks", "nlp-why-sequence-models-are-needed"],
        recommended: ["nlp-long-short-term-memory-networks", "nlp-gated-recurrent-units"]
      },
      {
        id: 52,
        order: 3,
        slug: "nlp-long-short-term-memory-networks",
        title: "Long Short-Term Memory Networks",
        shortTitle: "Long Short-Term Memory Network...",
        readingTime: 12,
        tags: ["natural language processing", "nlp", "artificial intelligence", "sequence models", "deep learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master LSTMs, a specialized RNN architecture designed to overcome the vanishing gradient problem and learn long-term dependencies.",
        prerequisites: ["nlp-recurrent-neural-networks-for-nlp", "nlp-why-sequence-models-are-needed"],
        related: ["nlp-gated-recurrent-units", "nlp-recurrent-neural-networks-for-nlp"],
        recommended: ["nlp-gated-recurrent-units", "nlp-bidirectional-rnns"]
      },
      {
        id: 53,
        order: 4,
        slug: "nlp-gated-recurrent-units",
        title: "Gated Recurrent Units",
        shortTitle: "Gated Recurrent Units",
        readingTime: 13,
        tags: ["natural language processing", "nlp", "artificial intelligence", "sequence models", "deep learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand GRUs, a streamlined alternative to LSTMs that offers similar performance with fewer parameters.",
        prerequisites: ["nlp-long-short-term-memory-networks", "nlp-recurrent-neural-networks-for-nlp"],
        related: ["nlp-bidirectional-rnns", "nlp-long-short-term-memory-networks"],
        recommended: ["nlp-bidirectional-rnns", "nlp-sequence-to-sequence-models"]
      },
      {
        id: 54,
        order: 5,
        slug: "nlp-bidirectional-rnns",
        title: "Bidirectional RNNs",
        shortTitle: "Bidirectional RNNs",
        readingTime: 14,
        tags: ["natural language processing", "nlp", "artificial intelligence", "sequence models", "deep learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how bidirectional RNNs process sequences in both forward and backward directions to capture full context.",
        prerequisites: ["nlp-gated-recurrent-units", "nlp-long-short-term-memory-networks"],
        related: ["nlp-sequence-to-sequence-models", "nlp-gated-recurrent-units"],
        recommended: ["nlp-sequence-to-sequence-models", "nlp-encoder-decoder-architecture"]
      },
      {
        id: 55,
        order: 6,
        slug: "nlp-sequence-to-sequence-models",
        title: "Sequence-to-Sequence Models",
        shortTitle: "Sequence-to-Sequence Models",
        readingTime: 15,
        tags: ["natural language processing", "nlp", "artificial intelligence", "sequence models", "deep learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the Seq2Seq architecture, the foundation for tasks like machine translation and text summarization.",
        prerequisites: ["nlp-bidirectional-rnns", "nlp-gated-recurrent-units"],
        related: ["nlp-encoder-decoder-architecture", "nlp-bidirectional-rnns"],
        recommended: ["nlp-encoder-decoder-architecture", "nlp-the-need-for-attention-mechanisms"]
      },
      {
        id: 56,
        order: 7,
        slug: "nlp-encoder-decoder-architecture",
        title: "Encoder-Decoder Architecture",
        shortTitle: "Encoder-Decoder Architecture",
        readingTime: 8,
        tags: ["natural language processing", "nlp", "artificial intelligence", "sequence models", "deep learning"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how the encoder compresses input sequences into a context vector and the decoder generates the output sequence.",
        prerequisites: ["nlp-sequence-to-sequence-models", "nlp-bidirectional-rnns"],
        related: ["nlp-sequence-to-sequence-models", "nlp-the-need-for-attention-mechanisms"],
        recommended: ["nlp-the-need-for-attention-mechanisms", "nlp-attention-mechanism"]
      }
    ]
  },
  {
    id: "attention-and-transformers",
    title: "Attention and Transformers",
    order: 10,
    difficulty: "Advanced",
    lessons: [
      {
        id: 57,
        order: 1,
        slug: "nlp-the-need-for-attention-mechanisms",
        title: "The Need for Attention Mechanisms",
        shortTitle: "The Need for Attention Mechani...",
        readingTime: 9,
        tags: ["natural language processing", "nlp", "artificial intelligence", "transformers", "large language models"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the bottleneck of the fixed-length context vector in Seq2Seq models and how attention solves this problem.",
        prerequisites: ["nlp-encoder-decoder-architecture", "nlp-sequence-to-sequence-models"],
        related: ["nlp-attention-mechanism", "nlp-encoder-decoder-architecture"],
        recommended: ["nlp-attention-mechanism", "nlp-self-attention"]
      },
      {
        id: 58,
        order: 2,
        slug: "nlp-attention-mechanism",
        title: "Attention Mechanism",
        shortTitle: "Attention Mechanism",
        readingTime: 10,
        tags: ["natural language processing", "nlp", "artificial intelligence", "transformers", "large language models"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn the core concepts of the attention mechanism, which allows models to focus on relevant parts of the input sequence.",
        prerequisites: ["nlp-the-need-for-attention-mechanisms", "nlp-encoder-decoder-architecture"],
        related: ["nlp-self-attention", "nlp-the-need-for-attention-mechanisms"],
        recommended: ["nlp-self-attention", "nlp-transformer-architecture"]
      },
      {
        id: 59,
        order: 3,
        slug: "nlp-self-attention",
        title: "Self-Attention",
        shortTitle: "Self-Attention",
        readingTime: 11,
        tags: ["natural language processing", "nlp", "artificial intelligence", "transformers", "large language models"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master self-attention, the mechanism that allows a sequence to relate different positions of a single sequence to compute a representation.",
        prerequisites: ["nlp-attention-mechanism", "nlp-the-need-for-attention-mechanisms"],
        related: ["nlp-transformer-architecture", "nlp-attention-mechanism"],
        recommended: ["nlp-transformer-architecture", "nlp-positional-encoding"]
      },
      {
        id: 60,
        order: 4,
        slug: "nlp-transformer-architecture",
        title: "Transformer Architecture",
        shortTitle: "Transformer Architecture",
        readingTime: 12,
        tags: ["natural language processing", "nlp", "artificial intelligence", "transformers", "large language models"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Dive into the Transformer architecture, which relies entirely on attention mechanisms and has revolutionized NLP.",
        prerequisites: ["nlp-self-attention", "nlp-attention-mechanism"],
        related: ["nlp-positional-encoding", "nlp-self-attention"],
        recommended: ["nlp-positional-encoding", "nlp-encoder-and-decoder-transformers"]
      },
      {
        id: 61,
        order: 5,
        slug: "nlp-positional-encoding",
        title: "Positional Encoding",
        shortTitle: "Positional Encoding",
        readingTime: 13,
        tags: ["natural language processing", "nlp", "artificial intelligence", "transformers", "large language models"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how positional encoding injects information about the relative or absolute position of tokens in a sequence.",
        prerequisites: ["nlp-transformer-architecture", "nlp-self-attention"],
        related: ["nlp-encoder-and-decoder-transformers", "nlp-transformer-architecture"],
        recommended: ["nlp-encoder-and-decoder-transformers", "nlp-transformers-vs-rnns"]
      },
      {
        id: 62,
        order: 6,
        slug: "nlp-encoder-and-decoder-transformers",
        title: "Encoder and Decoder Transformers",
        shortTitle: "Encoder and Decoder Transforme...",
        readingTime: 14,
        tags: ["natural language processing", "nlp", "artificial intelligence", "transformers", "large language models"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the specific roles of the encoder and decoder stacks within the Transformer architecture.",
        prerequisites: ["nlp-positional-encoding", "nlp-transformer-architecture"],
        related: ["nlp-transformers-vs-rnns", "nlp-positional-encoding"],
        recommended: ["nlp-transformers-vs-rnns", "nlp-introduction-to-pretrained-language-models"]
      },
      {
        id: 63,
        order: 7,
        slug: "nlp-transformers-vs-rnns",
        title: "Transformers vs RNNs",
        shortTitle: "Transformers vs RNNs",
        readingTime: 15,
        tags: ["natural language processing", "nlp", "artificial intelligence", "transformers", "large language models"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Compare the parallelization capabilities and performance of Transformers against traditional RNN-based models.",
        prerequisites: ["nlp-encoder-and-decoder-transformers", "nlp-positional-encoding"],
        related: ["nlp-encoder-and-decoder-transformers", "nlp-introduction-to-pretrained-language-models"],
        recommended: ["nlp-introduction-to-pretrained-language-models", "nlp-transfer-learning-in-nlp"]
      }
    ]
  },
  {
    id: "pretrained-language-models",
    title: "Pretrained Language Models",
    order: 11,
    difficulty: "Advanced",
    lessons: [
      {
        id: 64,
        order: 1,
        slug: "nlp-introduction-to-pretrained-language-models",
        title: "Introduction to Pretrained Language Models",
        shortTitle: "Introduction to Pretrained Lan...",
        readingTime: 8,
        tags: ["natural language processing", "nlp", "artificial intelligence", "transformers", "large language models"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get introduced to the paradigm shift of pretraining large models on massive corpora before fine-tuning for specific tasks.",
        prerequisites: ["nlp-transformers-vs-rnns", "nlp-encoder-and-decoder-transformers"],
        related: ["nlp-transfer-learning-in-nlp", "nlp-transformers-vs-rnns"],
        recommended: ["nlp-transfer-learning-in-nlp", "nlp-bert-and-bidirectional-language-understanding"]
      },
      {
        id: 65,
        order: 2,
        slug: "nlp-transfer-learning-in-nlp",
        title: "Transfer Learning in NLP",
        shortTitle: "Transfer Learning in NLP",
        readingTime: 9,
        tags: ["natural language processing", "nlp", "artificial intelligence", "transformers", "large language models"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how transfer learning allows NLP models to leverage knowledge learned from one task to improve performance on another.",
        prerequisites: ["nlp-introduction-to-pretrained-language-models", "nlp-transformers-vs-rnns"],
        related: ["nlp-bert-and-bidirectional-language-understanding", "nlp-introduction-to-pretrained-language-models"],
        recommended: ["nlp-bert-and-bidirectional-language-understanding", "nlp-gpt-and-autoregressive-language-modeling"]
      },
      {
        id: 66,
        order: 3,
        slug: "nlp-bert-and-bidirectional-language-understanding",
        title: "BERT and Bidirectional Language Understanding",
        shortTitle: "BERT and Bidirectional Languag...",
        readingTime: 10,
        tags: ["natural language processing", "nlp", "artificial intelligence", "transformers", "large language models"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore BERT, a groundbreaking bidirectional transformer model that set new standards for NLP benchmarks.",
        prerequisites: ["nlp-transfer-learning-in-nlp", "nlp-introduction-to-pretrained-language-models"],
        related: ["nlp-gpt-and-autoregressive-language-modeling", "nlp-transfer-learning-in-nlp"],
        recommended: ["nlp-gpt-and-autoregressive-language-modeling", "nlp-encoder-decoder-and-encoder-decoder-models"]
      },
      {
        id: 67,
        order: 4,
        slug: "nlp-gpt-and-autoregressive-language-modeling",
        title: "GPT and Autoregressive Language Modeling",
        shortTitle: "GPT and Autoregressive Languag...",
        readingTime: 11,
        tags: ["natural language processing", "nlp", "artificial intelligence", "transformers", "large language models"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the Generative Pre-trained Transformer (GPT) architecture and its strength in autoregressive text generation.",
        prerequisites: ["nlp-bert-and-bidirectional-language-understanding", "nlp-transfer-learning-in-nlp"],
        related: ["nlp-encoder-decoder-and-encoder-decoder-models", "nlp-bert-and-bidirectional-language-understanding"],
        recommended: ["nlp-encoder-decoder-and-encoder-decoder-models", "nlp-fine-tuning-pretrained-nlp-models"]
      },
      {
        id: 68,
        order: 5,
        slug: "nlp-encoder-decoder-and-encoder-decoder-models",
        title: "Encoder, Decoder, and Encoder-Decoder Models",
        shortTitle: "Encoder, Decoder, and Encoder-...",
        readingTime: 12,
        tags: ["natural language processing", "nlp", "artificial intelligence", "transformers", "large language models"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Categorize modern pretrained models based on their architecture and understand their ideal use cases.",
        prerequisites: ["nlp-gpt-and-autoregressive-language-modeling", "nlp-bert-and-bidirectional-language-understanding"],
        related: ["nlp-fine-tuning-pretrained-nlp-models", "nlp-gpt-and-autoregressive-language-modeling"],
        recommended: ["nlp-fine-tuning-pretrained-nlp-models", "nlp-hugging-face-transformers"]
      },
      {
        id: 69,
        order: 6,
        slug: "nlp-fine-tuning-pretrained-nlp-models",
        title: "Fine-Tuning Pretrained NLP Models",
        shortTitle: "Fine-Tuning Pretrained NLP Mod...",
        readingTime: 13,
        tags: ["natural language processing", "nlp", "artificial intelligence", "transformers", "large language models"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn the practical steps and best practices for fine-tuning large pretrained models on your specific downstream tasks.",
        prerequisites: ["nlp-encoder-decoder-and-encoder-decoder-models", "nlp-gpt-and-autoregressive-language-modeling"],
        related: ["nlp-hugging-face-transformers", "nlp-encoder-decoder-and-encoder-decoder-models"],
        recommended: ["nlp-hugging-face-transformers", "nlp-named-entity-recognition"]
      },
      {
        id: 70,
        order: 7,
        slug: "nlp-hugging-face-transformers",
        title: "Hugging Face Transformers",
        shortTitle: "Hugging Face Transformers",
        readingTime: 14,
        tags: ["natural language processing", "nlp", "artificial intelligence", "python nlp", "nlp libraries"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the Hugging Face `transformers` library, the industry standard for working with state-of-the-art NLP models.",
        prerequisites: ["nlp-fine-tuning-pretrained-nlp-models", "nlp-encoder-decoder-and-encoder-decoder-models"],
        related: ["nlp-fine-tuning-pretrained-nlp-models", "nlp-named-entity-recognition"],
        recommended: ["nlp-named-entity-recognition", "nlp-sentiment-analysis"]
      }
    ]
  },
  {
    id: "core-nlp-tasks-and-applications",
    title: "Core NLP Tasks and Applications",
    order: 12,
    difficulty: "Advanced",
    lessons: [
      {
        id: 71,
        order: 1,
        slug: "nlp-named-entity-recognition",
        title: "Named Entity Recognition",
        shortTitle: "Named Entity Recognition",
        readingTime: 15,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text classification", "nlp applications"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to identify and classify key entities like names, organizations, and locations in unstructured text.",
        prerequisites: ["nlp-hugging-face-transformers", "nlp-fine-tuning-pretrained-nlp-models"],
        related: ["nlp-sentiment-analysis", "nlp-hugging-face-transformers"],
        recommended: ["nlp-sentiment-analysis", "nlp-text-classification"]
      },
      {
        id: 72,
        order: 2,
        slug: "nlp-sentiment-analysis",
        title: "Sentiment Analysis",
        shortTitle: "Sentiment Analysis",
        readingTime: 8,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text classification", "nlp applications"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how to determine the emotional tone or opinion expressed in a piece of text, from product reviews to social media.",
        prerequisites: ["nlp-named-entity-recognition", "nlp-hugging-face-transformers"],
        related: ["nlp-text-classification", "nlp-named-entity-recognition"],
        recommended: ["nlp-text-classification", "nlp-text-summarization"]
      },
      {
        id: 73,
        order: 3,
        slug: "nlp-text-classification",
        title: "Text Classification",
        shortTitle: "Text Classification",
        readingTime: 9,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text classification", "nlp applications"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Apply modern NLP techniques to build robust text classification systems for spam detection, topic labeling, and more.",
        prerequisites: ["nlp-sentiment-analysis", "nlp-named-entity-recognition"],
        related: ["nlp-text-summarization", "nlp-sentiment-analysis"],
        recommended: ["nlp-text-summarization", "nlp-machine-translation"]
      },
      {
        id: 74,
        order: 4,
        slug: "nlp-text-summarization",
        title: "Text Summarization",
        shortTitle: "Text Summarization",
        readingTime: 10,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text classification", "nlp applications"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore extractive and abstractive text summarization techniques for condensing long documents into concise summaries.",
        prerequisites: ["nlp-text-classification", "nlp-sentiment-analysis"],
        related: ["nlp-machine-translation", "nlp-text-classification"],
        recommended: ["nlp-machine-translation", "nlp-question-answering"]
      },
      {
        id: 75,
        order: 5,
        slug: "nlp-machine-translation",
        title: "Machine Translation",
        shortTitle: "Machine Translation",
        readingTime: 11,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text classification", "nlp applications"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the architecture and challenges of building neural machine translation systems for converting text between languages.",
        prerequisites: ["nlp-text-summarization", "nlp-text-classification"],
        related: ["nlp-question-answering", "nlp-text-summarization"],
        recommended: ["nlp-question-answering", "nlp-text-generation"]
      },
      {
        id: 76,
        order: 6,
        slug: "nlp-question-answering",
        title: "Question Answering",
        shortTitle: "Question Answering",
        readingTime: 12,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text classification", "nlp applications"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to build systems that can read a context and accurately answer natural language questions based on that context.",
        prerequisites: ["nlp-machine-translation", "nlp-text-summarization"],
        related: ["nlp-text-generation", "nlp-machine-translation"],
        recommended: ["nlp-text-generation", "nlp-building-an-nlp-pipeline-with-python"]
      },
      {
        id: 77,
        order: 7,
        slug: "nlp-text-generation",
        title: "Text Generation",
        shortTitle: "Text Generation",
        readingTime: 13,
        tags: ["natural language processing", "nlp", "artificial intelligence", "text classification", "nlp applications"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the techniques and ethical considerations behind using language models to generate coherent and contextually relevant text.",
        prerequisites: ["nlp-question-answering", "nlp-machine-translation"],
        related: ["nlp-question-answering", "nlp-building-an-nlp-pipeline-with-python"],
        recommended: ["nlp-building-an-nlp-pipeline-with-python", "nlp-nltk-for-natural-language-processing"]
      }
    ]
  },
  {
    id: "modern-nlp-systems-and-practical-development",
    title: "Modern NLP Systems and Practical Development",
    order: 13,
    difficulty: "Advanced",
    lessons: [
      {
        id: 78,
        order: 1,
        slug: "nlp-building-an-nlp-pipeline-with-python",
        title: "Building an NLP Pipeline with Python",
        shortTitle: "Building an NLP Pipeline with ...",
        readingTime: 14,
        tags: ["natural language processing", "nlp", "artificial intelligence", "python nlp", "nlp libraries"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to orchestrate all the steps of an NLP project into a cohesive, reproducible Python pipeline.",
        prerequisites: ["nlp-text-generation", "nlp-question-answering"],
        related: ["nlp-nltk-for-natural-language-processing", "nlp-text-generation"],
        recommended: ["nlp-nltk-for-natural-language-processing", "nlp-spacy-for-nlp"]
      },
      {
        id: 79,
        order: 2,
        slug: "nlp-nltk-for-natural-language-processing",
        title: "NLTK for Natural Language Processing",
        shortTitle: "NLTK for Natural Language Proc...",
        readingTime: 15,
        tags: ["natural language processing", "nlp", "artificial intelligence", "python nlp", "nlp libraries"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get hands-on experience with the Natural Language Toolkit (NLTK), a classic library for NLP research and education.",
        prerequisites: ["nlp-building-an-nlp-pipeline-with-python", "nlp-text-generation"],
        related: ["nlp-spacy-for-nlp", "nlp-building-an-nlp-pipeline-with-python"],
        recommended: ["nlp-spacy-for-nlp", "nlp-working-with-hugging-face-datasets"]
      },
      {
        id: 80,
        order: 3,
        slug: "nlp-spacy-for-nlp",
        title: "spaCy for NLP",
        shortTitle: "spaCy for NLP",
        readingTime: 8,
        tags: ["natural language processing", "nlp", "artificial intelligence", "python nlp", "nlp libraries"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master spaCy, an industrial-strength NLP library optimized for speed and production-ready applications.",
        prerequisites: ["nlp-nltk-for-natural-language-processing", "nlp-building-an-nlp-pipeline-with-python"],
        related: ["nlp-working-with-hugging-face-datasets", "nlp-nltk-for-natural-language-processing"],
        recommended: ["nlp-working-with-hugging-face-datasets", "nlp-evaluating-nlp-models"]
      },
      {
        id: 81,
        order: 4,
        slug: "nlp-working-with-hugging-face-datasets",
        title: "Working with Hugging Face Datasets",
        shortTitle: "Working with Hugging Face Data...",
        readingTime: 9,
        tags: ["natural language processing", "nlp", "artificial intelligence", "python nlp", "nlp libraries"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to efficiently load, process, and manage large-scale text datasets using the Hugging Face `datasets` library.",
        prerequisites: ["nlp-spacy-for-nlp", "nlp-nltk-for-natural-language-processing"],
        related: ["nlp-evaluating-nlp-models", "nlp-spacy-for-nlp"],
        recommended: ["nlp-evaluating-nlp-models", "nlp-saving-and-loading-nlp-models"]
      },
      {
        id: 82,
        order: 5,
        slug: "nlp-evaluating-nlp-models",
        title: "Evaluating NLP Models",
        shortTitle: "Evaluating NLP Models",
        readingTime: 10,
        tags: ["natural language processing", "nlp", "artificial intelligence", "python nlp", "nlp libraries"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the key metrics like BLEU, ROUGE, and F1-score used to evaluate the performance of NLP models.",
        prerequisites: ["nlp-working-with-hugging-face-datasets", "nlp-spacy-for-nlp"],
        related: ["nlp-saving-and-loading-nlp-models", "nlp-working-with-hugging-face-datasets"],
        recommended: ["nlp-saving-and-loading-nlp-models", "nlp-deploying-an-nlp-model"]
      },
      {
        id: 83,
        order: 6,
        slug: "nlp-saving-and-loading-nlp-models",
        title: "Saving and Loading NLP Models",
        shortTitle: "Saving and Loading NLP Models",
        readingTime: 11,
        tags: ["natural language processing", "nlp", "artificial intelligence", "python nlp", "nlp libraries"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn best practices for serializing, versioning, and deploying your trained NLP models for production use.",
        prerequisites: ["nlp-evaluating-nlp-models", "nlp-working-with-hugging-face-datasets"],
        related: ["nlp-deploying-an-nlp-model", "nlp-evaluating-nlp-models"],
        recommended: ["nlp-deploying-an-nlp-model", "nlp-building-end-to-end-nlp-applications"]
      },
      {
        id: 84,
        order: 7,
        slug: "nlp-deploying-an-nlp-model",
        title: "Deploying an NLP Model",
        shortTitle: "Deploying an NLP Model",
        readingTime: 12,
        tags: ["natural language processing", "nlp", "artificial intelligence", "python nlp", "nlp libraries"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore strategies for wrapping your NLP model in an API and deploying it to serve real-time predictions at scale.",
        prerequisites: ["nlp-saving-and-loading-nlp-models", "nlp-evaluating-nlp-models"],
        related: ["nlp-building-end-to-end-nlp-applications", "nlp-saving-and-loading-nlp-models"],
        recommended: ["nlp-building-end-to-end-nlp-applications", "nlp-building-an-nlp-pipeline-with-python"]
      },
      {
        id: 85,
        order: 8,
        slug: "nlp-building-end-to-end-nlp-applications",
        title: "Building End-to-End NLP Applications",
        shortTitle: "Building End-to-End NLP Applic...",
        readingTime: 13,
        tags: ["natural language processing", "nlp", "artificial intelligence", "python nlp", "nlp libraries"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Bring everything together to design, build, and deploy a complete, production-ready NLP application from scratch.",
        prerequisites: ["nlp-deploying-an-nlp-model", "nlp-saving-and-loading-nlp-models"],
        related: ["nlp-deploying-an-nlp-model", "nlp-building-an-nlp-pipeline-with-python"],
        recommended: ["nlp-building-an-nlp-pipeline-with-python", "nlp-nltk-for-natural-language-processing"]
      }
    ]
  }
];

export const resources = [
  {
    id: "nlp-libraries-and-ecosystem",
    title: "NLP Libraries and Ecosystem",
    order: 1,
    items: [
      {
        id: 86,
        order: 1,
        slug: "nlp-nltk-vs-spacy",
        title: "NLTK vs spaCy",
        shortTitle: "NLTK vs spaCy",
        type: "article",
        readingTime: 10,
        tags: ["nlp", "libraries", "nltk", "spacy", "python", "text processing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Compare NLTK and spaCy to understand their strengths, weaknesses, and when to use each for natural language processing tasks."
      },
      {
        id: 87,
        order: 2,
        slug: "nlp-textblob-and-gensim",
        title: "TextBlob and Gensim",
        shortTitle: "TextBlob & Gensim",
        type: "article",
        readingTime: 8,
        tags: ["nlp", "libraries", "textblob", "gensim", "topic modeling", "sentiment analysis"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore TextBlob for simplified text processing and Gensim for topic modeling, document similarity, and word embeddings."
      },
      {
        id: 88,
        order: 3,
        slug: "nlp-hugging-face-ecosystem",
        title: "Hugging Face Ecosystem",
        shortTitle: "Hugging Face",
        type: "article",
        readingTime: 12,
        tags: ["nlp", "hugging face", "transformers", "pretrained models", "tokenizers", "ecosystem"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Navigate the Hugging Face ecosystem including Transformers, Datasets, and Tokenizers for state-of-the-art NLP model development."
      },
      {
        id: 89,
        order: 4,
        slug: "nlp-scikit-learn-for-nlp",
        title: "scikit-learn for NLP",
        shortTitle: "scikit-learn NLP",
        type: "article",
        readingTime: 10,
        tags: ["nlp", "scikit-learn", "machine learning", "feature extraction", "text classification", "vectorization"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to leverage scikit-learn for text vectorization, classification, clustering, and traditional machine learning NLP pipelines."
      },
      {
        id: 90,
        order: 5,
        slug: "nlp-choosing-the-right-library",
        title: "Choosing the Right NLP Library",
        shortTitle: "Choosing Libraries",
        type: "article",
        readingTime: 10,
        tags: ["nlp", "libraries", "comparison", "best practices", "tools", "framework selection"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "A practical guide to selecting the most suitable NLP library based on your project requirements, scale, and constraints."
      },
    ]
  },

  {
    id: "nlp-datasets-and-data-sources",
    title: "NLP Datasets and Data Sources",
    order: 2,
    items: [
      {
        id: 91,
        order: 1,
        slug: "nlp-finding-datasets",
        title: "Finding NLP Datasets",
        shortTitle: "Finding Datasets",
        type: "article",
        readingTime: 8,
        tags: ["nlp", "datasets", "data sources", "resources", "research", "data collection"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover where and how to find high-quality text datasets for various natural language processing tasks and research."
      },
      {
        id: 92,
        order: 2,
        slug: "nlp-common-datasets-and-benchmarks",
        title: "Common NLP Datasets and Benchmarks",
        shortTitle: "Common Benchmarks",
        type: "article",
        readingTime: 10,
        tags: ["nlp", "datasets", "benchmarks", "glue", "squad", "imdb", "evaluation"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Overview of widely-used NLP benchmarks like GLUE, SQuAD, and IMDB for training, fine-tuning, and evaluating language models."
      },
      {
        id: 93,
        order: 3,
        slug: "nlp-creating-custom-datasets",
        title: "Creating Custom Text Datasets",
        shortTitle: "Custom Datasets",
        type: "article",
        readingTime: 10,
        tags: ["nlp", "datasets", "data collection", "custom data", "preparation", "text mining"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn strategies for building custom text datasets tailored to specific domains, languages, and NLP applications."
      },
      {
        id: 94,
        order: 4,
        slug: "nlp-dataset-annotation-and-labeling",
        title: "Dataset Annotation and Labeling",
        shortTitle: "Annotation & Labeling",
        type: "article",
        readingTime: 10,
        tags: ["nlp", "annotation", "labeling", "datasets", "data quality", "crowdsourcing"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand best practices for annotating and labeling text data to ensure reliable training outcomes and model performance."
      },
      {
        id: 95,
        order: 5,
        slug: "nlp-data-quality-and-bias",
        title: "Data Quality and Bias in NLP Datasets",
        shortTitle: "Quality & Bias",
        type: "article",
        readingTime: 12,
        tags: ["nlp", "bias", "data quality", "ethics", "datasets", "fairness", "responsible ai"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Examine issues of data quality, representation, and societal bias in NLP datasets and how to mitigate them effectively."
      },
    ]
  },

  {
    id: "nlp-evaluation-and-analysis",
    title: "NLP Evaluation and Analysis",
    order: 3,
    items: [
      {
        id: 96,
        order: 1,
        slug: "nlp-accuracy-precision-recall-f1",
        title: "Accuracy, Precision, Recall, and F1-Score",
        shortTitle: "Classification Metrics",
        type: "article",
        readingTime: 10,
        tags: ["nlp", "evaluation", "metrics", "precision", "recall", "f1-score", "classification"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master core classification metrics including accuracy, precision, recall, and F1-score for evaluating NLP models."
      },
      {
        id: 97,
        order: 2,
        slug: "nlp-bleu-for-machine-translation",
        title: "BLEU for Machine Translation",
        shortTitle: "BLEU Score",
        type: "article",
        readingTime: 8,
        tags: ["nlp", "bleu", "machine translation", "evaluation", "metrics", "nmt"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the BLEU metric and how it measures the quality of machine-translated text against reference translations."
      },
      {
        id: 98,
        order: 3,
        slug: "nlp-rouge-for-text-summarization",
        title: "ROUGE for Text Summarization",
        shortTitle: "ROUGE Score",
        type: "article",
        readingTime: 8,
        tags: ["nlp", "rouge", "text summarization", "evaluation", "metrics", "content overlap"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how ROUGE metrics evaluate automatic text summarization by comparing overlapping content with human references."
      },
      {
        id: 99,
        order: 4,
        slug: "nlp-perplexity-and-lm-evaluation",
        title: "Perplexity and Language Model Evaluation",
        shortTitle: "Perplexity & LM Eval",
        type: "article",
        readingTime: 10,
        tags: ["nlp", "perplexity", "language models", "evaluation", "metrics", "llm"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore perplexity as a key intrinsic metric for evaluating language model performance, uncertainty, and generalization."
      },
      {
        id: 100,
        order: 5,
        slug: "nlp-human-evaluation",
        title: "Human Evaluation of NLP Systems",
        shortTitle: "Human Evaluation",
        type: "article",
        readingTime: 10,
        tags: ["nlp", "evaluation", "human evaluation", "metrics", "quality assessment", "user study"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover methodologies for conducting human evaluations to assess NLP system outputs beyond automated metrics."
      },
    ]
  },

  {
    id: "nlp-challenges-and-responsible-ai",
    title: "NLP Challenges and Responsible AI",
    order: 4,
    items: [
      {
        id: 101,
        order: 1,
        slug: "nlp-ambiguity-in-natural-language",
        title: "Ambiguity in Natural Language",
        shortTitle: "Language Ambiguity",
        type: "article",
        readingTime: 10,
        tags: ["nlp", "ambiguity", "linguistics", "challenges", "semantics", "syntax"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand lexical, syntactic, and semantic ambiguity and why it remains a fundamental challenge in natural language processing."
      },
      {
        id: 102,
        order: 2,
        slug: "nlp-multilingual-and-low-resource",
        title: "Multilingual and Low-Resource NLP",
        shortTitle: "Multilingual NLP",
        type: "article",
        readingTime: 12,
        tags: ["nlp", "multilingual", "low-resource", "languages", "global nlp", "cross-lingual"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore techniques and challenges in building NLP systems for multiple languages and low-resource settings."
      },
      {
        id: 103,
        order: 3,
        slug: "nlp-bias-in-models",
        title: "Bias in NLP Models",
        shortTitle: "Model Bias",
        type: "article",
        readingTime: 10,
        tags: ["nlp", "bias", "fairness", "responsible ai", "ethics", "model behavior"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Examine sources of bias in NLP models, their societal impact, and approaches to building fairer, more equitable systems."
      },
      {
        id: 104,
        order: 4,
        slug: "nlp-hallucination-and-factuality",
        title: "Hallucination and Factuality",
        shortTitle: "Hallucination",
        type: "article",
        readingTime: 10,
        tags: ["nlp", "hallucination", "factuality", "generative ai", "responsible ai", "truthfulness"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn about hallucination in generative NLP models and methods to improve factuality, grounding, and reliability."
      },
      {
        id: 105,
        order: 5,
        slug: "nlp-privacy-and-ethics",
        title: "Privacy and Ethical Considerations in NLP",
        shortTitle: "Privacy & Ethics",
        type: "article",
        readingTime: 10,
        tags: ["nlp", "privacy", "ethics", "responsible ai", "gdpr", "data protection"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Review privacy risks, consent issues, and ethical guidelines for developing and deploying NLP applications responsibly."
      },
    ]
  },

  {
    id: "nlp-project-ideas-and-further-learning",
    title: "NLP Project Ideas and Further Learning",
    order: 5,
    items: [
      {
        id: 106,
        order: 1,
        slug: "nlp-sentiment-analysis-projects",
        title: "Sentiment Analysis Project Ideas",
        shortTitle: "Sentiment Projects",
        type: "article",
        readingTime: 8,
        tags: ["nlp", "sentiment analysis", "projects", "ideas", "practice", "polarity detection"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Practical project ideas for building sentiment analysis systems on product reviews, social media, and customer feedback."
      },
      {
        id: 107,
        order: 2,
        slug: "nlp-text-classification-projects",
        title: "Text Classification Project Ideas",
        shortTitle: "Text Classification",
        type: "article",
        readingTime: 8,
        tags: ["nlp", "text classification", "projects", "ideas", "practice", "spam detection"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore text classification projects spanning spam detection, topic labeling, intent recognition, and toxic comment detection."
      },
      {
        id: 108,
        order: 3,
        slug: "nlp-chatbot-and-qa-projects",
        title: "Chatbot and Question-Answering Projects",
        shortTitle: "Chatbot & QA Projects",
        type: "article",
        readingTime: 10,
        tags: ["nlp", "chatbot", "question answering", "projects", "conversational ai", "rag"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Build conversational AI projects including rule-based chatbots and retrieval-augmented question-answering systems."
      },
      {
        id: 109,
        order: 4,
        slug: "nlp-summarization-translation-projects",
        title: "Text Summarization and Translation Projects",
        shortTitle: "Summarization & NMT",
        type: "article",
        readingTime: 10,
        tags: ["nlp", "summarization", "machine translation", "projects", "seq2seq", "abstractive"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Implement projects for automatic text summarization and neural machine translation using modern encoder-decoder architectures."
      },
      {
        id: 110,
        order: 5,
        slug: "nlp-building-apps-with-transformers",
        title: "Building NLP Applications with Transformers",
        shortTitle: "Transformer Apps",
        type: "article",
        readingTime: 12,
        tags: ["nlp", "transformers", "applications", "projects", "hugging face", "deployment"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn to build production-ready NLP applications by fine-tuning and deploying transformer models for real-world use cases."
      },
    ]
  },
];