// ============================================================
// src/registry/lessons/nodejsLessons.js
// STUB — same shape as htmlLessons.js, empty until you fill it in.
// lessonRegistry.js can safely import this right now without
// breaking anything; it'll just show 0 lessons for Node.js until
// you add sections here.
// ============================================================

import { STATUS } from "../../config/constants";

export const tutorialInfo = {
  id: "rest-apis",
  title: "REST APIs Tutorial",
  shortTitle: "REST APIs",
  category: "Backend",
  description: "Master REST APIs from beginner to advanced with comprehensive tutorials covering HTTP, REST architecture, API design, CRUD operations, authentication, authorization, versioning, validation, documentation, testing, security, caching, performance optimization, and real-world API development.",
  icon: "rest-apis",
  difficulty: "Advanced", // course-level badge, separate from per-section defaults
  estimatedHours: 40,
  totalLessons: 73,
  version: "Latest",
  language: "English",
  path: "/rest-apis",
  authorId: "faiz",
  updatedAt: "2026-07-09",
  tags: ["rest api", "restful api", "api", "backend", "http", "json", "crud", "api design", "web services", "authentication", "authorization", "jwt", "oauth", "api security", "api testing", "openapi", "swagger", "postman", "api documentation", "microservices"],
  seo: {
    title: "REST APIs Tutorial - Complete Backend Development Guide | DevSphere",
    description: "Learn REST APIs from scratch with our complete tutorial covering HTTP methods, REST architecture, CRUD operations, API design, authentication, security, documentation, testing, versioning, caching, and production-ready API development.",
    keywords: ["REST APIs Tutorial", "REST API Tutorial", "Learn REST API", "REST API Course", "RESTful API", "RESTful Web Services", "REST Architecture", "REST Principles", "REST Constraints", "Backend Development", "API Development", "Web API", "HTTP Tutorial", "HTTP Methods", "GET POST PUT PATCH DELETE", "CRUD API", "JSON API", "API Design", "API Best Practices", "API Authentication", "JWT Authentication", "OAuth 2.0", "API Authorization", "API Security", "CORS", "Rate Limiting", "API Versioning", "API Validation", "Status Codes", "HTTP Headers", "Request and Response", "API Documentation", "Swagger", "OpenAPI", "Postman", "API Testing", "Caching", "Pagination", "Filtering", "Sorting", "Microservices", "Scalable APIs", "Production REST APIs", "DevSphere"]
  }
};

export const sections = [
    {
    id: "rest-api-fundamentals",
    title: "REST API Fundamentals",
    order: 1,
    difficulty: "Beginner",
    lessons: [
      {
        id: 1,
        order: 1,
        slug: "restapis-what-is-an-api",
        title: "What is an API?",
        shortTitle: "What is an API",
        readingTime: 8,
        tags: ["rest api", "backend", "api development", "web services", "fundamentals", "basics"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn what an API is and how it enables communication between software applications.",
        prerequisites: [],
        related: [],
        recommended: []
      },
      {
        id: 2,
        order: 2,
        slug: "restapis-what-is-a-rest-api",
        title: "What is a REST API?",
        shortTitle: "What is a REST API",
        readingTime: 10,
        tags: ["rest api", "backend", "api development", "web services", "fundamentals", "basics"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand what a REST API is and why it is the most popular architectural style for web services.",
        prerequisites: ["restapis-what-is-an-api"],
        related: ["restapis-history-of-rest", "restapis-rest-vs-http", "restapis-rest-architecture"],
        recommended: ["restapis-history-of-rest", "restapis-rest-vs-http"]
      },
      {
        id: 3,
        order: 3,
        slug: "restapis-history-of-rest",
        title: "History of REST",
        shortTitle: "History of REST",
        readingTime: 8,
        tags: ["rest api", "backend", "api development", "web services", "fundamentals", "basics"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the history and evolution of REST architecture from its origins to modern usage.",
        prerequisites: ["restapis-what-is-a-rest-api", "restapis-what-is-an-api"],
        related: ["restapis-rest-vs-http", "restapis-rest-architecture", "restapis-six-rest-constraints"],
        recommended: ["restapis-rest-vs-http", "restapis-rest-architecture"]
      },
      {
        id: 4,
        order: 4,
        slug: "restapis-rest-vs-http",
        title: "REST vs HTTP",
        shortTitle: "REST vs HTTP",
        readingTime: 10,
        tags: ["rest api", "backend", "http", "protocol", "fundamentals", "basics"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Compare REST architecture with the HTTP protocol to understand their relationship and differences.",
        prerequisites: ["restapis-history-of-rest", "restapis-what-is-a-rest-api"],
        related: ["restapis-rest-architecture", "restapis-six-rest-constraints", "restapis-characteristics"],
        recommended: ["restapis-rest-architecture", "restapis-six-rest-constraints"]
      },
      {
        id: 5,
        order: 5,
        slug: "restapis-rest-architecture",
        title: "REST Architecture",
        shortTitle: "REST Architecture",
        readingTime: 12,
        tags: ["rest api", "backend", "api development", "web services", "fundamentals", "basics"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn the core architectural principles that define RESTful systems and web services.",
        prerequisites: ["restapis-rest-vs-http", "restapis-history-of-rest"],
        related: ["restapis-six-rest-constraints", "restapis-characteristics", "restapis-how-rest-apis-work"],
        recommended: ["restapis-six-rest-constraints", "restapis-characteristics"]
      },
      {
        id: 6,
        order: 6,
        slug: "restapis-six-rest-constraints",
        title: "Six REST Constraints",
        shortTitle: "Six Constraints",
        readingTime: 12,
        tags: ["rest api", "backend", "api development", "web services", "fundamentals", "basics"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the six architectural constraints that make an API truly RESTful.",
        prerequisites: ["restapis-rest-architecture", "restapis-rest-vs-http"],
        related: ["restapis-characteristics", "restapis-how-rest-apis-work", "restapis-lifecycle"],
        recommended: ["restapis-characteristics", "restapis-how-rest-apis-work"]
      },
      {
        id: 7,
        order: 7,
        slug: "restapis-characteristics",
        title: "Characteristics of REST APIs",
        shortTitle: "Characteristics",
        readingTime: 10,
        tags: ["rest api", "backend", "api development", "web services", "fundamentals", "basics"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover the key characteristics that define REST APIs and set them apart from other API styles.",
        prerequisites: ["restapis-six-rest-constraints", "restapis-rest-architecture"],
        related: ["restapis-how-rest-apis-work", "restapis-lifecycle", "restapis-http-request-response"],
        recommended: ["restapis-how-rest-apis-work", "restapis-lifecycle"]
      },
      {
        id: 8,
        order: 8,
        slug: "restapis-how-rest-apis-work",
        title: "How REST APIs Work",
        shortTitle: "How REST Works",
        readingTime: 10,
        tags: ["rest api", "backend", "api development", "web services", "fundamentals", "basics"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the complete request-response cycle and how REST APIs process client requests.",
        prerequisites: ["restapis-characteristics", "restapis-six-rest-constraints"],
        related: ["restapis-lifecycle", "restapis-http-request-response", "restapis-http-methods"],
        recommended: ["restapis-lifecycle", "restapis-http-request-response"]
      },
      {
        id: 9,
        order: 9,
        slug: "restapis-lifecycle",
        title: "REST API Lifecycle",
        shortTitle: "API Lifecycle",
        readingTime: 10,
        tags: ["rest api", "backend", "api development", "web services", "fundamentals", "basics"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn the full lifecycle of a REST API from design and development to deployment and deprecation.",
        prerequisites: ["restapis-how-rest-apis-work", "restapis-characteristics"],
        related: ["restapis-http-request-response", "restapis-http-methods", "restapis-safe-vs-idempotent-methods"],
        recommended: ["restapis-http-request-response", "restapis-http-methods"]
      },
    ]
  },

  {
    id: "http-fundamentals-for-rest",
    title: "HTTP Fundamentals for REST",
    order: 2,
    difficulty: "Beginner",
    lessons: [
      {
        id: 10,
        order: 1,
        slug: "restapis-http-request-response",
        title: "HTTP Request & Response",
        shortTitle: "HTTP Request & Response",
        readingTime: 10,
        tags: ["rest api", "backend", "http", "protocol", "fundamentals", "basics"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the structure and components of HTTP requests and responses in REST communication.",
        prerequisites: ["restapis-lifecycle", "restapis-how-rest-apis-work"],
        related: ["restapis-http-methods", "restapis-safe-vs-idempotent-methods", "restapis-http-headers"],
        recommended: ["restapis-http-methods", "restapis-http-headers"]
      },
      {
        id: 11,
        order: 2,
        slug: "restapis-http-methods",
        title: "HTTP Methods (GET, POST, PUT, PATCH, DELETE)",
        shortTitle: "HTTP Methods",
        readingTime: 12,
        tags: ["rest api", "backend", "http", "protocol", "fundamentals", "basics"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master all HTTP methods including GET, POST, PUT, PATCH, DELETE and when to use each one.",
        prerequisites: ["restapis-http-request-response", "restapis-lifecycle"],
        related: ["restapis-safe-vs-idempotent-methods", "restapis-http-headers", "restapis-query-parameters"],
        recommended: ["restapis-safe-vs-idempotent-methods", "restapis-http-headers"]
      },
      {
        id: 12,
        order: 3,
        slug: "restapis-safe-vs-idempotent-methods",
        title: "Safe vs Idempotent Methods",
        shortTitle: "Safe vs Idempotent",
        readingTime: 10,
        tags: ["rest api", "backend", "http", "protocol", "http methods", "safety", "fundamentals", "basics"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the concepts of safe and idempotent HTTP methods and their importance in API design.",
        prerequisites: ["restapis-http-methods", "restapis-http-request-response"],
        related: ["restapis-http-headers", "restapis-query-parameters", "restapis-path-parameters"],
        recommended: ["restapis-http-headers", "restapis-query-parameters"]
      },
      {
        id: 13,
        order: 4,
        slug: "restapis-http-headers",
        title: "HTTP Headers",
        shortTitle: "HTTP Headers",
        readingTime: 10,
        tags: ["rest api", "backend", "http", "protocol", "fundamentals", "basics"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to use HTTP headers effectively for caching, authentication, and content negotiation.",
        prerequisites: ["restapis-safe-vs-idempotent-methods", "restapis-http-methods"],
        related: ["restapis-query-parameters", "restapis-path-parameters", "restapis-request-body"],
        recommended: ["restapis-query-parameters", "restapis-path-parameters"]
      },
      {
        id: 14,
        order: 5,
        slug: "restapis-query-parameters",
        title: "Query Parameters",
        shortTitle: "Query Parameters",
        readingTime: 8,
        tags: ["rest api", "backend", "parameters", "routing", "fundamentals", "basics"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master query parameters for filtering, sorting, and passing optional data in REST API requests.",
        prerequisites: ["restapis-http-headers", "restapis-safe-vs-idempotent-methods"],
        related: ["restapis-path-parameters", "restapis-request-body", "restapis-response-body"],
        recommended: ["restapis-path-parameters", "restapis-request-body"]
      },
      {
        id: 15,
        order: 6,
        slug: "restapis-path-parameters",
        title: "Path Parameters",
        shortTitle: "Path Parameters",
        readingTime: 8,
        tags: ["rest api", "backend", "parameters", "routing", "fundamentals", "basics"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to use path parameters to identify specific resources in REST API endpoints.",
        prerequisites: ["restapis-http-headers", "restapis-query-parameters"],
        related: ["restapis-http-headers", "restapis-request-body", "restapis-mime-types-and-content-type"],
        recommended: ["restapis-request-body", "restapis-resource-naming-best-practices"]
      },
      {
        id: 16,
        order: 7,
        slug: "restapis-request-body",
        title: "Request Body",
        shortTitle: "Request Body",
        readingTime: 10,
        tags: ["rest api", "backend", "http", "protocol", "fundamentals", "basics"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand how to structure and send data in the request body for POST, PUT, and PATCH operations.",
        prerequisites: ["restapis-query-parameters", "restapis-path-parameters"],
        related: ["restapis-http-headers", "restapis-path-parameters", "restapis-safe-vs-idempotent-methods"],
        recommended: ["restapis-uri-vs-url-vs-endpoint", "restapis-response-body"]
      },
      {
        id: 17,
        order: 8,
        slug: "restapis-response-body",
        title: "Response Body",
        shortTitle: "Response Body",
        readingTime: 10,
        tags: ["rest api", "backend", "http", "protocol", "fundamentals", "basics"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to design clean and consistent response bodies for REST API endpoints.",
        prerequisites: ["restapis-request-body", "restapis-path-parameters"],
        related: ["restapis-path-parameters", "restapis-nested-resources", "restapis-request-body"],
        recommended: ["restapis-uri-vs-url-vs-endpoint", "restapis-nested-resources"]
      },
      {
        id: 18,
        order: 9,
        slug: "restapis-mime-types-and-content-type",
        title: "MIME Types & Content-Type",
        shortTitle: "MIME Types",
        readingTime: 10,
        tags: ["rest api", "backend", "http", "protocol", "fundamentals", "basics"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand MIME types and the Content-Type header for handling different data formats in APIs.",
        prerequisites: ["restapis-response-body", "restapis-request-body"],
        related: ["restapis-resource-naming-best-practices", "restapis-path-parameters", "restapis-designing-clean-rest-urls"],
        recommended: ["restapis-resource-naming-best-practices", "restapis-designing-clean-rest-urls"]
      },
    ]
  },

  {
    id: "resources-and-url-design",
    title: "Resources & URL Design",
    order: 3,
    difficulty: "Beginner",
    lessons: [
      {
        id: 19,
        order: 1,
        slug: "restapis-what-is-a-resource",
        title: "What is a Resource?",
        shortTitle: "What is a Resource",
        readingTime: 10,
        tags: ["rest api", "backend", "api design", "url design", "resources"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn what a resource is in REST and how everything in a REST API is modeled as a resource.",
        prerequisites: ["restapis-mime-types-and-content-type", "restapis-response-body"],
        related: ["restapis-query-parameters", "restapis-designing-clean-rest-urls", "restapis-mime-types-and-content-type"],
        recommended: ["restapis-designing-clean-rest-urls", "restapis-nested-resources"]
      },
      {
        id: 20,
        order: 2,
        slug: "restapis-resource-naming-best-practices",
        title: "Resource Naming Best Practices",
        shortTitle: "Resource Naming",
        readingTime: 10,
        tags: ["rest api", "backend", "api design", "url design", "resources"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Discover best practices for naming REST resources using nouns and plural forms.",
        prerequisites: ["restapis-what-is-a-resource", "restapis-mime-types-and-content-type"],
        related: ["restapis-response-body", "restapis-content-negotiation", "restapis-uri-vs-url-vs-endpoint"],
        recommended: ["restapis-designing-clean-rest-urls", "restapis-uri-vs-url-vs-endpoint"]
      },
      {
        id: 21,
        order: 3,
        slug: "restapis-uri-vs-url-vs-endpoint",
        title: "URI vs URL vs Endpoint",
        shortTitle: "URI vs URL vs Endpoint",
        readingTime: 10,
        tags: ["rest api", "backend", "api design", "url design", "resources"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the differences between URI, URL, and API endpoint in REST architecture.",
        prerequisites: ["restapis-what-is-a-resource", "restapis-resource-naming-best-practices"],
        related: ["restapis-versioning-apis", "restapis-response-body", "restapis-request-body"],
        recommended: ["restapis-versioning-apis", "restapis-status-codes-overview"]
      },
      {
        id: 22,
        order: 4,
        slug: "restapis-nested-resources",
        title: "Nested Resources",
        shortTitle: "Nested Resources",
        readingTime: 10,
        tags: ["rest api", "backend", "api design", "url design", "resources"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to design and implement nested resource relationships in REST API URLs.",
        prerequisites: ["restapis-resource-naming-best-practices", "restapis-uri-vs-url-vs-endpoint"],
        related: ["restapis-mime-types-and-content-type", "restapis-status-codes-overview", "restapis-designing-clean-rest-urls"],
        recommended: ["restapis-versioning-apis", "restapis-designing-clean-rest-urls"]
      },
      {
        id: 23,
        order: 5,
        slug: "restapis-designing-clean-rest-urls",
        title: "Designing Clean REST URLs",
        shortTitle: "Clean REST URLs",
        readingTime: 12,
        tags: ["rest api", "backend", "api design", "url design", "resources"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master the art of designing clean, intuitive, and developer-friendly REST API URLs.",
        prerequisites: ["restapis-uri-vs-url-vs-endpoint", "restapis-nested-resources"],
        related: ["restapis-uri-vs-url-vs-endpoint", "restapis-what-is-a-resource", "restapis-versioning-apis"],
        recommended: ["restapis-success-responses-2xx", "restapis-status-codes-overview"]
      },
      {
        id: 24,
        order: 6,
        slug: "restapis-versioning-apis",
        title: "Versioning APIs",
        shortTitle: "API Versioning",
        readingTime: 10,
        tags: ["rest api", "backend", "versioning", "backward compatibility", "api design", "resources"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore different strategies for versioning REST APIs to maintain backward compatibility.",
        prerequisites: ["restapis-designing-clean-rest-urls", "restapis-nested-resources"],
        related: ["restapis-what-is-a-resource", "restapis-success-responses-2xx", "restapis-server-errors-5xx"],
        recommended: ["restapis-content-negotiation", "restapis-client-errors-4xx"]
      },
      {
        id: 25,
        order: 7,
        slug: "restapis-content-negotiation",
        title: "Content Negotiation",
        shortTitle: "Content Negotiation",
        readingTime: 10,
        tags: ["rest api", "backend", "content negotiation", "formats", "api design", "resources"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how content negotiation allows clients and servers to agree on response formats.",
        prerequisites: ["restapis-designing-clean-rest-urls", "restapis-versioning-apis"],
        related: ["restapis-error-response-design", "restapis-uri-vs-url-vs-endpoint", "restapis-resource-naming-best-practices"],
        recommended: ["restapis-server-errors-5xx", "restapis-error-response-design"]
      },
    ]
  },

  {
    id: "status-codes-and-responses",
    title: "Status Codes & Responses",
    order: 4,
    difficulty: "Beginner",
    lessons: [
      {
        id: 26,
        order: 1,
        slug: "restapis-status-codes-overview",
        title: "HTTP Status Codes Overview",
        shortTitle: "Status Codes Overview",
        readingTime: 10,
        tags: ["rest api", "backend", "status codes", "error handling", "responses"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get a complete overview of HTTP status codes and their meanings in REST APIs.",
        prerequisites: ["restapis-versioning-apis", "restapis-content-negotiation"],
        related: ["restapis-versioning-apis", "restapis-content-negotiation", "restapis-uri-vs-url-vs-endpoint"],
        recommended: ["restapis-client-errors-4xx", "restapis-consistent-api-response-format"]
      },
      {
        id: 27,
        order: 2,
        slug: "restapis-success-responses-2xx",
        title: "Success Responses (2xx)",
        shortTitle: "2xx Success Codes",
        readingTime: 10,
        tags: ["rest api", "backend", "status codes", "error handling", "responses"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn all 2xx success status codes and when to return each one in your REST API.",
        prerequisites: ["restapis-content-negotiation", "restapis-status-codes-overview"],
        related: ["restapis-stateless-apis", "restapis-server-errors-5xx", "restapis-nested-resources"],
        recommended: ["restapis-consistent-api-response-format", "restapis-stateless-apis"]
      },
      {
        id: 28,
        order: 3,
        slug: "restapis-client-errors-4xx",
        title: "Client Errors (4xx)",
        shortTitle: "4xx Client Errors",
        readingTime: 10,
        tags: ["rest api", "backend", "status codes", "error handling", "responses"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand 4xx client error status codes and how to handle invalid requests properly.",
        prerequisites: ["restapis-success-responses-2xx", "restapis-status-codes-overview"],
        related: ["restapis-error-response-design", "restapis-consistent-api-response-format", "restapis-pagination"],
        recommended: ["restapis-server-errors-5xx", "restapis-stateless-apis"]
      },
      {
        id: 29,
        order: 4,
        slug: "restapis-server-errors-5xx",
        title: "Server Errors (5xx)",
        shortTitle: "5xx Server Errors",
        readingTime: 10,
        tags: ["rest api", "backend", "status codes", "error handling", "responses"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn about 5xx server error status codes and how to handle internal failures gracefully.",
        prerequisites: ["restapis-client-errors-4xx", "restapis-success-responses-2xx"],
        related: ["restapis-pagination", "restapis-versioning-apis", "restapis-status-codes-overview"],
        recommended: ["restapis-consistent-api-response-format", "restapis-pagination"]
      },
      {
        id: 30,
        order: 5,
        slug: "restapis-error-response-design",
        title: "Error Response Design",
        shortTitle: "Error Response Design",
        readingTime: 12,
        tags: ["rest api", "backend", "status codes", "error handling", "responses"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Design consistent and informative error responses that help developers debug API issues.",
        prerequisites: ["restapis-client-errors-4xx", "restapis-server-errors-5xx"],
        related: ["restapis-client-errors-4xx", "restapis-success-responses-2xx", "restapis-pagination"],
        recommended: ["restapis-pagination", "restapis-stateless-apis"]
      },
      {
        id: 31,
        order: 6,
        slug: "restapis-consistent-api-response-format",
        title: "Consistent API Response Format",
        shortTitle: "Consistent Response Format",
        readingTime: 10,
        tags: ["rest api", "backend", "status codes", "responses"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Establish a uniform response format across all endpoints for predictable API behavior.",
        prerequisites: ["restapis-error-response-design", "restapis-server-errors-5xx"],
        related: ["restapis-stateless-apis", "restapis-searching", "restapis-filtering"],
        recommended: ["restapis-stateless-apis", "restapis-sorting"]
      },
    ]
  },

  {
    id: "api-design-best-practices",
    title: "API Design Best Practices",
    order: 5,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 32,
        order: 1,
        slug: "restapis-stateless-apis",
        title: "Stateless APIs",
        shortTitle: "Stateless APIs",
        readingTime: 10,
        tags: ["rest api", "backend", "api best practices", "scalability", "best practices", "patterns"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the stateless nature of REST and why each request must contain all necessary information.",
        prerequisites: ["restapis-error-response-design", "restapis-consistent-api-response-format"],
        related: ["restapis-server-errors-5xx", "restapis-consistent-api-response-format", "restapis-success-responses-2xx"],
        recommended: ["restapis-pagination", "restapis-sorting"]
      },
      {
        id: 33,
        order: 2,
        slug: "restapis-pagination",
        title: "Pagination",
        shortTitle: "Pagination",
        readingTime: 10,
        tags: ["rest api", "backend", "api best practices", "scalability", "best practices", "patterns"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Implement pagination to handle large datasets efficiently in REST API responses.",
        prerequisites: ["restapis-stateless-apis", "restapis-consistent-api-response-format"],
        related: ["restapis-caching", "restapis-searching", "restapis-error-response-design"],
        recommended: ["restapis-rate-limiting", "restapis-caching"]
      },
      {
        id: 34,
        order: 3,
        slug: "restapis-filtering",
        title: "Filtering",
        shortTitle: "Filtering",
        readingTime: 10,
        tags: ["rest api", "backend", "api best practices", "scalability", "best practices", "patterns"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to implement filtering capabilities to allow clients to narrow down API results.",
        prerequisites: ["restapis-pagination", "restapis-stateless-apis"],
        related: ["restapis-searching", "restapis-api-documentation", "restapis-rate-limiting"],
        recommended: ["restapis-api-documentation", "restapis-caching"]
      },
      {
        id: 35,
        order: 4,
        slug: "restapis-sorting",
        title: "Sorting",
        shortTitle: "Sorting",
        readingTime: 10,
        tags: ["rest api", "backend", "api best practices", "scalability", "best practices", "patterns"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Master sorting techniques to let clients order API response data as needed.",
        prerequisites: ["restapis-filtering", "restapis-pagination"],
        related: ["restapis-caching", "restapis-rate-limiting", "restapis-richardson-maturity-model"],
        recommended: ["restapis-rate-limiting", "restapis-caching"]
      },
      {
        id: 36,
        order: 5,
        slug: "restapis-searching",
        title: "Searching",
        shortTitle: "Searching",
        readingTime: 10,
        tags: ["rest api", "backend", "api best practices", "scalability", "best practices", "patterns"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Implement full-text search functionality in your REST APIs for powerful data discovery.",
        prerequisites: ["restapis-filtering", "restapis-sorting"],
        related: ["restapis-stateless-apis", "restapis-pagination", "restapis-caching"],
        recommended: ["restapis-richardson-maturity-model", "restapis-api-documentation"]
      },
      {
        id: 37,
        order: 6,
        slug: "restapis-rate-limiting",
        title: "Rate Limiting",
        shortTitle: "Rate Limiting",
        readingTime: 10,
        tags: ["rest api", "backend", "api best practices", "scalability", "best practices", "patterns"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Protect your API from abuse by implementing rate limiting and throttling mechanisms.",
        prerequisites: ["restapis-searching", "restapis-sorting"],
        related: ["restapis-api-documentation", "restapis-richardson-maturity-model", "restapis-caching"],
        recommended: ["restapis-authentication-vs-authorization", "restapis-caching"]
      },
      {
        id: 38,
        order: 7,
        slug: "restapis-caching",
        title: "Caching",
        shortTitle: "Caching",
        readingTime: 10,
        tags: ["rest api", "backend", "api best practices", "scalability", "best practices", "patterns"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn caching strategies to improve API performance and reduce server load.",
        prerequisites: ["restapis-searching", "restapis-rate-limiting"],
        related: ["restapis-authentication-vs-authorization", "restapis-api-documentation", "restapis-filtering"],
        recommended: ["restapis-api-keys", "restapis-jwt-authentication"]
      },
      {
        id: 39,
        order: 8,
        slug: "restapis-api-documentation",
        title: "API Documentation",
        shortTitle: "API Documentation",
        readingTime: 12,
        tags: ["rest api", "backend", "api best practices", "scalability", "best practices", "patterns"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Create comprehensive API documentation using tools like Swagger and OpenAPI.",
        prerequisites: ["restapis-rate-limiting", "restapis-caching"],
        related: ["restapis-authentication-vs-authorization", "restapis-richardson-maturity-model", "restapis-filtering"],
        recommended: ["restapis-jwt-authentication", "restapis-richardson-maturity-model"]
      },
      {
        id: 40,
        order: 9,
        slug: "restapis-richardson-maturity-model",
        title: "Richardson Maturity Model",
        shortTitle: "Richardson Model",
        readingTime: 12,
        tags: ["rest api", "backend", "api design", "url design", "api best practices", "scalability", "best practices", "patterns"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Understand the Richardson Maturity Model and levels of REST API compliance.",
        prerequisites: ["restapis-api-documentation", "restapis-caching"],
        related: ["restapis-jwt-authentication", "restapis-searching", "restapis-authentication-vs-authorization"],
        recommended: ["restapis-authentication-vs-authorization", "restapis-oauth-overview"]
      },
    ]
  },

  {
    id: "security",
    title: "Security",
    order: 6,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 41,
        order: 1,
        slug: "restapis-authentication-vs-authorization",
        title: "Authentication vs Authorization",
        shortTitle: "Auth vs Authz",
        readingTime: 10,
        tags: ["rest api", "backend", "security", "authentication", "protection"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn the critical difference between authentication and authorization in API security.",
        prerequisites: ["restapis-richardson-maturity-model", "restapis-api-documentation"],
        related: ["restapis-oauth-overview", "restapis-input-validation", "restapis-rate-limiting"],
        recommended: ["restapis-oauth-overview", "restapis-input-validation"]
      },
      {
        id: 42,
        order: 2,
        slug: "restapis-api-keys",
        title: "API Keys",
        shortTitle: "API Keys",
        readingTime: 10,
        tags: ["rest api", "backend", "security", "authentication", "protection"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Implement API key authentication for simple and effective access control.",
        prerequisites: ["restapis-authentication-vs-authorization", "restapis-richardson-maturity-model"],
        related: ["restapis-security-best-practices", "restapis-jwt-authentication", "restapis-input-validation"],
        recommended: ["restapis-input-validation", "restapis-cors"]
      },
      {
        id: 43,
        order: 3,
        slug: "restapis-jwt-authentication",
        title: "JWT Authentication",
        shortTitle: "JWT Auth",
        readingTime: 12,
        tags: ["rest api", "backend", "security", "authentication", "protection"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Use JSON Web Tokens for stateless authentication in your REST APIs.",
        prerequisites: ["restapis-authentication-vs-authorization", "restapis-api-keys"],
        related: ["restapis-security-best-practices", "restapis-api-keys", "restapis-introduction-to-postman"],
        recommended: ["restapis-security-best-practices", "restapis-introduction-to-postman"]
      },
      {
        id: 44,
        order: 4,
        slug: "restapis-oauth-overview",
        title: "OAuth Overview",
        shortTitle: "OAuth Overview",
        readingTime: 12,
        tags: ["rest api", "backend", "security", "authentication", "protection"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get an overview of OAuth 2.0 and how it enables secure third-party API access.",
        prerequisites: ["restapis-api-keys", "restapis-jwt-authentication"],
        related: ["restapis-api-keys", "restapis-security-best-practices", "restapis-richardson-maturity-model"],
        recommended: ["restapis-creating-requests", "restapis-security-best-practices"]
      },
      {
        id: 45,
        order: 5,
        slug: "restapis-cors",
        title: "CORS",
        shortTitle: "CORS",
        readingTime: 10,
        tags: ["rest api", "backend", "security", "authentication", "protection"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Configure Cross-Origin Resource Sharing to control which domains can access your API.",
        prerequisites: ["restapis-oauth-overview", "restapis-jwt-authentication"],
        related: ["restapis-oauth-overview", "restapis-security-best-practices", "restapis-api-keys"],
        recommended: ["restapis-input-validation", "restapis-security-best-practices"]
      },
      {
        id: 46,
        order: 6,
        slug: "restapis-input-validation",
        title: "Input Validation",
        shortTitle: "Input Validation",
        readingTime: 10,
        tags: ["rest api", "backend", "security", "authentication", "protection"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Validate all incoming API requests to prevent malformed data and security vulnerabilities.",
        prerequisites: ["restapis-cors", "restapis-oauth-overview"],
        related: ["restapis-testing-environment-variables", "restapis-security-best-practices", "restapis-creating-requests"],
        recommended: ["restapis-introduction-to-postman", "restapis-security-best-practices"]
      },
      {
        id: 47,
        order: 7,
        slug: "restapis-security-best-practices",
        title: "Security Best Practices",
        shortTitle: "Security Best Practices",
        readingTime: 12,
        tags: ["rest api", "backend", "api design", "url design", "security", "authentication", "protection"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Follow comprehensive security best practices to protect your REST APIs from threats.",
        prerequisites: ["restapis-input-validation", "restapis-cors"],
        related: ["restapis-oauth-overview", "restapis-api-keys", "restapis-testing-environment-variables"],
        recommended: ["restapis-creating-requests", "restapis-collections"]
      },
    ]
  },

  {
    id: "testing-rest-apis",
    title: "Testing REST APIs",
    order: 7,
    difficulty: "Intermediate",
    lessons: [
      {
        id: 48,
        order: 1,
        slug: "restapis-introduction-to-postman",
        title: "Introduction to Postman",
        shortTitle: "Postman Intro",
        readingTime: 10,
        tags: ["rest api", "backend", "testing", "postman", "qa"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Get started with Postman for testing and exploring REST APIs interactively.",
        prerequisites: ["restapis-security-best-practices", "restapis-input-validation"],
        related: ["restapis-oauth-overview", "restapis-input-validation", "restapis-debugging-failed-requests"],
        recommended: ["restapis-creating-requests", "restapis-collections"]
      },
      {
        id: 49,
        order: 2,
        slug: "restapis-creating-requests",
        title: "Creating Requests",
        shortTitle: "Creating Requests",
        readingTime: 10,
        tags: ["rest api", "backend", "testing", "qa"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn how to create and send various types of API requests using Postman.",
        prerequisites: ["restapis-introduction-to-postman", "restapis-security-best-practices"],
        related: ["restapis-collections", "restapis-debugging-failed-requests", "restapis-with-expressjs"],
        recommended: ["restapis-testing-environment-variables", "restapis-with-expressjs"]
      },
      {
        id: 50,
        order: 3,
        slug: "restapis-testing-environment-variables",
        title: "Environment Variables",
        shortTitle: "Env Variables",
        readingTime: 10,
        tags: ["rest api", "backend", "testing", "postman", "qa"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Use environment variables in Postman to manage different API configurations.",
        prerequisites: ["restapis-introduction-to-postman", "restapis-creating-requests"],
        related: ["restapis-cors", "restapis-debugging-failed-requests", "restapis-creating-requests"],
        recommended: ["restapis-collections", "restapis-crud-api-example"]
      },
      {
        id: 51,
        order: 4,
        slug: "restapis-collections",
        title: "Collections",
        shortTitle: "Collections",
        readingTime: 10,
        tags: ["rest api", "backend", "testing", "postman", "qa"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Organize your API tests into collections for efficient testing and sharing.",
        prerequisites: ["restapis-creating-requests", "restapis-testing-environment-variables"],
        related: ["restapis-introduction-to-postman", "restapis-input-validation", "restapis-connecting-database"],
        recommended: ["restapis-with-expressjs", "restapis-crud-api-example"]
      },
      {
        id: 52,
        order: 5,
        slug: "restapis-api-testing",
        title: "API Testing",
        shortTitle: "API Testing",
        readingTime: 12,
        tags: ["rest api", "backend", "testing", "postman", "qa"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Write comprehensive API tests to validate functionality, performance, and reliability.",
        prerequisites: ["restapis-collections", "restapis-testing-environment-variables"],
        related: ["restapis-introduction-to-postman", "restapis-collections", "restapis-connecting-database"],
        recommended: ["restapis-debugging-failed-requests", "restapis-building-validation"]
      },
      {
        id: 53,
        order: 6,
        slug: "restapis-debugging-failed-requests",
        title: "Debugging Failed Requests",
        shortTitle: "Debugging Requests",
        readingTime: 10,
        tags: ["rest api", "backend", "testing", "postman", "qa"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn techniques for debugging and troubleshooting failed API requests effectively.",
        prerequisites: ["restapis-api-testing", "restapis-collections"],
        related: ["restapis-collections", "restapis-building-validation", "restapis-creating-requests"],
        recommended: ["restapis-crud-api-example", "restapis-with-expressjs"]
      },
    ]
  },

  {
    id: "building-rest-apis",
    title: "Building REST APIs",
    order: 8,
    difficulty: "Advanced",
    lessons: [
      {
        id: 54,
        order: 1,
        slug: "restapis-with-expressjs",
        title: "REST API with Express.js",
        shortTitle: "REST with Express.js",
        readingTime: 14,
        tags: ["rest api", "backend", "expressjs", "implementation", "development"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Build a complete REST API from scratch using Express.js and Node.js.",
        prerequisites: ["restapis-debugging-failed-requests", "restapis-api-testing"],
        related: ["restapis-connecting-database", "restapis-creating-requests", "restapis-building-error-handling"],
        recommended: ["restapis-connecting-database", "restapis-production-best-practices"]
      },
      {
        id: 55,
        order: 2,
        slug: "restapis-crud-api-example",
        title: "CRUD API Example",
        shortTitle: "CRUD API Example",
        readingTime: 14,
        tags: ["rest api", "backend", "expressjs", "implementation", "development"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Implement full CRUD operations with a practical Express.js API example.",
        prerequisites: ["restapis-with-expressjs", "restapis-debugging-failed-requests"],
        related: ["restapis-building-error-handling", "restapis-api-testing", "restapis-debugging-failed-requests"],
        recommended: ["restapis-connecting-database", "restapis-production-best-practices"]
      },
      {
        id: 56,
        order: 3,
        slug: "restapis-connecting-database",
        title: "Connecting Database",
        shortTitle: "Connecting Database",
        readingTime: 12,
        tags: ["rest api", "backend", "expressjs", "implementation", "development"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Connect your REST API to a database for persistent data storage and retrieval.",
        prerequisites: ["restapis-with-expressjs", "restapis-crud-api-example"],
        related: ["restapis-building-error-handling", "restapis-long-running-operations", "restapis-with-expressjs"],
        recommended: ["restapis-building-error-handling", "restapis-long-running-operations"]
      },
      {
        id: 57,
        order: 4,
        slug: "restapis-building-validation",
        title: "Validation",
        shortTitle: "Validation",
        readingTime: 12,
        tags: ["rest api", "backend", "expressjs", "implementation", "development"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Add robust request validation to your REST API using middleware and libraries.",
        prerequisites: ["restapis-crud-api-example", "restapis-connecting-database"],
        related: ["restapis-api-testing", "restapis-with-expressjs", "restapis-hateoas"],
        recommended: ["restapis-production-best-practices", "restapis-compression"]
      },
      {
        id: 58,
        order: 5,
        slug: "restapis-building-error-handling",
        title: "Error Handling",
        shortTitle: "Error Handling",
        readingTime: 12,
        tags: ["rest api", "backend", "status codes", "error handling", "expressjs", "implementation", "development"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Implement centralized error handling for consistent API error responses.",
        prerequisites: ["restapis-building-validation", "restapis-connecting-database"],
        related: ["restapis-building-validation", "restapis-debugging-failed-requests", "restapis-with-expressjs"],
        recommended: ["restapis-compression", "restapis-production-best-practices"]
      },
      {
        id: 59,
        order: 6,
        slug: "restapis-production-best-practices",
        title: "Production Best Practices",
        shortTitle: "Production Best Practices",
        readingTime: 14,
        tags: ["rest api", "backend", "expressjs", "implementation", "development"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Follow best practices for deploying and running REST APIs in production environments.",
        prerequisites: ["restapis-building-error-handling", "restapis-building-validation"],
        related: ["restapis-monitoring-and-logging", "restapis-connecting-database", "restapis-performance-optimization"],
        recommended: ["restapis-hateoas", "restapis-performance-optimization"]
      },
    ]
  },

  {
    id: "advanced-rest-concepts",
    title: "Advanced REST Concepts",
    order: 9,
    difficulty: "Advanced",
    lessons: [
      {
        id: 60,
        order: 1,
        slug: "restapis-hateoas",
        title: "HATEOAS",
        shortTitle: "HATEOAS",
        readingTime: 12,
        tags: ["rest api", "backend", "advanced", "architecture", "internals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Implement HATEOAS to make your REST API discoverable and self-descriptive.",
        prerequisites: ["restapis-building-error-handling", "restapis-production-best-practices"],
        related: ["restapis-building-validation", "restapis-long-running-operations", "restapis-monitoring-and-logging"],
        recommended: ["restapis-long-running-operations", "restapis-performance-optimization"]
      },
      {
        id: 61,
        order: 2,
        slug: "restapis-long-running-operations",
        title: "Long Running Operations",
        shortTitle: "Long Running Ops",
        readingTime: 12,
        tags: ["rest api", "backend", "advanced", "architecture", "internals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Handle long-running API operations gracefully using async patterns and status endpoints.",
        prerequisites: ["restapis-hateoas", "restapis-production-best-practices"],
        related: ["restapis-production-best-practices", "restapis-monitoring-and-logging", "restapis-building-validation"],
        recommended: ["restapis-rest-vs-grpc", "restapis-performance-optimization"]
      },
      {
        id: 62,
        order: 3,
        slug: "restapis-compression",
        title: "Compression",
        shortTitle: "Compression",
        readingTime: 10,
        tags: ["rest api", "backend", "advanced", "architecture", "internals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Enable response compression to reduce payload sizes and improve API performance.",
        prerequisites: ["restapis-long-running-operations", "restapis-hateoas"],
        related: ["restapis-building-error-handling", "restapis-rest-vs-soap", "restapis-long-running-operations"],
        recommended: ["restapis-monitoring-and-logging", "restapis-rest-vs-soap"]
      },
      {
        id: 63,
        order: 4,
        slug: "restapis-performance-optimization",
        title: "API Performance Optimization",
        shortTitle: "Performance Optimization",
        readingTime: 12,
        tags: ["rest api", "backend", "advanced", "architecture", "internals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Optimize your REST API for speed, scalability, and efficient resource usage.",
        prerequisites: ["restapis-compression", "restapis-long-running-operations"],
        related: ["restapis-rest-vs-graphql", "restapis-rest-vs-soap", "restapis-building-error-handling"],
        recommended: ["restapis-github-rest-api", "restapis-rest-vs-soap"]
      },
      {
        id: 64,
        order: 5,
        slug: "restapis-monitoring-and-logging",
        title: "API Monitoring & Logging",
        shortTitle: "Monitoring & Logging",
        readingTime: 12,
        tags: ["rest api", "backend", "advanced", "architecture", "internals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Set up monitoring and logging to track API health, performance, and errors.",
        prerequisites: ["restapis-performance-optimization", "restapis-compression"],
        related: ["restapis-performance-optimization", "restapis-github-rest-api", "restapis-rest-vs-graphql"],
        recommended: ["restapis-stripe-rest-api", "restapis-rest-vs-grpc"]
      },
      {
        id: 65,
        order: 6,
        slug: "restapis-rest-vs-graphql",
        title: "REST vs GraphQL",
        shortTitle: "REST vs GraphQL",
        readingTime: 12,
        tags: ["rest api", "backend", "advanced", "architecture", "internals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Compare REST and GraphQL to understand when to use each API architecture.",
        prerequisites: ["restapis-monitoring-and-logging", "restapis-performance-optimization"],
        related: ["restapis-rest-vs-grpc", "restapis-long-running-operations", "restapis-rest-vs-soap"],
        recommended: ["restapis-stripe-rest-api", "restapis-openweather-api"]
      },
      {
        id: 66,
        order: 7,
        slug: "restapis-rest-vs-grpc",
        title: "REST vs gRPC",
        shortTitle: "REST vs gRPC",
        readingTime: 12,
        tags: ["rest api", "backend", "advanced", "architecture", "internals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Compare REST and gRPC for high-performance API communication scenarios.",
        prerequisites: ["restapis-rest-vs-graphql", "restapis-monitoring-and-logging"],
        related: ["restapis-monitoring-and-logging", "restapis-github-rest-api", "restapis-long-running-operations"],
        recommended: ["restapis-stripe-rest-api", "restapis-google-maps-api"]
      },
      {
        id: 67,
        order: 8,
        slug: "restapis-rest-vs-soap",
        title: "REST vs SOAP",
        shortTitle: "REST vs SOAP",
        readingTime: 12,
        tags: ["rest api", "backend", "advanced", "architecture", "internals"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Compare REST and SOAP to understand the evolution of web service architectures.",
        prerequisites: ["restapis-rest-vs-grpc", "restapis-rest-vs-graphql"],
        related: ["restapis-performance-optimization", "restapis-compression", "restapis-openweather-api"],
        recommended: ["restapis-building-production-ready-rest-api", "restapis-google-maps-api"]
      },
    ]
  },

  {
    id: "real-world-rest-apis",
    title: "Real-World REST APIs",
    order: 10,
    difficulty: "Advanced",
    lessons: [
      {
        id: 68,
        order: 1,
        slug: "restapis-github-rest-api",
        title: "GitHub REST API",
        shortTitle: "GitHub API",
        readingTime: 14,
        tags: ["rest api", "backend", "real world", "examples", "projects"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the GitHub REST API and learn from a real-world production API example.",
        prerequisites: ["restapis-rest-vs-soap", "restapis-rest-vs-grpc"],
        related: ["restapis-building-production-ready-rest-api", "restapis-rest-vs-soap", "restapis-openweather-api"],
        recommended: ["restapis-google-maps-api", "restapis-openweather-api"]
      },
      {
        id: 69,
        order: 2,
        slug: "restapis-stripe-rest-api",
        title: "Stripe REST API",
        shortTitle: "Stripe API",
        readingTime: 14,
        tags: ["rest api", "backend", "real world", "examples", "projects"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Study the Stripe REST API design for insights into payment API best practices.",
        prerequisites: ["restapis-github-rest-api", "restapis-rest-vs-soap"],
        related: ["restapis-rest-vs-grpc", "restapis-google-maps-api", "restapis-github-rest-api"],
        recommended: ["restapis-google-maps-api", "restapis-interview-questions"]
      },
      {
        id: 70,
        order: 3,
        slug: "restapis-openweather-api",
        title: "OpenWeather API",
        shortTitle: "OpenWeather API",
        readingTime: 14,
        tags: ["rest api", "backend", "real world", "examples", "projects"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Learn from the OpenWeather API example for weather data integration patterns.",
        prerequisites: ["restapis-github-rest-api", "restapis-stripe-rest-api"],
        related: ["restapis-interview-questions", "restapis-github-rest-api", "restapis-rest-vs-graphql"],
        recommended: ["restapis-interview-questions", "restapis-building-production-ready-rest-api"]
      },
      {
        id: 71,
        order: 4,
        slug: "restapis-google-maps-api",
        title: "Google Maps API",
        shortTitle: "Google Maps API",
        readingTime: 14,
        tags: ["rest api", "backend", "real world", "examples", "projects"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Explore the Google Maps API for geolocation and mapping service integration.",
        prerequisites: ["restapis-openweather-api", "restapis-stripe-rest-api"],
        related: ["restapis-rest-vs-soap", "restapis-interview-questions", "restapis-github-rest-api"],
        recommended: ["restapis-building-production-ready-rest-api", "restapis-interview-questions"]
      },
      {
        id: 72,
        order: 5,
        slug: "restapis-building-production-ready-rest-api",
        title: "Building a Production-Ready REST API",
        shortTitle: "Production-Ready API",
        readingTime: 18,
        tags: ["rest api", "backend", "real world", "examples", "projects"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Build a complete production-ready REST API applying all learned concepts.",
        prerequisites: ["restapis-openweather-api", "restapis-google-maps-api"],
        related: ["restapis-interview-questions", "restapis-google-maps-api", "restapis-stripe-rest-api"],
        recommended: ["restapis-interview-questions"]
      },
      {
        id: 73,
        order: 6,
        slug: "restapis-interview-questions",
        title: "REST API Interview Questions",
        shortTitle: "Interview Questions",
        readingTime: 16,
        tags: ["rest api", "backend", "interview", "career", "real world", "projects"],
        status: STATUS.PUBLISHED,
        featured: true,
        description: "Prepare for REST API interviews with commonly asked questions and scenarios.",
        prerequisites: ["restapis-building-production-ready-rest-api", "restapis-google-maps-api"],
        related: ["restapis-google-maps-api", "restapis-building-production-ready-rest-api", "restapis-github-rest-api"],
        recommended: ["restapis-openweather-api", "restapis-github-rest-api"]
      },
    ]
  },
];

export const resources = [
  
];